feat(plugin): Show Hidden Channels
Vendicated/Vencord pull request #101
Opened 2022-10-14 21:34 UTC by sneksnake

i've re-written it so it doesn't mess with permissions.
![Hidden Channel](https://i.imgur.com/WQe2wkd.png)

2022-10-14 21:38 UTC, zachjmurphy commented
It would be nice if the channel icon turned to a lock rather than adding [🔒] to the channel name.

2022-10-14 23:48 UTC, ArjixWasTaken commented
There is no stop method...disabling the plugin won't have an effect.

That's not nice.

2022-10-14 23:57 UTC, sneksnake commented
> There is no stop method...disabling the plugin won't have an effect.
> 
> That's not nice.

the plugin patches things so if you disable it you will have to restart discord.



> It would be nice if the channel icon turned to a lock rather than adding [🔒] to the channel name.

yeah i'm trying right now but the patcher doesn't want me to

2022-10-15 00:00 UTC, ArjixWasTaken commented
> the plugin patches things so if you disable it you will have to restart discord.

That's just an excuse, you can make it so that your callback only shows hidden channels when the plugin is enabled.

Even if the patch is still there until the user restarts, it doesn't mean that the user has to restart for it to take effect.

2022-10-15 09:22 UTC, sneksnake commented
> It would be nice if the channel icon turned to a lock rather than adding [🔒] to the channel name.

![Channel with lock icon](https://i.imgur.com/FTGZF0H.png)

2022-10-15 15:42 UTC, BanTheNons commented
> > the plugin patches things so if you disable it you will have to restart discord.
> 
> ~That's just an excuse, you can make it so that your callback only shows hidden channels when the plugin is enabled.~
> 
> ~Even if the patch is still there until the user restarts, it doesn't mean that the user has to restart for it to take effect.~
> 
> Edit: I reread the patches, yeah it ain't as simple as I described it, but it is not that hard either.
> 
> You can prob use
> 
> ```js
> Vencord.Plugins.plugins["Show Hidden Channels"].enabled
> ```
> 
> to access if the plugin is enabled directly from within the patches.
> 
> (I am on my phone and I can't test it)

Since it uses patches, it will prompt the user to restart the app anyway. Even when clicking "Later", the channels stay because the channel view is not updated unless it receives either CHANNEL_CREATE, CHANNEL_DELETE or CHANNEL_UPDATE. Switching guilds and coming back also removes the lock icon but doesn't hide the channel, so I think you should revert this. (or call handleViewUpdate somehow)

2022-10-17 12:10 UTC, x6r requested changes

2022-10-17 12:10 UTC, x6r commented on src/plugins/showHiddenChannels.ts
> +var enabled = false;
```suggestion
import { findByProps } from "../webpack";

const VIEW_CHANNEL = 1024n;
const VOICE_CHANNEL = 2;
```

2022-10-17 12:10 UTC, x6r commented on src/plugins/showHiddenChannels.ts
> +                replace: "renderLevel:Vencord.Plugins.plugins[\"ShowHiddenChannels\"].isEnabled()?$1.Show:$1.CannotShow"
```suggestion
                replace: "renderLevel:$1.Show"
```

2022-10-17 12:10 UTC, x6r commented on src/plugins/showHiddenChannels.ts
> +                replace: "hasActiveThreads,$1=function($2,$3,$4){switch(Vencord.Plugins.plugins[\"ShowHiddenChannels\"].getChannelTypeIcon($2))"
```suggestion
                replace: "hasActiveThreads,$1=function($2,$3,$4){switch(Vencord.Plugins.plugins.ShowHiddenChannels.getChannelTypeIcon($2))"
```

2022-10-17 12:10 UTC, x6r commented on src/plugins/showHiddenChannels.ts
> +});
```suggestion
    getChannelTypeIcon: (channel) => {
        const { can } = findByProps("can", "initialize");
        channel._isHiddenChannel = !can(VIEW_CHANNEL, channel);
        return channel._isHiddenChannel ? VOICE_CHANNEL : channel.type;
    },
});
```

2022-10-17 12:10 UTC, x6r commented on src/plugins/showHiddenChannels.ts
> +});
i dont really understand what getChannelTypeIcon **actually** does but this is the way to do it probably:)

2022-10-17 15:10 UTC, sneksnake reviewed
fixed in lastest commit + removed minified variables names from replacement + renamed "getChannelTypeIcon" to "isHiddenChannel"

2022-10-19 07:52 UTC, Vendicated commented on src/plugins/showHiddenChannels.ts
> +                replace: "Vencord.Plugins.plugins.ShowHiddenChannels.isHiddenChannel($3)?true:$1.locked$2switch($3._isHiddenChannel?2:$3.type)$4"
```suggestion
                replace: "Vencord.Plugins.plugins.ShowHiddenChannels.isHiddenChannel($3)||$1.locked$2switch($3._isHiddenChannel?2:$3.type)$4"
```

2022-10-19 08:05 UTC, ArjixWasTaken commented
Ven is dum dum

2022-10-22 20:18 UTC, sneksnake commented
is there anything left to fix ?

2022-10-22 20:27 UTC, Vendicated commented on src/plugins/showHiddenChannels.ts
> +        const { can } = findByProps("can", "initialize");
this should be moved to the top level with waitFor

2022-10-22 21:50 UTC, Vendicated approved these changes
looks good now. Please fix lint  then it can be merged

2022-10-22 22:02 UTC, sneksnake commented
👍

2022-10-22 22:09 UTC, Vendicated commented
Could you make it so that clicking a Hidden channel doesn't do anything? Or it could open a modal with more info on the channel like its topic

Currently it tries to load it which sends bad api requests

2022-10-23 01:16 UTC, sneksnake commented
Alright, i added a small model when you try to select an hidden channel.
The topic section doesn't appear if there is no topic.

![NSFW channel with topic](https://i.imgur.com/zsSi1Tt.png)
![Channel with no topic](https://i.imgur.com/0Qrl4dv.png)

2022-10-23 09:30 UTC, Vendicated approved these changes

2022-10-23 09:44 UTC, Vendicated commented
thank you!

2022-10-23 09:44 UTC, merged