moreUserTags: Ability to customize text inside tag & settings design overhaul
Vendicated/Vencord pull request #1077
Opened 2023-05-07 16:16 UTC by LordEliasTM

In the attempt of syncing the fork i accidentally pressed discard changes 💀 
Original PR is https://github.com/Vendicated/Vencord/pull/821

2023-05-08 22:04 UTC, Vendicated requested changes

2023-05-08 22:04 UTC, Vendicated commented on src/plugins/moreUserTags.tsx
> +    if (!settings.store.tagSettings) settings.store.tagSettings = defaultSettings;
```suggestion
    settings.store.tagSettings ??= defaultSettings;
```

2023-05-08 22:04 UTC, Vendicated commented on src/plugins/moreUserTags.tsx
> +    const [tagSettings, setTagSettings] = useState(settings.store.tagSettings ?? defaultSettings as TagSettings);
shouldn't need this due to above line

```suggestion
    const [tagSettings, setTagSettings] = useState(settings.store.tagSettings as TagSettings);
```

2023-05-08 22:04 UTC, Vendicated commented on src/plugins/moreUserTags.tsx
> +    return <>
multi line components should be wrapped in () and start on a new line, like
```jsx
return (
	<div>
	</div>
)
```

2023-05-08 22:04 UTC, Vendicated commented on src/plugins/moreUserTags.tsx
> +        {tags.map(t => <Flex flexDirection="column" style={{ gap: 5 }}>
missiing a key

2023-05-08 22:04 UTC, Vendicated commented on src/plugins/moreUserTags.tsx
> +        if (!settings.store.tagSettings) {
invert this if statement with a return to reduce indent

2023-05-08 22:04 UTC, Vendicated commented on src/plugins/moreUserTags.tsx
> +                    Vencord.Settings.plugins.MoreUserTags[name] = null;
```suggestion
                    delete Vencord.Settings.plugins.MoreUserTags[name];
```

2023-05-08 22:04 UTC, Vendicated commented on src/plugins/moreUserTags.tsx
> +                    console.log(Vencord.Settings.plugins.MoreUserTags);
```suggestion
```

2023-05-13 06:25 UTC, ActuallyTheSun commented
threw the fix for canary in here LordEliasTM/Vencord#2 - should work for both canary and stable

2023-05-13 22:34 UTC, Vendicated approved these changes

2023-05-13 22:37 UTC, Vendicated commented
Please don't pr from the main branch in the future, it causes so much pain

2023-05-13 22:38 UTC, merged

2023-05-13 22:39 UTC, Vendicated commented
Thank you!

2023-05-14 00:42 UTC, LordEliasTM commented
> Please don't pr from the main branch in the future, it causes so much pain

What do you mean by that?