New plugin : Party mode 🎉
Vendicated/Vencord pull request #1161
Opened 2023-05-16 20:38 UTC by UwUDev

## Party mode 🎉

Enable the party mode + cool presets.

huge gif loading...
![](https://cdn.upload.systems/uploads/czG2XFFB.gif)

### Please note that's the first time of my life coding in TS so please don't trash me ;~;

I face 3 problems in my code :
- I set `GenericStore` in export from `stores.ts` to get the 'PoggermodeSettingsStore' store but i don't know if the best way to do it.
- I don't know if i am autorized to put spaces and emojis
- The way i imported `waitForStore` makes me feel bad

2023-05-17 22:47 UTC, UwUDev commented
Sorry sorry if my code was super ugly x)
And ty c:

2023-05-17 23:01 UTC, Imbwbl commented
That the best plugin I never see

2023-05-18 20:08 UTC, ArjixWasTaken requested changes

2023-05-18 20:08 UTC, ArjixWasTaken commented on src/plugins/partyMode/index.ts
> +        description: "Party intensity (disable and re-enable plugin to apply changes)",
Since I added the `onChange` callback, this no longer applies.
```suggestion
        description: "Party intensity",
```

2023-05-18 20:08 UTC, ArjixWasTaken commented on src/plugins/partyMode/index.ts
> +const PoggerModeSettingsStore: GenericStore = findStoreLazy("PoggermodeSettingsStore");
Use the actual store from `src/webpack/common/stores.ts` (after you've defined it there ofc)

2023-05-18 20:08 UTC, ArjixWasTaken commented on src/webpack/common/stores.ts
> +export let PoggerModeSettingsStore: GenericStore;
Since you defined a type for it, you should export the actual store just like the other ones.

2023-05-19 19:09 UTC, UwUDev commented on src/webpack/common/stores.ts
> +export let PoggerModeSettingsStore: GenericStore;
I had put the store here at the beginning but I preferred to put it in the plugin directly because this store is only used for the party mode and I will surely be the only one to use it

2023-05-19 19:13 UTC, ArjixWasTaken commented on src/webpack/common/stores.ts
> +export let PoggerModeSettingsStore: GenericStore;
Then please remove the type from `@webpack/common/stores` as it is not really useful.

2023-05-20 00:25 UTC, Vendicated commented on src/plugins/partyMode/index.ts
> +        screenshakeEnabledLocations: { 0: true, 1: true, 2: true },
```suggestion
        screenshakeEnabledLocations: [true, true, true],
```

2023-05-20 00:27 UTC, ArjixWasTaken commented on src/plugins/partyMode/index.ts
> +        screenshakeEnabledLocations: { 0: true, 1: true, 2: true },
I mean, it ain't wrong, it's the truth.

2023-05-23 01:30 UTC, Vendicated commented
Thank you!

Please don't pull request from the main branch in the future, use a feature branch

2023-05-23 01:32 UTC, merged