feat(plugin): BiggerStreamPreview
Vendicated/Vencord pull request #1222
Opened 2023-06-01 17:12 UTC by philhk

# BiggerStreamPreview

This pull request adds the BiggerStreamPreview plugin, which implements the idea proposed in #392. With this plugin, users can enlarge any Stream Preview.

![image](https://github.com/Vendicated/Vencord/assets/66958695/bba5a03f-c30b-4492-9998-2544d4a1e365)

The context menu mentioned above appears whenever you right-click on a user or directly on a stream.

![image](https://github.com/Vendicated/Vencord/assets/66958695/a37c2ab1-cefc-4a01-a2f2-c6efa75321b6)

2023-06-01 17:17 UTC, Vendicated commented on src/components/MaskedLink.tsx
> +export const MaskedLink = LazyComponent(() => find(m => m?.type?.toString()?.includes("MASKED_LINK")) as MaskedLink);
this should be in webpack commons, not here

2023-06-01 17:19 UTC, Vendicated commented on src/webpack/common/types/classes.d.ts
> +}
there are some more class commons that are in components, could you please move them here as well?

2023-06-01 17:34 UTC, philhk commented on src/webpack/common/types/classes.d.ts
> +}
Sure. Is the `ButtonWrapperClasses` the only one or did I miss anything?

2023-06-01 18:11 UTC, philhk commented on src/components/MaskedLink.tsx
> +export const MaskedLink = LazyComponent(() => find(m => m?.type?.toString()?.includes("MASKED_LINK")) as MaskedLink);
[Okay](https://github.com/Vendicated/Vencord/pull/1222/files#diff-b579282bc8a47a3af7dcf9d446f2188a5bef1f493fbd14338dfeec369c5a3723R51) I have done that now.

2023-06-09 20:08 UTC, Vendicated commented on src/plugins/biggerStreamPreview/index.tsx
> +    if (children.some(child => child?.props?.id === streamPreviewItemIdentifier)) return;
instead of this check, you can return a function from your patch. Vencord will only call that function once

2023-06-09 20:08 UTC, Vendicated commented on src/plugins/biggerStreamPreview/index.tsx
> +export const addViewStreamContext = (children, { userId }: { userId: string | bigint; }) => {
```suggestion
export const addViewStreamContext = (children, { userId }: { userId: string | bigint; }) => () => {
```

for the suggestion below

2023-06-09 20:09 UTC, Vendicated commented on src/plugins/biggerStreamPreview/index.tsx
> +    openModalLazy(async () => {
ViewIcons also makes use of this exact modal. Thus it would be beneficial to move this into utils/discord so both plugins can use it!

2023-06-09 20:10 UTC, Vendicated commented on src/webpack/common/stores.ts
> +waitForStore("ApplicationStreamingStore", m => ApplicationStreamingStore = m);
webpack commons like the name implies are for commonly used modules. These stores are very niche, i can't think of any other plugin that would want these, so they should probably be in your plugin instead

2023-06-15 01:41 UTC, Vendicated commented on src/webpack/common/index.ts
> +export * from "./internal";
this is called internal for a reason, you shouldn't use it in ur plugin

2023-06-15 01:41 UTC, Vendicated commented on src/utils/discord.tsx
> +    return openModalLazy(async () => _props => (
```suggestion
    return openModal(modalProps=> (
```

2023-06-15 01:43 UTC, Vendicated commented on src/plugins/viewIcons.tsx
> +        description: "Choose the default image size to use, reducing this value will decrease load time and bandwidth.",
```suggestion
        description: "The image size to use",
```

2023-06-15 01:46 UTC, Vendicated requested changes

2023-06-15 01:46 UTC, Vendicated commented on src/plugins/viewIcons.tsx
> +        options: [
you could make this slightly prettier like so:
```js
options: [128, 256, 512, 1024, 2048, 4096].map(n => ({ label: n, value: n }))
```

2023-06-15 01:46 UTC, Vendicated commented on src/plugins/viewIcons.tsx
> +    imgsize: {
```suggestion
    imgSize: {
```

2023-06-15 01:46 UTC, Vendicated commented on src/plugins/biggerStreamPreview/webpack/types/stores.ts
> + * Here is a example how an stream key could look like `call(type of connection):1116549917987192913(channelId):305238513941667851(ownerId)`
```suggestion
 * example how a stream key could look like: `call(type of connection):1116549917987192913(channelId):305238513941667851(ownerId)`
```

2023-06-15 01:46 UTC, Vendicated commented on src/plugins/biggerStreamPreview/webpack/stores.ts
> +waitForStore("ApplicationStreamPreviewStore", m => ApplicationStreamPreviewStore = m);
as mentioned below, plugins shouldn't use this. Use findStoreLazy instead

2023-06-16 17:27 UTC, Vendicated commented on src/plugins/viewIcons.tsx
> +        options: [128, 256, 512, 1024, 2048, 4096].map(n => ({ label: `${n}`, value: n, default: n === 1024 }))
```suggestion
        options: ["128", "256", "512", "1024", "2048", "4096"].map(n => ({ label: n, value: n, default: n === "1024" }))
```

2023-06-16 17:34 UTC, Vendicated approved these changes

2023-06-16 17:35 UTC, merged

2023-06-16 17:36 UTC, Vendicated commented
thanks!!