Plugin: MutualGroupDMs
Vendicated/Vencord pull request #1239
Opened 2023-06-06 16:51 UTC by aamiaa

This plugin adds a Mutual Group DMs tab on user profile, which lets you view all group dms you share with the user and navigate to them.

2023-06-06 18:08 UTC, TheKodeToad commented on src/plugins/mutualGroupDMs.tsx
> +                    replace: ",!$1.bot?$2\"MUTUAL_GDMS\"$3\"Mutual GDMs\"}):null" // The label is "Mutual GDMs" because otherwise it's too long when Activity tab is present
As a muggle i just call them groups

2023-06-06 18:24 UTC, aamiaa commented on src/plugins/mutualGroupDMs.tsx
> +                    replace: ",!$1.bot?$2\"MUTUAL_GDMS\"$3\"Mutual GDMs\"}):null" // The label is "Mutual GDMs" because otherwise it's too long when Activity tab is present
I labeled it "Mutual Group DMs" before, but "Mutual Groups" seems to work

2023-06-12 23:10 UTC, Vendicated commented on src/plugins/mutualGroupDMs.tsx
> +const Avatar = LazyComponent(() => Menu.Avatar);
don't do this, you're not supposed to use anything from Menu that isn't a Menu. It's just the entire module for simplicity. You will instead want to add additional members to this line:
https://github.com/Vendicated/Vencord/blob/3e3d05fc26a634b17549c9473bd8aeebb7dec4ec/src/webpack/common/components.ts#L57

2023-06-12 23:11 UTC, Vendicated commented on src/plugins/mutualGroupDMs.tsx
> +        const entries = ChannelStore.getSortedPrivateChannels().filter(x => x.type === 3 && x.recipients.includes(user.id)).map(x => {
magic numbers are bad, for better readability please extract it into a properly named constant

2023-06-12 23:12 UTC, Vendicated commented on src/plugins/mutualGroupDMs.tsx
> +            return <Clickable className={ProfileListClasses.listRow} onClick={() => {
it's prettier if u change it from
```js
.map(x => {
	return <Clickable ...
})
```
to
```js
.map(x => (
	<Clickable ...
))
```

2023-06-12 23:13 UTC, Vendicated commented on src/plugins/mutualGroupDMs.tsx
> +function GetGroupDMName(channel: Channel) {
```suggestion
function getGroupDMName(channel: Channel) {
```

2023-06-12 23:13 UTC, Vendicated commented on src/plugins/mutualGroupDMs.tsx
> +        return RelationshipStore.getNickname(x.id) || UserUtils.getName(x);
same as below

2023-06-13 01:14 UTC, aamiaa commented on src/plugins/mutualGroupDMs.tsx
> +const Avatar = LazyComponent(() => Menu.Avatar);
okay I did my best to type those components, idk if I got everything correctly though

2023-06-15 01:24 UTC, Vendicated requested changes

2023-06-15 01:24 UTC, Vendicated commented on src/plugins/mutualGroupDMs.tsx
> +                    match: /({user:(\i),onClose:(\i)}\);)(case \i\.\i\.MUTUAL_FRIENDS)/,
no need to match either of these
```suggestion
                    match: /(?<={user:(\i),onClose:(\i)}\);)(?=case \i\.\i\.MUTUAL_FRIENDS)/,
```

2023-06-15 01:24 UTC, Vendicated commented on src/plugins/mutualGroupDMs.tsx
> +                    replace: "$1case \"MUTUAL_GDMS\":return $self.renderMutualGDMs($2,$3);$4"
```suggestion
                    replace: "case \"MUTUAL_GDMS\":return $self.renderMutualGDMs($1,$2);"
```

2023-06-15 01:24 UTC, Vendicated commented on src/plugins/mutualGroupDMs.tsx
> +                    match: /(?<=(\i)\.isClyde\(\)\?null:(\(0,\i\.\i\).+?id:)\i\.\i\.MUTUAL_GUILDS(,children:)\i\.\i\.Messages\.MUTUAL_GUILDS}\))/,
this looks pretty bad. `.+` is really dangerous (even with ?) and you should avoid it if possible

2023-06-15 01:39 UTC, Vendicated approved these changes

2023-06-15 01:39 UTC, merged

2023-06-15 01:39 UTC, Vendicated commented
thank you, pretty cool!!

2023-06-15 06:50 UTC, D3SOX commented
Would be nice if this was also shown on the profile sidebar :)
![image](https://github.com/Vendicated/Vencord/assets/24937357/1d10e8f6-99e2-4418-95f0-b81569702262)