New Plugin: UnsuppressEmbeds
Vendicated/Vencord pull request #1262
Opened 2023-06-11 02:53 UTC by HypedDomi

Preview: ![](https://cdn.domi-btnr.dev/r/5Bd9Mh.gif)

2023-06-11 17:16 UTC, aamiaa reviewed
It would be nice if this worked on your own messages in dms as well

2023-06-11 17:16 UTC, aamiaa commented on src/plugins/UnsuppressEmbeds.tsx
> +import { Menu, PermissionStore, RestAPI } from "@webpack/common";
```suggestion
import { Menu, PermissionStore, ChannelStore, UserStore, RestAPI } from "@webpack/common";
```

2023-06-11 17:16 UTC, aamiaa commented on src/plugins/UnsuppressEmbeds.tsx
> +    const canManageMessages = !!(PermissionStore.getChannelPermissions({ id: props.channel.id }) & MANAGE_MESSAGES);
```suggestion
    const canManageMessages = !!(PermissionStore.getChannelPermissions({ id: props.channel.id }) & MANAGE_MESSAGES);
    const isOwnDM = author.id === UserStore.getCurrentUser().id && (channel.isDM() || channel.isGroupDM());
```

2023-06-11 17:16 UTC, aamiaa commented on src/plugins/UnsuppressEmbeds.tsx
> +    if (!canManageMessages) return;
```suggestion
    if (!canManageMessages && !isOwnDM) return;
```

2023-06-11 17:33 UTC, aamiaa commented on src/plugins/UnsuppressEmbeds.tsx
> +    const { message: { embeds, flags } } = props;
And this (forgot, sorry)
```suggestion
    const { message: { embeds, flags, author } } = props;
    const channel = ChannelStore.getChannel(props.channel.id);
```

2023-06-11 17:46 UTC, HypedDomi commented
Completely forgot about DMs 😅

2023-06-11 21:01 UTC, Vendicated requested changes

2023-06-11 21:01 UTC, Vendicated commented on src/plugins/UnsuppressEmbeds.tsx
> +    const menuItem = (() => {
this is kinda weird, why not skip this entirely and call children.push() inline?

2023-06-11 21:03 UTC, Vendicated commented
i think the current position is meh, it would be much better above delete message

Also would possibly make more sense being red? And finally adding an icon for proper consistency would be nice 
![image](https://github.com/Vendicated/Vencord/assets/45497981/cf83ab17-b663-4900-a7cd-96acbcb8ce7d)

2023-06-11 23:41 UTC, HypedDomi commented
It's now red for suppressing embeds and in the normal color for unsuppressing. I couldn't find a matching icon tho

2023-06-11 23:45 UTC, HypedDomi commented
<details>
<summary>Unsuppressed Embed</summary>

![image](https://github.com/Vendicated/Vencord/assets/50876016/0ffc6ee8-d470-4b3c-ac14-f229948e7d66)

</details>

<details>
<summary>Suppressed Embed</summary>

![image](https://github.com/Vendicated/Vencord/assets/50876016/c007ab48-1bb1-4719-808e-e18e085811a1)

</details>

2023-06-12 22:59 UTC, Vendicated commented
still needs an icon cause right now it looks reaaally out of place

2023-06-12 23:01 UTC, Vendicated commented
how about this from the HideAttachments plugin? You can move it from HideAttachments to components/Icons

![image](https://github.com/Vendicated/Vencord/assets/45497981/e5c36865-fb03-41a7-a359-e739bfcb9395)

2023-06-13 01:11 UTC, Vendicated commented on src/plugins/UnsuppressEmbeds.tsx
> +    if (!canManageMessages && !isOwnDM) return;
couldn't these checks be removed? If the delete message button exists, you have perms

2023-06-13 01:13 UTC, HypedDomi commented on src/plugins/UnsuppressEmbeds.tsx
> +    if (!canManageMessages && !isOwnDM) return;
The Button also exists for your own Messages when you don’t have perms

2023-06-15 01:17 UTC, Vendicated approved these changes

2023-06-15 01:18 UTC, merged