add setting to switch viewRaw button
Vendicated/Vencord pull request #1263
Opened 2023-06-11 02:56 UTC by RadNotRed

2023-06-11 21:12 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +        description: "Click method",
this is very meaningless. You should give it a better name

2023-06-11 21:13 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +            { label: "Right Click", value: "Right", default: true },
Same as above. 
```suggestion
            { label: "Right Click to copy", value: "Right", default: true },
```

2023-06-11 21:13 UTC, Vendicated requested changes

2023-06-11 21:13 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +                if (Settings.plugins.ViewRaw.clickMethod === "Left") {
```suggestion
                if (settings.store.clickMethod === "Left") {
```

2023-06-11 21:13 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +                if (Settings.plugins.ViewRaw.clickMethod === "Right") {
```suggestion
                if (settings.store.clickMethod === "Right") {
```

2023-06-11 21:13 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +            const label = Settings.plugins.ViewRaw.clickMethod === "Left"
```suggestion
            const label = settings.store.clickMethod === "Left"
```

2023-06-11 22:40 UTC, RadNotRed commented on src/plugins/viewRaw.tsx
> +            { label: "Right Click", value: "Right", default: true },
I realized that I was doing it backwards, so I just switched the buttons around because it's called viewRaw and not copyRaw

2023-06-12 23:03 UTC, Vendicated approved these changes

2023-06-12 23:03 UTC, Vendicated commented
Please don't pr from the main branch in the future

2023-06-12 23:05 UTC, merged

2023-06-12 23:05 UTC, Vendicated commented
thank you!!