feat(api): add Clipboard entry in webpack common
Vendicated/Vencord pull request #127
Opened 2022-10-20 16:07 UTC by Cynosphere

Gives access to copying on web if browser supports it.

2022-10-20 16:18 UTC, Vendicated commented
Does this just call navigator.clipboard.writeText?

2022-10-20 16:22 UTC, Cynosphere commented
No, it checks if its embedded (desktop app) and uses DiscordNative.copy, otherwise if it can use copy it'll offload to another module that does things with a textarea element and ranges.

I just think it's smarter to use existing function in the client if they exist than relying on DiscordNative.

2022-10-20 22:06 UTC, Vendicated approved these changes

2022-10-20 22:06 UTC, Vendicated requested changes
there are multiple modules matching this filter, I matched some random react component

2022-10-21 22:16 UTC, Vendicated approved these changes

2022-10-21 22:18 UTC, merged