VencordToolbox: rework to add and remove plugin settings (2: electric boogaloo)
Vendicated/Vencord pull request #1320
Opened 2023-06-21 06:38 UTC by Redundakitties

Adds the ability to quick reload discord, toggle css, and check updater tab. Best part is you can add plugin settings to menu using a checkbox dropdown menu. 

You get all of the features of the old PR with all of the same things I do not know to fix! 
- contributors still become bots
- and checkbox menu scrolls to the top every time you add a new plugin

2023-06-21 06:41 UTC, Redundakitties commented on src/components/VencordSettings/UpdaterTab.tsx
> +function updaterBody() {
created something more generic that is used by both updater tab and the updater modal

2023-06-21 06:45 UTC, Redundakitties commented on src/plugins/vencordToolbox/index.tsx
> +    DevCompanion: settingsSwitch("DevCompanion", "DevCompanion", "Reconnect Dev Companion from toolbox"),
I'm unable to use camelCase here because later (in line 81) I'm taking the settingsName of Object.entries(settings.store) and pushing them to a list to later be added to the toolbox modal. Thus their name here has to match their plugin name. I could slap a .toLowerCase() maybe but this is simpler.

2023-07-10 21:14 UTC, Vendicated requested changes

2023-07-10 21:14 UTC, Vendicated commented on src/components/VencordSettings/UpdaterTab.tsx
> +    const updaterContent = updaterBody();
React components should always be created via jsx, not by calling it as a function:
```suggestion
    const updaterContent = <UpdaterBody />;
```

2023-07-10 21:14 UTC, Vendicated commented on src/components/VencordSettings/UpdaterTab.tsx
> +function updaterBody() {
React components should be named in PascalCase

```suggestion
function UpdaterBody() {
```

2023-07-10 21:14 UTC, Vendicated commented on src/components/VencordSettings/UpdaterTab.tsx
> +            {updaterContent}
There doesn't seem to be any reason for this to require a variable, is there?
```suggestion
            <UpdaterContent />
```

2023-07-10 21:14 UTC, Vendicated commented on src/components/VencordSettings/UpdaterTab.tsx
> +                {updaterContent}
same as above

2023-07-10 21:14 UTC, Vendicated commented on src/components/VencordSettings/UpdaterTab.tsx
> +            close={() => closeModal(key)}
there is no need for manually closing. You should instead just use modalProps.onClose()

2023-07-10 21:14 UTC, Vendicated commented on src/plugins/vencordToolbox/index.tsx
> +    relaunchDiscord: settingsSwitch("Relaunch Discord", "relaunchDiscord", "Quit and restart discord from toolbox", IS_WEB),
BOOLEAN settings have recently been changed to switches so using a custom component should now be obsolete

2023-07-10 21:14 UTC, Vendicated commented on src/plugins/vencordToolbox/index.tsx
> +const getAllPlugins = makeLazy(() => Object.values(Vencord.Plugins.plugins));
What's this for? It would be better to just call this at the top of the component

2023-07-10 22:09 UTC, Redundakitties commented on src/plugins/vencordToolbox/index.tsx
Writing reminder to myself to fix needing to hardcode misc plugin actions because it's dumb

2023-07-28 04:53 UTC, Redundakitties reviewed
- Made changes to UpdaterBody creating jsx components and removing custom close from modal
- changed the custom switch to default boolean function
- created a singular for loop to sort all the plugins to their correct display list
- now plugin actions can be added and removed using a checkbox system instead of settings

There are three types of toolbox items:
Plugin Custom Actions (toolbox actions custom set by plugins) 
Plugin Settings (pinning plugin settings for easy access)
App Tools (relaunching discord, checking for updates, Opening QuickCSS)

2026-04-17 23:02 UTC, closed without merging