MessageLogger: Add "Clear Message Log History"
Vendicated/Vencord pull request #1333
Opened 2023-06-23 21:45 UTC by nmsturcke

Clear the Message Log History for a whole channel/user/gdm with one click.

2023-06-23 21:48 UTC, Vendicated requested changes

2023-06-23 21:48 UTC, Vendicated commented on src/plugins/messageLogger/index.tsx
> +                        message.editHistory = [];
this doesn't rerender messages so edits will not properly be removed, no?

2023-06-23 21:48 UTC, Vendicated commented on src/plugins/messageLogger/index.tsx
> +    if (!toDelete.length) return;
shouldn't this be
```suggestion
    if (!toDelete.length && !toClearEditHistory.length) return;
```

2023-06-23 21:48 UTC, Vendicated commented on src/plugins/messageLogger/index.tsx
> +const patchChannelContextMenu: NavContextMenuPatchCallback = (children, props) => () => {
```suggestion
const patchChannelContextMenu: NavContextMenuPatchCallback = (children, { channel }) => () => {
```

2023-06-23 21:56 UTC, nmsturcke commented on src/plugins/messageLogger/index.tsx
> +                        message.editHistory = [];
https://github.com/Vendicated/Vencord/assets/30734036/30e66d44-bea0-47a3-a567-d32dd0e28d4d

2023-06-23 21:57 UTC, Vendicated commented on src/plugins/messageLogger/index.tsx
> +                        message.editHistory = [];
yes, you have to hover it to rerender

2023-06-23 21:58 UTC, nmsturcke commented on src/plugins/messageLogger/index.tsx
> +                        message.editHistory = [];
Ah.. I think it updates when the message is hovered, but I basically just copied what the message CTX Menu does
![7G3cV](https://github.com/Vendicated/Vencord/assets/30734036/83e13970-1616-419d-bfe8-5eb646f0a434)

2023-06-23 21:59 UTC, Vendicated commented on src/plugins/messageLogger/index.tsx
> +                        message.editHistory = [];
yes, but that one is fine because it will always rerender the message after you close the context menu

not the same for the normal chat

2023-06-23 21:59 UTC, nmsturcke commented on src/plugins/messageLogger/index.tsx
> +const patchChannelContextMenu: NavContextMenuPatchCallback = (children, props) => () => {
c35523ac343208947842b52a23ff087b60e859bc

2023-06-24 14:21 UTC, nmsturcke commented on src/plugins/messageLogger/index.tsx
> +                        message.editHistory = [];
Do I just leave this PR sitting here for now?

2023-11-21 16:58 UTC, closed without merging