New Plugin: BetterSessions
Vendicated/Vencord pull request #1339
Opened 2023-06-25 22:16 UTC by PennyBunny

This plugin adds the function to send message notifications to XSOverylay's Notification API over UDP

2023-06-25 22:19 UTC, Vendicated commented
why is udp needed here? You should just use plain fetch or a normal websocket

2023-06-25 22:21 UTC, PennyBunny commented
XSOverlay's notification system uses UDP, I don't really have a choice other than distributing a whole new executable to do IPC over fetch/ws to XSO's UDP server

2023-06-27 03:08 UTC, PennyBunny commented
Ok, that is everything this this needs I think. Should be ready unless there is any more changes you guys need.

2023-06-27 20:55 UTC, Vendicated requested changes

2023-06-27 20:55 UTC, Vendicated commented on src/main/ipcPlugins.ts
> +import dgram from "dgram";
nit
```suggestion
import { createSocket } from "dgram";
```

2023-06-27 20:55 UTC, Vendicated commented on src/main/ipcPlugins.ts
> +ipcMain.handle(IpcEvents.DGRAM_SEND, (_, data) => dgramSend(data));
why not inline this?
```suggestion
ipcMain.handle(IpcEvents.DGRAM_SEND, (_, data) => {
	...
});
```

2023-06-27 20:55 UTC, Vendicated commented on src/plugins/xsoverlay.discordDesktop.ts
> +        markers: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
```suggestion
        markers: makeRange(0, 1, 0.1)
```

2023-06-27 20:55 UTC, Vendicated commented on src/plugins/xsoverlay.discordDesktop.ts
> +function supposedToNotify(message, channel) {
```suggestion
function shouldNotify(message, channel) {
```

2023-06-27 20:55 UTC, Vendicated commented on src/plugins/xsoverlay.discordDesktop.ts
> +    if (content.length <= 100) {
nit: These could just be plain ifs
```js
if (content.length <= 100) return 100;
if (content.length <= 200) return 150;
if (content.length <= 300) return 200;
return 250;
```

2023-06-27 20:55 UTC, Vendicated commented on src/plugins/xsoverlay.discordDesktop.ts
> +    return content.replace(new RegExp("<[^>]*>", "g"), "");
this seems to completely remove stuff like emojis, mentions, etc

Why not instead transform these to human readable ones? For mentions, the username, for emotes the emoji name, etc

Otherwise `@jeff told me that @john did a very bad thing` suddenly becomes `told me that did a very bad thing` and suddenly it makes no sense anymore

2023-06-27 20:55 UTC, Vendicated commented on src/plugins/xsoverlay.discordDesktop.ts
> +            const author = UserStore.getUser(message.author.id);
what's this for? message.author is already a full user

2023-06-27 21:12 UTC, PennyBunny commented on src/plugins/xsoverlay.discordDesktop.ts
> +    return content.replace(new RegExp("<[^>]*>", "g"), "");
This is only used to calculate the height.

2023-06-29 13:07 UTC, Vendicated commented on src/main/ipcPlugins.ts
> +    const client = createSocket("udp4");
wouldn't it be better to keep the socket alive instead of constantly recreating and closing it?

2023-06-29 13:09 UTC, Vendicated commented on src/plugins/xsoverlay.discordDesktop.ts
> +                finalMsg += " [sticker] ";
why not include the sticker name?

2023-06-29 14:24 UTC, PennyBunny commented on src/main/ipcPlugins.ts
> +    const client = createSocket("udp4");
I did this so people who didn't have the plugin enabled would not have a socket sitting around, but I don't know much about ts so if its not a big deal to just make it at the beginning then I can do that.

2023-06-29 14:28 UTC, PennyBunny commented on src/plugins/xsoverlay.discordDesktop.ts
> +                finalMsg += " [sticker] ";
it would just be message.stickers.name? right?

2023-06-29 14:29 UTC, Vendicated commented on src/main/ipcPlugins.ts
> +    const client = createSocket("udp4");
you can just lazy initialise it
```js
let xsoSocket: SomeTypeIdk;

ipcMain.handle(... => {
	xsoSocket ??= createSocket("udp4");
})

2023-07-13 23:15 UTC, Vendicated commented
Is this even ready or still a draft? Considering there are several TODO comments

2023-07-14 00:16 UTC, PennyBunny commented
Sorry this is a draft, should I convert it to a draft pr?

2023-07-14 01:48 UTC, Vendicated commented
Yes please! That makes it easier for me to keep track. Let me know once it's ready :3

2023-09-07 16:09 UTC, closed without merging