moarKaomojis plugin
Vendicated/Vencord pull request #135
Opened 2022-10-21 20:43 UTC by Jacob1Tm

moar Kaomojis <(￣︶￣)> ~~hope someone will accept it lol~~

2022-10-21 22:14 UTC, Vendicated requested changes

2022-10-21 22:14 UTC, Vendicated commented on src/plugins/moarKaomojis.ts
> +        Devs.echo,
?

2022-10-21 22:14 UTC, Vendicated commented on src/plugins/moarKaomojis.ts
> +            description: "＞﹏＜",
since these are all the same, you could use a .map like

```js
commands: [
  { name: "name", description: "emoji" },
  { name: "other name", description: "other emoji"},
].map(data => ({
   ...data,
   options: [OptionalMessageOption],
   execute: opts => ({
       content: findOption(opts, "message", "") + data.description
    })
})
```

2022-10-22 09:13 UTC, Jacob1Tm commented on src/plugins/moarKaomojis.ts
> +        Devs.echo,
?

2022-10-22 09:13 UTC, Jacob1Tm commented on src/plugins/moarKaomojis.ts
> +            description: "＞﹏＜",
sure

2022-10-22 09:19 UTC, somerandomcloud commented on src/plugins/moarKaomojis.ts
> +        Devs.echo,
Why is echo listed

2022-10-22 09:33 UTC, Jacob1Tm commented on src/plugins/moarKaomojis.ts
> +        Devs.echo,
i used more commands plugin for this and forgot to delete this lol

2022-10-22 10:40 UTC, Vendicated commented
122 files changed whaaaaaa

2022-10-22 11:39 UTC, MeguminSama commented
horror

2022-10-22 12:25 UTC, botatooo commented on browser/VencordNativeStub.ts
> +    [IpcEvents.GET_REPO]: () => "", // TODO
this would like, break the updator no?

2022-10-22 12:27 UTC, botatooo commented on scripts/patcher/common.js
> -            { title: "Specify custom path", info: "custom" },
why remove custom path

2022-10-22 12:30 UTC, botatooo commented
this does like, everything except add a plugin
horror

2022-10-22 12:30 UTC, Jacob1Tm commented
> this does like, everything except add a plugin horror

sorry i fucked up with one thing...

2022-10-22 12:30 UTC, closed without merging

2022-10-22 12:36 UTC, Jacob1Tm commented
someone please remove that ;<