moarKaomojis plugin
Vendicated/Vencord pull request #137
Opened 2022-10-22 12:34 UTC by Jacob1Tm

~~yes again sorry for that~~

2022-10-22 14:51 UTC, botatooo approved these changes

2022-10-22 15:44 UTC, MeguminSama requested changes
Please fix the linting errors flagged by the GitHub Action. Otherwise, LGTM.

2022-10-22 15:44 UTC, MeguminSama commented on src/plugins/moarKaomojis.ts
> +        { name: "dissatisfaction", description: "＞﹏＜"},
This one doesn't have a space at the start of the description

2022-10-24 16:06 UTC, MeguminSama commented
If you run `pnpm lint:fix` it should resolve the linting issues

2022-10-26 13:38 UTC, Vendicated approved these changes

2022-10-26 13:38 UTC, merged