feat(plugin): Favorite Gif Search
Vendicated/Vencord pull request #1386
Opened 2023-07-06 18:22 UTC by Syncxv

lets you search your favorite gifs

idea: https://github.com/Vendicated/Vencord/discussions/1385

https://github.com/Vendicated/Vencord/assets/47534062/e4905548-0800-4b10-ba09-ff15da6f16da

2023-07-06 18:23 UTC, Vendicated commented
holy shit

2023-07-06 18:42 UTC, Vendicated requested changes

2023-07-06 18:42 UTC, Vendicated commented on src/plugins/favGifSearch.tsx
> +interface Sizes {
nit: this could be better written as
```suggestion
type Sizes = Record<"SMALL" | "MEDIUM" | "LARGE", string>;
```

2023-07-06 18:42 UTC, Vendicated commented on src/plugins/favGifSearch.tsx
> +    renderSearchBar: (instance: Instance) => instance.state?.resultType === "Favorites" ? <SearchBar instance={instance} /> : null
```suggestion
    renderSearchBar: ErrorBoundary.wrap((instance: Instance) => instance?.state?.resultType === "Favorites" ? <SearchBar instance={instance} /> : null, { noop: true })
```

2023-07-06 18:42 UTC, Vendicated commented on src/plugins/favGifSearch.tsx
> +        if (!props.originalFav) props.originalFav = props.favorites;
```suggestion
        props.originalFav ||= props.favorites;
```

2023-07-06 18:42 UTC, Vendicated commented on src/plugins/favGifSearch.tsx
> +                replace: "$1[$self.renderSearchBar(this), $2]}"
i don't like the way this patch works. Wouldn't it be way easier to patch renderHeaderContent?

the FAVORITES case (frame 1) would only need to be changed to return the SearchBar similar to in frame 2. Then you could even capture the SearchBar component instead of having to webpack find it

![image](https://github.com/Vendicated/Vencord/assets/45497981/0ee6542c-38ca-45a0-b491-767c0f818078)

2023-07-06 19:37 UTC, Syncxv commented on src/plugins/favGifSearch.tsx
> +                replace: "$1[$self.renderSearchBar(this), $2]}"
alright i tried doing that. what do you think?

2023-07-07 07:49 UTC, MaddyUnderStars commented
holy shit that was fast. thanks

2023-07-07 08:13 UTC, MaddyUnderStars commented on src/plugins/favGifSearch.tsx
> +            }
while using `.includes` works, wouldn't it be better to do, say, fuzzy find instead? or similar? perhaps a lil sneaky matching of individual words? idk.
otherwise searching for gifs you don't remember the URL of will be slightly annoying, you'll need to search for 1 word only since you might be wrong on the order of words perhaps. also it prevents queries like `tenor cat` or `discord dog`.
also also shouldn't you replaceAll `-` with spaces for convenience?

regardless: thank you very much. this has bothered me for so long lol

2023-07-07 16:41 UTC, Syncxv commented on src/plugins/favGifSearch.tsx
> +            }
thanks

2023-07-07 16:47 UTC, Syncxv commented
alright i think adding the dropdown in the gif picker is a bad idea.

The problem is that the Select component uses a popout to render its items, and having a popout within a popout makes it difficult to select any of the items in the dropdown

I have a fix but implementing it in this plugin may not be the best idea

so basically its because of `target === g.current` the target doenst match the current active element, which makes discord think we clicked outside the gif picker and causes it to be closed.

```js
// WebpackModule656823 line 7440
handleDocumentMouse = o.useCallback(function (e) {
    if (!hasAnyModalOpen()) {
        var target = e.target;
        if (/* ... */) {
            for (; (0, ko.k)(target); ) {
                // HERE is the issue. when we click the options in the select dropdown these 2 dont match and closes the gif picker
                if (target === g.current) return;
                // we need to add data-menu-item="true" to the options but we can only render teh labels not the actual option container :pensive:
                if ("true" === target.getAttribute("data-menu-item")) return;
                // ...
                target = target.parentNode;
            }
            (0, Do._Q)(); // Close gif picker
            // ...
        }
    }
}, [/* ... */]);

o.useLayoutEffect(function () {
    // ...
    P.addEventListener("mousedown", handleDocumentMouse);
    P.addEventListener("contextmenu", handleDocumentMouse);
    // ...
    return function () {
        P.removeEventListener("mousedown", handleDocumentMouse);
        P.removeEventListener("contextmenu", handleDocumentMouse);
        // ...
    };
}, [/* ... */]);


```

so the solution is either to patch the select component and add `data-menu-item="true"` to each option container or patch this function
i dont like either of these options and i think we shouldnt add the dropdown

I tried to fix it by using the renderOptionLabel prop of the Select component, but this did not work as expected. The first element does not work when other items are selected. also if we do `pointer-events: all` then the hover stuff wont work for the options 😔 

Here is the code I tried
```tsx
<Select
    // ...
    renderOptionLabel={option => {
        return (
            <>
                <div data-menu-item={true} style={{ position: "absolute", top: "0", left: "0", width: "100%", height: "100%", zIndex: "9999", pointerEvents: "none" }} />
                <div data-menu-item={true}>
                    {option.label}
                </div>
            </>
        );
    }}
    // ...
/>
```

but if there is another way to render the dropdown in a popout let me know

2023-07-08 00:41 UTC, Vendicated commented on src/plugins/favGifSearch.tsx
> +                label: "Host Only (tenor.com)",
this honestly seems useless

2023-07-10 20:38 UTC, Vendicated commented on src/plugins/favGifSearch.tsx
> +        options: [
shouldn't this specify a default option?

2023-07-25 23:49 UTC, Vendicated commented
thank you! i am too lazy to review further so i will just merge :trollface:

2023-07-25 23:50 UTC, merged