Add a "NEW" Badge for New Plugins
Vendicated/Vencord pull request #141
Opened 2022-10-22 19:50 UTC by nmsturcke

People don't have to look through commits anymore, they can just see the **NEW** Badge on recently added plugins and activate the new features Vencord brings!

> *Note: [common.mjs](/Vendicated/Vencord/tree/main/scripts/build/common.mjs) has been reformatted (automatically) by my formatter, I assume it previously didn't meet styleguide in the [Contribution Guide](/Vendicated/Vencord/tree/main/CONTRIBUTING.md)*

*Ps. Feel free to bully and correct my ~~horrendous~~ code*

![image](https://user-images.githubusercontent.com/30734036/197359709-91f664ca-060f-4adc-af07-d6b851915e9a.png)

![image](https://user-images.githubusercontent.com/30734036/197359706-549283bd-a8a1-4562-92c6-81d70738fc13.png)

2022-10-22 19:52 UTC, botatooo commented
can't you just webppack get the component instead of recreating it?

2022-10-22 20:11 UTC, Vendicated commented
> Note: [common.mjs](https://github.com/Vendicated/Vencord/tree/main/scripts/build/common.mjs) has been reformatted (automatically) by my formatter, I assume it previously didn't meet styleguide in the [Contribution Guide](https://github.com/Vendicated/Vencord/tree/main/CONTRIBUTING.md)

it does meet it, you're just using prettier. Use the vscode formatter

2022-10-22 20:12 UTC, Vendicated commented
Please use asynchronous fs apis from fs/promises

2022-10-22 21:02 UTC, nmsturcke commented
> Please use asynchronous fs apis from fs/promises

Updated & Resolved conflicts

2022-10-22 21:55 UTC, Vendicated commented on scripts/build/common.mjs
> +                            (new Date(stats.birthtime.valueOf()).setDate(
please refactor this to use a variable and be less unreadable

2022-10-22 21:57 UTC, Vendicated commented
Also fix lint and undo all the formatting changes, the easiest way would probably be to copy your changes, reset then paste them again

2022-10-23 12:02 UTC, nmsturcke commented on scripts/build/common.mjs
> +                            (new Date(stats.birthtime.valueOf()).setDate(
> please refactor this to use a variable and be less unreadable

Hopefully it's more readable now?

2022-10-23 12:07 UTC, nmsturcke commented
New view after resolving conflicts:

![image](https://user-images.githubusercontent.com/30734036/197391188-618e3bdb-755a-4f05-9c64-e602d1f8da81.png)

2022-10-23 12:34 UTC, Vendicated commented
that looks nice but what happens if the name is very long

2022-10-23 12:48 UTC, nmsturcke commented
> that looks nice but what happens if the name is very long

![image](https://user-images.githubusercontent.com/30734036/197393019-84c005a0-d78f-4ff9-9232-c7a556e23ed1.png)

2022-10-23 12:49 UTC, nmsturcke commented
Let me add some more space in between the text and badge

2022-10-23 13:41 UTC, nmsturcke commented
Can do this
![image](https://user-images.githubusercontent.com/30734036/197395593-e73d6887-0516-46d4-9a0c-5484adb4001a.png)

2022-10-23 17:20 UTC, nmsturcke commented
@Vendicated

2022-10-23 17:20 UTC, somerandomcloud commented
bro?

2022-10-28 21:16 UTC, Cynosphere requested changes

2022-10-28 21:16 UTC, Cynosphere commented on src/components/PluginSettings/components/NewBadge.tsx
> +        <div style={{ backgroundColor: "#ED4245", justifySelf: "flex-end", marginLeft: "auto" }} className="textBadge-1fdDPJ base-3IDx3L baseShapeRound-3epLEv">New</div>
Don't hardcode class names, use `findByProps` to find them.

2022-10-29 14:21 UTC, KraXen72 commented
please make it so the distance between your badge and settings is the same as distance between settings and switch.

right now it looks inconsistent.

2022-10-30 19:20 UTC, nmsturcke commented on src/components/PluginSettings/components/NewBadge.tsx
> +        <div style={{ backgroundColor: "#ED4245", justifySelf: "flex-end", marginLeft: "auto" }} className="textBadge-1fdDPJ base-3IDx3L baseShapeRound-3epLEv">New</div>
Would it be better if I style it instead of applying discord's class to avoid changes in the future?

2022-10-30 19:24 UTC, nmsturcke commented
![image](https://user-images.githubusercontent.com/30734036/198897616-77794ef7-379a-4c64-8396-8ec7a063d7fc.png)

2022-10-31 09:18 UTC, KraXen72 commented
idk If the screenshot is meant to be updated;

i didn't mean equal padding/margin values,
i meant to have exactly the same amount of pixels in gaps between the 3 buttons, achieved however it is sensible to do.

2022-10-31 09:19 UTC, KraXen72 commented
![Screenshot_20221031-101911_DuckDuckGo.png](https://user-images.githubusercontent.com/21956756/198974124-3a5f8eef-42ba-4c5e-91d0-dd4feb8a8b90.png)

2022-10-31 11:03 UTC, nmsturcke commented
> idk If the screenshot is meant to be updated;
> 
> i didn't mean equal padding/margin values, i meant to have exactly the same amount of pixels in gaps between the 3 buttons, achieved however it is sensible to do.

Ohh, I thought you meant space between the text and new badge should be the same as between the badge and the settings icon. Let me make it the same as what you say, whoopsies.

2022-10-31 11:09 UTC, nmsturcke commented
![image](https://user-images.githubusercontent.com/30734036/198994685-09b44191-1cc4-4062-a4dc-c5f3dc81d51a.png)

2022-10-31 15:58 UTC, KraXen72 commented
very nice! thx

2022-11-03 07:22 UTC, somerandomcloud approved these changes

2022-11-21 15:57 UTC, closed without merging