New Plugin: Discord Colorways
Vendicated/Vencord pull request #1448
Opened 2023-07-18 12:44 UTC by DaBluLite

A very early version of the plugin, until I port the UIs and more features from the BD version.

2023-07-20 20:19 UTC, DaBluLite commented
"wow, such empty"

2023-08-10 01:49 UTC, Vendicated commented on src/plugins/discordColorways/index.tsx
> +                    document.getElementById("activeColorwayCSS")!.innerHTML = foundColorway;
this is very dangerous (remote code execution)

2023-08-10 06:44 UTC, DaBluLite commented on src/plugins/discordColorways/index.tsx
> +                    document.getElementById("activeColorwayCSS")!.innerHTML = foundColorway;
when you say remote code, you mean the imports, and the json file?
Cause this is literally how the plugin works, everything comes from the same repo
(except for like 1 colorway, which is again from one of my repos)

2023-08-10 08:23 UTC, DaBluLite commented
Ok so I finished with the main changes, as well as bumping the fork

2023-08-10 08:27 UTC, DaBluLite commented on src/plugins/discordColorways/index.tsx
> +                    document.getElementById("activeColorwayCSS")!.innerHTML = foundColorway;
I changed it to innertext, no idea if that'll help

2023-08-10 12:16 UTC, DaBluLite commented on src/plugins/discordColorways/index.tsx
> +                    document.getElementById("activeColorwayCSS")!.innerHTML = foundColorway;
I think I should resolve this conversation 💀
![image](https://github.com/Vendicated/Vencord/assets/73998678/5276f14d-718f-4e1d-8a7a-b6da57ec9cfb)

2023-09-01 17:38 UTC, DaBluLite commented
bump, I guess

2023-10-06 23:43 UTC, DaBluLite commented
bump, I guess (x2)

2023-10-13 08:22 UTC, DaBluLite commented
Day 87 of waiting for a plugin review

2023-10-13 15:48 UTC, lewisakura requested changes
overall, a lot of this code needs to be rewritten to use `async/await` - there's a lot of deeply nested promises that can be made a lot nicer.

also, this code is *very* dense to read, so if you could add linebreaks just to help with readability that would be great

2023-10-13 15:48 UTC, lewisakura commented on src/plugins/discordColorways/components/selectorModal.tsx
> +                        </div>
```suggestion

```

we don't have changelogs for plugins, i don't see why colorways would be any different

2023-10-13 15:48 UTC, lewisakura commented on README.md
> +
```suggestion
```

2023-10-13 15:48 UTC, lewisakura commented on README.md
> +## Join Vencord's Support/Community Server
```suggestion
## Join our Support/Community Server
```

2023-10-13 15:48 UTC, lewisakura commented on src/plugins/discordColorways/components/icons.tsx
hmm.. wonder if these would be useful to put into `src/components/Icons.tsx` ?

2023-10-13 15:48 UTC, lewisakura commented on src/plugins/discordColorways/components/spinner.tsx
> +}
please do not hardcode discord's class names and redefine them if you aren't going to be using their icon component, otherwise they will break when the CSS identifiers change

2023-10-13 15:48 UTC, lewisakura commented on src/plugins/discordColorways/style.css
> +    clip-path: path('M 12 7.5 C 13.242188 7.5 14.25 6.492188 14.25 5.25 C 14.25 4.007812 13.242188 3 12 3 C 10.757812 3 9.75 4.007812 9.75 5.25 C 9.75 6.492188 10.757812 7.5 12 7.5 Z M 18 12 C 19.242
can't you use `<clipPath>` ?

2023-10-13 17:31 UTC, DaBluLite commented on README.md
> +
Tbh, I don't have a good reason for why I added it

2023-10-13 17:32 UTC, DaBluLite commented on src/plugins/discordColorways/components/icons.tsx
I was trying to avoid adding/changing too much outside of the plugin folder, but I will try it

2023-10-13 17:32 UTC, DaBluLite commented on src/plugins/discordColorways/components/spinner.tsx
> +}
I will prob try to find the module that provides this, or make custom classes

2023-10-13 18:29 UTC, DaBluLite reviewed
Why are these outdated?

2023-10-16 17:10 UTC, DaBluLite commented
> overall, a lot of this code needs to be rewritten to use `async/await` - there's a lot of deeply nested promises that can be made a lot nicer.
> 
> also, this code is _very_ dense to read, so if you could add linebreaks just to help with readability that would be great

The promise issue has been resolved, I believe, for the most part, if not entirely. As for the unreadability of the code, part of the problem has been resolved, thanks to Arjix, who was kind enough to go through my spaghetti code and clean it up

2024-01-06 18:35 UTC, DaBluLite commented
Bump

2024-04-23 12:36 UTC, DaBluLite commented
bump

2024-05-31 20:32 UTC, DaBluLite commented
Sorry to bump this, but could someone review this? It's been kind of stuck in this state of limbo for a few months now

2024-06-07 11:59 UTC, DaBluLite commented
Sorry to bump this, but could someone review this? It's been kind of stuck in this state of limbo for a few months now (x2, seriously I resolved the requested changes almost 8 months ago)

2024-09-30 17:45 UTC, JustOptimize commented
Sad life lol

2024-09-30 17:54 UTC, DaBluLite commented
At this point it's been over a year since I've opened the pr, though I can't really complain. This is a very niche plugin, and there are many more open PRs for important features and plugins. All I can do is be patient.

2024-09-30 17:56 UTC, programminglaboratorys commented
> At this point it's been over a year since I've opened the pr, though I can't really complain. This is a very niche plugin, and there are many more open PRs for important features and plugins. All I can do is be patient.

the only thing you can do is hope and refactor

2024-09-30 18:19 UTC, schoeneBiene reviewed
plugins need a README.md file

2024-09-30 18:19 UTC, schoeneBiene commented on src/plugins/discordColorways/index.tsx
> +        "Open Settings": () => SettingsRouter.open("ColorwaysSettings"),
i don't think having the settings in the toolbox is needed (imagine if every plugin did that)

2024-09-30 18:19 UTC, schoeneBiene commented on src/plugins/discordColorways/components/ColorwaysButton.tsx
> +    return (visibility || PluginProps.clientMod === "BetterDiscord") ? <ListItem
```suggestion
    return (visibility) ? <ListItem
```

2024-09-30 18:22 UTC, DaBluLite commented on src/plugins/discordColorways/index.tsx
> +        "Open Settings": () => SettingsRouter.open("ColorwaysSettings"),
fair enough, didn't think about that

2024-09-30 18:24 UTC, DaBluLite commented on src/plugins/discordColorways/components/ColorwaysButton.tsx
> +    return (visibility || PluginProps.clientMod === "BetterDiscord") ? <ListItem
This s there because the core of the plugin is shared between the vencord and bd versions, with the only different part being the index

2024-09-30 18:25 UTC, DaBluLite commented on src/plugins/discordColorways/index.tsx
> +            predicate: () => true
Prob because I didn't know at the time how they worked, will remove it

2024-09-30 18:31 UTC, DaBluLite commented on src/plugins/discordColorways/index.tsx
> +};
That is for plugin UIs and is unique to each client mod (BD, vencord, vc userplugin)

2024-09-30 18:34 UTC, DaBluLite commented on src/plugins/discordColorways/index.tsx
> +};
the plugin version is to indicate any sort of change or bug fix, UI version is for, well, UI, and CSS version is to indicate that the CSS generator code has been updated (which is the most important)

2024-09-30 19:47 UTC, DaBluLite commented on README.md
> +## Note, this is an unofficial fork of Vencord for an offcial port of the DiscordColorways plugin from BetterDiscord. This repo might be behind the main repo at times and its usage is meant for devel
This has been removed

2024-09-30 19:47 UTC, DaBluLite commented on src/plugins/discordColorways/index.tsx
> +            predicate: () => true
Fixed

2024-09-30 19:47 UTC, DaBluLite commented on src/plugins/discordColorways/index.tsx
> +        "Open Settings": () => SettingsRouter.open("ColorwaysSettings"),
Removed

2024-09-30 21:46 UTC, closed without merging

2024-09-30 21:46 UTC, Vendicated commented
okay i gotta keep it real with you: due to the sheer volume of code, the odds of this getting merged are near zero, sorry :( good job on improving the code quality though!

i know it kinda sucks, especially due to the lack of support for external plugins. but it seems like the plugin has at least found a home in the third party plugins channel ~ maybe in the future we can have a section for them on the vencord site

on a side note, i'm also uncertain about how useful this as a plugin is anyway ~ is this not just a theme generator? what makes it better than the popular BD theme editor?
why does this have to be a plugin instead of an external website that gives the user a theme file to use? making a website seems like it would give you much more control over your code and possibilities as to what you can do

2024-10-01 02:09 UTC, DaBluLite commented
I'm happy I was at least told that. Thank you for letting me know, vee