Plugin Addition: copyProfileThemes
Vendicated/Vencord pull request #1452
Opened 2023-07-18 21:40 UTC by KannaDev

This plugin adds the ability to copy profile themes from the context menu, and then output the result via Clyde. Was requested to do it by someone so I decided to add it as it makes it easier than running via console.
All files were linted prior to commit, and any feedback or changes are welcome.

In Guild:
![image](https://github.com/Vendicated/Vencord/assets/65371696/2908db76-a370-44d4-8b14-eb2a7296b4e0)
In DM's / Group Chats:
![image](https://github.com/Vendicated/Vencord/assets/65371696/e5626042-99da-40c8-918d-87cb29676563)
If none found:
![image](https://github.com/Vendicated/Vencord/assets/65371696/b0f00ffa-c584-44d2-ae06-67c2b762f080)

2023-07-18 21:41 UTC, KannaDev commented
Also I kinda forgot to generate a new GPG key to verify commits, and if you wish I can make a new commit with them verified.

2023-08-04 18:05 UTC, Vendicated requested changes, later dismissed

2023-08-04 18:05 UTC, Vendicated commented on src/plugins/copyProfileThemes.tsx
> +        const fetchProfileTheme = async (id: string, guildId: string | null = null) => {
please declare functions on the top level unless there is a good reason not to

2023-08-04 18:05 UTC, Vendicated commented on src/plugins/copyProfileThemes.tsx
> +    name: "copyProfileThemes",
```suggestion
    name: "CopyProfileThemes",
```

2023-08-04 18:05 UTC, Vendicated commented on src/plugins/copyProfileThemes.tsx
> +            if (userProfile && userProfile.themeColors && userProfile.themeColors.length >= 2) {
```suggestion
            if (userProfile.themeColors.length >= 2) {
```

2023-08-04 18:05 UTC, Vendicated commented on src/plugins/copyProfileThemes.tsx
> +            if (themeString === "") {
```suggestion
            return themeString || "No theme..."
```

2023-08-04 18:05 UTC, Vendicated commented on src/plugins/copyProfileThemes.tsx
> +                                console.log(theme);
```suggestion
```

2023-08-04 20:55 UTC, KannaDev commented on src/plugins/copyProfileThemes.tsx
> +                                console.log(theme);
Removed.

2023-08-04 20:57 UTC, KannaDev commented on src/plugins/copyProfileThemes.tsx
> +            if (userProfile && userProfile.themeColors && userProfile.themeColors.length >= 2) {
Changing this causes issues with sending the hex colours, or error message. So I have left it as is.

2023-08-04 20:58 UTC, KannaDev commented on src/plugins/copyProfileThemes.tsx
> +            if (themeString === "") {
Modified.

2023-08-04 20:58 UTC, KannaDev commented on src/plugins/copyProfileThemes.tsx
> +    name: "copyProfileThemes",
Edited

2023-08-04 20:58 UTC, KannaDev commented on src/plugins/copyProfileThemes.tsx
> +        const fetchProfileTheme = async (id: string, guildId: string | null = null) => {
Done

2023-08-12 00:38 UTC, Vendicated commented on src/plugins/copyProfileThemes.tsx
> +            if (userProfile && userProfile.themeColors && userProfile.themeColors.length >= 2) {
please explain? this code is equivalent

2023-08-12 00:40 UTC, Vendicated commented on src/plugins/copyProfileThemes.tsx
> +            if (userProfile && userProfile.themeColors && userProfile.themeColors.length >= 2) {
oh im stupid i gave the wrong suggestion i meant `userProfile?.themeColors?.length >= 2`

2023-08-12 01:36 UTC, KannaDev commented on src/plugins/copyProfileThemes.tsx
> +            if (userProfile && userProfile.themeColors && userProfile.themeColors.length >= 2) {
just tested and works fine with what you just provided so gonna push that

2023-08-12 01:39 UTC, KannaDev commented
@Vendicated if you got anymore changes lmk

2023-09-04 02:16 UTC, KannaDev commented
@Vendicated Mentioning just to bump.

2023-09-07 18:48 UTC, KannaDev commented
Chance this merge broke it so will need to review it to check.

2023-10-18 22:42 UTC, Vendicated commented
Please add a README.md!

Additionally, the current name is a bit misleading since it does not actually copy anything, maybe you have a better idea for a name?

2024-05-11 22:52 UTC, Vendicated commented
hii hazel, still got interest in finishing this up? i left a comment requesting small final changes but you never replied

codewise this is good now so it'll definitely be merged if those things are resolved

my apologies for getting back to you so late back then, i guess that might be why

2024-05-11 22:54 UTC, Vendicated commented
also probably would be better to move it here instead? the normal user context menu is already soo full

![image](https://github.com/Vendicated/Vencord/assets/45497981/c51e3461-d93c-4b7c-980a-6cfc100f780a)

2024-10-10 19:33 UTC, kisames commented
how can i use this plugin?

2026-07-27 18:05 UTC, closed without merging