Replace plugin list link
Vendicated/Vencord pull request #151
Opened 2022-10-23 18:13 UTC by somerandomcloud

Replaces plugin list link with a gist with a list of all plugins with authors and descriptions instead of having to go into each file

2022-10-23 18:16 UTC, MeguminSama requested changes

2022-10-23 18:16 UTC, MeguminSama commented on README.md
> +-   Many Useful™ plugins - [List](https://gist.github.com/somerandomcloud/3287ceee0813c2aa4972a4defe0a2d82)
Why would you do this instead of just making a .md file in the repo (possibly in the docs folder)? We don't want to be linking to third-party resources for security reasons.

2022-10-23 18:21 UTC, somerandomcloud commented on README.md
> +-   Many Useful™ plugins - [List](https://gist.github.com/somerandomcloud/3287ceee0813c2aa4972a4defe0a2d82)
Fair :shrimp:

2022-10-23 18:42 UTC, Vendicated commented
now also add a script to do this automatically

2022-10-23 18:46 UTC, somerandomcloud commented
its already automatic, but the way I did it is so dodgy i dont know how to make it a workflow

Script: https://github.com/somerandomcloud/vencord-plugin-list

2022-10-25 08:09 UTC, ArjixWasTaken commented
Sighs, this is a really bad way of doing this...

2022-10-25 08:15 UTC, D3SOX commented
Just make a GitHub action maybe

2022-10-25 09:36 UTC, ArjixWasTaken commented
> Just make a GitHub action maybe

I did not comment about that, the code he wrote to generate the readme is...

2022-10-25 09:44 UTC, D3SOX commented
@ArjixWasTaken Wasn't really related to your comment. I just wanted to say that this could just be done with an action using a script

2022-10-25 09:45 UTC, ArjixWasTaken commented
> @ArjixWasTaken Wasn't really related to your comment. I just wanted to say that this could just be done with an action using a script

Oh, I assumed you replied to me since the author of this PR himself said that he doesn't know how to make workflows.

So saying "just make a workflow" to him doesn't make sense...

2022-10-25 09:47 UTC, D3SOX commented
Oh sry I didn't see this
> i dont know how to make it a workflow

2022-10-25 10:20 UTC, closed without merging