feat(plugin): CustomBadges
Vendicated/Vencord pull request #1573
Opened 2023-07-30 08:09 UTC by PFearr

Just a simple plugin that allows the user to create/remove custom badges to the user of their choice.
https://cdn.discordapp.com/attachments/661033414207602698/1135120974187085865/20230730-0801-15.1092885.mp4

2023-07-30 08:36 UTC, ryanccn commented
https://github.com/Vendicated/Vencord/pull/375#issuecomment-1586122860

> Badges are a way to denote people who contributed in certain ways

2023-07-30 08:39 UTC, ActuallyTheSun commented
> https://github.com/Vendicated/Vencord/pull/375#issuecomment-1586122860
> 
> > Badges are a way to denote people who contributed in certain ways

that's unrelated. since these badges are local only, they don't need some special significance, they're just there for you.

that plugin got denied because it added badges for *all* users

2023-07-30 08:46 UTC, ActuallyTheSun commented on src/plugins/customBadges.tsx
> +    options: {
You should use `definePluginSettings` to add settings to a plugin (you can see how it works from other plugins). This allows for a top level `settings` variable which makes your code way cleaner

2023-07-30 08:46 UTC, ActuallyTheSun commented on src/plugins/customBadges.tsx
> +        // transfer settings from the old ones, which had a select menu instead of booleans
ctrl+c ctrl+v moment

2023-07-30 08:46 UTC, ActuallyTheSun commented on src/plugins/customBadges.tsx
> +            style={{
please use a `style.css` file for this

2023-07-30 08:48 UTC, ryanccn requested changes

2023-07-30 08:48 UTC, ryanccn commented on src/plugins/customBadges.tsx
> +    authors: [{ name: "PFearr", id: 147436995679879168n }],
add yourself to Devs

2023-07-30 08:50 UTC, ryanccn commented on src/plugins/customBadges.tsx
> +            description: "Next the the username in messages",
This doesn't look right

2023-07-30 16:52 UTC, SomeAspy commented
> > is there a reason why this was denied
> 
> Badges are a way to denote people who contributed in certain ways, whether that be via contributing, donating or possible more ways
> 
> Adding badges from all mods combined is counter-intuitive, slightly confusing and also fairly pointless

https://github.com/Vendicated/Vencord/pull/375#issuecomment-1586122860

duplicate of pr#375

2024-01-13 21:09 UTC, Osinted commented
Is this still working?

2024-05-11 23:41 UTC, Vendicated commented
hi, thank you for your contribution!

i don't think this is that useful, if anything it should be part of a bigger EditUsers plugin. you also haven't addressed any of the feedback

thus i'll be closing this, sorry

2024-05-11 23:41 UTC, closed without merging