feat(plugin): PreviewMessage
Vendicated/Vencord pull request #1607
Opened 2023-08-02 01:51 UTC by Syncxv

lets you preview your message before you send it
basically this plugin: https://betterdiscord.app/plugin/PreviewMessage

![image](https://i.imgur.com/z8qwUZZ.png)

2023-08-12 00:05 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +                match: /(.)\.push.{1,30}disabled:(\i),.{1,20}\},"gift"\)\)/,
omg we really need to make an api for this hahaha this is getting ridiculous how many plugins have this patch copy pasted

2023-08-12 00:07 UTC, Vendicated requested changes
looks good other than these mostly nitpicks

2023-08-12 00:07 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +
```suggestion
```

2023-08-12 00:07 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +            {(tooltipProps: any) => (
why the any type here? this is already strongly typed so this shouldn't be necessary. If ts is complaining about Button not taking some of these props, you could just pick the specific ones you want, usually onMouseEnter and onMouseLeave

2023-08-12 00:07 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +            {(tooltipProps: any) => (
this button also needs an aria-label, but I'm pretty sure the tooltip props have aria label that defaults to the text value

2023-08-12 00:07 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +                    disabled={DraftStore.getDraft(SelectedChannelStore.getChannelId(), DRAFT_TYPE).length === 0}
maybe return null would be better? to keep the bar less bloated

2023-08-12 00:07 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +const DraftStore = findStoreLazy("DraftStore");
might be worthwhile to move this to commons since I think this is used by multiple plugins?

2023-08-12 00:09 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +                match: /(.)\.push.{1,30}disabled:(\i),.{1,20}\},"gift"\)\)/,
(not saying you should do it in this pr (unless you would like to), just a general comment)

2023-08-12 00:09 UTC, Vendicated commented
maybe make the botmessage have your pfp and name? For the most complete ✨ immersion ✨

2023-08-12 09:22 UTC, Syncxv commented
thanks for reviewing

> why the any type here? 

oops i was just copy pasting.

> maybe make the botmessage have your pfp and name? For the most complete ✨ immersion ✨

ill try add that tomorrow

> might be worthwhile to move this to commons since I think this is used by multiple plugins?

sure, i tried doing that in the latest commit 6c25c08. maybe check if its okay?

ill continue tomorrow

2023-08-15 23:16 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +    return draft;
please remove this pointless variable

2023-08-15 23:18 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +    const draft = DraftStore.getDraft(channelId, 0);
it would benefit readability to move this 0 into a constant, something like

```js
const DRAFT_TYPE_CHANNEL_MESSAGE = 0;
```

2023-08-15 23:19 UTC, Vendicated commented on src/webpack/common/types/stores.d.ts
> +// ApplicationLauncherCommand = 3
how about making this an enum and exporting it from stores.ts? (kinda similar as above)

2023-08-15 23:20 UTC, Vendicated commented on src/webpack/common/types/stores.d.ts
> +    } | undefined;
instead of `| undefined` you should use `[userId: string]?: {`

2023-08-15 23:20 UTC, Vendicated commented on src/webpack/common/types/stores.d.ts
> +export class DraftStore {
```suggestion
export class DraftStore extends Store {
```

2023-08-15 23:25 UTC, Vendicated commented on src/plugins/previewMessage.tsx
> +    description: "Lets you preview your message before sending it.",
```suggestion
    description: "Lets you preview your message before sending it",
```

2023-08-15 23:25 UTC, Vendicated commented
looks good other than the suggestions

2023-08-16 09:26 UTC, Syncxv commented on src/webpack/common/types/stores.d.ts
> +// ApplicationLauncherCommand = 3
i tried  that but since its a .d.ts file it cant export enums. i get a webpack/types not resolved
here is the commit that tries to import DraftType enum from the  store.d.ts
[f2d3625](https://github.com/Vendicated/Vencord/pull/1607/commits/f2d3625f743e93e1f359dc429d2eafc3f1e45c6c)

here is the error
https://github.com/Vendicated/Vencord/actions/runs/5844460147/job/15847602652#step:6:34

2023-08-16 09:26 UTC, Syncxv commented on src/webpack/common/types/stores.d.ts
> +    } | undefined;
yeah i tried that but theres an error 😔 and i have no idea how to solve it. no clear error message
![error](https://i.imgur.com/JolnYb2.png)

2023-08-16 14:53 UTC, Vendicated commented on src/webpack/common/types/stores.d.ts
> +    } | undefined;
try using a type instead of an interface

2023-08-16 21:55 UTC, Syncxv commented on src/webpack/common/types/stores.d.ts
> +    } | undefined;
i tried making it a type too
apparently you cant do `[userId: string]?: {` in ts
https://stackoverflow.com/questions/57337815/why-cant-this-index-signature-be-optional

 `[key in DraftType]?: ` works probably because its a mapped type and not an index signature ¯\_(ツ)_/¯

2023-08-18 23:15 UTC, Vendicated commented on src/webpack/common/types/stores.d.ts
> +    } | undefined;
thats fine then

2023-08-18 23:18 UTC, Vendicated approved these changes

2023-08-18 23:19 UTC, merged

2023-08-18 23:19 UTC, Vendicated commented
thank you