feat(plugin): Highlight
Vendicated/Vencord pull request #1621
Opened 2023-08-05 02:49 UTC by Cynosphere

Keyword notifier plugin

Also included:
- New setting type: List (array of strings)
- Markdown API to add new markdown rules (horrendous, I spent hours trying to find the best way to make this work)

2023-08-10 01:59 UTC, Vendicated requested changes

2023-08-10 01:59 UTC, Vendicated commented on src/components/PluginSettings/components/SettingListComponent.tsx
> +                {state.map((value, index)=>(<div style={{ display: "grid", height: "40px", gap: "10px", gridTemplateColumns: "1fr 40px" }}>
it would be better to use a class and style it with css

2023-08-10 01:59 UTC, Vendicated commented on src/components/PluginSettings/components/SettingListComponent.tsx
> +                    onClick={()=>{ state.push("");handleChange(state); }}
please separate these (and above) statements by newlines

2023-08-10 01:59 UTC, Vendicated commented on src/plugins/highlight.tsx
> +                match: function (text, state) {
```suggestion
                match(text, state) {
```

2023-08-10 01:59 UTC, Vendicated commented on src/plugins/_api/markdown.ts
> +                    match: /=(\i)\.originalMatch;(.+?case"emoticon":(return .+?;).+?case"link":(.+?))(?=default:)/,
these `.+?` scare me. How much are you matching here? I usually either limit the amount of characters eg `.{0,200}` or just match the whole thing if shooort

2023-08-12 00:00 UTC, Vendicated commented
TODO: refactor slate rules (from ur message on discord)

2023-09-08 04:11 UTC, Cynosphere commented
...i guess thats why you dont rebase...

2024-06-08 22:59 UTC, closed without merging