feat(PermissionsViewer): separated list scrolling, hide irrelevant perms
Vendicated/Vencord pull request #1639
Opened 2023-08-12 03:14 UTC by bb010g

The role listing in the permissions viewer can now be scrolled separately from the permissions listing. Additionally, the permission list scroll position is preserved when changing which role is displayed.

The permissions viewer permissions listing now has a toggle to hide permissions which are irrelevant to the computed permission set. By default, all permissions are shown, but this default can be changed. You can also hide or show irrelevant permissions for just the current permissions viewer instance. This hiding is performed via CSS, for efficiency.

2023-08-12 03:42 UTC, Vendicated commented on src/plugins/permissionsViewer/components/icons.tsx
> +export function PermissionDefaultIcon(): JSX.Element {
```suggestion
export function PermissionDefaultIcon() {
```
don't type the return type unless necessary (eg overloads or recursive funcs)

2023-08-15 22:59 UTC, Vendicated commented on src/plugins/permissionsViewer/styles.css
> +.vc-permviewer-perms-perms-hide-irrelevant-permissions > .vc-permviewer-perms-perms-item:where(:not([data-vc-permviewer-permission-state]), [data-vc-permviewer-permission-state="default"], [data-vc-p
this selector is veeery complex, it would likely benefit readability to split it into multiple selectors or split it across multiple lines

2023-08-15 23:06 UTC, Nuckyz requested changes
Instead of messing with new classes, attributes and css the code should simply skip rendering the irrelevant permissions

2023-08-18 01:21 UTC, bb010g commented on src/plugins/permissionsViewer/styles.css
> +.vc-permviewer-perms-perms-hide-irrelevant-permissions > .vc-permviewer-perms-perms-item:where(:not([data-vc-permviewer-permission-state]), [data-vc-permviewer-permission-state="default"], [data-vc-p
I initially split this over multiple lines, but Stylelint's indentation rule required 0 leading spaces for each subsequent line of the same rule, which reads the same as multiple rules (separated by `,`) would, so I avoided that for clarity.

2023-08-18 04:21 UTC, bb010g commented
> the code should simply skip rendering the irrelevant permissions

Done. While handling this I realized that the list rendering wasn't keyed, which gets more relevant when adding/removing classes from a list, so that's done for both listings now.

The nesting got severe after introducing `<Fragment>` to handle permissions that aren't rendered, so permission item display has been factored out to a standalone `PermissionItem` component.

2024-04-12 01:36 UTC, bb010g commented
Refactored and cleaned up the patch stack some. Should be much easier to review commit-by-commit now.

2026-07-26 19:17 UTC, Vendicated commented
This has since been implemented

2026-07-26 19:17 UTC, closed without merging