feat(plugin): Picture in Picture
Vendicated/Vencord pull request #1697
Opened 2023-08-31 21:24 UTC by lumap

This plugin adds a picture in picture button for videos next to the Download button.
TODO:
- Make the SVG fit more with the others color-wise
- Find a way to remove the ts-ignore in the onClick event
- Test more

2023-08-31 21:54 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +            match: /\.nonMediaAttachment.{0,10}children:\[(.),/gm,
unless you deliberately mean to replace multiple places
```suggestion
            match: /\.nonMediaAttachment.{0,10}children:\[(.),/,
```

2023-08-31 21:54 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +            match: /\.nonMediaAttachment.{0,10}children:\[(.),/gm,
use \i, not .

2023-08-31 21:57 UTC, Vendicated requested changes

2023-08-31 21:57 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +                        <g>
remove this useless group

2023-08-31 21:57 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +                    <svg width="24px" height="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style={{ pointerEvents: "none" }}>
```suggestion
                    <svg width="24px" height="24px" viewBox="0 0 24 24">
```

2023-08-31 21:57 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +                    aria-disabled={false}
```suggestion
```

2023-08-31 21:57 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +        return <Tooltip text={"Enable Picture in Picture"}>
```suggestion
        return <Tooltip text="Enable Picture in Picture">
```

2023-08-31 21:57 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +                    aria-label={"Enable Picture in Picture"}
iirc, the tooltip props contain an aria Label, so if you just spread the tooltip props info your div it should just work

2023-09-01 17:47 UTC, lumap commented
issue i noticed: switching channels when a video is playing in PiP doesn’t close the PiP window, it just pauses the video until you close it

2023-09-02 18:44 UTC, lumap commented
next up: ff the video in PiP to the same time at the og video if it’s playing and pause the og video afterwards

2023-09-02 19:10 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +    options: {
options are deprecated. use settings coupled with definePluginSettings

2023-09-02 19:10 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +                match: /\.nonMediaAttachment.{0,10}children:\[(\i),/gm,
```suggestion
                match: /\.nonMediaAttachment.{0,10}children:\[(\i),/,
```
don't add flags unless you need them

2023-09-02 19:12 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +    renderPiPButton() {
wrap in ErrorBoundary for error safety

2023-09-02 19:21 UTC, lumap commented
> next up: ff the video in PiP to the same time at the og video if it’s playing and pause the og video afterwards

implemented this as well as all of ven's review suggestions

2023-09-05 17:44 UTC, Vendicated commented on src/plugins/pictureInPicture.tsx
> +                            const oldVid = e.currentTarget.parentNode!.parentNode!.querySelector("video")!;
please add some comments explaing why stuff is done. for example, why do you conditionally display: none it

2023-09-08 01:56 UTC, Vendicated commented
thank you!

2023-09-08 01:56 UTC, Vendicated approved these changes

2023-09-08 01:57 UTC, merged

2023-09-08 19:41 UTC, Cyanide0210 commented
Can we also add this to streams please?

2023-09-08 19:43 UTC, castdrian commented
video embeds within richembeds could also use at least the looped playback