feat(plugin): add muteNewGuild Plugin
Vendicated/Vencord pull request #17
Opened 2022-09-30 23:07 UTC by GlitchChan

add a plugin that will auto-magically mute newly joined guilds.

2022-09-30 23:31 UTC, Vendicated commented on src/plugins/muteNewGuild.ts
> +                replace: "Vencord.Plugins.plugins.muteNewGuild.muteGuild(a);$1"
don't hardcode variable names, match them with the regex, also u can use \w instead of [a-z]

the muteGuild call could just be inlined (Vencord.Webpack.findByProps......)

2022-09-30 23:59 UTC, GlitchChan commented on src/plugins/muteNewGuild.ts
> +                replace: "Vencord.Plugins.plugins.muteNewGuild.muteGuild(a);$1"
Working on this right now

2022-10-01 00:38 UTC, Vendicated requested changes

2022-10-01 00:38 UTC, Vendicated commented on src/plugins/muteNewGuild.ts
> +            find: "acceptInvite:function",
there are two modules containing this string
```suggestion
            find: ",acceptInvite:function",
```

2022-10-01 00:38 UTC, Vendicated commented on src/plugins/muteNewGuild.ts
> +                replace: "$1;Vencord.Webpack.findByProps('updateGuildNotificationSettings').updateGuildNotificationSettings($1,{'muted': true, 'suppress_everyone': true, 'suppress_roles': true})"
```suggestion
                replace: "$1;Vencord.Webpack.findByProps('updateGuildNotificationSettings').updateGuildNotificationSettings($1,{'muted':true,'suppress_everyone':true,'suppress_roles':true})"
```

2022-10-01 00:46 UTC, GlitchChan commented
I have done both now 😎

2022-10-01 00:49 UTC, Vendicated approved these changes
Thank you!

2022-10-01 00:49 UTC, merged

2022-10-01 00:49 UTC, GlitchChan commented
This was definitely a fun learning experience

2023-07-28 09:44 UTC, br0gio commented
This plugin is broken