[ReviewDB] add emojis and discord markdown
Vendicated/Vencord pull request #1718
Opened 2023-09-08 15:18 UTC by mantikafasi

and some changes for better look

2023-09-08 15:19 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewComponent.tsx
> +    // this is terrible, blame ven
😠

2023-09-08 15:21 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewComponent.tsx
> +                {
remove {}

2023-09-08 15:21 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +waitFor(m => m?.Z?.type?.render?.toString().includes("CHANNEL_TEXT_AREA).AnalyticsLocationProvider"), m => InputComponent = m.Z);
use LazyComponent(() => findByCode())

2023-09-08 15:22 UTC, mantikafasi commented on src/plugins/reviewDB/components/ReviewComponent.tsx
> +                {
TRUE

2023-09-08 15:24 UTC, mantikafasi commented on src/plugins/reviewDB/components/ReviewComponent.tsx
> +    // this is terrible, blame ven
blobcatcozer

2023-09-08 16:31 UTC, mantikafasi reviewed
g

2023-09-12 21:36 UTC, Vendicated requested changes

2023-09-12 21:36 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +    inputType.disableAutoFocus = true;
avoid polluting discord objects. instead, try
```js
const inputType = { ...InputTypes.FORM, disableAutoFocus: true }
```

2023-09-12 21:36 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +const InputComponent = LazyComponent(() => find(m => m?.Z?.type?.render?.toString().includes("CHANNEL_TEXT_AREA).AnalyticsLocationProvider")).Z);
```suggestion
const InputComponent = LazyComponent(() => find(m => m?.type?.render?.toString().includes("CHANNEL_TEXT_AREA).AnalyticsLocationProvider")));
```

2023-09-12 21:36 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +                        editorRef = r.ref.current.getSlateEditor();
you should most likely use a proper ref

2023-09-12 21:36 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +                    channel={channel} placeholder={
```suggestion
                    channel={channel}
                    placeholder={
```

2023-09-12 21:36 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +                            }).then(res => {
make the callback an async func and use await instead of .then

2023-09-12 21:36 UTC, Vendicated commented on src/plugins/reviewDB/index.tsx
> +                    ), ...props
```suggestion
                    ),
                    ...props
```

2023-09-12 21:36 UTC, Vendicated commented on src/plugins/reviewDB/style.css
> +    margin-bottom: 8px !important;
why !important ?

2023-09-13 06:16 UTC, mantikafasi commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +                        editorRef = r.ref.current.getSlateEditor();
how

2023-09-13 06:23 UTC, mantikafasi commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +    inputType.disableAutoFocus = true;
okay

2023-09-13 06:23 UTC, mantikafasi commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +const InputComponent = LazyComponent(() => find(m => m?.Z?.type?.render?.toString().includes("CHANNEL_TEXT_AREA).AnalyticsLocationProvider")).Z);
okay

2023-09-13 06:24 UTC, mantikafasi commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +                    channel={channel} placeholder={
OKAY

2023-09-13 06:24 UTC, mantikafasi commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +                            }).then(res => {
FINE

2023-09-13 06:24 UTC, mantikafasi commented on src/plugins/reviewDB/index.tsx
> +                    ), ...props
done

2023-09-13 06:28 UTC, mantikafasi commented on src/plugins/reviewDB/style.css
> +    margin-bottom: 8px !important;
same question

2023-09-13 14:52 UTC, mantikafasi commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +    inputType.disableAutoFocus = true;
@Vendicated this breaks emoji behaivour on popout I am keeping it on old way

2023-09-13 20:34 UTC, Euro-pol commented
fire

2023-09-21 15:14 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +                                console.log(editorRef);
```suggestion
```

2023-09-21 15:16 UTC, merged