fix(vcDoubleClick): don't require double-click on active voice channel
Vendicated/Vencord pull request #172
Opened 2022-10-28 22:35 UTC by D3SOX

2022-10-28 22:40 UTC, Vendicated commented on src/plugins/vcDoubleClick.ts
> +        if (activeVoiceChannel) {
```suggestion
        if (SelectedChannelStore.getVoiceChannelId() === id) {
```

2022-10-28 22:45 UTC, D3SOX commented on src/plugins/vcDoubleClick.ts
> +        if (activeVoiceChannel) {
Why? The suggestion doesn't make sense, what did you want to achieve?

2022-10-28 22:46 UTC, Vendicated commented on src/plugins/vcDoubleClick.ts
> +        if (activeVoiceChannel) {
the outer if is unnecessary, you can just do the comparison right away. now you can also eliminate the variable

2022-10-28 22:48 UTC, D3SOX commented on src/plugins/vcDoubleClick.ts
> +        if (activeVoiceChannel) {
I just wanted to be sure that it's not undefined and `id` is also `undefined` and then it's equal but yeah

2022-10-28 22:50 UTC, Vendicated commented on src/plugins/vcDoubleClick.ts
> +        if (activeVoiceChannel) {
Id shouldn't ever be undefined, should it? in any case, I would just add a separate check that returns early if id is undefined, that's way prettier

2022-10-28 22:53 UTC, D3SOX commented
For the stage channels patch: I'm not sure if this is different in Canary and Stable right now. I can't test it with Canary rn but maybe it should cover both ways

2022-10-28 22:54 UTC, Vendicated commented
special canary treatment is kinda pointless and will be very cumbersome, I would just make sure it works on stable

2022-10-28 22:55 UTC, D3SOX commented
As of this PR, the patch works in stable

2022-10-29 20:58 UTC, Vendicated requested changes

2022-10-29 20:58 UTC, Vendicated commented on src/plugins/vcDoubleClick.ts
> +                    match: /onClick:(.*)this\.handleClick,/g,
This greedy operator is dangerous, do something else or limit it to as litte chars as possible, such as `.{0,20}`

2022-10-30 17:43 UTC, D3SOX commented on src/plugins/vcDoubleClick.ts
> +                    match: /onClick:(.*)this\.handleClick,/g,
Updated

2022-10-30 17:46 UTC, Vendicated commented on src/plugins/vcDoubleClick.ts
> +            cb();
nitpick but u can just `return void cb()`

2022-10-30 17:47 UTC, merged

2022-10-30 17:48 UTC, D3SOX commented on src/plugins/vcDoubleClick.ts
> +            cb();
Didn't know about that syntax and got this warning by SonarLint lol

![image](https://user-images.githubusercontent.com/24937357/198893289-2c261cdb-901e-439d-a84d-8d5b4d8ebfc2.png)