[LoadingQuotes] Custom quotes
Vendicated/Vencord pull request #1795
Opened 2023-10-13 04:17 UTC by UlyssesZh

Resolve #1654.

2023-10-18 22:11 UTC, Vendicated requested changes

2023-10-18 22:11 UTC, Vendicated commented on src/plugins/loadingQuotes/index.ts
> +                match: /(\._loadingText=\(\i=)(\[.{0,4000}\])(\)\[.{0,10}random\(.+?;)/s,
using such large ranges is weird. either use .+? if it's safe, or find a better way to do this

2023-10-18 22:11 UTC, Vendicated commented on src/plugins/loadingQuotes/index.ts
> +        let result: string[] = this.settings.store.enableDiscordPresetQuotes ? preset : [];
make a global variable for the settings and use that instead of using it via this

2023-10-18 22:11 UTC, Vendicated commented on src/plugins/loadingQuotes/index.ts
> +            result = result.concat(quotes.map(this.xor));
```suggestion
           result.push(...quotes.map(this.xor));
```

2023-10-18 22:11 UTC, Vendicated commented on src/plugins/loadingQuotes/index.ts
> +        result = result.concat(this.settings.store.additionalQuotes.split(this.settings.store.additionalQuotesDelimiter));
same as above. you should likely also .trim() the elements

2023-10-18 22:11 UTC, Vendicated commented on src/plugins/loadingQuotes/index.ts
> +        if (result.length === 0) {
bad style. `return result || "Loading..."`

2023-10-18 22:13 UTC, UlyssesZh commented on src/plugins/loadingQuotes/index.ts
> +                match: /(\._loadingText=\(\i=)(\[.{0,4000}\])(\)\[.{0,10}random\(.+?;)/s,
The range is large because there are many quotes in the middle. Setting the upper bound to 4000 is to prevent it from searching the rest of the module.

2023-10-18 23:07 UTC, UlyssesZh commented on src/plugins/loadingQuotes/index.ts
> +        if (result.length === 0) {
`result` is an array, so `[] || ["something"]` will return `[]`, which is undesired.

2023-10-18 23:08 UTC, UlyssesZh commented on src/plugins/loadingQuotes/index.ts
> +        result = result.concat(this.settings.store.additionalQuotes.split(this.settings.store.additionalQuotesDelimiter));
`trim()` may be undesired if users want to have their quotes with leading or trailing spaces.

2023-10-18 23:08 UTC, Vendicated commented on src/plugins/loadingQuotes/index.ts
> +        if (result.length === 0) {
i realised that too now. but you should still use a ternary

2024-05-15 00:25 UTC, Vendicated commented on src/plugins/loadingQuotes/index.ts
> +        result.push(...settings.store.additionalQuotes.split(settings.store.additionalQuotesDelimiter));
split on an empty string will yield `[""]` so if you don't use the custom quote feature there's a small chance to get an empty quote
```suggestion
        result.push(...settings.store.additionalQuotes.split(settings.store.additionalQuotesDelimiter).filter(Boolean));
```

2024-05-15 00:25 UTC, Vendicated commented on src/plugins/loadingQuotes/index.ts
>      replaceEvents: {
with the new option of toggling default discord badges, maybe this setting should be changed to "enableEventQuotes" that's independent of normal discord quotes? not sure how feasible that would be

2024-05-15 02:38 UTC, UlyssesZh commented on src/plugins/loadingQuotes/index.ts
>      replaceEvents: {
What do you mean by being independent of normal Discord quotes? Discord disables the normal quotes during events, so they are exclusive to each other. If you mean enabling the normal quotes on top of the event quotes during events, I may be able to do that.

What new option of toggling default Discord badges?

2024-05-15 02:48 UTC, Vendicated commented on src/plugins/loadingQuotes/index.ts
>      replaceEvents: {
> What new option of toggling default Discord badges?

quotes, not badges, brainfart! i was mainly referring to this setting being quite confusing now that you can toggle default discord quotes. it'd probably be better to reword it a bit

2024-05-15 02:55 UTC, UlyssesZh commented on src/plugins/loadingQuotes/index.ts
>      replaceEvents: {
Ah I see your point. What about this: `replaceEvents` says "This plugin effects events (e.g. Halloween)", and `enableDiscordPresetQuotes` says "Enable Discord's preset quotes (including event quotes, during events)".

2024-05-15 04:11 UTC, UlyssesZh commented
Converting to a draft because I suddenly cannot get my installation of Vencord working. The last commit is untested.

2024-05-15 05:17 UTC, UlyssesZh commented
Back on. It should be good now.

2024-05-17 21:10 UTC, lewisakura commented
Can you please outright remove the Vaporeon copypasta quote (see #2474)

2024-05-17 21:11 UTC, UlyssesZh commented
Already removed. See the last commit message.

2024-05-17 21:12 UTC, lewisakura commented
Outright, not commented out, I don't think we need to keep the line if it's never seen.

2024-05-17 21:14 UTC, Vendicated commented on src/plugins/loadingQuotes/quotes.js
> +/*
why's this a source file? just name it `quotes.txt` and make it newline separated quotes

you can import it in ur plugin via 
```js
import QuotesText from "~fileContent/quotes.txt";

const Quotes = QuotesText.trim().split("\n")
```

2024-05-18 05:24 UTC, UlyssesZh commented on src/plugins/loadingQuotes/quotes.js
> +/*
Hmm, I didn't know one can do this in JS/TS. I use this approach now.

2024-05-18 05:24 UTC, UlyssesZh commented
> Outright, not commented out, I don't think we need to keep the line if it's never seen.
Done. The commenting syntax is retained, though, in case people want to leave comments there.

2024-05-27 16:12 UTC, lewisakura commented
thank you!

2024-05-27 16:35 UTC, Vendicated commented
the patches were kinda bad for the following reasons, thus I changed them:
- reliant on the current easter egg that might get removed at any time
- reassigning the variable which might be made a `const` in the future. the plugin now mutates the array in place
- just generally using fixed length anything matchers is best avoided

but the rest is good now so I'll go ahead and merge this, thank you for your work!!

2024-05-27 16:36 UTC, merged