feat(nitroBypass): add sticker bypass
Vendicated/Vencord pull request #184
Opened 2022-10-31 22:55 UTC by D3SOX

2022-10-31 23:05 UTC, D3SOX commented
I'll try to resolve the to-dos tomorrow, anybody's welcome to help out :)

2022-11-02 20:01 UTC, D3SOX commented
Can't find a way to fix the glitchy GIF for now. I'd leave it like this for now, it's better than nothing.

2022-11-04 08:15 UTC, ArjixWasTaken commented
Otherwise this LGTM!

2022-11-04 08:16 UTC, ArjixWasTaken commented
Otherwise this LGTM!

2022-11-04 08:21 UTC, ArjixWasTaken requested changes
Oof, the review was pending

2022-11-04 08:21 UTC, ArjixWasTaken commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
Discord has a map exported (just an object) with all the API endpoints as well as the asset endpoints.

You should probably look for that, just search through the sources for the discord assets link and you will find it.

2022-11-04 08:22 UTC, Vendicated requested changes
Thanks! Some feedback

2022-11-04 08:22 UTC, Vendicated commented on src/api/MessageEvents.ts
> +            if (result && result.cancel) {
```suggestion
            if (result && result.cancel === true) {
```
just to make it more explicit

2022-11-04 08:22 UTC, Vendicated commented on src/api/MessageEvents.ts
> +        } catch (e) { MessageEventsLogger.error(`MessageSendHandler: Listener encountered an unknown error. (${e})`); }
I know this is old code but
```suggestion
        } catch (e) { MessageEventsLogger.error("MessageSendHandler: Listener encountered an unknown error\n", e); }
```

2022-11-04 08:22 UTC, Vendicated commented on src/api/MessageEvents.ts
> +        } catch (e) { MessageEventsLogger.error(`MessageClickHandler: Listener encountered an unknown error. (${e})`); }
same as above

2022-11-04 08:22 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +const getGifEncoder = makeLazy(() => import("https://unpkg.com/gifenc@1.0.3/dist/gifenc.esm.js"));
since two plugins use this same package now, I think it would be good if we introduced a central file like utils/dependencies.ts that would export all the dependencies plugins might use

2022-11-04 08:22 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +        // TODO: I think this could use something like const StickerStore = lazyWebpack(filters.byProps("getStickers??"));
so?

2022-11-04 08:22 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +                                    const { GIFEncoder, quantize, applyPalette } = this.gif;
since this is async anyway, please import the libraries on demand instead of unconditionally

2022-11-04 08:26 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
likely findByProps("STICKER")

2022-11-04 08:50 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
> likely findByProps("STICKER")

Returns this
![image](https://user-images.githubusercontent.com/24937357/199931389-cd91c0db-28da-4891-a72d-be26dc88c277.png)

2022-11-04 08:59 UTC, D3SOX commented
Ok TIL the rebase on master option makes all commits unverified (for whatever reason) and now it looks like I pushed everything again

2022-11-04 09:02 UTC, Vendicated commented
lmao yeah, merge doesn't have this issue

2022-11-04 09:02 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
find(m => typeof m.STICKER === "function")

2022-11-04 09:09 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
You mean't like this? `STICKER` only returns `/stickers/INPUT` 🤔 

```suggestion
        const { STICKER } = find(m => typeof m.STICKER === "function");
        return `${location.origin}${STICKER(`${stickerId}.png`)}`;
```

2022-11-04 09:14 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
Well there's not really any issue with hardcoding it, it's not like it's gonna change

2022-11-04 11:18 UTC, ArjixWasTaken commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
You are getting the wrong webpack module, imma help when I'm on my pc

2022-11-05 08:49 UTC, ArjixWasTaken commented
@D3SOX 
`GLOBAL_ENV.CDN_HOST` gives `cdn.discordapp.com`

2022-11-05 08:51 UTC, Vendicated commented
cdn sticker endpoint has cors issues. why are u even making an issue out of a total non issue, the current implementation is fine

2022-11-05 08:52 UTC, ArjixWasTaken commented
i am not? the PR description itself has it as a goal to not hardcode the url

2022-11-05 08:59 UTC, Vendicated requested changes

2022-11-05 08:59 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +waitFor(["getChannel"], m => ChannelStore = m);
pretty sure this is a common module

2022-11-05 08:59 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +                                            ctx.drawImage(frame.img, 0, 0, resolution, resolution);
instead of always reusing the same resolution, why not use each frame's height and width? maybe that will fix the weird glitching, who knows

2022-11-05 08:59 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
it would be cool if you could make it also check if you can use that sticker, since then it would still be useful for nitro havers to be able to post unavailable stickers

2022-11-05 08:59 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
consider using the ?size parameter to make the fake stickers be exactly the same size as real ones. Would be cool to make it a setting maybe?

2022-11-05 10:30 UTC, D3SOX commented
Thanks for the suggestions, will implement later

2022-11-05 10:32 UTC, D3SOX commented
> i am not? the PR description itself has it as a goal to not hardcode the url
> although it doesnt actually hardcode it

I've set it as TODO because I had previously hardcoded it but then it turned out that I need to use discord.com instead anyways because the cdn endpoint can't be fetched for animated sticker because of CORS

2022-11-05 10:35 UTC, ArjixWasTaken commented
naruhodo

2022-11-05 10:56 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +                                            ctx.drawImage(frame.img, 0, 0, resolution, resolution);
I tried it right now and it makes it glitch even worse

2022-11-05 10:57 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
Where to get the size from the real sticker from?

2022-11-05 10:58 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
Can nitro users not use all stickers?

2022-11-05 11:03 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
size 160 is exactly the same as real stickers 
![image](https://user-images.githubusercontent.com/45497981/200116738-0f24d9e6-963c-4054-a8b2-76b1af999cfa.png)

https://media.discordapp.net/stickers/1026517526106087454.webp?size=160

2022-11-05 11:03 UTC, ArjixWasTaken commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
![image](https://user-images.githubusercontent.com/53124886/200116758-69fd2261-b463-418d-af18-1cd9b46f34cf.png)

looks like it is 160x160

2022-11-05 11:03 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
I tried to add `?size=32`, `?size=64`, `?size=128` and it doesn't seem that it makes a difference.

2022-11-05 11:03 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
Some may be unavailable due to the server hosting them losing a premium tier or similar

2022-11-05 11:05 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +        return `${location.origin}/stickers/${stickerId}.png`;
It seems like it only works for the format of `https://media.discordapp.net/stickers/1026517526106087454.webp?size=160` and not `https://discord.com/stickers/1026517526106087454.png?size=160`

2022-11-05 11:12 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
Hm, how would I go and check if the sticker is currently available? Do you have a tip where I could look?

2022-11-05 11:16 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
sticker.available = true

2022-11-05 11:17 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
I'm literally blind, I looked inside the sticker object and overlooked that property 🤦

2022-11-05 11:17 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +        // TODO: I think this could use something like const StickerStore = lazyWebpack(filters.byProps("getStickers??"));
findByProps("getAllGuildStickers").getAllGuildStickers() => Map<GuildID, Sticker[]>

2022-11-05 11:19 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
Nvm I think `available` is not correct as it's always `true` for me and I don't have Nitro

2022-11-05 11:22 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
available means whether the sticker is available, not usable

2022-11-05 11:27 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
Ah I see. So if the user has Nitro and it's unavailable it should use the bypass.

2022-11-05 12:16 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +                            // get guild id from sticker
Turns out this needs another patch to make unavailable stickers clickable 😒

2022-11-05 12:18 UTC, ArjixWasTaken commented on src/plugins/nitroBypass.ts
> +                const url = emoji.url.replace(/\?size=\d+/, "?size=48");
uhh....depending on the locale of the user, `\d` can match letters that represent numbers...
well, I guess there is no point worrying about that, since its kinda hard for those letters to be there in the first place

2022-11-05 12:18 UTC, ArjixWasTaken commented on src/plugins/nitroBypass.ts
> +                const url = emoji.url.replace(/\?size=\d+/, "?size=48");
I just wanted to let you know that I didn't do it for no reason

2022-11-05 12:20 UTC, ArjixWasTaken commented
It would be nice if this worked when editing a message as well

but in that case instead of adding an attachment you'd have to append the link at the end, and that wouldn't work well for animated stickers, so nvm

2022-11-05 12:21 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +                const url = emoji.url.replace(/\?size=\d+/, "?size=48");
> uhh....depending on the locale of the user, `\d` can match letters that represent numbers...

Oh, I didn't know about that. I think then I'll revert this change

2022-11-05 12:24 UTC, ArjixWasTaken commented on src/plugins/nitroBypass.ts
> +                const url = emoji.url.replace(/\?size=\d+/, "?size=48");
nah its ok, the url is given by discord in the first place, so its kinda guaranteed that only european numerals (AKA [0-9]) will be there

2022-11-05 12:30 UTC, ArjixWasTaken commented
Question: Can ya also resize the animated stickers?
(I know its not possible via the url query parameters since you are converting them to gifs in the first place)

2022-11-05 12:37 UTC, D3SOX commented
Animated stickers are already created in the configured size

2022-11-05 12:38 UTC, ArjixWasTaken commented
oh yeah, i was on an older commit, nvm then

2022-11-05 13:02 UTC, D3SOX commented
I think now the glitching is the only thing that's left, any help is appreciated, otherwise I'd say we could merge it like this for now

2022-11-06 10:28 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +        this.stickerPacks = stickerPacks;
is this still needed? I told you how to get the stickers from Discord dynamically

2022-11-06 10:30 UTC, Vendicated commented on src/plugins/nitroBypass.ts
> +        getAllGuildStickers().forEach((packs: Sticker[]) => {
why not via a patch? what if a new sticker is created after loading

2022-11-06 11:13 UTC, D3SOX commented on src/plugins/nitroBypass.ts
> +        getAllGuildStickers().forEach((packs: Sticker[]) => {
Tried to find the place where it's queried but I didn't suceed

2022-11-07 21:23 UTC, Vendicated approved these changes

2022-11-07 21:23 UTC, merged