feat(plugin): FakeProfileThemesAndEffects
Vendicated/Vencord pull request #1930
Opened 2023-10-30 03:24 UTC by ryan-0324

This plugin is meant to replace FakeProfileThemes.
It allows for profile theming and the usage of profile effects.
The character counts of the 3y3 strings generated are significantly less than the character counts of those generated by FakeProfileThemes.

2023-11-04 18:38 UTC, MrDiamondDog requested changes

2023-11-04 18:38 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +    authors: [
Add yourself to `Devs`, see other plugins

2023-11-04 18:38 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +    "Hide 3y3 Builder": {
```suggestion
    hide3y3Builder: {
```
and change things accessing this

2023-11-04 18:38 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +        if (user !== undefined) {
```suggestion
        if (user === undefined) return;
```
Do this for a bunch of the other `if` statements, prevents nesting as much and improves readability

2023-11-04 18:38 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +        const [primaryColor, setPrimaryColor]: [number, (v: number) => void] = useState(-1);
You don't need to type these, as they will get their types from `useState`

2023-11-04 18:38 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +                        onClick={(): void => {
This whole function is completely unreadable, move to a different function and use the `if` statement strategy from before, space out some blocks, and maybe some comments

2023-11-04 18:38 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +                            if (buildLegacy3y3 === true) {
```suggestion
                            if (buildLegacy3y3) {
```

2023-11-04 18:38 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +                    onClick={(): void => {
Not everything needs types

```suggestion
                    onClick={() => {
```

2023-11-04 18:38 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +    profileEffectID: string | undefined;
```suggestion
    profileEffectID?: string;
```

2023-11-04 18:38 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +function base10NumToBase125Str(base10: number): string {
Add some jsdocs to these functions

2023-11-04 19:21 UTC, ryan-0324 commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +    "Hide 3y3 Builder": {
This must be done otherwise the setting name will show as "Hide3y3 Builder" in the plugin settings modal.

2023-11-04 21:56 UTC, ryan-0324 commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +    profileEffectID: string | undefined;
`profileEffectID?: string` is not the same as `profileEffectID: string | undefined`. `string | undefined` requires the property `profileEffectID` to exist and have a type of string or undefined, whereas the optional marker does not require `profileEffectID` to exist at all.

2023-11-04 22:00 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +    profileEffectID: string | undefined;
It's a lot easier to let `profileEffectID` to not exist rather than just making it undefined

2023-11-04 22:06 UTC, ryan-0324 commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +    profileEffectID: string | undefined;
I extended the type `User` from `discord-types/general` as it is not up to date. The user object returned by the `getUserProfile` function always contains `profileEffectID` even if it is undefined. That is why `string | undefined` is correct and the optional marker is not.

2023-11-04 22:07 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +    profileEffectID: string | undefined;
Makes sense then

2023-11-05 22:37 UTC, MrDiamondDog requested changes

2023-11-05 22:37 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +            { textContent: "." + this.name + "TextOverflow{white-space:normal!important;text-overflow:clip!important}" }
You shouldn't have to do this, inline styles exist

2023-11-05 22:37 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +        if (settings.store["Hide 3y3 Builder"] === true) return <></>;
```suggestion
        if (settings.store["Hide 3y3 Builder"]) return <></>;
```

2023-11-05 22:43 UTC, ryan-0324 commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +            { textContent: "." + this.name + "TextOverflow{white-space:normal!important;text-overflow:clip!important}" }
I tried using inline styles at first. The problem is that the `Button` component from `@webpack/common` has its text contained in a separate `div` element. The only way I was able to style the text was by using the `innerClassName` property.

2023-11-05 22:44 UTC, MrDiamondDog commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +            { textContent: "." + this.name + "TextOverflow{white-space:normal!important;text-overflow:clip!important}" }
Include the `<style>` tag inside that component then, don't insert it into the dom like this

2023-11-09 01:50 UTC, Vendicated commented on src/plugins/fakeProfileThemesAndEffects/index.tsx
> +    fetch("/api/v9/user-profile-effects", { mode: "same-origin", cache: "only-if-cached" })
this is terrible. use Discord's RestAPI module

2023-11-09 01:51 UTC, Vendicated commented
this is a crazy amount of code for such a small feature. why is all of this needed? it seems very overengineered

2023-11-10 22:41 UTC, ImpishMoxxie commented
LGTM 👍

2023-11-11 11:36 UTC, Yeetov requested changes
Shorten the plugin name as it goes off screen in the Plugin Browser:
![image](https://github.com/Vendicated/Vencord/assets/69159547/70758c41-bb68-4aa2-9837-b46a7c26e587)

2023-11-17 13:53 UTC, tiagorangel2011 commented
Looks good

2023-11-17 21:51 UTC, ImpishMoxxie approved these changes

2023-11-24 05:47 UTC, MrDiamondDog approved these changes
Seems over engineered as ven said but not sure how you can improve it

2024-01-12 15:08 UTC, beatmakerofficial commented
Where do I download it?

2024-01-30 02:17 UTC, ryan-0324 commented
@rniii Do you know what could be causing the `Invalid header` errors? All of my headers were automatically added on save.

2024-02-20 14:47 UTC, omegion3 commented
get that thing **declined,** because this is _reupload from discord assets._

now if only we get custom profile effects, then just a reupload one, this would've be good.

2024-02-20 14:51 UTC, MrDiamondDog commented
> get that thing **declined,** because this is _reupload from discord assets._
> 
> 
> 
> now if only we get custom profile effects, rather then just a reupload one, this would've be prefect.

What are you talking about

2024-02-20 15:05 UTC, MrDiamondDog commented
> nah i'm just kidding, even though it's a reupload assets, but i hope this plugin will merge 

It's not reuploaded assets..?

2024-03-02 11:36 UTC, omegion3 commented
> It doesn't have reuploaded assets..?
well it does sadly, but hopefully someone might plan to make custom profile effect or this plugin will finally merge.

2024-03-20 08:36 UTC, CompeyDev commented
What's the status on this? Anything blocking a merge on this?

2024-03-20 08:44 UTC, Sqaaakoi commented
> What's the status on this? Anything blocking a merge on this?

vee gets around to PRs "*eventually*"
this is also (relatively) a big plugin

2024-03-20 08:49 UTC, CompeyDev commented
Makes sense, I'm running a manually compiled build from ryan's repo and it seems to work about fine. Haven't really looked much at the code though.

2024-09-01 18:39 UTC, ryan-0324 commented
> Some issues:
> 
> 1. The stock profile effect editor is patched by this plugin resulting in it displaying all effects as unlocked and are unable to apply any & it falsely showing the remove effect button. Should behave like Decor where it doesn't modify the stock feature.
> 2. The FPTE Builder should auto fill with the values from the bio.
> 3. The FPTE Builder should have buttons to save to bio without manual copy & pasting being required And likewise have a clear button.

1. This seems to be a recent breakage. Thanks for letting me know.
2. I've though about adding something like this before, and it seems reasonable.
3. This has been suggested before, and I don't think it's worth the added complexity:
    1. Should I just prepend the FPTE string to the user's bio, displaying an error if their bio doesn't have enough space or already starts with an FPTE character?
    2. Or should I try to automatically detect preexisting FPTE strings and strings from other plugins, and remove them from the user's bio, showing an error if there still isn't enough space?
    3. If not (ii), when the user's bio already starts with an FPTE character, should I add a non-FPTE character as a separator, or should I display an error?
    4. Should I send an API request to save the user's bio, or should I have the user do it manually?

2025-07-03 14:59 UTC, abhishek09gd commented
can other can see it

2026-07-26 17:27 UTC, Vendicated commented
This is really overengineered. Also honestly not something I want to add, profile effects are so useless and annoying

Also if we add profile effects, next it's gonna be animated pfps, profile frames, nameplates, etc. There are so many things that could be spoofed but I think theme is already more than enough

2026-07-26 17:27 UTC, closed without merging