feat: add switch to use `fullscreen-ui` vibrancy on macOS
Vendicated/Vencord pull request #1941
Opened 2023-11-01 03:04 UTC by eramdam

I was working on a custom theme that [takes advantage of the vibrancy option](https://github.com/eramdam/slacker-discord) when I noticed the vibrancy option was "only" set to `sidebar` which isn't as see-through as `fullscreen-ui` so this PR adds a switch to allow for that.

I guess there could be a dropdown menu to choose a specific [vibrancy type](https://www.electronjs.org/docs/latest/api/browser-window#winsetvibrancytype-macos) but I figured it might be a bit much. Open to feedback as this is my first PR in this project 😁 

Here's a preview of what the switch does (with nothing on top of the window material to show the effect).

**Off:**
![CleanShot 2023-10-31 at 19 57 54@2x](https://github.com/Vendicated/Vencord/assets/1409924/cbaf9914-18f0-4bc6-85cc-485eec92b714)

**On:**
![CleanShot 2023-10-31 at 19 57 28@2x](https://github.com/Vendicated/Vencord/assets/1409924/dd5cac05-81be-44d6-9a5f-6fe96cc34769)

2023-11-01 07:02 UTC, ryanccn requested changes

2023-11-01 07:02 UTC, ryanccn commented on src/main/patcher.ts
> +                const needsVibrancy = process.platform === "darwin" || (settings.macOsVibrancyStyle || settings.macosTranslucency);
Maybe merge the two settings into one and migrate the old option to `"sidebar"`

2023-11-01 15:27 UTC, eramdam commented on src/main/patcher.ts
> +                const needsVibrancy = process.platform === "darwin" || (settings.macOsVibrancyStyle || settings.macosTranslucency);
I'm not sure I get what you mean 😅 Do you meant change the type of `macosTranslucency`? Wouldn't that require a migration to support the old settings properly? (I couldn't find where to do that)

2023-11-02 01:44 UTC, ryanccn commented on src/main/patcher.ts
> +                const needsVibrancy = process.platform === "darwin" || (settings.macOsVibrancyStyle || settings.macosTranslucency);
Keep the old setting in the types but don't make it editable by the user, and migrate the old option to the new option if the old option is set and the new option isn't

2023-11-02 04:05 UTC, eramdam commented on src/main/patcher.ts
> +                const needsVibrancy = process.platform === "darwin" || (settings.macOsVibrancyStyle || settings.macosTranslucency);
Done! https://github.com/Vendicated/Vencord/pull/1941/commits/81dd0fd11e73bb4b46bc4336e8a76cf05473a582

2023-11-11 19:28 UTC, eramdam commented
@ryanccn any chance of getting a re-review on this one? 😅

2023-12-06 23:30 UTC, merged