feat(plugin): UserPFP
Vendicated/Vencord pull request #1956
Opened 2023-11-04 08:07 UTC by nexpid

adds support for UserPFP without the need for a theme

2023-11-06 20:43 UTC, nexpid commented
i made the patches and settings better and stuff

2023-11-11 00:30 UTC, Vendicated commented on src/plugins/usrpfp/index.tsx
> +                match: /(getUserAvatarURL:)(\i),/,
this module seems to export getUserAvatarURL both
- as a named export
- on the default export (what you're patching)

Optimally, you should patch both, which you could achieve by patching the function directly instead of wrapping the property

2023-11-11 12:34 UTC, Yeetov requested changes
Doesn't include all userpfp contributors in credits, doesn't include badges or badge text.
Please include FoxStorm1, Katlyn, Coolesding and thororen

2023-11-11 12:36 UTC, nexpid commented
> Doesn't include all userpfp contributors in credits, doesn't include badges or badge text. Please include FoxStorm1, Katlyn, Coolesding and thororen

they did not code this plugin

2023-11-11 12:49 UTC, Yeetov commented
> > Doesn't include all userpfp contributors in credits, doesn't include badges or badge text. Please include FoxStorm1, Katlyn, Coolesding and thororen
> 
> they did not code this plugin

They created UserPFP though

2023-11-11 12:49 UTC, Yeetov commented
Just have u in author section then

2023-11-11 12:51 UTC, nexpid commented
> > > Doesn't include all userpfp contributors in credits, doesn't include badges or badge text. Please include FoxStorm1, Katlyn, Coolesding and thororen
> > 
> > 
> > they did not code this plugin
> 
> They created UserPFP though

yes however they haven't contributed to this Vencord plugin, so it doesn't really make sense to mark them as authors

2023-11-11 13:05 UTC, nexpid commented on src/plugins/usrpfp/index.tsx
> +                match: /(getUserAvatarURL:)(\i),/,
lmk if the latest commit resolved this @Vendicated

2023-11-11 13:16 UTC, Yeetov commented
Doesn't include badges and badge text

2023-11-11 14:57 UTC, Vendicated commented
why in the world would it contain badges

UserPFP is for pfps, throwing badges in there is weird. Badges are also meant to be a perk for Vencord donors and a way to point out contributors

2023-11-11 15:42 UTC, Yeetov commented
I could ask Wolfie to add it to globalbadges

2023-11-11 15:44 UTC, Yeetov approved these changes
Everything functional and as intended

2024-01-05 23:28 UTC, Vendicated commented on src/plugins/usrpfp/index.tsx
> +                match: /(getUserAvatarURL:)(\i),/,
probably, but please merge both patches into one! you can make replacement an array

2024-01-05 23:29 UTC, Vendicated commented on src/plugins/usrpfp/index.tsx
> +            "Which avatar to use if both Nitro and UserPFP avatars are present",
this name is slightly confusing. maybe something like this instead?
```suggestion
            "Which avatar to use if both default animated (Nitro) pfp and UserPFP avatars are present",
```

2024-01-05 23:29 UTC, Vendicated commented on src/plugins/usrpfp/types.d.ts
> +export interface DataFile {
please just move this type to the main file

2024-01-08 02:36 UTC, thororen1234 commented
that pr i did should have fixed the complaints you had ven.

2024-02-18 17:42 UTC, thororen1234 commented
very cute bump!!!

2024-02-22 22:15 UTC, thororen1234 commented on src/plugins/usrpfp/index.tsx
> +                match: /(getUserAvatarURL:)(\i),/,
Done

2024-02-22 22:15 UTC, thororen1234 commented on src/plugins/usrpfp/types.d.ts
> +export interface DataFile {
This was moved and shrunk down to only carry avatars

2024-02-22 22:15 UTC, thororen1234 commented on src/plugins/usrpfp/index.tsx
> +            "Which avatar to use if both Nitro and UserPFP avatars are present",
Replaced with your suggested modification

2024-05-04 17:38 UTC, nexpid commented
bumper

2024-05-12 00:36 UTC, Vendicated commented
yeaahhh i dont know about this...

unlike userbg, this doesn't really add anything that's missing, having an animated avatar is not that big of a deal

your project also includes people who are known to be toxic / have a personal vendetta against the vencord project, so i don't really trust you with handling an external database (could be used maliciously)

i'll have to reject this on these grounds, sorry. thank you for the contribution nonetheless!

2024-05-12 00:36 UTC, closed without merging

2024-05-12 07:14 UTC, Yeetov commented
:(