[Plugin] Added Always Super React Plugin
Vendicated/Vencord pull request #1958
Opened 2023-11-04 18:23 UTC by ant0n-0x0000

Saw a lot of people requesting this today so I tried my best and made this.  As far as I can tell it's fully compliant with the guidelines.

2023-11-04 18:25 UTC, MrDiamondDog requested changes

2023-11-04 18:25 UTC, MrDiamondDog commented on src/plugins/alwaysSuperReact/index.ts
> +import definePlugin from "@utils/types";
Add the license at the top, see any other file

2023-11-04 18:25 UTC, MrDiamondDog commented on src/plugins/alwaysSuperReact/index.ts
> +    authors: [
Add yourself to `Devs`, see other plugins

2023-11-04 20:44 UTC, ant0n-0x0000 commented
Merged @FieryFlames's super reaction tweaks into the pull request.

2023-11-09 01:45 UTC, Vendicated reviewed
either this or just make it one single return statement with ||

2023-11-09 01:45 UTC, Vendicated commented on src/plugins/superReactionTweaks/index.ts
> +        else if (playingCount <= settings.store.superReactionPlayingLimit) return true;
```suggestion
        if (playingCount <= settings.store.superReactionPlayingLimit) return true;
```

2023-11-09 01:45 UTC, Vendicated commented on src/plugins/superReactionTweaks/index.ts
> +        else return false;
```suggestion
        return false;
```

2023-11-09 01:47 UTC, Vendicated commented on src/plugins/superReactionTweaks/index.ts
> +        default: false,
```suggestion
        default: true,
```

2023-11-09 01:47 UTC, Vendicated commented
This plugin needs a README.md file

2023-11-09 01:52 UTC, FieryFlames commented on src/plugins/superReactionTweaks/index.ts
> +        else if (playingCount <= settings.store.superReactionPlayingLimit) return true;
I went with this for verbosity

2023-11-09 01:52 UTC, FieryFlames commented on src/plugins/superReactionTweaks/index.ts
> +        else return false;
fine

2023-11-09 02:58 UTC, ant0n-0x0000 commented
Added README.md

2023-11-09 02:59 UTC, Vendicated commented on src/plugins/superReactionTweaks/README.md
> +### Currently, the plugin allows for two tweaks:
headers should not skip levels
```suggestion
## Currently, the plugin allows for two tweaks:
```

2023-11-09 03:00 UTC, Vendicated commented on src/plugins/superReactionTweaks/README.md
> +### Currently, the plugin allows for two tweaks:
Also i would just rename this header to 
```suggestion
## Features
```

2023-11-09 03:04 UTC, Vendicated commented on src/plugins/superReactionTweaks/index.ts
> +                match: /(?<=BURST_REACTION_EFFECT_PLAY:\i=>{.{50,100})(\i\(\i,\i\)>=\d+)/,
this doesn't seem quite right. shouldPlayBurstReaction expects a number, not a boolean

![image](https://github.com/Vendicated/Vencord/assets/45497981/18a87a3c-3f23-4425-9594-074beba7300d)

2023-11-09 03:05 UTC, FieryFlames commented on src/plugins/superReactionTweaks/index.ts
> +                match: /(?<=BURST_REACTION_EFFECT_PLAY:\i=>{.{50,100})(\i\(\i,\i\)>=\d+)/,
to be fair

I wrote that at like 5 am

2023-11-09 03:42 UTC, merged

2023-11-09 03:42 UTC, Vendicated commented
cool thanks!