[Plugin] Keyword Notify
Vendicated/Vencord pull request #1960
Opened 2023-11-06 02:20 UTC by camila314

Sends a notification when a message matches any number of regex cases.

2023-11-11 23:43 UTC, ant0n-0x0000 requested changes
Plugin needs a README.md

2023-11-11 23:43 UTC, ant0n-0x0000 commented on src/plugins/keywordNotify/index.tsx
> +*/
You can use this smaller license. Edited to include you instead of exhq.

```suggestion
/*
 * Vencord, a Discord client mod
 * Copyright (c) 2023 Vendicated, camila314, and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
```

2023-11-11 23:56 UTC, FieryFlames commented on src/plugins/keywordNotify/index.tsx
> +}
Might be better to use a setting? I don't believe DataStore is synced by Cloud

2023-11-11 23:59 UTC, camila314 commented on src/plugins/keywordNotify/index.tsx
> +}
Isn't that just what TextReplace uses? Is there a good example plugin using the settings API I can look at

2023-11-12 00:04 UTC, ant0n-0x0000 commented
Would it not be a better approach to modify the message object directly before it's rendered and include your user ID in the mentions array if it matches?

2023-11-12 00:05 UTC, camila314 commented
What benefits could that give over the current method?

2023-11-12 00:07 UTC, ant0n-0x0000 commented
Currently when something triggers the match the message hasn't been highlighted in chat which at least for me defeats the point slightly.

2023-11-12 00:08 UTC, camila314 commented
Got it, will try that when I get home

2023-11-12 01:35 UTC, AutumnVN commented on src/plugins/keywordNotify/index.tsx
> +            replace: "$& Vencord.Plugins.plugins.KeywordNotify.contains($2) ||"
```suggestion
            replace: "$& $self.contains($2) ||"
```

2023-11-12 04:37 UTC, camila314 commented
Added the message highlighting feature

2023-11-17 06:34 UTC, AutumnVN commented on src/plugins/keywordNotify/index.tsx
> +                match: /}_dispatch\((.{1,2}),.{1,2}\){/,
```suggestion
                match: /}_dispatch\((\i),\i\){/,
```

2023-11-21 05:49 UTC, AutumnVN commented on src/plugins/keywordNotify/index.tsx
> +            find: ".default.guildFilter:null",
```suggestion
            find: ".guildFilter:null,",
```
`default` can change

2023-11-28 18:45 UTC, lewisakura requested changes

2023-11-28 18:45 UTC, lewisakura commented on src/plugins/keywordNotify/index.tsx
Confused on what this change accomplishes besides adding unnecessary complexity. Can you elaborate more beyond the commit message?

2023-11-28 18:46 UTC, camila314 commented on src/plugins/keywordNotify/index.tsx
Well you see destructuring a lazy result is completely broken when the destructured value is a string, so I had to change it to no longer destructure. Tried to fix the issue myself by tinkering with Vencord internals but the only good solution would be to wrap the string within an object when creating the Proxy, which would defeat the purpose

2023-11-28 18:52 UTC, lewisakura approved these changes

2024-01-21 15:35 UTC, camila314 commented
uhhh hello

2024-02-09 00:27 UTC, Hiviexd commented
wondering if this is currently waiting on anything now that it's been approved for a while :eyes:

2024-02-24 07:22 UTC, PortalRex commented
Any chance this could get a server blacklist setting?

2024-02-27 01:36 UTC, NepNep21 commented
> Any chance this could get a server blacklist setting?

Agreed, my username is the name of a game character, so using it as a keyword causes a lot of triggering from that game series' server.

2024-02-28 14:13 UTC, belg1o commented
@ant0n-0x0000 can you review this again, so it can get merged. It's a pretty good plugin. Been using it myself in dev mode.

2024-02-28 14:55 UTC, rafitamolin commented
> @ant0n-0x0000 can you review this again, so it can get merged. It's a pretty good plugin. Been using it myself in dev mode.

Agreed, please take a look when possible, as the best way to thank the author's work would be to have it as an official plugin @Vendicated

2024-05-22 21:27 UTC, nyakowint commented
@CodiumAI-Agent /review

2024-05-22 21:28 UTC, CodiumAI-Agent commented
## PR Review 🔍

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

4, due to the complexity and size of the PR, which includes a significant amount of new functionality involving regex operations, state management, and UI components. The PR integrates deeply with existing data stores and user interfaces, requiring careful review to ensure compatibility and performance.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> ⚡&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> The `highlightKeywords` function constructs an array in a way that might not correctly handle overlapping matches or maintain the original order of text and highlights. This could lead to incorrect UI rendering of message parts.</td></tr>
<tr>
<td>

<strong>Performance Concern:</strong> The `applyRegexes` function checks every message against potentially complex regexes, which could be computationally expensive, especially with a high volume of messages.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>src/plugins/keywordNotify/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider using a more efficient method for updating the `regexes` array in the `setRegexes` function to avoid potential performance issues with large arrays. Using a functional update with `useState` can ensure that the state updates are batched and more performant. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/1960/files#diff-0c73e2475a5c105846192414ab7053f0760808d22223dc7a8efde2c8d1d99dbdR28'>regexes[idx] = reg;</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/keywordNotify/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Implement error handling for regex operations in `safeMatchesRegex` to log or report errors when regex matching fails. This can help in debugging issues related to user-provided regex patterns. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/1960/files#diff-0c73e2475a5c105846192414ab7053f0760808d22223dc7a8efde2c8d1d99dbdR47'>} catch {</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/keywordNotify/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Optimize the `highlightKeywords` function to handle overlapping regex matches and ensure that the split text and matches are correctly interleaved for display. This might involve rethinking the logic to split and merge strings and matches. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/1960/files#diff-0c73e2475a5c105846192414ab7053f0760808d22223dc7a8efde2c8d1d99dbdR64'>let parts = [...matches.map((e) => {</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/keywordNotify/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

To prevent potential memory leaks or excessive memory usage, consider implementing a cleanup mechanism in the `addToLog` function to remove old log entries when the log exceeds a certain size or after a certain time period. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/1960/files#diff-0c73e2475a5c105846192414ab7053f0760808d22223dc7a8efde2c8d1d99dbdR212'>if (this.keywordLog.length > 50)</a></td></tr></table><hr>

</details>

2024-06-11 01:57 UTC, randoomdude commented
How do you isntall this in Vencord? I don't see it on the default list in the app

2024-06-11 02:08 UTC, NepNep21 commented
> How do you isntall this in Vencord? I don't see it on the default list in the app

Until it is merged, you have to build and install it manually (linux-specific instructions):
1. Uninject upstream Vencord with the installer.
2. Download the fork (`git clone https://github.com/camila314/Vencord-fork && cd Vencord-fork`)
3. Build the fork (`pnpm run build`)
4. Inject the fork (`sudo pnpm run inject` and follow the menu)

2024-06-18 16:23 UTC, ImLvna reviewed
user thinks they are fit to review prs :blobcatcozystars:

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +const Popout = findByCodeLazy("let{analyticsName:");
wtf are these finds, please make them more readable

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +    updater();
rename to forceUpdate

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +        matches!.length ? (<span className="highlight">{matches!.splice(0, 1)[0]}</span>) : []
use a cl function to generate a unique class name

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +                className="keywordnotify-collapsible">
`cl("keywordnotify-collapsible")`

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +                    className="keywordnotify-delete">
cl

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +        <SearchableSelect
does a select with two entries need to be searchable?

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +                            className="keywordnotify-delete">
cl

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +                    <Forms.FormDivider className={Margins.top8 + " " + Margins.bottom8}/>
`[Margins.top8, Margins.bottom8].join(" ")` is cleaner

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +        description: "",
remove the empty description field

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +            find: "}_dispatch(",
horrible find???

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +                match: /}_dispatch\((\i),\i\){/,
the find should not be the same as the match in most cases

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +        this.onUpdate = () => null;
qhar

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +        currentUser = await UserUtils.getUser(UserStore.getCurrentUser().id);
why are you getting the user twice

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +        currentUser = await UserUtils.getUser(UserStore.getCurrentUser().id);
account switch will invalidate this

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +        keywordEntries.forEach(entry => {
use `for (entry in keywordEntries)` instead

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +                    listed = entry.listIds.some(id => id === channel.guild_id);
dms do not have a guild id iirc

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +            m.mentions.push(currentUser);
typecast this instead of ignoring it

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +            <TabBar.Item className="vc-settings-tab-bar-item" id={5}>
HORRIBLE CLASSNAME

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +            const newLog = [...keywordLog];
`Array.from(keywordLog)`

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +            console.log(this);
left in a log lmao

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +        /*return (
whoopsie daisy

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +            msg.props.children[0].props.children.props.onClick = () => onDelete(e);
PLEASE USE NULLCHECKING I BEG OF YOU

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/index.tsx
> +                <p>hi uwu</p>
:husk:

2024-06-18 16:23 UTC, ImLvna commented on src/plugins/keywordNotify/style.css
> +.keywordnotify-delete:hover {
prefix all these with vc-

2024-06-23 19:18 UTC, camila314 reviewed
i did the stuff except for the for loop thing bc when i did for loop it made error and i didn't wanna fix it

might fix later tho

2024-06-23 19:34 UTC, camila314 reviewed
made the last two changes we chill now

2024-06-24 01:18 UTC, camila314 commented
i made a new pr using a diff branch, #2615

2024-06-24 01:18 UTC, closed without merging