Added the SoundBoardLogger plugin
Vendicated/Vencord pull request #1967
Opened 2023-11-09 03:38 UTC by ImpishMoxxie

# About SoundBoardLogger

SoundBoardLogger is a plugin that lets you log all soundboard sounds that are played in a voice chat.

## Main menu

![Menu](https://i.imgur.com/ponGzcl.png)

## People that played the sound

![People menu](https://i.imgur.com/gmf1ckr.png)

## Info about a specific user

![User info](https://i.imgur.com/lfpwqx1.png)

## Open SoundBoard Log icon
(The user can choose where should the button to open the logs be displayed)

Toolbar button
![Toolbar icon](https://i.imgur.com/mO1yCg4.png)

Chat bar button
![Chat bar icon](https://i.imgur.com/FQO2YNL.png)

2023-11-09 03:45 UTC, MrDiamondDog requested changes

2023-11-09 03:45 UTC, MrDiamondDog commented on src/plugins/SoundBoardLogger/index.tsx
> +//import start
Make sure you use eslint for code styling, as the license header is needed, and it will also sort these imports for you based on our standards. You can also run `pnpm lint` to check it

2023-11-09 03:45 UTC, MrDiamondDog commented on src/plugins/SoundBoardLogger/index.tsx
> +// #region User stuff
Don't use regions, move some of the bigger ones into separate files like icons and other components

2023-11-09 03:45 UTC, MrDiamondDog commented on src/plugins/SoundBoardLogger/index.tsx
> +//start logger gui
Like regions these comments imo are clutter, and move this component to a separate file as it's really big

2023-11-09 03:45 UTC, MrDiamondDog commented on src/plugins/SoundBoardLogger/index.tsx
> +    description: "Logs all soundboards that are played in vc and allows you to download them",
```suggestion
    description: "Logs all soundboards that are played in a voice chat and allows you to download them",
```

2023-11-09 03:55 UTC, ryan-0324 requested changes

2023-11-09 03:55 UTC, ryan-0324 commented on src/plugins/SoundBoardLogger/index.tsx
> +        <svg
These SVGs could be optimized. Try using SVGO.

2023-11-09 05:38 UTC, MrDiamondDog commented on src/plugins/soundBoardLogger/types.ts
> +/*
I wouldn't separate the file that much, the smaller ones like types and settings can still be in the main file if you prefer

2023-11-09 07:32 UTC, ImpishMoxxie commented
Fixed that it uploaded index.tsx and style.css to a nonexistent folder

2023-11-09 11:58 UTC, TheKodeToad commented on src/plugins/soundBoardLogger/components/SoundBoardLog.tsx
> +                                <Button color={Button.Colors.LINK} size={Button.Sizes.SMALL} onClick={() => downloadAudio(item.soundId)}>Download</Button>
```suggestion
                                <Button color={Button.Colors.PRIMARY} size={Button.Sizes.SMALL} onClick={() => downloadAudio(item.soundId)}>Download</Button>
```
more consistent

2023-11-09 12:48 UTC, ImpishMoxxie commented on src/plugins/soundBoardLogger/components/SoundBoardLog.tsx
> +                                <Button color={Button.Colors.LINK} size={Button.Sizes.SMALL} onClick={() => downloadAudio(item.soundId)}>Download</Button>
we did different colors for the buttons so they wont just blend together and you can know what each button dose without the need to read the text on it

2023-11-09 12:53 UTC, TheKodeToad commented on src/plugins/soundBoardLogger/components/SoundBoardLog.tsx
> +                                <Button color={Button.Colors.LINK} size={Button.Sizes.SMALL} onClick={() => downloadAudio(item.soundId)}>Download</Button>
still different design language to Discord

2023-11-09 12:54 UTC, ImpishMoxxie commented on src/plugins/soundBoardLogger/components/SoundBoardLog.tsx
> +                                <Button color={Button.Colors.LINK} size={Button.Sizes.SMALL} onClick={() => downloadAudio(item.soundId)}>Download</Button>
ill update the download to primary

2023-11-10 20:14 UTC, D3SOX commented
I suggest adding some kind of hint when there are no sounds logged yet. Currently it looks a bit empty there
![image](https://github.com/Vendicated/Vencord/assets/24937357/83a48a84-8c18-41c5-b9c2-777114f5873c)

2023-11-10 20:17 UTC, D3SOX commented on src/plugins/soundBoardLogger/components/UserModal.tsx
> +                    <Text variant="text-md/normal">Played {currentUser.plays.length} times.</Text>
```suggestion
                    <Text variant="text-md/normal">Played {currentUser.plays.length} {currentUser.plays.length === 1 'time' : 'times'}.</Text>
```

2023-11-10 20:20 UTC, D3SOX commented on src/plugins/soundBoardLogger/components/MoreUsersModal.tsx
> +                                <Forms.FormText variant="text-xs/medium" style={{ cursor: "pointer" }}>Played {currentUser.plays.length} times</Forms.FormText>
```suggestion
                                <Forms.FormText variant="text-xs/medium" style={{ cursor: "pointer" }}>Played {currentUser.plays.length} {currentUser.plays.length === 1 ? 'time' : 'times'}</Forms.FormText>
```

2023-11-10 21:09 UTC, ImpishMoxxie commented on src/plugins/soundBoardLogger/components/UserModal.tsx
> +                    <Text variant="text-md/normal">Played {currentUser.plays.length} times.</Text>
we totally forgot about this tnx ill add this.

2023-11-10 21:14 UTC, ImpishMoxxie commented on src/plugins/soundBoardLogger/components/MoreUsersModal.tsx
> +                                <Forms.FormText variant="text-xs/medium" style={{ cursor: "pointer" }}>Played {currentUser.plays.length} times</Forms.FormText>
it's not meant to be clickable it's just a text. There is no reason to make the cursor a pointer.

2023-11-10 21:37 UTC, D3SOX commented on src/plugins/soundBoardLogger/components/MoreUsersModal.tsx
> +                                <Forms.FormText variant="text-xs/medium" style={{ cursor: "pointer" }}>Played {currentUser.plays.length} times</Forms.FormText>
> it's not meant to be clickable it's just a text. There is no reason to make the cursor a pointer.

It wasn't my suggestion. I think should've put this as a new review :)

2023-11-10 21:43 UTC, ImpishMoxxie commented on src/plugins/soundBoardLogger/components/MoreUsersModal.tsx
> +                                <Forms.FormText variant="text-xs/medium" style={{ cursor: "pointer" }}>Played {currentUser.plays.length} times</Forms.FormText>
oh ok ill put this just without the cursor: "pointer" part

2023-11-10 21:49 UTC, ImpishMoxxie commented on src/plugins/soundBoardLogger/components/MoreUsersModal.tsx
> +                                <Forms.FormText variant="text-xs/medium" style={{ cursor: "pointer" }}>Played {currentUser.plays.length} times</Forms.FormText>
thought it was on the same file I'm stupid anyway tnx for the fix <3

2023-11-10 23:28 UTC, ImpishMoxxie commented
@D3SOX added the soundboard volume into the play button and added an ester egg when no sounds are logged :3

2023-11-11 20:54 UTC, D3SOX commented
I noticed two more things:
- the volume isn't used when playing via the user modals.
- when you're deafened you can't play sounds (not that big of a deal but might be confusing)

2023-11-13 14:33 UTC, ImpishMoxxie commented
@D3SOX fixed the volume in the user modals and made it play when on deafen!
We also added a soundboard cloner option

# Sound Cloning

![sound](https://i.imgur.com/stW2TeW.png)

accessible by the context menu in sounds in the soundboard log :3

2023-11-13 14:36 UTC, D3SOX commented on src/plugins/soundBoardLogger/utils.ts
> +export const getSoundboardVolume = () => v1.amplitudeToPerceptual(v2.getAmplitudinalSoundboardVolume());
Untested but should work
```suggestion
const { amplitudeToPerceptual } = findByPropsLazy("amplitudeToPerceptual");
const { getAmplitudinalSoundboardVolume } = findByPropsLazy("getAmplitudinalSoundboardVolume");

export const getSoundboardVolume = () => amplitudeToPerceptual(getAmplitudinalSoundboardVolume());
```

2023-11-13 14:38 UTC, D3SOX commented
Works as excepted now for me! :rocket:

2023-11-13 14:42 UTC, ImpishMoxxie commented on src/plugins/soundBoardLogger/utils.ts
> +export const getSoundboardVolume = () => v1.amplitudeToPerceptual(v2.getAmplitudinalSoundboardVolume());
trying to destructure those at the top level seems to cause a crash for reasons I do not understand

2023-11-13 14:44 UTC, D3SOX commented on src/plugins/soundBoardLogger/utils.ts
> +export const getSoundboardVolume = () => v1.amplitudeToPerceptual(v2.getAmplitudinalSoundboardVolume());
Oh I see, I don't understand it either .-.

2023-11-13 14:45 UTC, ImpishMoxxie commented on src/plugins/soundBoardLogger/utils.ts
> +export const getSoundboardVolume = () => v1.amplitudeToPerceptual(v2.getAmplitudinalSoundboardVolume());
errors do be funny what can I say

2023-11-13 14:57 UTC, Nuckyz commented on src/plugins/soundBoardLogger/utils.ts
> +export const getSoundboardVolume = () => v1.amplitudeToPerceptual(v2.getAmplitudinalSoundboardVolume());
destructuring the lazy find makes it non lazy, so it ends up trying to search for it before discord has loaded

2023-11-13 14:57 UTC, TheKodeToad commented on src/plugins/soundBoardLogger/utils.ts
> +export const getSoundboardVolume = () => v1.amplitudeToPerceptual(v2.getAmplitudinalSoundboardVolume());
it's because it's lazily evaluated and isn't available on initialisation i guess

2023-11-13 14:58 UTC, TheKodeToad commented on src/plugins/soundBoardLogger/utils.ts
> +export const getSoundboardVolume = () => v1.amplitudeToPerceptual(v2.getAmplitudinalSoundboardVolume());
lmao

2023-11-13 14:58 UTC, ImpishMoxxie commented on src/plugins/soundBoardLogger/utils.ts
> +export const getSoundboardVolume = () => v1.amplitudeToPerceptual(v2.getAmplitudinalSoundboardVolume());
💀

2023-11-22 06:43 UTC, ImpishMoxxie commented
I had to remove the option to select the file type of the downloaded sound because it was broken.

2023-11-24 08:46 UTC, D3SOX requested changes
Context Menu API changed

2023-11-24 08:46 UTC, D3SOX commented on src/plugins/soundBoardLogger/components/SoundBoardLog.tsx
> +import { UserUtils, Clickable, Tooltip, Forms, Button, Text, useState, useEffect, ContextMenu, Menu, FluxDispatcher } from "@webpack/common";
```suggestion
import { UserUtils, Clickable, Tooltip, Forms, Button, Text, useState, useEffect, ContextMenuApi, Menu, FluxDispatcher } from "@webpack/common";
```

2023-11-24 08:46 UTC, D3SOX commented on src/plugins/soundBoardLogger/components/SoundBoardLog.tsx
> +                                ContextMenu.open(e, () => <SoundContextMenu item={item} />)
```suggestion
                                ContextMenuApi.openContextMenu(e, () => <SoundContextMenu item={item} />)
```

2023-12-08 10:35 UTC, D3SOX approved these changes
I've been using the plugin for a while now and haven't experienced any more issues!

2023-12-24 14:15 UTC, ImpishMoxxie commented
Is there anything I should add/change? 
or is this ready?

2024-02-06 21:43 UTC, ImpishMoxxie commented
updated everything for latest version

2024-02-28 14:45 UTC, closed without merging