[Plugin] LargeProfileAvatars
Vendicated/Vencord pull request #1976
Opened 2023-11-11 21:53 UTC by BoardTM

Makes avatars take up the full width of the profile modal and renders them in higher resolution.
![before](https://github.com/Vendicated/Vencord/assets/26598490/0550bbb3-c3a1-4edd-8563-8ff47702d49a)
![after](https://github.com/Vendicated/Vencord/assets/26598490/05e868ca-f498-404f-b8a5-cbbc87de02d2)

2023-11-11 22:09 UTC, ant0n-0x0000 reviewed
Could be a good idea to add fallbacks incase discord update UI but that's up to you.

2023-11-11 22:09 UTC, ant0n-0x0000 commented on src/plugins/largeProfileAvatars/index.ts
> + * Copyright (c) 2023 Vendicated and Board
I think this needs to include contributors.

```suggestion
 * Copyright (c) 2023 Vendicated, Board, and contributors
```

2023-11-11 22:14 UTC, ant0n-0x0000 requested changes
Oh also, add a README.md for your plugin!

2023-11-11 23:26 UTC, MrDiamondDog commented
This can be done with css

2023-11-12 11:41 UTC, BoardTM commented
> This can be done with css

Correct me if I’m wrong, but css will not be able to change the resolution of the avatar which is why this is a plugin and not just a theme.

2023-11-12 17:48 UTC, MrDiamondDog commented
I don't think you can change the resolution but most pfps are high enough resolution already, either way this doesn't feel like it should be a whole plugin

2023-11-12 17:54 UTC, BoardTM commented
Discord only grabs the picture in 80x80px by default this plugin makes it user selectable.

2023-11-13 13:47 UTC, BoardTM commented
Turns out the patch is kinda flawed so I’m closing this so I can rework it.

2023-11-13 18:28 UTC, BoardTM commented
Completely rewrote the patch such that it no longer touches chat avatars

2024-05-11 22:37 UTC, Vendicated commented
honestly the way this looks is kinda ugly. might be better to have it in larger size here instead and push the rest down?
![image](https://github.com/Vendicated/Vencord/assets/45497981/a93f0d56-3126-42d4-9675-38baaaa487c9)

alternatively, and especially considering this plugin mostly consists of css, you could instead just define a larger pfp link as a data attribute on the pfp node and leave the rest of the work to themes / quick css? this way a theme could do something like the following and then adjust the ui accordingly
```css
.avatar {
	content: attr(large-avatar-url);
}
```
this could be part of the ThemeAttributes plugin

let me know your thoughts! (and sorry for taking so long to get to this)

2024-05-12 10:17 UTC, BoardTM commented
> alternatively, and especially considering this plugin mostly consists of css, you could instead just define a larger pfp link as a data attribute on the pfp node and leave the rest of the work to themes / quick css? this way a theme could do something like the following and then adjust the ui accordingly
> 
> ```css
> .avatar {
> 	content: attr(large-avatar-url);
> }
> ```
> 
> this could be part of the ThemeAttributes plugin
> 
> let me know your thoughts! (and sorry for taking so long to get to this)

I like this idea, would probably need a completely new patch since it would probably be better to try to add it to all avatarstack elements so that it could be used in more places. I'll keep this PR open for the time being (if that's alright) but I assume it would be better to open a new one for the addition to ThemeAttributes.

2024-05-14 02:31 UTC, closed without merging

2024-05-14 02:31 UTC, Vendicated commented
assuming this can be closed now as superseded by #2249?