showBadgesInChat
Vendicated/Vencord pull request #1980
Opened 2023-11-12 21:26 UTC by ShalevG114

Allows the user to see Vencord and profile badges in the chat.

2023-11-13 01:07 UTC, MrDiamondDog requested changes

2023-11-13 01:07 UTC, MrDiamondDog commented on src/plugins/showBadgesInChat/index.tsx
> +const dcBadges: [number, string, string][] = [
Is there a reason for using an array over an object?

2023-11-13 02:57 UTC, FieryFlames commented on src/plugins/showBadgesInChat/index.tsx
> +    return userDCBadges;
```suggestion
    return dcBadges
      .filter(badge => flags & (1 << badge[0]))
      .map(badge => [badge[1], badge[2]])
```

2024-03-12 00:46 UTC, KrstlSkll69 commented on src/plugins/showBadgesInChat/index.tsx
> +                src={"https://cdn.discordapp.com/attachments/1033680203433660458/1092089947126780035/favicon.png"}
```suggestion
                src={"https://vencord.dev/assets/favicon.png"}
```

2024-03-12 01:05 UTC, KrstlSkll69 commented on src/plugins/showBadgesInChat/index.tsx
> +                src={"https://cdn.discordapp.com/attachments/1033680203433660458/1092089947126780035/favicon.png"}
possible fix for the dead link

2024-03-12 19:20 UTC, KrstlSkll69 commented on src/plugins/showBadgesInChat/index.tsx
> +
```suggestion
let VencordBadges = {} as Record<string, Array<Record<"tooltip" | "badge", string>>>;
```

2024-05-28 02:19 UTC, Vendicated commented
superseded by #2347, thanks for your work!

2024-05-28 02:19 UTC, closed without merging