new plugin: notificationVolume
Vendicated/Vencord pull request #1992
Opened 2023-11-15 21:20 UTC by philipbry

separate adjustment for notification sound volume (e.g. messages, call sound, mute/unmute) because setting it in the windows volume mixer isn't persistent across restarts and it hurts my ears.
(not sure if i should request a merge into main so chose dev)

2023-11-15 21:27 UTC, MrDiamondDog requested changes

2023-11-15 21:27 UTC, MrDiamondDog commented on src/plugins/notificationVolume/index.ts
> +                replace: "_ensureAudio(){this._volume*=$self.settings.store.notificationVolume/100;"
Use `$&` to insert the match instead of doing it manually

2023-11-15 21:27 UTC, MrDiamondDog commented on src/plugins/notificationVolume/index.ts
> +    authors: [
Add yourself to devs

2023-11-15 21:28 UTC, ant0n-0x0000 commented
Include a README.md file with your plugin that explains what it does tooo
gd idea tho

2023-11-15 21:46 UTC, philipbry commented on src/plugins/notificationVolume/index.ts
> +    authors: [
done

2023-11-15 21:46 UTC, philipbry commented on src/plugins/notificationVolume/index.ts
> +                replace: "_ensureAudio(){this._volume*=$self.settings.store.notificationVolume/100;"
done

2023-11-15 21:47 UTC, philipbry commented
> Include a README.md file with your plugin that explains what it does tooo gd idea tho

where exectly would i add one?

2023-11-15 21:52 UTC, MrDiamondDog commented
Top level of your plugin folder

2023-11-15 21:53 UTC, MrDiamondDog approved these changes

2023-11-15 22:02 UTC, philipbry commented
> Top level of your plugin's folder

done

2023-12-06 21:29 UTC, Vendicated commented on src/plugins/notificationVolume/index.ts
> +                replace: "$&this._volume*=$self.settings.store.notificationVolume/100;"
why *=? just a = seems more logical to me

2023-12-06 21:48 UTC, philipbry commented on src/plugins/notificationVolume/index.ts
> +                replace: "$&this._volume*=$self.settings.store.notificationVolume/100;"
you have a point, ill fix it in a few minutes

2023-12-06 22:00 UTC, philipbry commented on src/plugins/notificationVolume/index.ts
> +                replace: "$&this._volume*=$self.settings.store.notificationVolume/100;"
done

2023-12-06 22:15 UTC, merged