feat(plugin): clock
Vendicated/Vencord pull request #2001
Opened 2023-11-18 23:29 UTC by Tnixc

Adds a customizable clock with timezones to the user panels section.
<img width="261" alt="image" src="https://github.com/Vendicated/Vencord/assets/85466117/a215ca2a-ae04-4f1b-b192-32cfbb82f259">

2023-11-18 23:53 UTC, MrDiamondDog requested changes

2023-11-18 23:53 UTC, MrDiamondDog commented on src/plugins/Clock/index.ts
> +            if (slotOneEnabled) { slotOneClock.textContent = slotOneLabel + seperator + now.toLocaleTimeString([], clockOneOptions); }
```suggestion
            if (slotOneEnabled) slotOneClock.textContent = slotOneLabel + seperator + now.toLocaleTimeString([], clockOneOptions);
```
Same thing for the rest of them

2023-11-18 23:53 UTC, MrDiamondDog commented on src/plugins/Clock/index.ts
> +        panels?.appendChild(clockContainer);
Since you already checked it existed
```suggestion
        panels.appendChild(clockContainer);
```

2023-11-18 23:53 UTC, MrDiamondDog commented on src/plugins/Clock/index.ts
> +            clockContainer?.appendChild(slotOneClock);
This is literally never null/undefined
```suggestion
            clockContainer.appendChild(slotOneClock);
```

2023-11-18 23:57 UTC, Tnixc commented on src/plugins/Clock/index.ts
> +            if (slotOneEnabled) { slotOneClock.textContent = slotOneLabel + seperator + now.toLocaleTimeString([], clockOneOptions); }
Done

2023-11-19 00:47 UTC, Vendicated commented
sorry but this pr is very low quality, thus unmergeable

- it has waaay too many / confusing settings
- it uses dom manipulation instead of using react and patches
- you're hardcoding css classes instead of obtaining them from webpack

2023-11-19 00:48 UTC, Tnixc commented
Understandable

2023-11-19 00:48 UTC, closed without merging

2023-11-19 00:49 UTC, Vendicated commented
thank you for your effort anyway! you can still post it in the third party plugins channel if you want (although i still advise fixing these issues)

2023-11-19 00:51 UTC, Tnixc commented
Of course, I'm not skilled enough to recognize its issues. I'll work this.

2023-12-03 21:25 UTC, Wannacry-ops commented
> ¡Gracias por tu esfuerzo de todos modos! aún puedes publicarlo en el canal de complementos de terceros si lo deseas (aunque aún así recomiendo solucionar estos problemas)

what is that channel? can you send me the link