Add light mode support to ClientTheme
Vendicated/Vencord pull request #2010
Opened 2023-11-22 05:47 UTC by CodeF53

Pretty confident this is up to Vencord standard except maybe variable names

2023-11-22 06:06 UTC, Vendicated commented on src/plugins/clientTheme/clientTheme.css
> +.theme-light {
you're changing global styles in a non managed css file. thats baaaaad. make your css managed

2023-11-22 06:06 UTC, Vendicated commented on src/plugins/clientTheme/index.tsx
> +const saveClientTheme = findByPropsLazy("saveClientTheme");
```suggestion
const { saveClientTheme } = findByPropsLazy("saveClientTheme");
```

2023-11-22 19:21 UTC, Nuckyz requested changes

2023-11-22 19:21 UTC, Nuckyz commented on src/plugins/clientTheme/index.tsx
> +function swapTheme() {
```suggestion
function swapTheme(currentTheme: string) {
```

2023-11-22 19:21 UTC, Nuckyz commented on src/plugins/clientTheme/index.tsx
> +    const isLightTheme = getTheme() === Theme.Light;
```suggestion
```

2023-11-22 19:21 UTC, Nuckyz commented on src/plugins/clientTheme/index.tsx
> +    saveClientTheme({ theme: isLightTheme ? "dark" : "light" });
```suggestion
    saveClientTheme({ theme: currentTheme === "light" ? "dark" : "light" });
```

2023-11-22 19:21 UTC, Nuckyz commented on src/plugins/clientTheme/index.tsx
> +                    {!unFixableContrast && <Button onClick={swapTheme}>Swap Theme</Button>}
```suggestion
                    {!unFixableContrast && <Button onClick={() => swapTheme(theme)}>Swap Theme</Button>}
```

2023-11-22 23:52 UTC, CodeF53 commented
Last commit was pretty big, as it added another generator

I switched to generating light mode fixing css because:
1. Overriding white-500 screwed with font color rendering
2. Manually writing overwrites for every single usage of white-500 for a background is not fun. (the generator makes 80 lines of css)
3. Manually written overrides will break, and a major part of the plugin is to generate css so it doesn't break when discord changes/adds/removes stuff.

Also in this commit, lots of code was moved to helper functions due to usage by both `generateColorOffsets` and `generateLightModeFixes`

2023-11-23 00:08 UTC, CodeF53 commented
Its stuck saying there is a "Changes requested 1 review requesting changes" when I have already resolved everything

2023-11-30 18:45 UTC, FieryFlames commented on src/plugins/clientTheme/index.tsx
> +import { Button, Forms, lodash as _, useStateFromStores } from "@webpack/common";
why import lodash as _?

2023-11-30 18:45 UTC, FieryFlames commented on src/plugins/clientTheme/index.tsx
> +    console.log(selectedLuminance);
a console.log 😨

2024-01-16 02:53 UTC, merged