feat(plugin): Change previewMessage SVG icon
Vendicated/Vencord pull request #2045
Opened 2023-12-10 23:40 UTC by Andrew6rant

This PR changes the SVG icon in the plugin previewMessage with one that attempts to closer match the style of Discord's chat bar icons.

Before:

![before_IMG](https://github.com/Vendicated/Vencord/assets/57331134/b910855b-e5c5-4831-95a9-f8c5233bcebc)

After:

![after_SVG](https://github.com/Vendicated/Vencord/assets/57331134/6ba1f468-eebc-4f24-b987-5215bc26f82d)

2023-12-11 00:13 UTC, Andrew6rant commented
Alternately, use the same icon that Discord has for these types of messages.

![after_alternate_icon](https://github.com/Vendicated/Vencord/assets/57331134/d712fa14-d3a1-4694-98df-434d3bbfca21)

2023-12-11 23:16 UTC, ryan-0324 requested changes
I made the button more consistent with the default chat box buttons and cleaned up and optimized the SVG.

2023-12-13 05:21 UTC, Andrew6rant commented on src/plugins/previewMessage/index.tsx
>                      </div>
Optimized and repositioned SVG looks good to me, although I think I personally prefer the style to have 3px padding and margin instead of 4px.

GitHub web is throwing a fit about committing your suggested changes:
![suggested_changes](https://github.com/Vendicated/Vencord/assets/57331134/7918da73-f099-4e95-b05f-1ba75fd26b05)
So I am just going to do it through the command line.

2024-01-05 23:50 UTC, Vendicated commented
hi, could you please show an updated image

2024-01-06 03:33 UTC, Andrew6rant commented
![Cleaned-up SVG Showcase image](https://github.com/Vendicated/Vencord/assets/57331134/b21c0edc-ced2-4bea-b284-3a160abfcf09)

2024-02-06 16:53 UTC, Vendicated commented
thanks! incorporated into https://github.com/Vendicated/Vencord/commit/685b6f2fa799123273581fef52316a9136ffd1c4

2024-02-06 16:53 UTC, closed without merging