feat: Badge API
Vendicated/Vencord pull request #206
Opened 2022-11-11 21:40 UTC by MeguminSama

2022-11-11 22:35 UTC, Vendicated requested changes

2022-11-11 22:35 UTC, Vendicated commented on src/api/Badges.ts
> +export enum InsertAt {
```suggestion
export enum BadgePosition {
```

2022-11-11 22:35 UTC, Vendicated commented on src/api/Badges.ts
> +    insertAt?: InsertAt;
```suggestion
    position?: BadgePosition;
```

2022-11-11 22:35 UTC, Vendicated commented on src/api/Badges.ts
> +    Badges.delete(badge);
```suggestion
    return Badges.delete(badge);
```

2022-11-11 22:35 UTC, Vendicated commented
pls rename file to apiBadges or something like that to have all api plugins show grouped!!!

2022-11-11 22:49 UTC, Vendicated approved these changes

2022-11-11 22:50 UTC, merged

2022-11-12 00:21 UTC, ArjixWasTaken commented
> pls rename file to apiBadges or something like that to have all api plugins show grouped!!!

Isn't it time we move all the internal patches to a separate folder?

2022-11-12 00:22 UTC, Vendicated commented
that would require a refactor of the commands module builder which I'm too lazy to do rn