(feat) allow customization for the speed of the cat :3
Vendicated/Vencord pull request #2075
Opened 2023-12-27 09:47 UTC by not-varram

2023-12-27 09:49 UTC, not-varram commented
this has been bugging me for way too long hahaha (and I don't feel like manually making a new dev build for everytime this thing gets updated)

2023-12-29 22:05 UTC, lewisakura requested changes

2023-12-29 22:05 UTC, lewisakura commented on src/plugins/oneko/index.ts
> +    description: "cat follow mouse (real) x2 speed",
?

2023-12-29 22:05 UTC, lewisakura commented on src/plugins/oneko/index.ts
> +    },
Use `definePluginSettings`, the options API is deprecated.

2023-12-29 22:05 UTC, lewisakura commented on src/plugins/oneko/index.ts
> +                }
Code duplication no bueno, just call `stop()` and `start()`.

2023-12-29 22:05 UTC, lewisakura commented on src/plugins/oneko/index.ts
> +            .then(s => s.replace("const nekoSpeed = 10;", `const nekoSpeed = ${Settings.plugins.oneko.randomisedLength};`))
Replace with new settings API.

2024-01-13 04:40 UTC, not-varram commented
Fixed all the issues pointed out in the comments :D

2024-01-22 04:25 UTC, closed without merging