SearchFix plugin
Vendicated/Vencord pull request #2122
Opened 2024-01-21 15:50 UTC by Jaxx7594

Fixes the annoying "We dropped the magnifying glass" error when using the search bar. I very rarely use typescript or javascript, so if there are any issues with this code, please tell me and I'll try to fix it.

2024-01-21 16:20 UTC, sunnniee requested changes

2024-01-21 16:20 UTC, sunnniee commented on src/plugins/searchFix/index.ts
> +    description: "Fixes the annoying \"We dropped the magnifying glass!\" error. This fix isn't perfect, so you may have to reload the search bar to fix issues. Note: Discord only allows a max offset
keep the description in a single sentence, and then use the `settingsAboutComponent` plugin property to keep the additional info

```ts
export default definePlugin({
    name: "SearchFix",
    description: 'Fixes the annoying "We dropped the magnifying glass!" error.',
    settingsAboutComponent: () => "Discord only allows a max offset of 5000 (this is what causes the magnifying glass error). This means that ..."
```

2024-01-21 16:20 UTC, sunnniee commented on src/plugins/searchFix/index.ts
> +                match: /(.)\.offset=null!==\((.)=(.)\.offset\)&&void 0!==(.)\?(.):0/i,
hardcoding variable names (& webpack module ids) inside the finder is very very bad. you should use something that wont change the next time discord decides to rebuild. here since you're just patching a store, you can use `.displayName="SearchStore";`

also you should use `\i` to match variable names, it's a custom token by vencord for that purpose

2024-01-21 16:20 UTC, sunnniee commented on src/plugins/searchFix/index.ts
> +                    `${v}.offset = null !== (${v1} = ${query}.offset) && void 0 !== ${v3} ? ${v4} : 0`
you can add a function to your plugin that does this in a readable way, and then reference it within the patch by using `$self` (you can also make groups larger than a single variable, or use `$&` to reinsert the entire match, to not have to rewrite discord's code within the patch)

```ts
export default definePlugin({
  patches: [
  // ...
  replace: (_, myval) => `foo;$self.doSomething(${myval});bar`
  ],
  doSomething(myval) {
      // ...
  }
```

2024-01-21 16:26 UTC, MrDiamondDog reviewed
Add a readme.md to your plugin, providing a longer description (like the one you have now) and possibly some images.

2024-01-21 16:26 UTC, MrDiamondDog commented on src/plugins/searchFix/index.ts
> +    authors: [
Add yourself to devs

2024-01-21 16:28 UTC, Jaxx7594 commented
Thanks for all the feedback! I'll try to fix all this tomorrow

2024-01-22 10:46 UTC, Jaxx7594 commented
Should be much more readable, and now has a readme showing before and after gifs

2024-01-22 14:29 UTC, MrDiamondDog commented on src/plugins/searchFix/index.tsx
> +        if (query.offset > 5000) {
try inverting this if statement so you dont nest as much
```suggestion
        if (query.offset <= 5000) return;
```

2024-01-22 14:29 UTC, MrDiamondDog commented on src/plugins/searchFix/index.tsx
> +            }
This if block would be better using ternary, not so much the other one
```suggestion
            query.sort_order === "asc" ? "desc" : "asc";
```

2024-01-22 16:06 UTC, Jaxx7594 commented on src/plugins/searchFix/index.tsx
> +        if (query.offset > 5000) {
Inverting it broke everything for some reason, and its too small of an issue for me to bother debugging it. I did the ternary thing though

2024-01-22 16:11 UTC, Jaxx7594 commented on src/plugins/searchFix/index.tsx
> +        if (query.offset > 5000) {
nvm ternary broke it too.. guess ive gotta do some debugging

2024-01-22 16:13 UTC, Jaxx7594 commented on src/plugins/searchFix/index.tsx
> +        if (query.offset > 5000) {
oml im an idiot, forgot to assign the var lmao

2024-01-22 16:27 UTC, MrDiamondDog commented on src/plugins/searchFix/index.tsx
> +        if (query.offset > 5000) {
Yeah I forgot to put that lol

2024-02-24 17:55 UTC, Jaxx7594 commented
bump

2024-06-06 02:30 UTC, Vendicated commented
i finally understood what this is supposed to solve but now i don't exactly understand the use case. in what scenario would you go this far back in history and not just sort by old instead?

you might be better off asking discord to instead remove this limitation

2024-06-07 07:45 UTC, Jaxx7594 commented
@Vendicated I can't remember exactly why I made this, but its probably because its just a pointless limitation that only annoys users, and its pretty annoying having to calculate (for example) what page 6324 while sorting by newest would be when sorting by oldest. As for why you would go so far back in history, for example, a user may be looking for a specific message on a specific date

2024-06-07 21:33 UTC, Vendicated commented
yeaahh i really cannot find a use case for this... thank you for the contribution anyway!

2024-06-07 21:33 UTC, closed without merging