Add custom allCallTimers plugin
Vendicated/Vencord pull request #2132
Opened 2024-01-27 12:00 UTC by Max-Herbold

Builds on the idea of the callTimer plugin but adds timers to all users in guild voice calls.

Note: this only keeps track of users as long as Discord is open. When restarting Discord for any reason the data is lost.

### Looks like this
![image](https://github.com/Vendicated/Vencord/assets/49804267/2ccf5408-796c-45a5-879c-3867be82215f)

Please let me know if you have any questions or suggestions for improvement.

2024-01-27 12:14 UTC, D3SOX requested changes
I think you could use IPC events instead of the interval to handle users joining/switching channels.
As per looks I think it looks kinda bad as the red color doesn't fit very well and it overlaps other things
Your plugin is missing a `README.md`

The data is lost on restart because the plugin is restarted btw :)

2024-01-27 12:14 UTC, D3SOX commented on src/plugins/allCallTimers/index.tsx
> +    ],
Add yourself to Devs

2024-01-27 12:14 UTC, D3SOX commented on src/plugins/allCallTimers/index.tsx
> +    update_listings() {
Don't use snake case, please use ESLint

2024-01-27 12:14 UTC, D3SOX commented on src/plugins/allCallTimers/index.tsx
> +        }
You could use array functions like `.map` here to make the code prettier

2024-01-27 12:38 UTC, Max-Herbold commented on src/plugins/allCallTimers/index.tsx
> +    update_listings() {
thx, old habit

2024-01-27 12:39 UTC, Max-Herbold commented on src/plugins/allCallTimers/index.tsx
> +        }
brackets was the linter suggestion seemed less readable to me but listening to the linter removed the underline

2024-01-27 13:29 UTC, Max-Herbold commented
> I think you could use IPC events instead of the interval to handle users joining/switching channels

How it is at the moment works; given it's never necessary to update this more than once a second. I agree, where could I find some example how to do/use this? I have 0 experience with this.

>As per looks I think it looks kinda bad as the red color doesn't fit very well and it overlaps other things

I also agree. It's less than ideal to move elements around; there is very limited space. When it is inline, a long username will cause ellipsed usernames. Under the username makes it too confusing about who the timer belongs to. there is not enough space to the left. Where it is now is conditionally free when there are no rendered icons. The icons can still be seen clearly. As for the red, again I agree but if the element doesn't fit cleanly why not go all out?

2024-01-27 13:57 UTC, D3SOX requested changes
Some more suggestions:

For the looks maybe use a clock icon and then put the time in the tooltip if it's okay to be only visible on hover

For the IPC implementation just look into other plugins. For example
https://github.com/Vendicated/Vencord/blob/620c127b58e94ce4bf0b78d7e55fbce8e4f376e2/src/plugins/vcNarrator/index.tsx#L160-L188

The Plugin name doesn't need to be camelCase (also see other plugins for reference)

2024-01-27 14:06 UTC, D3SOX requested changes

2024-01-27 14:06 UTC, D3SOX commented on src/plugins/allCallTimers/index.tsx
> +        const timer = useTimer({});
`timer` is unused here

2024-01-27 14:06 UTC, D3SOX commented on src/plugins/allCallTimers/index.tsx
> +    showInjection(property) {
add type

2024-01-27 14:06 UTC, D3SOX commented on src/plugins/allCallTimers/index.tsx
> +    allUsers(guilds) {
add type

2024-01-27 14:06 UTC, D3SOX commented on src/plugins/allCallTimers/index.tsx
> +        this.VoiceStateStore = findStore("VoiceStateStore");
Not sure if it's a problem to have the store in `this`. Other plugins do it differently. Another contributor should probably review this.

2024-01-27 14:09 UTC, Max-Herbold commented on src/plugins/allCallTimers/index.tsx
> +        const timer = useTimer({});
it calls itself? I don't understand this inbuilt react timer but it works. Without it, the timer won't refresh

2024-01-27 14:20 UTC, D3SOX commented on src/plugins/allCallTimers/index.tsx
> +        const timer = useTimer({});
Oh ok, I'm sure there's a better way to make the component re-render but I can't debug it right now

2024-01-27 16:12 UTC, Max-Herbold commented
> For the looks maybe use a clock icon and then put the time in the tooltip if it's okay to be only visible on hover

<img width="165" alt="image" src="https://github.com/Vendicated/Vencord/assets/49804267/9e2e7fa2-ebf0-48d0-bf94-9c4e59cfb397"> (mouse is hovering on the user's clock icon)

Also implemented with a toggle switch setting (because I like not having to move my mouse to see the times). The default setting is with the icon + tooltip.

2024-01-27 16:22 UTC, Max-Herbold commented on src/plugins/allCallTimers/index.tsx
> +        this.VoiceStateStore = findStore("VoiceStateStore");
Looks like the standard is to lazily find at the top of the file - switched to this.

2024-01-27 16:53 UTC, D3SOX commented
Are you working on the IPC implementation? Or should I do it?

2024-01-27 17:02 UTC, Max-Herbold commented
> Are you working on the IPC implementation? Or should I do it? And a quick heads-up the `README.md` is still missing
I was planning to have a look tomorrow but I would love to see what you come up with!

2024-01-27 18:41 UTC, D3SOX commented
Done: https://github.com/Max-Herbold/Vencord/pull/1

2024-01-28 00:20 UTC, Max-Herbold commented
It occurred to me previously but I only realised it was an issue now. UserState does not dispatch updates for users in a guild that has not been opened (literally viewed on the client side). This plays into the issue I was trying to fix with https://github.com/Vendicated/Vencord/pull/2132/commits/5ebc2c8819b3fa489ce5e3bcaaa8083d00d65d33. I guess on the first open of a guild discord client bulk updates all users in the guide and then updates them when something actually happens. Essentially; if a guild hasn't been opened and a user moves/joins this cannot be tracked with UserState.

2024-01-28 00:23 UTC, D3SOX commented
Oh yes good catch haven't noticed that

2024-01-28 00:26 UTC, D3SOX commented
> Potentially also there is an issue after a certain period of time of a guild being unopened events stop being dispatched but this is only an intuitive guess that should be checked

I don't think so as this worked for me
![image](https://github.com/Vendicated/Vencord/assets/24937357/afb18614-e43b-45c0-86aa-24704700d2f2)

2024-01-28 00:46 UTC, Max-Herbold commented
> Oh yes good catch haven't noticed that. Analyze the format when the client is loaded I don't think the way you do it right now is necessary.

True. I think that change (https://github.com/Vendicated/Vencord/commit/5ebc2c8819b3fa489ce5e3bcaaa8083d00d65d33) simply made the issue more complicated

2024-01-28 00:49 UTC, D3SOX commented
Hm but it does seem to work for me

2024-01-28 00:58 UTC, Max-Herbold commented
> Hm but it does seem to work for me

There is the case where a user joins/moves channel that hasn't been opened and they end up without a timer (in the `userJoinTimes`) and therefor no visual timer.

2024-01-28 05:39 UTC, Max-Herbold commented
reverted the change to use VoiceStateStore but kept everything else.

https://github.com/Max-Herbold/Vencord/pull/2

2024-01-28 12:48 UTC, D3SOX commented
> VOICE_STATE_UPDATES does not dispatch updates for users in a guild that has not been opened (literally viewed on the client side)

> There is the case where a user joins/moves channel that hasn't been opened and they end up without a time (in the `userJoinTimes`) and therefor no visual timer.

I can't reproduce this issue with the state of my PR. Can you give me more detailed instructions on how to reproduce it?
I have two Discord accounts open. With the Vencord one I'm just at the friends tab and when I log the voice state updates and search for my user ID I can clearly see the update looking fine on initial load (without `oldChannelId`) and when switching channels

2024-01-28 13:17 UTC, Max-Herbold commented
> I can't reproduce this issue with the state of my PR. Can you give me more detailed instructions on how to reproduce it? I have two Discord accounts open. With the Vencord one I'm just at the friends tab and when I log the voice state updates and search for my user ID I can clearly see the update looking fine on initial load (without `oldChannelId`) and when switching channels

After restarting Discord directly into DM's (somewhere other than a guild); I had added a console debug in the IPC only really to look at when it occurrs. Without opening any guilds it never occurred (other than the initial startup). Although this test case was probably exclusive to 10+ servers with 100+ users. After opening some of the guilds and returning to DM's updates could then be seen flowing.

2024-01-28 13:59 UTC, Max-Herbold commented
soz for force - wrong branch

2024-01-28 14:24 UTC, D3SOX commented
I think I definitely know why it happens and can fix the IPC implementation. Are you on Discord btw?

2024-01-28 14:25 UTC, Max-Herbold commented
> I think I definitely know why it happens and can fix the IPC implementation. Are you on Discord btw?

yeah ill msg u

2024-01-28 15:49 UTC, Max-Herbold commented on src/plugins/allCallTimers/index.tsx
> +                    replace: "$&$self.showInjection(this),"
fixed with https://github.com/Vendicated/Vencord/pull/2132/commits/9cc5c09fba604cc9d3515d9ca2159590a8b8c02c

2024-01-29 13:35 UTC, D3SOX approved these changes

2024-03-04 09:16 UTC, Max-Herbold commented
@Vendicated please review!

2024-04-05 14:47 UTC, Max-Herbold commented
This is ready to merge.

2024-04-05 16:56 UTC, Inbestigator commented
Damn, and here was me thinking that **I** committed a lot

2024-04-05 18:37 UTC, Loukious requested changes

2024-04-05 18:37 UTC, Loukious commented on src/plugins/allCallTimers/timerText.tsx
> +        marginTop: -6,  // this margin value doesn't change the default size of the user container
The test workflow will fail because of this comment and the one below it as well.

2024-04-05 23:54 UTC, Max-Herbold reviewed
Do these changes address the issue?

2024-04-05 23:58 UTC, Max-Herbold commented on src/plugins/allCallTimers/timerText.tsx
> +        marginTop: -6,  // this margin value doesn't change the default size of the user container
Does [de5c4d0](https://github.com/Vendicated/Vencord/pull/2132/commits/de5c4d04477af405bc52ead52b8f7324bf1423cd) address this correctly?

2024-04-06 02:48 UTC, Loukious commented on src/plugins/allCallTimers/timerText.tsx
> +        marginTop: -6,  // this margin value doesn't change the default size of the user container
> Does [de5c4d0](https://github.com/Vendicated/Vencord/pull/2132/commits/de5c4d04477af405bc52ead52b8f7324bf1423cd) address this correctly?

Yes, thanks.

2024-04-06 02:48 UTC, Loukious approved these changes

2024-04-06 02:49 UTC, Loukious approved these changes

2024-04-25 07:30 UTC, Max-Herbold commented
This is ready to be merged.

2024-06-24 15:19 UTC, kittygirlyy reviewed
meow

2024-08-19 12:40 UTC, Max-Herbold commented
> did i do something wrong because the build still doesn't work
Hi, @6faw it looks as though you have copied across the folder `AllCallTimers`. Unfortunately, this is not sufficient because some changes (refactoring/improvements/additions) were made to internal helper functions. Still waiting for some review/merge from @Vendicated.

2024-10-10 08:33 UTC, Max-Herbold commented
@Vendicated still awaiting some review.

2024-12-25 03:54 UTC, closed without merging