feat(translate): Auto Translate Received Messages
Vendicated/Vencord pull request #2169
Opened 2024-02-12 01:46 UTC by MrDiamondDog

Saw this requested a lot so I made it

2024-02-12 11:01 UTC, lewisakura commented
this will get you rate limited from the translate api, which is why it isnt in the main mod; it was a conscious choice made to prevent api abuse

2024-02-12 11:08 UTC, Vendicated commented
i think this feature is fine to have. i tested the rate limit in the past by sending thousands of requests to google and there doesn't seem to be any sort of rate limit

2024-02-15 08:55 UTC, Vendicated commented on src/plugins/translate/TranslateIcon.tsx
> +            <TranslateIcon className={cl({ "auto-translate": autoTranslate || autoTranslateReceived, "chat-button": true })} />
i think it might be better to use different colours / icon modifiers to signalise the state

2024-02-15 08:55 UTC, Vendicated commented on src/plugins/translate/index.tsx
> +            console.log(event.message);
```suggestion
```

2024-02-15 08:58 UTC, Vendicated requested changes
i think the current implementation is kinda meh. it would be better to keep separate state per channel. most people will only want to translate specific channels

2024-02-15 08:58 UTC, Vendicated commented on src/plugins/translate/index.tsx
> +import { Util } from "Vencord";
no

2024-02-15 09:00 UTC, Vendicated commented
i think the best solution to making it configurable per server would be smth like this
![image](https://github.com/Vendicated/Vencord/assets/45497981/bee03be1-58c0-4469-bf70-83104e93daea)

2024-02-29 04:16 UTC, MrDiamondDog commented
Everything you mentioned should now be implemented. I'm not sure what I should do to show when you are translating received messages though.

2024-03-02 19:39 UTC, Vendicated commented on src/components/PluginSettings/components/SettingSliderComponent.tsx
> +            <Forms.FormText style={{ color: "var(--text-muted)" }}>{option.description}</Forms.FormText>
please use a css class instead of inline style

2024-06-24 17:58 UTC, MrDiamondDog commented
hold on i messed up this branch

2024-06-24 17:58 UTC, closed without merging