feat(plugin): KeyboardClick
Vendicated/Vencord pull request #2206
Opened 2024-02-25 01:43 UTC by Slluxx

Adds nice clicking sounds when typing.

2024-02-25 04:11 UTC, CodeF53 commented
Take off headphones to enjoy this feature without any extra code

2024-02-25 06:58 UTC, Sqaaakoi commented
Was this PR sponsored by Opera GX?
Also I'd suggest adding a different sound for space, and also move yourself into the Devs list

2024-02-25 07:03 UTC, MrDiamondDog requested changes

2024-02-25 07:03 UTC, MrDiamondDog commented on src/plugins/keyboardClick/index.ts
> +    authors: [
Add yourself to devs

2024-02-25 07:03 UTC, MrDiamondDog commented on src/plugins/keyboardClick/index.ts
> +        sound_click1 = new Audio('https://dl.dropboxusercontent.com/s/vfxrfu2u8jiq6xw/click1.wav?raw=1');
The click sounds should definitely be configurable

2024-02-25 07:03 UTC, MrDiamondDog commented on src/plugins/keyboardClick/index.ts
> +    allowEscape: {
There has to be a better way to do this (custom settings component maybe?)

2024-02-25 07:03 UTC, MrDiamondDog commented on src/plugins/keyboardClick/index.ts
> +import definePlugin, { OptionType } from "@utils/types";
Make sure to run eslint

2024-02-25 07:10 UTC, Sqaaakoi commented on src/plugins/keyboardClick/index.ts
> +    allowEscape: {
Why would a custom settings component be useful in this case?

2024-02-25 07:21 UTC, MrDiamondDog commented on src/plugins/keyboardClick/index.ts
> +    allowEscape: {
So each key doesn't need an individual setting, would also make checking if the sound should play simpler. Although it might be fine how it is

2024-02-25 07:22 UTC, MrDiamondDog commented on src/plugins/keyboardClick/index.ts
> +    description: "Modified BD plugin for some nice clicking sounds when typing.",
```suggestion
    description: "Adds nice clicking sounds when typing.",
```

2024-02-25 11:16 UTC, Slluxx commented on src/plugins/keyboardClick/index.ts
> +    allowEscape: {
> So each key doesn't need an individual setting, would also make checking if the sound should play simpler. Although it might be fine how it is

The goal was not to have settings for each button but to blacklist common modifier and control buttons. The BD plugin has no such option and there is no and was no intent to expand this in any way.

2024-02-25 11:17 UTC, Slluxx commented on src/plugins/keyboardClick/index.ts
> +    authors: [
Roger

2024-02-25 11:18 UTC, Slluxx commented on src/plugins/keyboardClick/index.ts
> +import definePlugin, { OptionType } from "@utils/types";
I dont think eslint is mentioned anywhere. The Plugin Doc specifically says "Once you've made your plugin, make sure you run pnpm test and make sure your code is nice and clean!", which i did. Does the guide need to be changed?

2024-02-25 11:19 UTC, Slluxx commented on src/plugins/keyboardClick/index.ts
> +        sound_click1 = new Audio('https://dl.dropboxusercontent.com/s/vfxrfu2u8jiq6xw/click1.wav?raw=1');
I agree.

2024-02-25 11:55 UTC, verticalsync commented on src/plugins/keyboardClick/index.ts
> +import definePlugin, { OptionType } from "@utils/types";
eslint will already throw an error for missing header, it's just best to run eslint to also ensure the codebase is the same throughout.

2024-02-25 11:56 UTC, verticalsync commented on src/plugins/keyboardClick/index.ts
> +import definePlugin, { OptionType } from "@utils/types";
eslint will already throw an error for missing header, it's just best to run eslint to also ensure the codebase is the same throughout.

2024-02-25 16:44 UTC, MrDiamondDog commented on src/plugins/keyboardClick/index.ts
> +import definePlugin, { OptionType } from "@utils/types";
Your pr is actually blocked from merging if it fails listing. Install the eslint extension in vscode and it will auto-format

2024-05-11 23:53 UTC, Vendicated commented
hi, thanks a lot for your contribution!

i don't think this is very useful, too niche. why not just do it on a system level?

2024-05-11 23:53 UTC, closed without merging