feat(plugin): DeleteMessageFromMe
Vendicated/Vencord pull request #2207
Opened 2024-02-25 16:09 UTC by hanzydev

Adds a context menu option to delete the message from you.

2024-02-25 16:20 UTC, hanzydev commented
> How is this different from the existing delete message button?

The Delete Message button deletes the message you sent from everyone. The difference of this plugin is that it only deletes the message from your client, it does not send any API requests.

2024-02-25 16:34 UTC, Koishukaze commented
> > How is this different from the existing delete message button?
> 
> The Delete Message button deletes the message you sent from everyone. The difference of this plugin is that it only deletes the message from your client, it does not send any API requests.

what's the use case for this even

2024-02-25 16:36 UTC, TheKodeToad commented
I guess maybe if you're taking screenshots and you want to delete stuff that contains private info or irrelavent stuff?

2024-02-25 16:38 UTC, hanzydev commented
> > > How is this different from the existing delete message button?
> > 
> > 
> > The Delete Message button deletes the message you sent from everyone. The difference of this plugin is that it only deletes the message from your client, it does not send any API requests.
> 
> what's the use case for this even

Sometimes our friends and other people can send nsfw or disturbing images/content in a text channel that we don't want to see in a public place. This plugin removes the message from the DOM on demand. Kind of WhatsApp does but without a storage mechanism. When you reload your client the messages will be shown again.

2024-02-25 16:39 UTC, hanzydev commented
> I guess maybe if you're taking screenshots and you want to delete stuff that contains private info or irrelavent stuff?

Exactly.

2024-02-25 17:27 UTC, ReXulEc commented
Cool stuff. Keep it up!

2024-02-25 17:31 UTC, MrDiamondDog reviewed
I think this could do with a rebranding. Imo, "Delete From Me" doesn't make much sense. I would change it to "Hide Message".

2024-02-25 17:31 UTC, MrDiamondDog commented on src/plugins/deleteMessageFromMe/utils.ts
> +export const cl = classNameFactory("vc-delete-from-me-");
Just move this into the main file

2024-02-25 18:22 UTC, hanzydev commented
> I think this could do with a rebranding. Imo, "Delete From Me" doesn't make much sense. I would change it to "Hide Message".

I will do it.

2024-02-25 18:51 UTC, hanzydev commented
> I think this could do with a rebranding. Imo, "Delete From Me" doesn't make much sense. I would change it to "Hide Message".

You are absolutely right. I changed the plugin name to Hide Message.

2024-02-25 19:56 UTC, MrDiamondDog approved these changes

2024-02-27 22:45 UTC, ethan-davies commented
Haven't tried this plugin but I feel, if it's not already implemented, that there should be a button to show all hidden messages without having to reload your client. Maybe this could be a command or something that show when you right click a message.

2024-03-02 11:10 UTC, Ushie commented
Hi, I already [opened a PR](https://github.com/Vendicated/Vencord/pull/1568) for the same plugin a while back, should I close it?

2024-03-02 17:54 UTC, hanzydev commented
> Haven't tried this plugin but I feel, if it's not already implemented, that there should be a button to show all hidden messages without having to reload your client. Maybe this could be a command or something that show when you right click a message.

Implemented in my latest commit

![Discord_4mEKVFYwhp](https://github.com/Vendicated/Vencord/assets/77491112/44bd1313-d669-4fa2-b899-ebd1f670e92f)

2024-03-02 17:59 UTC, hanzydev commented
I also added support for using Message Logger with Hide Message plugin:

![Discord_5z0lDSHZHx](https://github.com/Vendicated/Vencord/assets/77491112/3444c440-d82c-4455-aa07-7a5f7f82ce20)

2024-03-10 17:18 UTC, hanzydev commented
It's been 2 weeks and no one is looking at PR. Why is that? @Vendicated

2024-03-10 17:32 UTC, nin0-dev commented
> It's been 2 weeks and no one is looking at PR. Why is that? @Vendicated

vee reviews PRs when they are motivated to, be patient

2024-03-13 11:49 UTC, lewisakura requested changes

2024-03-13 11:49 UTC, lewisakura commented on src/plugins/hideMessage/index.tsx
> +};
why is this done with CSS rather than a patch?

2024-03-28 20:50 UTC, hanzydev commented on src/plugins/hideMessage/index.tsx
> +};
> why is this done with CSS rather than a patch?

it is much easier to hide and show messages using CSS rather than JavaScript. I would have to delete the element from the DOM but putting it back would be hard and if I have to stick with JavaScript, I have to append a style to the message div that will hide the message but I will eventually use CSS if I do that.

2024-04-19 16:51 UTC, hanzydev commented
Currently there is no result and in 6 days, 2 months will have passed.

2024-04-19 16:59 UTC, Ushie commented
There is over a hundred PRs with some dating over a year ago, someone will eventually review your PR but until then it's best to just forget about this until you get that magic notification

2024-04-19 21:18 UTC, hanzydev commented
> There is over a hundred PRs with some dating over a year ago, someone will eventually review your PR but until then it's best to just forget about this until you get that magic notification, [my PR](https://github.com/Vendicated/Vencord/pull/1568) for the same function took place over 9 months ago

They're literally making fun of people 😂

2024-04-20 04:48 UTC, lewisakura commented
Your PR will not be reviewed if you keep asking about it. Please be patient, we have other things to do both for the project and in life.

2024-05-16 13:07 UTC, hanzydev commented
> Your PR will not be reviewed if you keep asking about it. Please be patient, we have other things to do both for the project and in life.

A month has passed and the pull request has still not been merged. You say we have things to do in our lives, but a pull request opened 4 hours ago is merged. There are people who have been waiting for a year. If you are not going to approve it, close this pull request and don't drag it out any longer.

2024-05-16 13:50 UTC, lewisakura commented
Okay, I don't normally do codereview for plugins anymore, but I'll give a response.

As it stands this plugin is not suited to be merged - creating tons of CSS for hiding messages is not effective and will eventually create a client slowdown. You don't need to manipulate the DOM to do this, you need to create a patch that filters out the hidden messages by ID when the channel view is rendered. I flagged this up previously but it seems like it was dismissed.

2024-05-17 16:04 UTC, Vendicated commented
yeah, as pointed out by lewi, this current implementation is not very good. using css for this is hacky and not sustainable. HideAttachments suffers from very much the same problem and honestly needs a rewrite, it's just that it's very old (made within the first two months of vencord existing), that's why it doesn't follow the quality standard as much as other plugins

in the current state this is not mergeable for that reason. here are a few better approaches i can think of:
- patch the message component to render null for hidden messages
- patch somewhere else to filter out undesired messages
- dispatch MESSAGE_DELETE events for the hidden messages

prs are looked at and merged whenever they are looked at and merged. this is a hobby project and there is a long backlog of contributions. this is not a very high priority change. if you are not okay with waiting, you probably shouldn't be contributing

2024-07-23 23:34 UTC, closed without merging