feat(plugin): DM Typing Indicator
Vendicated/Vencord pull request #221
Opened 2022-11-19 16:12 UTC by kem0x

2022-11-20 15:01 UTC, Vendicated requested changes
also use jsx please

2022-11-20 15:01 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +            },
use an arrow function please

2022-11-20 15:16 UTC, kem0x commented on src/plugins/typingIndicator.tsx
> +        removeUser(e.channelId, e.message.author.id);
yeah, it's not enough sadly, discord doesn't send typing stop sometimes, I'm not sure about the causer of this issue

2022-11-21 02:55 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +            transform="translate(4.5 11)"
what does this even do? Maybe add a comment

2022-11-21 03:02 UTC, Vendicated requested changes

2022-11-21 03:02 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +    const user = typingUsers.find(o => o.channelId === channelId && o.userId === userId);
```suggestion
    const hasUser = typingUsers.some(o => o.channelId === channelId && o.userId === userId);
```
But in any case, an array is not the right data structure here, use a Set which has add and remove operations

2022-11-21 03:02 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +    }
use array map instead of this for loop, also please add a unique key property (just make it the user-id) as there might be otherwise be ui bugs

2022-11-21 05:01 UTC, kem0x commented on src/plugins/typingIndicator.tsx
> +            transform="translate(4.5 11)"
it centers the icon in the button, it's a part of the svg itself you can paste that path in an svg editor and you will see what i mean

2022-11-21 07:25 UTC, KraXen72 commented
so good i love you

2022-11-21 14:47 UTC, Vendicated commented
> Sets are not a fit for this at all

How?

2022-11-27 17:55 UTC, KraXen72 commented
noooo please continue this @kem0x

2022-11-27 17:55 UTC, KraXen72 commented
if you don't want to i guess i could continue this, this is a good plugin

2022-11-28 00:18 UTC, Vendicated requested changes
I would have done a lot of these myself but you didn't give me permissions to do edits

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +        if (!user) return <></>;
```suggestion
        if (!user) return null;
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +
```suggestion
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +
```suggestion
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +
```suggestion
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +const UpdateElement = () => {
```suggestion
const updateElement = () => {
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +        const user = UserStore.getUser(typingUsers.values().next().value.userId);
```suggestion
        const user = UserStore.getUser(typingUsers[0].userId);
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +        if (user && user.userId) {
```suggestion
        if (user?.userId) {
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +            if (!member) continue;
```suggestion
            if (member) toolTipString += `${member.username}, `;;
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +    toolTipString += "are typing...";
```suggestion
    toolTipString = toolTipString.slice(0, -2) + "are typing...";
``` to remove the last comma

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +    renderIndicator: () => <Element />,
Please wrap this in an errorboundary to prevent crashes

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +
```suggestion
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +        if (!channel?.isPrivate()) return;
```suggestion
        if (channel?.isPrivate()) addUser(e.channelId, e.userId);
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +
```suggestion
```

2022-11-28 00:18 UTC, Vendicated commented on src/plugins/typingIndicator.tsx
> +        if (!channel?.isPrivate()) return;
```suggestion
        if (channel?.isPrivate()) removeUser(e.channelId, e.userId);
```

2022-11-28 10:48 UTC, kem0x commented
how about you commit all those suggestions instead of me copying them one by one and pushing them 💀

2022-11-28 10:51 UTC, Vendicated commented
> I would have done a lot of these myself but you didn't give me permissions to do edits

?

You can also just press the commit suggestion button you know

2023-01-13 22:39 UTC, Vendicated commented
Feel free to reopen with the requested changes fixed / write permissions enabled

2023-01-13 22:39 UTC, closed without merging