feat(plugin): CopyEmojiAsFormattedString
Vendicated/Vencord pull request #2251
Opened 2024-03-11 18:46 UTC by happyendermangit

- Add's a button to copy an emoji as a formatted string: 
Example formatted string: `<:blessing:1216442476148293722>`

![image](https://github.com/Vendicated/Vencord/assets/66224387/162318d7-eef4-411c-9c26-4e5dc74fafb7)
![image](https://github.com/Vendicated/Vencord/assets/66224387/2dbfa083-2f8b-4388-b48f-76bc537fdb53)

2024-03-11 21:57 UTC, happyendermangit commented
any review?

2024-03-13 12:54 UTC, happyendermangit commented
....

2024-03-13 12:55 UTC, nin0-dev commented
prs are reviewed when vee has the time to do so/wants to do so. be patient

2024-03-13 13:00 UTC, Vendicated commented
how is this useful? why not just send the emote somewhere and copy it? you only very rarely need to copy the code

also please be patient and don't spam. literally only 2 days passed and you already asked twice

2024-03-13 13:20 UTC, Grafaffel commented
> how is this useful? why not just send the emote somewhere and copy it? you only very rarely need to copy the code
> 
> also please be patient and don't spam. literally only 2 days passed and you already asked twice

I need the emoji strings very often when developing a Bot

2024-03-13 17:57 UTC, happyendermangit commented
> how is this useful? why not just send the emote somewhere and copy it? you only very rarely need to copy the code
> 
> also please be patient and don't spam. literally only 2 days passed and you already asked twice

Yea, and for nitro users it's a pain, this is really useful when developing a bot

2024-04-25 17:05 UTC, Vendicated requested changes

2024-04-25 17:05 UTC, Vendicated commented on src/plugins/CopyEmojiAsFormattedString/CopyEmojiAsFormattedString.tsx
> +        addContextMenuPatch("expression-picker", this.expressionPickerPatch);
please use the contextMenu property of your plugin to register patches instead. you can find many usage examples by checking othjer plugins

2024-04-25 17:05 UTC, Vendicated commented on src/plugins/CopyEmojiAsFormattedString/CopyEmojiAsFormattedString.tsx
> +        if (!children.find(element=>element.props.id === "copy-formatted-string")) {
no need for this

2024-04-25 17:05 UTC, Vendicated commented on src/plugins/CopyEmojiAsFormattedString/CopyEmojiAsFormattedString.tsx
> +    description: "Add's button to copy emoji as formatted string!",
```suggestion
    description: "Adds button to copy emoji as formatted string!",
```

2024-04-25 17:05 UTC, Vendicated commented on src/plugins/CopyEmojiAsFormattedString/CopyEmojiAsFormattedString.tsx
> +            props.alreadyPatched = true;
no need for this

2024-04-25 17:05 UTC, Vendicated commented on src/plugins/CopyEmojiAsFormattedString/CopyEmojiAsFormattedString.tsx
> +            let isAnimated = firstChild && new URL(firstChild.src).pathname.endsWith(".gif");;
variables should use const if they don't need to be reassigned

2024-04-25 17:05 UTC, Vendicated commented on src/plugins/CopyEmojiAsFormattedString/CopyEmojiAsFormattedString.tsx
> +                        const formatted_emoji_string = `${isAnimated ? "<a:" : "<:"}${data.name}:${data.id}>`;
variable names should be camelCase

2024-05-11 22:06 UTC, happyendermangit commented on src/plugins/CopyEmojiAsFormattedString/CopyEmojiAsFormattedString.tsx
> +            props.alreadyPatched = true;
when i didnt do this, it created Infinty instaces of the button without stopping

2024-05-11 22:06 UTC, happyendermangit commented on src/plugins/CopyEmojiAsFormattedString/CopyEmojiAsFormattedString.tsx
> +            let isAnimated = firstChild && new URL(firstChild.src).pathname.endsWith(".gif");;
Sure

2024-05-17 16:39 UTC, closed without merging