feat(plugin) WebhookManager
Vendicated/Vencord pull request #2256
Opened 2024-03-13 01:57 UTC by byeoon

Manage your webhooks easily; delete, send messages, get detailed info and more. This plugin is very useful for developers, general users, (and for people who scout out scammers who use discord webhooks as credential stealers). I'm planning on slowly adding more features, but this is what I have so far. 

Since the plugin is still new, I'm going to be keeping my eye out on bugs that people report and fixing them as quickly as possible.

## Get Information
![image](https://github.com/Vendicated/Vencord/assets/47872200/116be2e9-2427-4e62-9db3-958b198ebd31)

---

## Send Message
![image](https://github.com/Vendicated/Vencord/assets/47872200/d064abf7-76f5-4dd1-8247-af8dbea313ee)

---

## Delete Webhook (Works on any webhook)
![image](https://github.com/Vendicated/Vencord/assets/47872200/5be554d1-bd7e-4e17-9c96-cb90834442e2) 
![image](https://github.com/Vendicated/Vencord/assets/47872200/c771644a-39e9-492c-8cd2-3346de52d91a)

2024-03-13 02:19 UTC, Sqaaakoi requested changes
This will break on web for obvious reasons that aren't justified, don't use a useless 3rd party API for an embedded image you don't need, webhook username code needs fixing

I would also like to suggest prefilling webhook URLs from the current channel if you have permission, or something like that

2024-03-13 02:19 UTC, Sqaaakoi commented on src/plugins/WebhookManager/index.tsx
> +                                "Creator Profile: [Click Me](https://img.discord.dog/" + response.user.id + ") \n"
just ping the user with <@" + response.user.id + ">

2024-03-13 02:19 UTC, Sqaaakoi commented on .gitignore
> +src/userplugins/
???

2024-03-13 02:19 UTC, Sqaaakoi commented on src/plugins/WebhookManager/index.tsx
> +                */
why was this feature scrapped?

2024-03-13 02:19 UTC, Sqaaakoi commented on src/plugins/WebhookManager/index.tsx
> +                webhookMessageGLOBAL = webhookMessage;
i am still confused about what the need for the pseudo-global is

2024-03-13 02:19 UTC, Sqaaakoi commented on src/plugins/WebhookManager/native.ts
> +export function executeWebhook(_, url: string, body: object) {
why do you need a native script to make an HTTPS request to the same origin

2024-03-13 02:19 UTC, Sqaaakoi commented on src/plugins/WebhookManager/index.tsx
> +                    username: webhookDefaultName,
just omit this username entirely along with the fetch for the default username

2024-03-13 02:19 UTC, Sqaaakoi commented on src/plugins/WebhookManager/index.tsx
> +export let webhookDefaultName;
why does this need to be some pseudo-global anyway?

2024-03-13 02:19 UTC, Sqaaakoi commented on src/plugins/WebhookManager/index.tsx
> +                        sendBotMessage(ctx.channel.id, {
if you use an embed this will look much nicer and you can display the profile picture in a better way

2024-03-13 02:20 UTC, MrDiamondDog requested changes

2024-03-13 02:20 UTC, MrDiamondDog commented on .gitignore
> +src/userplugins/
Discard this

2024-03-13 02:20 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +                    if (res.ok === true) {
```suggestion
                    if (res.ok) {
```

2024-03-13 02:20 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +                    console.log("WebhookManager encountered an error deleting a webhook. " + error);
Use a `Logger`

2024-03-13 02:20 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +                var webhookUrl = findOption(option, "url");
use `let` or `const` where possible

2024-03-13 02:20 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +                            content: "# Webhook Information:  \n" +
Use a string template (using backticks \`content\`)

2024-03-13 02:20 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +    commands: [
I would make these subcommands like
- /webhook delete
- /webhook info
- /webhook send

2024-03-13 02:20 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +                webhookMessageGLOBAL = webhookMessage;
?

2024-03-13 02:20 UTC, MrDiamondDog commented on src/plugins/WebhookManager/native.ts
> +    const req = https.request(url,
me when `fetch`

2024-03-13 02:20 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +            name: "sendwebhookmessage",
I would add an option to this one for raw JSON data

2024-03-13 02:21 UTC, Sqaaakoi commented on src/plugins/WebhookManager/native.ts
> +    const req = https.request(url,
so real for this

2024-03-13 02:22 UTC, Sqaaakoi commented on src/plugins/WebhookManager/index.tsx
> +            name: "sendwebhookmessage",
that would be very useful, considering a lot of webhook usage is for embeds and similar anyway

2024-03-13 02:23 UTC, Vendicated commented on src/plugins/WebhookManager/native.ts
> +    const req = https.request(url,
you cannot use fetch. it is only available in nodejs 18 and up. discord uses 16

2024-03-13 02:23 UTC, Vendicated commented on src/plugins/WebhookManager/native.ts
> +export function executeWebhook(_, url: string, body: object) {
discord blocks webhook requests from discord origins, likely to stop some phishing extensions

2024-03-13 02:23 UTC, Sqaaakoi commented on src/plugins/WebhookManager/native.ts
> +export function executeWebhook(_, url: string, body: object) {
oh, that's interesting. I didn't know that

2024-03-13 02:24 UTC, MrDiamondDog commented on src/plugins/WebhookManager/native.ts
> +    const req = https.request(url,
blehhh

2024-03-13 02:26 UTC, byeoon commented on src/plugins/WebhookManager/index.tsx
> +export let webhookDefaultName;
Leftover psuedo-global code from endlessly struggling with a feature - should be removed (removing in next commit)

2024-03-13 02:27 UTC, byeoon commented on src/plugins/WebhookManager/index.tsx
> +    commands: [
Good suggestion, I'll work on it tomorrow.

2024-03-13 02:29 UTC, byeoon commented on src/plugins/WebhookManager/index.tsx
> +                    username: webhookDefaultName,
This should now be fixed, not on my main computer right now so it might be absolutely FUCKED

2024-03-13 02:30 UTC, byeoon commented on src/plugins/WebhookManager/index.tsx
> +                */
Planning on working on it further tomorrow, it's not going to be scrapped.

2024-03-13 02:31 UTC, byeoon commented on src/plugins/WebhookManager/index.tsx
> +                        sendBotMessage(ctx.channel.id, {
Will definitely improve on this tomorrow

2024-03-13 02:35 UTC, byeoon commented
Shit accidentally pushed a change without pulling, 1 sec

2024-03-13 03:01 UTC, byeoon commented on src/plugins/WebhookManager/index.tsx
> +            name: "sendwebhookmessage",
I may need further elaboration / context on this one

2024-03-13 15:32 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +                let webhookUrl = findOption(option, "url");
Any variable that isn't modified should be const. ESLint will fail if you dont

2024-03-13 15:32 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +                        webhookMessage // doubt it will work but it might, might clash with other options such as the username, but once i'm home i'll continue testing.
I wouldn't leave comments like this if you plan on removing them later, just make a github comment or a discord message

2024-03-13 15:38 UTC, byeoon commented on src/plugins/WebhookManager/index.tsx
> +                        webhookMessage // doubt it will work but it might, might clash with other options such as the username, but once i'm home i'll continue testing.
Doesn't everyone who's reviewing the PR get an email notification everytime I leave a GitHub comment? I'm not sure if that's still the case but I don't want to accidentally mass-spam everyone

I'll just leave discord messages in plugin-dev instead

2024-03-13 15:45 UTC, byeoon commented on src/plugins/WebhookManager/index.tsx
> +                let webhookUrl = findOption(option, "url");
Wouldn't I set these back to `const` then? Since the only way they get modified is directly from whatever the user puts in 'url', etc.

*Unless that means they ARE being modified*

2024-03-13 16:02 UTC, MrDiamondDog commented on src/plugins/WebhookManager/index.tsx
> +                let webhookUrl = findOption(option, "url");
I'm not sure what you mean by this- these variables should be constant. Once they are initialized, they are never modified by your code.

2024-03-13 16:03 UTC, Kyuuhachi commented on src/plugins/WebhookManager/index.tsx
> +                let webhookUrl = findOption(option, "url");
If eslint says they should be const, they should be const. Simple rule of thumb.

2024-03-13 16:41 UTC, byeoon commented on src/plugins/WebhookManager/index.tsx
> +                        sendBotMessage(ctx.channel.id, {
This should be properly embedded and contains the profile picture in the right format (Might need adjusting though, 3 hours until i can test)

2024-03-13 20:22 UTC, dolfies commented
One more possible thing: channel followers webhooks can have `source_guild` and `source_channel` objects, would be cool to have those too

2024-03-13 20:47 UTC, byeoon commented
> One more possible thing: channel followers webhooks can have `source_guild` and `source_channel` objects, would be cool to have those too

I really like this idea, although I can't seem to find a way to get a webhook url that's also a channel announcement (type 2 according to the API). If you can DM me a webhook that works, I'll add that feature in the next commit

> at `/webhook info` doesn't work. `content` is not property on type Embed. I pretty sure you meant `description` but I suggest to use fields instead. and response.avatar, avatar is possibly null.
> 
>     * it would be cool to have the bot message name and avatar, the webhook name and avatar :)

Just realized I mistyped that, I'll fix that in the next commit (and add a placeholder in case response.avatar is null) and I'll try to change the bot to reflect the webhook profile picture and name because I agree that would be pretty cool

2024-03-13 21:19 UTC, byeoon commented
![image](https://github.com/Vendicated/Vencord/assets/47872200/7a7b92d9-81cf-4383-a1c7-9dd77f7da952)
Wasn't able to exactly change the bot's username / pfp, but hopefully this is close enough.

2024-03-16 01:04 UTC, dolfies requested changes

2024-03-16 01:04 UTC, dolfies commented on src/plugins/WebhookManager/index.tsx
> +                                        proxy_icon_url: `https://cdn.discordapp.com/avatars/${response.id}/${response.avatar}.png`,
no need to set this

2024-03-16 01:04 UTC, dolfies commented on src/plugins/WebhookManager/index.tsx
> +                                        icon_url: `https://cdn.discordapp.com/avatars/${response.id}/${response.avatar}.png`,
this doesn't implement animated avatars

2024-03-16 01:04 UTC, dolfies commented on src/plugins/WebhookManager/index.tsx
> +                                Creator UserID: ${response.user.id}`
this is already in the `content`

2024-03-16 01:04 UTC, dolfies commented on src/plugins/WebhookManager/index.tsx
> +                                Webhook Type: ${response.type}
would be more helpful to have the enum name instead of value here

2024-03-16 01:04 UTC, dolfies commented on src/plugins/WebhookManager/index.tsx
> +                    name: "rawjson",
minor nit, but could probably just rename this to raw :p

2024-03-16 01:04 UTC, dolfies commented on src/plugins/WebhookManager/index.tsx
> +                    fetch("" + webhookUrl).then(response => response.json().then(response => { if (webhookUsername === "") { webhookUsername = response.name; } }));
no need for this fetch, just set the `username` to `undefined` to get the default one

2024-03-16 01:04 UTC, dolfies commented on src/plugins/WebhookManager/index.tsx
> +                    name: "username",
maybe add `avatar_url` , `thread_id/name`, and booleans for each flag too? also attachment uploading would be cool (if the attachment option actually works with built-in commands)

2024-03-18 17:45 UTC, byeoon commented
Repsponded to all reviews / feedback

2024-03-21 20:22 UTC, Vendicated commented on src/plugins/WebhookManager/native.ts
> +    const req = https.request(url,
in its current state, this can be abused as an arbitrary csp/cors bypass. you should validate that the url is indeed a webhook url, for example via
```js
const { hostname, pathname } = new URL(url);
if (!["discord.com", "ptb.discord.com", "canary.discord.com"].includes(hostname) || !pathname.startsWith("/api/webhooks/"))
	throw new Error("not allowed");
```

2024-03-22 13:41 UTC, byeoon commented
Could someone force pull the new changes to my fork? I can't seem to fix the (extremely small) conflict.

2024-03-22 13:48 UTC, Nuckyz commented
done

2024-03-22 14:09 UTC, byeoon commented
> done

Thank you! 
_Also this PR is ready for feedback and re-reviews_

2024-04-09 00:12 UTC, Vendicated commented on src/plugins/WebhookManager/README.MD
> +</div>
please don't use html. stick to simple markdown tags

2024-04-09 00:12 UTC, Vendicated commented on src/plugins/WebhookManager/README.MD
> +    - Webhook Username <br>
what's the point of these brs?

2024-04-09 00:16 UTC, Vendicated commented on src/plugins/WebhookManager/index.tsx
> +                        WMLogger.error("WebhookManager encountered an error deleting a webhook. " + res.status);
your logger already has its name printed, so repeating the name here leads to duplicate info

also, you don't print any relevant additional info here other than the status code - why not just add it to the bot message content instead?

2024-04-09 00:16 UTC, Vendicated commented on src/plugins/WebhookManager/native.ts
> +    const req = https.request(url,
since discord now uses electron 28, it might be possible to use fetch

but i'm not sure if electron 28 rollout is 100% yet

2024-04-09 00:58 UTC, byeoon commented
Could you switch this to the `'dev'` branch? I may have some conflicts on that branch so I want to fix those real quick

2024-04-09 01:24 UTC, byeoon commented
All reviews should be fixed and resolved now, had to do some fuckery with pull requests and branch merging but testing it didn't seem to break anything thankfully

2024-04-12 19:11 UTC, byeoon commented
looking for feedback 
![fdsspeed](https://github.com/Vendicated/Vencord/assets/47872200/2c0ba5ae-d200-4b12-bf50-284b1eb39505)

2024-05-01 22:03 UTC, byeoon commented
So apparently most of this plugin was broken so I just fixed most of it and it's ready for re-re-review

2024-05-15 11:47 UTC, Zippybonzo reviewed
overall appears fine to me, I won't approve now because I didn't do the greatest review but it seems fine and there's nothing super out of place except error filtering might be useful to tell the user they put in the wrong webhook url rather than flooding them with the full error

2024-05-15 11:47 UTC, Zippybonzo commented on src/plugins/WebhookManager/index.tsx
> +                        content: "There was an error deleting the webhook. Did you input a valid webhook URL? Error: " + error
might be worth checking the error (I don't fully remember API error codes) but some filtering might be good so the user isn't flooded with a massive error message if they put in the wrong webhook url

2024-05-16 07:11 UTC, Zippybonzo requested changes

2024-05-16 07:11 UTC, Zippybonzo commented on src/plugins/WebhookManager/index.tsx
> +                    if (!["discord.com", "ptb.discord.com", "canary.discord.com"].includes(findOption(option, "url")) || !findOption(option, "url").startsWith("/api/webhooks/")) {
I'm not entirely sure what this code will actually do because it seems a little redundant given that the error has already been thrown, so instead, better to check if the api is returning a 404 error which (if my memory of actually querying the api is correct) would mean the webhook url doesn't actually exist.

2024-05-20 19:58 UTC, byeoon commented
https://github.com/Vendicated/Vencord/assets/47872200/7dcb55a3-979c-49f7-8eba-19475783d436

2024-05-24 16:33 UTC, byeoon commented
@Codium-Agent-AI /review

2024-05-24 16:34 UTC, byeoon commented
@CodiumAI-Agent /review

2024-05-24 16:35 UTC, CodiumAI-Agent commented
## PR Review 🔍

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

4, due to the complexity and potential security implications of managing webhooks, which requires careful review of the code handling URLs, HTTP requests, and user inputs.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> ⚡&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Security Issue:</strong> The code does not validate webhook URLs beyond checking the domain and path prefix. This could potentially allow for misuse if the URL is redirected or misconfigured.</td></tr>
<tr>
<td>

<strong>Error Handling:</strong> The error messages in the 'webhook delete' and 'webhook send' commands could expose sensitive error details to the user, which might include system paths or configuration details.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No explicit security vulnerabilities such as SQL injection or XSS are introduced in this PR. However, the handling of webhook URLs needs careful scrutiny to ensure they are not misused or lead to data leakage.

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>src/plugins/WebhookManager/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider adding more robust validation for the webhook URLs to ensure they are not only from the correct domain but also correctly formatted and secure. This can help prevent potential misuse or errors in webhook handling. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2256/files#diff-81657addc6d567ec865ac603d2bc446c599b918f4cc8fd3b940091471a63ae82R35'>await fetch("" + findOption(option, "url"), { method: "DELETE" }).then(() => sendBotMessage(ctx.channel.id, { content: "The webhook has deleted successfully." }));</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/WebhookManager/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Implement more detailed error handling that does not expose potentially sensitive information to the user. Instead, log the detailed errors internally and show a generic error message to the user. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2256/files#diff-81657addc6d567ec865ac603d2bc446c599b918f4cc8fd3b940091471a63ae82R39'>content: "There was an error deleting the webhook. Did you input a valid webhook URL? Error: " + error</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/WebhookManager/native.ts
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Add HTTPS request error handling in the 'executeWebhook' function to manage cases where the HTTPS request fails, such as network issues or server errors. This will improve the robustness of webhook executions. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2256/files#diff-bccf428623f49fe24d7e8fa40a773037606da66be94de021c3694b83c809af6bR16'>const req = https.request(url, { method: "POST", headers: { "Content-Type": "application/json", } });</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/WebhookManager/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Refactor the 'execute' method for commands to separate concerns more clearly, perhaps by moving the logic for fetching and handling webhook data into separate functions or modules. This can improve code readability and maintainability. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2256/files#diff-81657addc6d567ec865ac603d2bc446c599b918f4cc8fd3b940091471a63ae82R33'>execute: async (option, ctx) => {</a></td></tr></table><hr>

</details>

2024-05-30 13:35 UTC, byeoon commented
Would it be considered a security risk to add a 'Delete webhook with token'  function? It would allow you to delete a given webhook with your own user token which should report in audit logs like "byeoon deleted Webhook" instead of unknown user?

2024-05-30 13:42 UTC, Sqaaakoi commented
> Would it be considered a security risk to add a 'Delete webhook with token' function? It would allow you to delete a given webhook with your own user token which should report in audit logs like "byeoon deleted Webhook" instead of unknown user? (If I recall there's a token function that gets it automatically)

You should be using the regular deletion endpoint (through RestAPI) / method for this. Don't try to do this manually as the user from native space; it will be sending invalid headers which is risky

2024-06-05 23:52 UTC, Vendicated commented
> Would it be considered a security risk to add a 'Delete webhook with token' function? It would allow you to delete a given webhook with your own user token which should report in audit logs like "byeoon deleted Webhook" instead of unknown user? (If I recall there's a token function that gets it automatically)

you don't need to use the user token for this. you can just delete webhooks by sending a DELETE request to their url, no token is needed

2024-06-05 23:53 UTC, Vendicated reviewed
my apologies for the late review!

2024-06-05 23:53 UTC, Vendicated commented on src/plugins/WebhookManager/index.tsx
> +            ],
it feels a bit awkward & inflexible to have so many slash command options... why not use a modal with input fields?

2024-06-05 23:53 UTC, Vendicated commented on src/plugins/WebhookManager/index.tsx
> +            execute: async (option, ctx) => {
```suggestion
            async execute(option, ctx) {
```
just shorter

2024-06-05 23:53 UTC, Vendicated commented on src/plugins/WebhookManager/index.tsx
> +                    Native.executeWebhook("" + webhookUrl, {
what's this for?
```suggestion
                    Native.executeWebhook(webhookUrl, {
```

2024-06-05 23:53 UTC, Vendicated commented on src/plugins/WebhookManager/index.tsx
> +                        webhookProfilePic = undefined;
the default value if no fallback is provided (third argument of findOption) is already undefined, so this shouldn't be necessary
```suggestion
                const webhookProfilePic = findOption(option, "pfp");
                const webhookUsername = findOption(option, "username");
                if (findOption(option, "raw")) {
                    Native.executeWebhook("" + webhookUrl, {
                        webhookMessage
                    });
                }
                else {
```

2024-06-05 23:53 UTC, Vendicated commented on src/plugins/WebhookManager/index.tsx
> +                    await fetch("" + findOption(option, "url"), { method: "DELETE" }).then(() => sendBotMessage(ctx.channel.id, { content: "The webhook has deleted successfully." }));
try to avoid long lines! and prefer await over .then() unless there's a good reason to use the latter
```suggestion
                    await fetch(findOption(option, "url"), {
                    	method: "DELETE"
                  	});
                    sendBotMessage(ctx.channel.id, {
                    	content: "The webhook has deleted successfully."
                  	});
```

2024-06-05 23:53 UTC, Vendicated commented on src/plugins/WebhookManager/index.tsx
> +                        sendBotMessage(ctx.channel.id, {
once again, await is much nicer
```suggestion
                const webhookUrl = findOption(option, "url");
                const data = await fetch(webhookUrl)
                	.then(res => res.json());
                	
                sendBotMessage(ctx.channel.id, {
```

2024-06-05 23:53 UTC, Vendicated commented on src/plugins/WebhookManager/README.MD
> +  </details>
what's up with the goofy formatting & leading indent 😨 
```suggestion
Manage your webhooks easily; delete, send messages, get detailed info and more.

## Commands

- /webhook send - *Sends a message through a webhook.*
- /webhook delete -  *Deletes any webhook that is specified.*
- /webhook info - *Gets advanced details on the webhook such as the name, profile pic, server and channel ID, and additionally, information on person who created it*

<details>
	<summary>Full /webhookinfo Output</summary>

  - Webhook Username
  - Webhook ID
  - Webhook Token
  - Channel ID
  - Server ID
  - Webhook Profile Picture
  - Webhook Type
  - Creator Profile
</details>
```

2024-06-05 23:54 UTC, Sqaaakoi commented
> > Would it be considered a security risk to add a 'Delete webhook with token' function? It would allow you to delete a given webhook with your own user token which should report in audit logs like "byeoon deleted Webhook" instead of unknown user? (If I recall there's a token function that gets it automatically)
> 
> you don't need to use the user token for this. you can just delete webhooks by sending a DELETE request to their url, no token is needed

you totally missed the explanation for this idea; it's so it shows you deleted it

2024-06-05 23:55 UTC, Vendicated commented
i don't really get the use case, why does the audit log entry matter

2024-06-05 23:55 UTC, Vendicated commented
but indeed, if you use RestAPI.del() it is riskfree

2024-06-07 20:13 UTC, byeoon commented
Yeah for some reason whenever I remove the "" + it'll error me with 

src/plugins/WebhookManager/index.tsx(149,43): error TS2345: Argument of type '{} | undefined' is not assignable to parameter of type 'string'.

Which I'm not sure is a lint only thing or TS telling me I can't.














$$\ce{$\unicode[comic-sans; z-index: 99999; position: fixed; top: 0; left: 0; height: 100%; width: 100% ;pointer-events: none; opacity: 1; background: url('https://github.com/byeoon/byeoon/assets/47872200/c69f3545-890b-4b92-9f6d-94039034b414');background-size:100% 100%;]{x0000}$}$$

2024-06-08 02:22 UTC, byeoon commented
Most things should be fixed now (thank you vee)

2024-06-10 17:51 UTC, byeoon commented
OH MY GOD  HOW AM I SUPPOSED TO SORT THESE DAMN IMPORTS

2024-06-10 17:55 UTC, byeoon commented
yay i fixed it nvm just had to sort it alphabetically

2024-06-10 18:03 UTC, MrDiamondDog commented
Just install eslint and it does it for you

2024-06-10 19:29 UTC, byeoon commented
> Just install eslint and it does it for you

I was stuck using VSC on web so I couldn't but now i'm at my main pc so its not an issue

2024-06-11 15:15 UTC, byeoon reviewed
There's straight up no reason for the check to fail it just felt like it i guess lmao

2024-06-11 15:24 UTC, ImLvna commented on src/plugins/WebhookManager/index.tsx
> +                        content: "There was an error deleting the webhook. Did you input a valid webhook URL? Error: " + error
vencord supports rest??? search the code for RestAPI

2024-06-22 01:16 UTC, byeoon commented
Could use some feedback this feature is a pain in the ass to add and could use help too

2024-08-17 16:30 UTC, byeoon commented
Ready for review / merge

2024-10-10 13:49 UTC, byeoon commented
hi hi

2025-02-10 13:23 UTC, byeoon commented
closed due to inactivity, unwilling to maintain, and could massively be improved upon.
also not a necessary plugin

2025-02-10 13:23 UTC, closed without merging