Fix PinDMs
Vendicated/Vencord pull request #2281
Opened 2024-03-22 14:07 UTC by Syncxv

When you add all your dms to a category it causes everything to disappear. This happens because of this:
https://github.com/Vendicated/Vencord/blob/ca18b6e0446b6f1858a82de47489bb01f925ce25/src/plugins/pinDms/index.tsx#L203

this line of code assumes an empty `channelIds` means dms havent been fetched from discord, but it doenst account for the case where dms have been fetched and all the private dms have been added to one or more categories.

2024-03-22 14:24 UTC, Syncxv commented
done

2024-03-22 14:45 UTC, Nuckyz requested changes

2024-03-22 14:45 UTC, Nuckyz commented on src/plugins/pinDms/index.tsx
>                  // Init
```suggestion
```

2024-03-22 15:56 UTC, Vendicated commented
this still seems to rely on length. what happens if you use this on an account with 0 dms?

2024-03-23 04:18 UTC, Syncxv commented
i dont think we need to check if its initialized.
https://github.com/Vendicated/Vencord/blob/ca18b6e0446b6f1858a82de47489bb01f925ce25/src/plugins/pinDms/index.tsx#L156-L160

https://github.com/Vendicated/Vencord/blob/ca18b6e0446b6f1858a82de47489bb01f925ce25/src/plugins/pinDms/data.ts#L35-L40

the init function forceUpdates the component on connection open (when channels have been fetched), meaning that check is kinda useless.

2024-03-28 20:40 UTC, merged

2024-03-28 20:40 UTC, Vendicated commented
thanks!