Blur removed spoiled images
Vendicated/Vencord pull request #2286
Opened 2024-03-23 20:58 UTC by k26pl

Fixes #1815

2024-03-23 23:27 UTC, waresnew requested changes

2024-03-23 23:27 UTC, waresnew commented on src/plugins/messageLogger/messageLogger.css
> +.hiddenSpoiler__57186 .hiddenAttachment_dfecc7 .messagelogger-deleted-attachment {
Try not to hardcode entire class names because the part after the `_` might change when Discord updates (maybe do something like `[class^="hiddenSpoiler_"]` instead)

2024-03-23 23:36 UTC, k26pl commented
i have removed hiddenSpoiler as there are to different classes with same name.  hiddenAttachment appears to be on all images too, so this should still work.

2024-04-09 02:10 UTC, Vendicated commented on src/plugins/messageLogger/messageLogger.css
> +.messagelogger-deleted-attachment [class^="hiddenAttachment_"] {
for me these two classes are on the same element, so this doesn't actually work
![image](https://github.com/Vendicated/Vencord/assets/45497981/252d944e-2334-40af-8a29-18596665fa50)

what works for me is changing line 11:
```diff
- .messagelogger-deleted-attachment,
+ .messagelogger-deleted-attachment:not([class*="hiddenAttachment_"]),
```

2024-04-09 19:12 UTC, k26pl commented on src/plugins/messageLogger/messageLogger.css
> +.messagelogger-deleted-attachment [class^="hiddenAttachment_"] {
Thanks! It is a better solution

2024-04-10 21:24 UTC, k26pl commented
Also we should disable buttons on removed polls, but that probably should be in separate issue

2024-05-10 16:29 UTC, closed without merging