feat(plugin): UnlockedAvatarZoom
Vendicated/Vencord pull request #2287
Opened 2024-03-24 18:53 UTC by nakoyasha

Unlocks and allows you to use custom multipliers for the zoom slider in the Edit Avatar modal as the default 2 is "barely enough"

2024-03-24 18:56 UTC, MrDiamondDog requested changes

2024-03-24 18:56 UTC, MrDiamondDog commented on src/plugins/unlockedAvatarZoom/index.ts
> +            find: "\"aria-label\":I.default.Messages.FORM_LABEL_AVATAR_SIZE",
Don't have obfuscated variables names in your finds. Otherwise you will need to change this every time discord updates.

`.Messages.FORM_LABEL_AVATAR_SIZE` would likely work.

2024-03-24 19:09 UTC, nakoyasha commented on src/plugins/unlockedAvatarZoom/index.ts
> +            find: "\"aria-label\":I.default.Messages.FORM_LABEL_AVATAR_SIZE",
Another component seems to use .Messages_FORM_LABEL_AVATAR_SIZE, so using that causes the patch to not have any effect.

I could probably use either `keyboardStep` or `asValueChanges` instead, as neither seem to be present elsewhere

2024-03-24 19:32 UTC, MrDiamondDog commented on src/plugins/unlockedAvatarZoom/index.ts
> +            find: "\"aria-label\":I.default.Messages.FORM_LABEL_AVATAR_SIZE",
It only matters for variables name `I`, `w`, etc. These variables are obfuscated and change with discord updates.

2024-03-27 20:49 UTC, Vendicated commented on src/plugins/unlockedAvatarZoom/index.ts
> +                match: /(maxValue:(\w))/,
```suggestion
                match: /maxValue:\d/,
```

2024-03-27 20:49 UTC, Vendicated commented on src/plugins/unlockedAvatarZoom/index.ts
> +        default: 2,
the default should definitely not be 2. otherwise, people will enable the plugin and wonder why it does nothing at all

is there any point adding a limit? why not just always have it as 16?

2024-03-27 20:51 UTC, Vendicated commented
please add a README.md file!

2024-03-27 21:20 UTC, nakoyasha commented on src/plugins/unlockedAvatarZoom/index.ts
> +        default: 2,
it was limited since I thought a slider would be way nicer, and it didn't make sense to use higher values anyway (as it got too unstable to be actually usable)

replaced it with a number value anyway - also increased the default to 4

2024-03-27 21:23 UTC, Vendicated commented on src/plugins/unlockedAvatarZoom/index.ts
> +        default: 2,
you can keep it as a slider, that's fine, especially if you say it becomes too unstable

just the default should be higher, at least 4

2024-03-27 21:29 UTC, nakoyasha commented on src/plugins/unlockedAvatarZoom/index.ts
> +        default: 2,
yea on second thoughts it wasnt really the best idea to turn it into a number - i feel like people will try to deliberately break it (by using really big numbers or negative numbers) just to complain :/

2024-04-09 01:56 UTC, merged

2024-04-09 01:56 UTC, Vendicated commented
thank you! :3