[Update Plugin] Update ReadAllButton
Vendicated/Vencord pull request #2291
Opened 2024-03-25 13:19 UTC by KrstlSkll69

This should update the "read all button", so its not so ugly and bland. Should be able to work with themes (especially the client theme plugin)

2024-03-25 13:21 UTC, KrstlSkll69 commented
updated "Constant.ts" twice to fix typo i made

2024-03-25 13:22 UTC, Vendicated commented on src/plugins/readAllNotificationsButton/style.css
> +[class^=scroller__] > button:first-of-type {
instead of using this insane selector, give the button a class and select that instead :3

2024-03-25 16:03 UTC, KrstlSkll69 commented
@Vendicated ok changed (I think, idk ive never used github before so im trying)

2024-03-25 16:04 UTC, MrDiamondDog requested changes

2024-03-25 16:04 UTC, MrDiamondDog commented on src/utils/constants.ts
> +
me when syntax error

2024-03-25 16:04 UTC, MrDiamondDog commented on src/plugins/readAllNotificationsButton/style.css
> +  background-color: var(--brand-experiment) !important;
make sure styling is consistent (tab width is different in this block vs. the one above)

2024-03-25 16:11 UTC, KrstlSkll69 commented on src/utils/constants.ts
> +
OMFG ITS THAT GODDAMN TYPO I THOUGHT I FIXXED THAT THING BEFORE

2024-03-25 16:16 UTC, MrDiamondDog requested changes

2024-03-25 16:16 UTC, MrDiamondDog commented on src/utils/constants.ts
> +
```suggestion
    }
```

2024-03-25 16:17 UTC, KrstlSkll69 commented on src/utils/constants.ts
> +
fuck, this thing keeps making typos just to hurt me on purpose

2024-03-25 16:36 UTC, KrstlSkll69 commented
misclicked didn't mean to close

2024-03-25 19:48 UTC, KrstlSkll69 commented
@Vendicated bump

2024-03-26 20:25 UTC, KrstlSkll69 commented
@Vendicated bump

2024-03-26 20:26 UTC, Vendicated commented
![cat-patience-cat](https://github.com/Vendicated/Vencord/assets/45497981/8f23904b-09fa-4ca0-b6f7-2a9c433e5fa3)

2024-03-26 20:27 UTC, Sqaaakoi commented
i was half way through writing a comment, but yes anyway

please get some patience. vee has a life outside of vencord

2024-03-27 18:04 UTC, Vendicated commented
@CodiumAI-Agent /review

2024-03-27 18:05 UTC, CodiumAI-Agent commented
## PR Review

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

2, because the changes are straightforward and localized to a specific feature. The addition of a new CSS file and modification of existing TypeScript files are clear and do not seem to introduce complex logic. However, reviewing the CSS for compatibility with various themes and ensuring the TypeScript changes do not affect other functionalities would require some effort.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td> 🔍&nbsp;<strong>Possible issues</strong></td><td>

<strong>Styling Compatibility:</strong> The hardcoded CSS values in `style.css` might not be compatible with all themes, especially custom themes that users might have. This could lead to the "Read All" button looking out of place in some themes.

</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>src/plugins/readAllNotificationsButton/style.css
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider using CSS variables for margins in `.vc-readAllNotis-button` to ensure consistency and ease of theme customization. For example, you could define `--read-all-button-margin: 2px 0 8px 9px;` in a theme's variables and use it here. This approach enhances theme compatibility and maintainability. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2291/files#diff-39defe9f83f514d039f0faa68a398090b08ef8d9c8d246ed763c8800fab6635dR7'>margin: 2px 0 8px 9px /* original styles */</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/readAllNotificationsButton/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

It's a good practice to avoid using `!important` in CSS unless absolutely necessary, as it makes overriding those styles more difficult later. Consider removing `!important` from `.vc-readAllNotis-button` and `.vc-readAllNotis-button:hover` in `style.css`, and ensure the CSS specificity is high enough to override default styles without it. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2291/files#diff-3157c2ee0638cfc35ca391371ade19757a3669dce6490af97e01889a32c79718R19'>import "./style.css";</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/readAllNotificationsButton/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Adding a new author to the plugin is a significant change. Ensure that `Devs.KrystalSkull` has agreed to be listed as an author and is aware of the responsibilities this entails, including maintenance and user support for the plugin. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2291/files#diff-3157c2ee0638cfc35ca391371ade19757a3669dce6490af97e01889a32c79718R61'>authors: [Devs.kemo, Devs.KrystalSkull],</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/utils/constants.ts
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

When adding new developers to the `Devs` object, consider also updating any relevant documentation or contributor lists outside of the codebase. This helps in recognizing their contributions in project logs or release notes. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2291/files#diff-e8d0a358ae2fb090c56f00a058050983cc9691b7d3622ddd443170017123e7d9R429'>KrystalSkull: {</a></td></tr></table><hr>

</details><hr>

<details> <summary><strong>✨ Review tool usage guide:</strong></summary><hr> 

**Overview:**
The `review` tool scans the PR code changes, and generates a PR review which includes several types of feedbacks, such as possible PR issues, security threats and relevant test in the PR. More feedbacks can be [added](https://pr-agent-docs.codium.ai/tools/review/#general-configurations) by configuring the tool.

The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on any PR.
- When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L23) related to the review tool (`pr_reviewer` section), use the following template:
```
/review --pr_reviewer.some_config1=... --pr_reviewer.some_config2=...
```
- With a [configuration file](https://pr-agent-docs.codium.ai/usage-guide/configuration_options/), use the following template:
```
[pr_reviewer]
some_config1=...
some_config2=...
```
    

See the review [usage page](https://pr-agent-docs.codium.ai/tools/review/) for a comprehensive guide on using this tool.


</details>

2024-03-27 18:17 UTC, KrstlSkll69 commented
reopening this because i only opened this as it was what Vee told me to do, but i dont know what to do now nor do i care, i did how i knew how to do it, might try to however they want ig we'll see

2024-03-27 20:45 UTC, Vendicated commented
superseded by https://github.com/Vendicated/Vencord/commit/8ab56f5bcfe720b8e6d03f85b5f4ada1a18bfc37

2024-03-27 20:45 UTC, closed without merging