feat(plugin): StreamerModeOnStream
Vendicated/Vencord pull request #2320
Opened 2024-03-31 04:33 UTC by Kodarru

This plugin makes it so when you start streaming in Discord, it enables streamer mode automatically. It disables it when you stop streaming too.

2024-03-31 04:35 UTC, Kodarru commented
IT PASSED!!

2024-03-31 06:10 UTC, Kodarru commented
Added a fix so it would only enable streamer mode on your stream. Whoops. Thank you to Venn for making me check that.

Also a thx to based_plutia and inftord for helping me test it.

2024-03-31 17:59 UTC, D3SOX commented
Lol this already existed for quite some time in my repo https://github.com/D3SOX/vencord-userplugins/tree/master/screenShareStreamerMode

2024-03-31 18:02 UTC, Kodarru commented
Mb, I didn't know it existed

2024-04-06 07:58 UTC, katlyn approved these changes

2024-04-08 03:44 UTC, Vendicated commented
welcome back from the dead

2024-04-09 00:10 UTC, Vendicated commented on src/plugins/streamerModeOnStream/index.ts
> +function stopStreamerMode(data) {
please type your arguments
```suggestion
function stopStreamerMode(data: { streamKey: string }) {
```

2024-04-09 00:41 UTC, Kodarru commented
I'll fix it right now

2024-04-09 00:47 UTC, Kodarru commented
Fixed!

2024-04-09 01:39 UTC, Vendicated commented on src/plugins/streamerModeOnStream/index.ts
> +        FluxDispatcher.subscribe("STREAM_CREATE", startStreamerMode);
prefer using the `flux` property instead of manually managing subscriptions

2024-04-09 01:40 UTC, Vendicated commented on src/plugins/streamerModeOnStream/index.ts
> +    description: "Automatically enables streamer mode when you start streaming in Discord.",
```suggestion
    description: "Automatically enables streamer mode when you start streaming in Discord",
```

2024-04-09 01:40 UTC, Vendicated commented on src/plugins/streamerModeOnStream/index.ts
> +    name: "streamerModeOnStream",
```suggestion
    name: "StreamerModeOnStream",
```

2024-04-09 04:36 UTC, Kodarru commented on src/plugins/streamerModeOnStream/index.ts
> +        FluxDispatcher.subscribe("STREAM_CREATE", startStreamerMode);
What Flux property? I feel like this is already good enough. I was searching and couldn't find what you were talking about

2024-04-16 09:06 UTC, lewisakura commented on src/plugins/streamerModeOnStream/index.ts
> +        FluxDispatcher.subscribe("STREAM_CREATE", startStreamerMode);
Vencord has a built in way of handling Flux subscriptions that mean plugins don't have to do it themselves. [Have a look at the coreplugin SupportHelper.](https://github.com/Vendicated/Vencord/blob/0f5a75aa4bc27af20b47ba3139d3f33f85901bde/src/plugins/_core/supportHelper.tsx#L96)

2024-04-17 01:33 UTC, Kodarru commented
I literally fixed the conflicting files but wtv

2024-04-18 00:23 UTC, Kodarru commented
This is FINALLY ready to merge now 🙏

2024-04-18 00:49 UTC, dolfies requested changes
so silly

2024-04-18 00:49 UTC, dolfies commented on src/plugins/streamerModeOnStream/index.ts
> +            toggleStreamerMode(StreamEvent, false);
```suggestion
            toggleStreamerMode(StreamData, false);
```

2024-04-18 00:49 UTC, dolfies commented on src/plugins/streamerModeOnStream/index.ts
> +            toggleStreamerMode(StreamEvent, true);
```suggestion
            toggleStreamerMode(StreamData, true);
```

2024-04-18 01:21 UTC, Kodarru commented
I'm very silly

2024-04-23 00:44 UTC, Kodarru commented
updated branch.. again

2024-04-24 03:51 UTC, merged

2024-04-24 03:52 UTC, Vendicated commented
thankies koda :3