plugin: Ollama integration
Vendicated/Vencord pull request #2327
Opened 2024-04-03 21:30 UTC by ArjixWasTaken

W.I.P. plugin that integrates local LLMs using Ollama.

2024-04-03 21:32 UTC, ArjixWasTaken commented
oof, looks like the source TS files for ollama-js require node

2024-04-03 22:44 UTC, TheKodeToad requested changes
Not working
Obama nowhere to be found

2024-04-03 22:44 UTC, TheKodeToad commented on src/plugins/personalAssistant/index.ts
> +        description: "Ollama's host address",
```suggestion
        description: "Obama's home address",
```

2024-04-04 10:40 UTC, CodeF53 requested changes

2024-04-04 10:40 UTC, CodeF53 commented on src/plugins/personalAssistant/index.ts
> +                        content: "You will generate text based on the user's prompt."
It would be nice to have access to custom system prompts

2024-04-04 10:40 UTC, CodeF53 commented on src/plugins/personalAssistant/index.ts
> +        default: "mistral"
I doubt the average vencord user can run Mistral. I would default to something like phi-2.

Also include a link to https://ollama.com/ somewhere in the settings

2024-04-04 10:54 UTC, ArjixWasTaken commented on src/plugins/personalAssistant/index.ts
> +                        content: "You will generate text based on the user's prompt."
Instead of submitting code-reviews, please have ur suggestions organized in a comment using bullet points. :pray:

2024-04-04 10:55 UTC, ArjixWasTaken commented on src/plugins/personalAssistant/index.ts
> +                        content: "You will generate text based on the user's prompt."
this PR is far from complete, everything you see is temporary

2024-04-04 10:57 UTC, ArjixWasTaken commented on src/plugins/personalAssistant/index.ts
> +        default: "mistral"
I plan to make this a custom component, that would fetch the available models from Ollama and allow you to choose one.

2024-04-04 10:58 UTC, ArjixWasTaken commented on src/plugins/personalAssistant/index.ts
> +        description: "Ollama's host address",
Obama isn't real, he can't hurt you.

2024-04-04 11:38 UTC, ArjixWasTaken commented on src/plugins/personalAssistant/index.ts
> +                        content: "You will generate text based on the user's prompt."
I see you downvoted my reply to your review.
Did you not like the idea of having all your suggestions in one place?

Please understand that I will gladly accept reviews, but since this is a WIP PR, I fear your reviews will go wasted since nothing is yet set in stone.

If that is ok with you, then keep making reviews like that!

2024-05-15 01:25 UTC, Vendicated commented
seems too niche, especially considering you need to selfhost these which most people won't be able to do

much more reasonable is for people to just use a discord bot or even use the recent userapps that add slash commands to your account

thanks for the contribution anyway!

2024-05-15 01:25 UTC, closed without merging

2024-05-15 04:12 UTC, ArjixWasTaken commented
mf, I did not even finish the PR
lol

Anyways, I was not actively going to work on this either way, my procrastination kicked in