(feat) Oneko: allow customization for the speed of the cat :3 && migrate from the decrypted define plugins to the new one
Vendicated/Vencord pull request #2333
Opened 2024-04-05 08:37 UTC by not-varram

P.S. check commit https://github.com/Vendicated/Vencord/commit/5f7c18a5666f5ecdb768d484b451e0cca087310f or the one with the comment "fix issues based on comments :3" to see the latest modifications to the core plugin (oneko)

2024-04-05 18:58 UTC, Nuckyz requested changes

2024-04-05 18:58 UTC, Nuckyz commented on src/plugins/oneko/index.ts
> +                    .then(eval);
Make this a function and re-use inside the sart method

2024-04-05 18:58 UTC, Nuckyz commented on src/plugins/oneko/index.ts
> +export const onekoSettings = definePluginSettings({
```suggestion
export const settings = definePluginSettings({
```

2024-04-05 18:58 UTC, Nuckyz commented on src/plugins/oneko/index.ts
> +    settings: onekoSettings,
```suggestion
    settings,
```

2024-04-05 18:58 UTC, Nuckyz commented on src/plugins/oneko/index.ts
> +            if (value && value < 0) return "The number must be bigger than 0";
You can just make this a slider instead

2024-04-06 05:19 UTC, not-varram commented
@Nuckyz Made all the changes as directed :D

2024-04-06 17:44 UTC, not-varram commented
@Nuckyz its ready to be commited :D

2024-04-16 08:58 UTC, lewisakura requested changes

2024-04-16 08:58 UTC, lewisakura commented on src/plugins/oneko/index.ts
> +            }
Can this be written in a way that doesn't cause it to re-eval the script every time? e.g. inject a way of modifying the speed without restarting script, or expose the speed variable to window and modify it here.

2024-04-16 10:09 UTC, not-varram commented on src/plugins/oneko/index.ts
> +            }
Good point; But the variable onekoSpeed is declared as "const" in the og script, Meaning the value cant be modified; +this is really inconsequential when coming to performance;

2024-04-16 10:10 UTC, not-varram commented
@lewisakura Good point; But the variable onekoSpeed is declared as a "const" in the OG script, Meaning the value cant be modified; +This is really inconsequential when coming to performance;

2024-04-16 10:12 UTC, not-varram commented
Also i tried that initally and it did not work for some reason :/

2024-04-16 10:12 UTC, not-varram commented
I think its ready to be commited now (i have been waiting for a few months 🙏)

2024-04-16 11:48 UTC, Sqaaakoi requested changes

2024-04-16 11:48 UTC, Sqaaakoi commented on src/plugins/oneko/index.ts
> +            }
I would remove the definition for `nekoSpeed` and replace all references to it with `Vencord.Plugins.plugins.oneko.settings.store.speed`

2024-04-16 11:48 UTC, Sqaaakoi commented on src/plugins/oneko/index.ts
> +        .then(s => s.replace("./oneko.gif", "https://raw.githubusercontent.com/adryd325/oneko.js/14bab15a755d0e35cd4ae19c931d96d306f99f42/oneko.gif")
What's with the multiple chained .then for replacing text, when the line below just continues this replacement statement?

2024-04-16 11:48 UTC, Sqaaakoi commented on src/plugins/oneko/index.ts
> +            return;
Remove this useless return, or remove the entire onChange function if you find my suggestion above would make it work without needing to restart it

2024-04-16 11:48 UTC, Sqaaakoi commented on src/plugins/oneko/index.ts
>      start() {
You could just use `start: runner,`

2024-04-16 11:48 UTC, Sqaaakoi commented on src/plugins/oneko/index.ts
> +import definePlugin, { OptionType } from "@utils/types";
where did the the empty line go

2024-04-16 17:21 UTC, not-varram commented on src/plugins/oneko/index.ts
> +            }
the main issue is that the core code for the oneko plugin (the cat) isn't mine and I don't wanna repost it to make changes (cuz I don't wanna upset the og creator of oneko)

2024-04-16 17:23 UTC, not-varram commented on src/plugins/oneko/index.ts
> +        .then(s => s.replace("./oneko.gif", "https://raw.githubusercontent.com/adryd325/oneko.js/14bab15a755d0e35cd4ae19c931d96d306f99f42/oneko.gif")
just for organization;+ (remember we are talking the script from another creator and modifying it slightly to work with discord) + I added like 26 bu the other .then statements where already there

2024-04-16 17:26 UTC, not-varram commented on src/plugins/oneko/index.ts
> +            return;
as started previously  the only way would be to take the code of og creator (which we eval from their script) make our own fork of it and modify it (which I don't know if they will  be ok with).
+ we don't need to go through all that hastle as this is a very **very** minor performance improvement that is not worth the hastle

2024-04-16 17:27 UTC, not-varram commented on src/plugins/oneko/index.ts
> +import definePlugin, { OptionType } from "@utils/types";
wym?

2024-04-16 20:17 UTC, ryan-0324 commented on src/plugins/oneko/index.ts
> +        .then(eval);
```suggestion
        .then(s => eval(s.replace(/(?<=const\s+nekoSpeed\s*=\s*)\S+?(?=\s*;)/, `${settings.store.speed}`)
            .replace("./oneko.gif", "https://raw.githubusercontent.com/adryd325/oneko.js/14bab15a755d0e35cd4ae19c931d96d306f99f42/oneko.gif")
            .replace("(isReducedMotion)", "(false)")));
```

2024-04-16 20:32 UTC, ryan-0324 commented on src/plugins/oneko/index.ts
> +        .then(eval);
I recommend making the search value for the `nekoSpeed` replace more robust, as it seems the author of oneko.js occasionally makes changes to the script.
Also, I believe that, as @Sqaaakoi previously mentioned, the extra chained `then()` methods are unnecessary, since the `replace()` method of String does not return a Promise object.

2024-05-14 23:52 UTC, Vendicated commented
this is cool but i think oneko is perfect in its current form

thank you regardless!

2024-05-14 23:52 UTC, closed without merging

2024-05-16 07:21 UTC, not-varram commented
@Vendicated the feature request to add an option to change oneko speed has been there for a while all this does is allow customization and it also moves it to the oneko plugin from the decrypted plugin decoration thing to the new one.