feat(ServerListIndicator) add ids for css
Vendicated/Vencord pull request #2335
Opened 2024-04-06 13:17 UTC by Panniku

2024-04-11 07:41 UTC, Panniku commented
bump

2024-05-03 13:04 UTC, Vendicated reviewed
thanks for your contribution! could you please show a screenshot?

2024-05-03 13:04 UTC, Vendicated commented on src/plugins/serverListIndicators/index.tsx
> +import style from "./styles.css?managed";
there's no need for this to be managed! you only need to manually manage your styles when they change styling of stock discord ui
```suggestion
import "./styles.css";
```

2024-05-03 13:04 UTC, Vendicated commented on src/plugins/spotifyControls/PlayerComponent.tsx
> +async function getDominantColor(imageUrl: any) {
please only include one change per pr. this change should not be here

2024-05-04 04:09 UTC, Panniku commented on src/plugins/spotifyControls/PlayerComponent.tsx
> +async function getDominantColor(imageUrl: any) {
sorrry, accidentally merged changes when attempting to sync repo

2024-05-04 05:08 UTC, Panniku commented
> thanks for your contribution! could you please show a screenshot?

Screenshot
![image](https://github.com/Vendicated/Vencord/assets/93918332/9efd7bc4-eccd-48d0-90fd-22daab8eec05)

2024-05-04 05:50 UTC, Cynosphere requested changes

2024-05-04 05:50 UTC, Cynosphere commented on src/plugins/spotifyControls/PlayerComponent.tsx
> +        <ErrorBoundary fallback={() => (
This added itself back from the revert

2024-07-16 06:30 UTC, closed without merging