fix: StartupTimings erroring on first run
Vendicated/Vencord pull request #2339
Opened 2024-04-07 15:58 UTC by waresnew

`findByPropsLazy` makes the properties of the lazy object also lazy, but that doesn't work for primitives bc `Reflect.get` can't be run on primitives

Before:

![image](https://github.com/Vendicated/Vencord/assets/45801973/269caf20-583d-4942-9a0a-4713bc702c19)

After:

![image](https://github.com/Vendicated/Vencord/assets/45801973/16bd72b1-37e1-4ab4-a672-f333865e4040)

2024-04-07 19:38 UTC, Nuckyz requested changes

2024-04-07 19:38 UTC, Nuckyz commented on src/utils/lazy.ts
> +            }
```suggestion
            const lazyTarget = target[kGET]();
            if (typeof lazyTarget === "object" || typeof lazyTarget === "function") {
                return Reflect.get(lazyTarget, p, receiver);
            }

            const val = lazyTarget[p];
            return typeof val === "function" ? val.bind(lazyTarget) : val;
```

2024-04-07 21:54 UTC, waresnew commented
Thanks @Nuckyz for telling me how to actually fix startuptimings

2024-04-07 22:15 UTC, Nuckyz requested changes

2024-04-07 22:15 UTC, Nuckyz commented on src/utils/lazy.ts
> +            throw new Error("proxyInner called on a primitive value");
```suggestion
            throw new Error("proxyLazy called on a primitive value");
```

2024-04-07 22:15 UTC, Nuckyz commented on src/plugins/startupTimings/index.tsx
> +import StartupTimingPage from "./StartupTimingPage";
```suggestion
import StartupTimingPage from "./StartupTimingPage";

```

2024-04-07 22:17 UTC, waresnew commented on src/utils/lazy.ts
> +            throw new Error("proxyInner called on a primitive value");
💀 mbbbbb

2024-04-08 04:32 UTC, Nuckyz approved these changes

2024-04-08 04:33 UTC, merged