Add a "NEW" Badge for New Plugins (V2)!
Vendicated/Vencord pull request #234
Opened 2022-11-21 15:57 UTC by nmsturcke

This does the following:

- [x] Store creation time of existing plugins in datastore
- [x] Check for creation time and, if it's less than 2 days ago, mark as new
- [x] Add a badge for new plugins
- [ ] Compare creation time with something to determine if the plugin is new, or they just install Vencord

2022-11-21 18:26 UTC, Vendicated commented
please fix conflicts

2022-11-21 18:42 UTC, nmsturcke commented
> please fix conflicts

Done

2022-11-21 19:20 UTC, ArjixWasTaken commented
Since you made a badge component, I'd suggest making the badge name and color be properties

So that the same component can be reused

2022-11-21 20:10 UTC, nmsturcke commented
> Since you made a badge component, I'd suggest making the badge name and color be properties
> 
> So that the same component can be reused

Changed ^^

2022-11-23 02:21 UTC, Vendicated requested changes

2022-11-23 02:21 UTC, Vendicated commented on src/components/PluginSettings/index.tsx
> +    if (JSON.stringify(newPlugins) === JSON.stringify(sortedPluginNames)) {
this should also be moved inside the useAwaiter

2022-11-23 02:21 UTC, Vendicated commented on src/components/PluginSettings/styles.ts
> +    textTransform: "uppercase",
why not just make it upper case in js? xd

2022-11-23 02:21 UTC, Vendicated commented on src/components/PluginSettings/styles.ts
> +    textOverflow: "ellipsis",
i dont think a badge should ever overflow and if it does thereshould definitely not be an ellipsis

2022-11-23 02:21 UTC, Vendicated commented on src/components/PluginSettings/styles.ts
> +    color: "white",
use a discord variable

2022-11-23 02:21 UTC, Vendicated commented on src/components/PluginSettings/styles.ts
> +    lineHeight: "16px",
most of these should be obsolete

2022-11-23 16:51 UTC, nmsturcke commented on src/components/PluginSettings/index.tsx
> +            if ((Vencord_existingPlugins[plugin.name] + 172800) > dateNow) {
Done

2022-11-23 16:52 UTC, nmsturcke commented on src/components/PluginSettings/index.tsx
> +    if (JSON.stringify(newPlugins) === JSON.stringify(sortedPluginNames)) {
Done, not sure if I set the type correctly though. I set it to `LoDashWrapper<any>`, be sure to say if it needs changing

2022-11-23 16:52 UTC, nmsturcke commented on src/components/PluginSettings/styles.ts
> +    paddingLeft: "6px",
Done

2022-11-23 16:52 UTC, nmsturcke commented on src/components/PluginSettings/styles.ts
> +    textTransform: "uppercase",
Just copied badge css properties lol

2022-11-23 16:53 UTC, nmsturcke commented on src/components/PluginSettings/styles.ts
> +    color: "white",
Done

2022-11-23 16:53 UTC, nmsturcke commented on src/components/PluginSettings/styles.ts
> +    lineHeight: "16px",
Done

2022-11-23 16:53 UTC, nmsturcke commented on src/components/PluginSettings/styles.ts
> +    textOverflow: "ellipsis",
Done

2022-11-27 22:44 UTC, Vendicated commented on src/components/PluginSettings/index.tsx
> +        const Vencord_existingPlugins: Record<string, number> = {};
```suggestion
        const existingPlugins: Record<string, number> = {};
```

2022-11-27 22:45 UTC, Vendicated commented on src/components/PluginSettings/index.tsx
> +            Vencord_existingPlugins[plugin.name] = Object.keys(existingPlugins || []).includes(plugin.name) ? existingPlugins[plugin.name] : dateNow;
```suggestion
            Vencord_existingPlugins[plugin.name] = existingPlugins[plugin.name] ?? dateNow;
```

2022-12-08 23:00 UTC, Vendicated requested changes

2022-12-08 23:00 UTC, Vendicated commented on src/components/PluginSettings/index.tsx
> +    const sortedPluginNames = Object.values(sortedPlugins).map(plugin => plugin.name);
this should be inside the awaiter to avoid unnecessary work

2022-12-08 23:00 UTC, Vendicated commented on src/components/PluginSettings/index.tsx
> +        sortedPlugins.map(plugin => {
this is map misuse since you're not using the result at all

2022-12-09 21:58 UTC, Vendicated commented on src/components/PluginSettings/index.tsx
> +    const [newPlugins, , newPluginsLoading] = useAwaiter(() => DataStore.get("Vencord_existingPlugins").then((cachedPlugins: Record<string, number>) => {
this get will return undefined if there is no entry which will later on read to a read of undefined.foo which will lead to a promise rejection. Please handle this case

2022-12-09 22:07 UTC, Vendicated commented on src/globals.d.ts
> +        _: LoDashWrapper<any>;
shouldn't this be LodashStatic?

2022-12-17 22:35 UTC, Vendicated commented on src/components/PluginSettings/index.tsx
> +    const [newPlugins, , newPluginsLoading] = useAwaiter(() => DataStore.get("Vencord_existingPlugins").then((cachedPlugins: Record<string, number>) => {
why did you mark this as resolved? this is still an issue

2022-12-17 23:25 UTC, ArjixWasTaken requested changes

2022-12-17 23:25 UTC, ArjixWasTaken commented on src/components/PluginSettings/index.tsx
> +            existingPlugins[plugin.name] = cachedPlugins[plugin.name] ?? dateNow;
```suggestion
            existingPlugins[plugin.name] = cachedPlugins?.[plugin.name] ?? dateNow;
```

when indexing a nullable value, you can simply use `?.` before the brackets to ensure that it won't error

2022-12-17 23:26 UTC, ArjixWasTaken commented on src/components/PluginSettings/index.tsx
> +            existingPlugins[plugin.name] = cachedPlugins[plugin.name] ?? dateNow;
since this is the only usage of `cachedPlugins` that I can see within this function, this should be enough to ensure no error happens

2022-12-17 23:27 UTC, ArjixWasTaken commented on src/components/PluginSettings/index.tsx
> +    const [newPlugins, , newPluginsLoading] = useAwaiter(() => DataStore.get("Vencord_existingPlugins").then((cachedPlugins: Record<string, number>) => {
```suggestion
    const [newPlugins, , newPluginsLoading] = useAwaiter(() => DataStore.get("Vencord_existingPlugins").then((cachedPlugins: Record<string, number> | undefined) => {
```

if it is true that it can be undefined, then it should be typed accordingly

2022-12-17 23:29 UTC, ArjixWasTaken commented on src/components/PluginSettings/index.tsx
> +            existingPlugins[plugin.name] = cachedPlugins[plugin.name] ?? dateNow;
(yes I know, this is weird syntax, but oh well)

2022-12-23 02:17 UTC, Vendicated approved these changes

2022-12-23 02:17 UTC, merged