feat(plugin): CustomIdle
Vendicated/Vencord pull request #2342
Opened 2024-04-08 20:18 UTC by waresnew

Fulfills Vencord/plugin-requests#199

Main feature is changing the timer until your status gets set to idle (or preventing auto-idle forever)

![image](https://github.com/Vendicated/Vencord/assets/45801973/e2f8912c-6294-40b8-a923-3cfd8c756725)

There's also a "grace period" where it'll let you stay idle, even if you come back to Discord

![Discord_Uzc6kS5kNB](https://github.com/Vendicated/Vencord/assets/45801973/5b6e945c-6a08-4bac-bdbd-c9658fc8b1c5)

Once you click "Stay idle", you will remain idle (so no more grace period nags) until you manually switch your status to Online

If you wait until the grace period is over, you'll be put back into Online

2024-04-08 20:26 UTC, waresnew commented
ngl i think it'd be better to do like a "You are currently still idle. Click the button to exit idle" bar instead of the grace period

lemme change that

2024-04-08 20:29 UTC, Vendicated commented
keep in mind that this idle timer is coupled with mobile notifications. so if you set it to a very high number or disable it outright, it might break mobile notifications

2024-04-08 20:31 UTC, waresnew commented
> keep in mind that this idle timer is coupled with mobile notifications. so if you set it to a very high number or disable it outright, it might break mobile notifications

oh ok i'll make a more precise patch for disabling then

2024-04-09 20:32 UTC, waresnew commented
aight it won't affect mobile notifications now (it'll respect the setting in vanilla discord)

you can see here:

![image](https://github.com/Vendicated/Vencord/assets/45801973/ceef6831-c406-4d17-862f-82bd13c47b3e)

^ I'm online (disabled auto-idle) but I'm afk

Also changed the "grace period" thing to this:

![image](https://github.com/Vendicated/Vencord/assets/45801973/9cf12de8-0951-4032-87ed-b4cc20f5326e)

2024-04-11 08:26 UTC, Golonchy commented
Cool af

2024-04-22 20:32 UTC, Wraaath commented
Bump

2024-05-07 11:36 UTC, R00tB33rMan commented
Did some testing with this and feel it’s ready for use. Vesktop currently does not handle Idling very well and this as a workaround seems like a fair consideration to me. Could not produce any bugs with this branch. At this time, I have to run four Discord tabs, instead of two to keep my Discord online at all times, which is incredibly inefficient. How ready would you say this is or what’s blocking this from being added to the plugin library, @Vendicated?

2024-05-07 14:17 UTC, JosTheDude commented
Requesting addition here, works well

2024-05-14 23:41 UTC, Kromilan commented
I was deperatly looking for a plugin like this. When I have Discord open on my second monitor and have an eye on it, I am there. Hands on my keyboard and mouse, and always an eye on Discord. But I still get set to idle when I don't actually click into the client for too long and then they think I'm not available and nobody messages me any more :( I'm so glad there's a plugin in development to fix this!!
I have a question though. I am absolutely not familiar with github though, so sorry if this is a stupid question: can this already be installed and if so, how? I saw some people in the comments tested it, so I guess they installed it somehow, but then there are also comments suggesting it's not available yet?

2024-05-15 00:45 UTC, waresnew commented
> can this already be installed and if so, how?

it can be installed, but it's not an official plugin yet (vee needs to approve it first) so you need to install the [dev version of Vencord](https://github.com/Vendicated/Vencord/blob/main/docs/1_INSTALLING.md). then you download the index.ts in this pull request and you move it to `src/userplugins/customidle` (create a folder)

however you won't get any support with dev versions/unofficial plugins like this one so you have to figure it out yourself in the end

2024-05-15 05:26 UTC, UglukOrc commented
I'm so happy you've made this dream come true! I understand it isn't officially released, But, I found it amazing how BetterDiscord had something like it, and I was just wondering beyond wonder why Vencord didn't have any option for it! Thanks @waresnew

2024-05-15 05:33 UTC, Vendicated commented
> How ready would you say this is or what’s blocking this from being added to the plugin library, @Vendicated?

@R00tB33rMan there's nothing blocking it from being merged, it's just that i haven't gotten to it yet! there's quite the backlog of pull requests so it sadly takes a while sometimes. anyway ill look at this some time in the coming few days

you (and anyone reading this) can always help by testing open pull requests early and leaving constructive feedback / finding bugs yourself

for example in this pr it'd be good to test & report if this causes any issues / edge cases with mobile notifications or if those work flawlessly

2024-05-15 05:35 UTC, Vendicated commented
please add a readme file

2024-05-15 12:37 UTC, waresnew commented
ok it looks like a lot of people use this plugin to partially solve idling while the window is in the foreground

i think i'll be able to add that as a separate setting at some point

in terms of formatting, i can't access vscode rn so i'll fix it in like 10 hours

i'll add a readme in a moment

2024-05-16 06:24 UTC, Nuckyz requested changes

2024-05-16 06:24 UTC, Nuckyz commented on src/plugins/customidle/index.ts
> +        }
```suggestion

        const backOnlineMessage = "Welcome back! Click the button to go online. Click the X to stay idle until reload.";
        if (Notices.noticesQueue.some(([, noticeMessage]) => noticeMessage === backOnlineMessage)) return;

        Notices.showNotice(backOnlineMessage, "Exit idle", () => {
            Notices.popNotice();
            FluxDispatcher.dispatch({
                type: "IDLE",
                idle: false
            });
        });
```

2024-05-16 06:27 UTC, Nuckyz commented
The way this is currently done has a big problem. The same function that handles setting mobile notifications to true is the function that sets the idle. It is ran using a setInterval as seen here:
![image](https://github.com/Vendicated/Vencord/assets/61953774/bd709d5e-054d-4d65-83f8-50ea713d0c09)

Modifying IDLE_DURATION to MAX_SAFE_INTEGER causes "C" to run on loop non stop. But also, modifying it means you are still making setting mobile notifications depend on the new idle timeout, because it changes how often it does the checking

2024-05-16 06:31 UTC, Nuckyz commented
I have applied my suggestion of a better of handling showing the notice, and also better formatting. But the issues I mentioned are still present

2024-05-16 14:38 UTC, waresnew commented
ok i just realized that setInterval's delay has to be a 32 bit integer

so MAX_SAFE_INTEGER was making it overflow to 0 :skull:

technically this made it so the setinterval was still being run but this probably caused lag

2024-05-17 15:55 UTC, Vendicated commented
so this still needs work if i'm understanding correctly? marking as draft accordingly

2024-05-18 14:06 UTC, waresnew commented
ok it won't prevent you from being AFK on web installs now

i'm gonna unmark it as draft now

2024-05-18 22:40 UTC, Nuckyz requested changes

2024-05-18 22:40 UTC, Nuckyz commented on src/plugins/customidle/index.ts
> +                    replace: "$1" // Decouple idle from afk (phone notifications will remain at user setting)
```suggestion
                    replace: "$1" // Decouple idle from afk (phone notifications will remain at user setting or 10 min maximum)
```

2024-05-18 22:40 UTC, Nuckyz commented on src/plugins/customidle/index.ts
> +        return idleTimeout === 0 ? Number.MAX_SAFE_INTEGER : idleTimeout * 60000;
```suggestion
        return idleTimeout === 0 ? Infinity : idleTimeout * 60000;
```

2024-05-18 22:40 UTC, Nuckyz commented
Great fix, just these two nitpicks and it should be ready

2024-05-18 22:41 UTC, Nuckyz requested changes

2024-05-18 22:41 UTC, Nuckyz commented on src/plugins/customidle/README.md
> +
```suggestion
![Plugin Configuration](https://github.com/Vendicated/Vencord/assets/45801973/4e5259b2-18e0-42e5-b69f-efc672ce1e0b)
```

2024-05-18 23:40 UTC, waresnew commented
okk made the changes 👍

2024-05-18 23:41 UTC, merged

2024-05-18 23:42 UTC, Nuckyz commented
Thank you for the new plugin!

2024-05-20 07:49 UTC, UglukOrc commented
> Thank you for the new plugin!

Hol up! This working now?? @Nuckyz

2024-05-20 08:00 UTC, Nuckyz commented
When it gets released to the main branch, yes

2024-05-22 04:25 UTC, R00tB33rMan commented
Thank you all for your hard work. I really appreciate everyone's interest in improving the user experience and am glad that this was merged through everyone's availability and persistence.

2024-08-21 16:04 UTC, DanielVALAT commented
Hello
The plugin doesn't work anymore :(
I remain inactive when I lock my computer (after 0 secs)

![Discord_OkDnD5FOFP](https://github.com/user-attachments/assets/db21e1fb-e75a-4fff-8367-8d7e09e7ffe2)
![Discord_YsCYE134lw](https://github.com/user-attachments/assets/b9be7340-1693-4f03-bba5-035df0b76f9b)

2024-08-21 17:39 UTC, Vendicated commented
use our support channel instead of necroing old threads.