feat(plugin): enables lootboxes back again
Vendicated/Vencord pull request #2344
Opened 2024-04-09 13:04 UTC by happyendermangit

Discord as of today disabled lootboxes, so i made this plugin that enables them back
![image](https://github.com/Vendicated/Vencord/assets/66224387/18112feb-e32b-45fb-a112-2e3dd3b5f074)
![image](https://github.com/Vendicated/Vencord/assets/66224387/02ab4040-f965-4968-a1aa-ff94493709a7)

2024-04-09 13:12 UTC, mufaroxyz reviewed
LGTM

2024-04-09 13:36 UTC, MrDiamondDog commented on src/plugins/LootBoxes/LootBoxes.js
> +            find: "Messages.PACKAGES_BADGE",
Dont use \w+, use \i (custom selector made by us)

2024-04-09 14:18 UTC, Vendicated commented on src/plugins/LootBoxes/LootBoxes.js
> +            find: "Messages.PACKAGES_BADGE",
no it isn't. variable names may contain characters that are not matched by \w, such as $

2024-04-09 14:19 UTC, Vendicated commented
i'm not sure how useful this is.

won't discord just remove the api / code for this very soon? longevity of this plugin seems unlikely

why not post it as a js snippet instead?

2024-04-09 14:25 UTC, happyendermangit commented
The api will never be removed, discord will just forget about this, a js snippet is not possible...

2024-04-09 21:08 UTC, MrDiamondDog commented
It is getting removed very soon https://discord.com/channels/1015060230222131221/1105582084237570088/1227358383468838965

2024-04-10 17:24 UTC, byeoon requested changes
If this were to be a update that was pushed upstream, this can't be the README.

2024-04-18 19:14 UTC, closed without merging