showBadgeInChat
Vendicated/Vencord pull request #2347
Opened 2024-04-10 16:47 UTC by KrstlSkll69

supersedes the abandoned #1980 _(Is also just complete rewrite of it_

Shows the message author's badges beside their name in chat. 
The badges include all built-in Discord badges. 
It also proudly displays your Vencord donor/contributor badges.

---

The settings editor lets you:

-   Drag to reorder
-   Click to enable/disable a specific badge type
-   Hover over a badge for the tool-tip about what badges it represents

---

An example of what the menu looks like ↓
![ExampleOfTheIntreface](https://github.com/Vendicated/Vencord/assets/150982280/a4ae2c7a-0788-4d44-a558-c0e5a465e5e1)

---

Vencord Creator: Vee (vending.machine) badge's ↓
![VencordCreator'sBadges](https://github.com/Vendicated/Vencord/assets/150982280/9d3dc3d4-0f7b-42c3-b896-ed2d7bba7ec6)

---

Video of menu in action ↓
https://github.com/Vendicated/Vencord/assets/150982280/5ebc21cc-19dc-4cf9-b988-c95eae1f9ca5

2024-04-10 17:22 UTC, byeoon commented
LGTM

2024-04-11 02:24 UTC, KrstlSkll69 commented
I am very sorry, This is like my third time using github, but I fucked up and this was my attempt to fix it. I hope it work. 😭

2024-05-08 02:41 UTC, KrstlSkll69 commented
I'm going to bump this because even tho it's lost in hell, I see at least one white name a day ask for a plug-in that does exactly this

2024-05-25 06:09 UTC, waterbufalowalking commented
> I see at least one white name a day ask for a plug-in that does exactly this
agreed, +1 from me

2024-05-26 21:12 UTC, byeoon commented
i hope this gets merged soon

2024-05-26 21:23 UTC, KrstlSkll69 commented
> i hope this gets merged soon

thank u for your kinda words i hope so too, Its almost everyday i see someone asking for plugin. So i also hope it gets merged too. <3 ;3

2024-05-28 00:58 UTC, Vendicated requested changes
meow

2024-05-28 00:58 UTC, Vendicated commented on src/plugins/showBadgesInChat/styles.css
> +.disabled {
please prefix your classes with `.vc-plugin-`, eg `.vc-sbic`

2024-05-28 02:35 UTC, KrstlSkll69 commented
i think everything is fixed @Vendicated

2024-05-28 02:39 UTC, Vendicated reviewed
for better maintainability and catching bugs before they occur, try to avoid using the `any` type. here you already have strong types on everything so there's no reason to use all these anys

2024-05-28 02:39 UTC, Vendicated commented on src/plugins/showBadgesInChat/index.tsx
> +function CheckBadge({ badge, author }: { badge: string; author: any; }): JSX.Element | null {
```suggestion
function CheckBadge({ badge, author }: { badge: string; author: User; }): JSX.Element | null {

```

2024-05-28 02:39 UTC, Vendicated commented on src/plugins/showBadgesInChat/index.tsx
> +                    {badges.getDonorBadges(author.id)?.map((badge: any) => (
```suggestion
                    {badges.getDonorBadges(author.id)?.map(badge => (

```

2024-05-28 02:39 UTC, Vendicated commented on src/plugins/showBadgesInChat/index.tsx
> +                .filter((badge: any) => (author.flags || author.publicFlags) & (1 << badge[0]))
```suggestion
                .filter(badge => (author.flags || author.publicFlags) & (1 << badge[0]))

```

2024-05-28 02:39 UTC, Vendicated commented on src/plugins/showBadgesInChat/index.tsx
> +                .map((badge: any) => (
```suggestion
                .map(badge => (

```

2024-05-28 02:39 UTC, Vendicated commented on src/plugins/showBadgesInChat/index.tsx
> +function ChatBadges({ author }: any) {
```suggestion
function ChatBadges({ author }: { author: User }) {

```

2024-05-28 02:39 UTC, Vendicated commented on src/plugins/showBadgesInChat/index.tsx
> +        addDecoration("vc-show-badges-in-chat", props => <ChatBadges author={props.message?.author} />);
you use optional chaining here, which could potentially result in `author` being undefined, however the above functions expect a non null user and don't do any null safety

that makes very little sense! you should either remove this optional chaining if you're sure the author always exists
```suggestion
        addDecoration("vc-show-badges-in-chat", props => <ChatBadges author={props.message.author} />);

```
or, safer, make sure it always exists
```suggestion
        addDecoration("vc-show-badges-in-chat", props => props.message?.author ? <ChatBadges author={props.message.author} /> : null);

```

2024-05-28 02:42 UTC, KrstlSkll69 commented
ok committed

2024-05-28 02:50 UTC, KrstlSkll69 commented
misclicked, didnt mean to do that

2024-05-28 02:59 UTC, KrstlSkll69 commented
ok bug fix, thx @Inbestigator for spotting that

2024-05-28 03:42 UTC, KrstlSkll69 commented
@Inbestigator is a meanie whom keeps waking me up*(joke)*, forgot the style import earlier

2024-06-07 16:27 UTC, Inbestigator approved these changes
Ready to merge

2024-06-12 03:56 UTC, Inbestigator commented
Vee, it still says you have a change requested, but there is no change 💀

2024-06-23 23:15 UTC, KrstlSkll69 commented
bumping this at the request of Inbestigator

2025-01-11 22:45 UTC, KrstlSkll69 commented
honestly after long forgetting and this plugin and pr, its updated to work with the `key={author.id}` and that semi new `#{intl::` thing... also a style fix

2025-03-22 04:05 UTC, closed without merging

2025-03-22 04:06 UTC, KrstlSkll69 commented
Imma be straight up so much time has passed and there’s been so many changes that I just have to start a whole new fork for these merge conflicts.

2025-03-22 04:31 UTC, KrstlSkll69 commented
New Pr https://github.com/Vendicated/Vencord/pull/3305