feat(plugin): PauseInvitesForever
Vendicated/Vencord pull request #2372
Opened 2024-04-20 16:42 UTC by dolfies

### Summary
Readds an option to pause invites permanently. 

![very simple](https://i.dolfi.es/6Xyo7uFWcc.png?key=WZ3s6sJXrehFip)

2024-04-20 19:51 UTC, byeoon commented
🙏 thank you

2024-04-21 09:52 UTC, Golonchy commented
this is epice,
nice

2024-04-24 04:07 UTC, Vendicated commented on src/plugins/pauseInvitesForever/index.tsx
> +        return enableInvitesDisabled && !GuildStore.getGuild(guildId).hasFeature("INVITES_DISABLED");
since this is not stateful, it won't update on change

i assume this means if you press the button it wont actually update the ui until you reopen the modal

you could make it stateful & subscribe to the experiment and guild updates (i assume changing features dispatches a guild update?)
```js
useShowDisabledInvites(guildId: string) {
	const { enableInvitesDisabled } = InvitesDisabledExperiment.useSetting({ guildId });
	const guild = useStateFromStores([GuildStore], () => GuildStore.getGuild(guildId));
	return enableInvitesDisabled && guild.hasFeature("INVITES_DISABLED");
}
```

2024-04-24 04:07 UTC, Vendicated commented on src/plugins/pauseInvitesForever/index.tsx
> +        return enableInvitesDisabled && !GuildStore.getGuild(guildId).hasFeature("INVITES_DISABLED");
but if you do this, you also need to turn your component below into a proper react component (as opposed to calling it as a plain function) or you might run into crashes due to inconsistent hook calling

the easiest way to do that is to wrap it in `ErrorBoundary.wrap()`

2024-04-24 04:08 UTC, Vendicated commented on src/plugins/pauseInvitesForever/README.md
> +Adds a button to the Security Actions modal to to pause invites indefinitely.
please add the screenshot you attached to the pr description here

2024-04-24 04:32 UTC, dolfies commented on src/plugins/pauseInvitesForever/README.md
> +Adds a button to the Security Actions modal to to pause invites indefinitely.
done!

2024-04-26 21:48 UTC, Nuckyz requested changes

2024-04-27 20:09 UTC, dolfies commented on src/plugins/pauseInvitesForever/index.tsx
> +    pauseHook(guildId: string) {
done!

2024-05-02 23:09 UTC, merged

2024-05-02 23:20 UTC, Vendicated commented
👽 💚