feat(plugin): Better Quests
Vendicated/Vencord pull request #2380
Opened 2024-04-23 17:53 UTC by kvbaxi

Somehow me changing default branch on my fork made my previous pull request ( https://github.com/Vendicated/Vencord/pull/2364 ) get closed and branch "removed" even though it still exists.

Sorry guys 😭 For info about what this pull request introduces check out the previous pull request that got closed.

2024-04-25 08:46 UTC, Sqaaakoi requested changes
Could we also get some patches to attempt to progress quests when streaming anything? It's possible, I'm doing it with a JS snippet right now

2024-04-25 08:46 UTC, Sqaaakoi commented on src/plugins/betterQuests/index.tsx
> +        { // Add new route
I feel like the way you're adding a route here will break something

2024-04-25 08:46 UTC, Sqaaakoi commented on src/plugins/betterQuests/index.tsx
> +routes.set("/questsMenu", {
This will cause a 404 on reload. If you use `/channels/@quests` or something like that it will not do this

2024-04-25 08:46 UTC, Sqaaakoi commented on src/plugins/betterQuests/index.tsx
> +const routes = new Map<string, RouteData>();
Make a proper routes API?

2024-04-25 08:46 UTC, Sqaaakoi commented on src/plugins/betterQuests/index.tsx
> +    redirectTo: "/channels/@me"
What does this do?

2024-04-25 08:46 UTC, Sqaaakoi commented on src/plugins/betterQuests/index.tsx
> +const redirectRoute = (ev: BeforeUnloadEvent) => {
This isn't foolproof

2024-05-02 18:22 UTC, happyendermangit commented
@CodiumAI-Agent /improve

2024-05-02 18:23 UTC, TheKodeToad commented
@CodiumAI-Agent /review

2024-05-02 18:25 UTC, CodiumAI-Agent commented
## PR Code Suggestions

<table><thead><tr><td>Category</td><td align=left>Suggestions&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </td></tr></thead><tbody><tr><td rowspan=1><strong>Enhancement</strong></td>
<td>



<details><summary>Improve reliability of navigation and page reload sequence.</summary>

___


**Replace the <code>setTimeout</code> function with a more reliable method to handle page reloads after <br>navigation to ensure that the reload happens after the navigation has completed. This can <br>be achieved by using promises or async/await pattern to wait for the navigation to finish.**
    
[src/plugins/betterQuests/index.tsx [91]](https://github.com/Vendicated/Vencord/pull/2380/files#diff-50309baaf878f3a1aaf5aafa61a12c3950c2b740bb58c6f1bf5cd5be768f0881R91-R91)

```diff
-setTimeout(() => window.location.reload(), 0);
+nav.transitionTo(data?.redirectTo ?? "/channels/@me").then(() => window.location.reload());
 
```
                   
</details></td></tr><tr><td rowspan=2><strong>Best practice</strong></td>
<td>



<details><summary>Enhance type safety by using specific types instead of <code>any</code>.</summary>

___


**Consider using a more specific type than <code>any</code> for the <code>props</code> parameter in the <code>QuestPage</code> <br>component to enhance type safety and improve code maintainability.**
    
[src/plugins/betterQuests/index.tsx [48]](https://github.com/Vendicated/Vencord/pull/2380/files#diff-50309baaf878f3a1aaf5aafa61a12c3950c2b740bb58c6f1bf5cd5be768f0881R48-R48)

```diff
-const QuestPage = (props?: any) => {
+interface QuestPageProps {
+    // Define specific properties
+}
+const QuestPage = (props?: QuestPageProps) => {
 
```
                   
</details></td></tr><tr><td>



<details><summary>Use destructuring for cleaner and more manageable code.</summary>

___


**Use destructuring to handle <code>props</code> in the <code>QuestPage</code> component for cleaner code and easier <br>property management.**
    
[src/plugins/betterQuests/index.tsx [48]](https://github.com/Vendicated/Vencord/pull/2380/files#diff-50309baaf878f3a1aaf5aafa61a12c3950c2b740bb58c6f1bf5cd5be768f0881R48-R48)

```diff
-const QuestPage = (props?: any) => {
+const QuestPage = ({ someProp, anotherProp }: QuestPageProps) => {
 
```
                   
</details></td></tr><tr><td rowspan=2><strong>Performance</strong></td>
<td>



<details><summary>Optimize filtering of active quests to avoid unnecessary array creation.</summary>

___


**Replace the <code>Array.from</code> and <code>filter</code> chaining with a more efficient method that avoids <br>creating an intermediate array, such as using a for-loop or <code>reduce</code> to filter and count <br>active quests directly.**
    
[src/plugins/betterQuests/index.tsx [69]](https://github.com/Vendicated/Vencord/pull/2380/files#diff-50309baaf878f3a1aaf5aafa61a12c3950c2b740bb58c6f1bf5cd5be768f0881R69-R69)

```diff
-const activeQuests = Array.from(questsStore.quests.values()).filter((q: any) => new Date(q.config.expiresAt).getTime() > Date.now() && q.claimedAt);
+const activeQuests = [];
+for (const quest of questsStore.quests.values()) {
+    if (new Date(quest.config.expiresAt).getTime() > Date.now() && quest.claimedAt) {
+        activeQuests.push(quest);
+    }
+}
 
```
                   
</details></td></tr><tr><td>



<details><summary>Improve performance by using a constant for the SVG content in the <code>CrownIcon</code> component.</summary>

___


**Refactor the <code>CrownIcon</code> component to use a constant for the SVG content to avoid <br>re-creating the SVG on every render, which can improve performance especially in large <br>applications.**
    
[src/plugins/betterQuests/index.tsx [38-44]](https://github.com/Vendicated/Vencord/pull/2380/files#diff-50309baaf878f3a1aaf5aafa61a12c3950c2b740bb58c6f1bf5cd5be768f0881R38-R44)

```diff
-const CrownIcon = () => {
-    return (
-        <svg width="800px" height="800px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
-            <path fill-rule="evenodd" clip-rule="evenodd" d="M5 19C5 18.4477 5.44772 18 6 18L18 18C18.5523 18 19 18.4477 19 19C19 19.5523 18.5523 20 18 20L6 20C5.44772 20 5 19.5523 5 19Z" fill="currentColor" />
-            <path fill-rule="evenodd" clip-rule="evenodd" d="M9.87867 4.70711C11.0502 3.53554 12.9497 3.53554 14.1213 4.70711L16.6878 7.27359C16.9922 7.57795 17.4571 7.6534 17.8421 7.46091L18.5528 7.10558C20.0877 6.33813 21.7842 7.80954 21.2416 9.43755L19.4045 14.9487C18.9962 16.1737 17.8498 17 16.5585 17H7.44151C6.15022 17 5.0038 16.1737 4.59546 14.9487L2.75842 9.43755C2.21575 7.80955 3.91231 6.33813 5.44721 7.10558L6.15787 7.46091C6.54286 7.6534 7.00783 7.57795 7.31219 7.27359L9.87867 4.70711Z" fill="currentColor" />
-        </svg>
-    );
-};
+const crownIconSvg = (
+    <svg width="800px" height="800px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
+        <path fill-rule="evenodd" clip-rule="evenodd" d="M5 19C5 18.4477 5.44772 18 6 18L18 18C18.5523 18 19 18.4477 19 19C19 19.5523 18.5523 20 18 20L6 20C5.44772 20 5 19.5523 5 19Z" fill="currentColor" />
+        <path fill-rule="evenodd" clip-rule="evenodd" d="M9.87867 4.70711C11.0502 3.53554 12.9497 3.53554 14.1213 4.70711L16.6878 7.27359C16.9922 7.57795 17.4571 7.6534 17.8421 7.46091L18.5528 7.10558C20.0877 6.33813 21.7842 7.80954 21.2416 9.43755L19.4045 14.9487C18.9962 16.1737 17.8498 17 16.5585 17H7.44151C6.15022 17 5.0038 16.1737 4.59546 14.9487L2.75842 9.43755C2.21575 7.80955 3.91231 6.33813 5.44721 7.10558L6.15787 7.46091C6.54286 7.6534 7.00783 7.57795 7.31219 7.27359L9.87867 4.70711Z" fill="currentColor" />
+    </svg>
+);
+const CrownIcon = () => crownIconSvg;
 
```
                   
</details></td></tr></tr></tbody></table><hr>

<details> <summary><strong>✨ Improve tool usage guide:</strong></summary><hr> 

**Overview:**
The `improve` tool scans the PR code changes, and automatically generates suggestions for improving the PR code. The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on a PR.
- When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L78) related to the improve tool (`pr_code_suggestions` section), use the following template:

```
/improve --pr_code_suggestions.some_config1=... --pr_code_suggestions.some_config2=...
```

- With a [configuration file](https://pr-agent-docs.codium.ai/usage-guide/configuration_options/), use the following template:

```
[pr_code_suggestions]
some_config1=...
some_config2=...
```
    


See the improve [usage page](https://pr-agent-docs.codium.ai/tools/improve/) for a comprehensive guide on using this tool.


</details>

2024-05-02 18:26 UTC, CodiumAI-Agent commented
## PR Review

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

4, due to the complexity and size of the PR, which includes a new plugin with multiple components, lazy loading, and dynamic routing. The PR involves advanced TypeScript features and React components, requiring a thorough understanding of asynchronous operations, state management, and event handling.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> 🔍&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> The `QuestButtonComponent` uses `questsStore.quests.values()` without checking if `questsStore.quests` is defined or if it's iterable. This might cause runtime errors if `questsStore.quests` is not as expected.</td></tr>
<tr>
<td>

<strong>Performance Concern:</strong> The `redirectRoute` function is attached to the `beforeunload` event and performs navigation and a page reload. This could lead to performance issues or unexpected behavior when navigating away from the page.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>src/plugins/betterQuests/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider adding error handling for the asynchronous operation within `QuestPage`. This will ensure that any failures in the `requireSettingsMenu` or other parts of the async function are gracefully handled and could provide a better user experience. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2380/files#diff-50309baaf878f3a1aaf5aafa61a12c3950c2b740bb58c6f1bf5cd5be768f0881R53'>await requireSettingsMenu();</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/betterQuests/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Implement a check for `questsStore.quests` before using its values in `QuestButtonComponent`. This prevents potential runtime errors if `questsStore` is not initialized as expected. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2380/files#diff-50309baaf878f3a1aaf5aafa61a12c3950c2b740bb58c6f1bf5cd5be768f0881R69'>const activeQuests = Array.from(questsStore.quests.values()).filter((q: any) => new Date(q.config.expiresAt).getTime() > Date.now() && q.claimedAt);</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/betterQuests/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

To improve code readability and maintainability, consider abstracting the SVG creation in `CrownIcon` into a separate component file. This separation can make the main plugin file cleaner and focus more on the logic. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2380/files#diff-50309baaf878f3a1aaf5aafa61a12c3950c2b740bb58c6f1bf5cd5be768f0881R38'>const CrownIcon = () => {</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>src/plugins/betterQuests/index.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Optimize the `redirectRoute` function by checking if the current path needs handling before preventing the default action. This can enhance performance by avoiding unnecessary function executions. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Vendicated/Vencord/pull/2380/files#diff-50309baaf878f3a1aaf5aafa61a12c3950c2b740bb58c6f1bf5cd5be768f0881R87'>if (paths.includes(path)) {</a></td></tr></table><hr>

</details><hr>

<details> <summary><strong>✨ Review tool usage guide:</strong></summary><hr> 

**Overview:**
The `review` tool scans the PR code changes, and generates a PR review which includes several types of feedbacks, such as possible PR issues, security threats and relevant test in the PR. More feedbacks can be [added](https://pr-agent-docs.codium.ai/tools/review/#general-configurations) by configuring the tool.

The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on any PR.
- When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L23) related to the review tool (`pr_reviewer` section), use the following template:
```
/review --pr_reviewer.some_config1=... --pr_reviewer.some_config2=...
```
- With a [configuration file](https://pr-agent-docs.codium.ai/usage-guide/configuration_options/), use the following template:
```
[pr_reviewer]
some_config1=...
some_config2=...
```
    

See the review [usage page](https://pr-agent-docs.codium.ai/tools/review/) for a comprehensive guide on using this tool.


</details>

2024-07-31 07:55 UTC, closed without merging