Plugin: CustomScreenShare
Vendicated/Vencord pull request #2385
Opened 2024-04-24 14:41 UTC by KawaiianPizza

Same as https://github.com/Vendicated/Vencord/pull/2094 but right this time(?)

2024-04-24 15:30 UTC, MrDiamondDog commented on src/plugins/customScreenShare.desktop/index.tsx
> +                match: /(.=)(.{19}FPS.+?([A-z]{1,2}).{11}>([A-z]{1,2}).[A-z]{1,2},([A-z]{1,2}),[A-z]{1,2},([A-z.]+).+?\}\)),/,
Use \i

2024-04-24 15:30 UTC, MrDiamondDog commented on src/plugins/customScreenShare.desktop/index.tsx
> +/*
Use the new header

2024-04-24 15:30 UTC, MrDiamondDog commented on src/plugins/customScreenShare.desktop/index.tsx
> +            find: "=4e6",
Probably not the best find, could break very easily

2024-04-24 17:12 UTC, Cynosphere requested changes

2024-04-24 17:12 UTC, Cynosphere commented on src/plugins/customScreenShare.desktop/index.tsx
> +                replace: "$18"
I don't know if it will interpret it as capture group 18 but it just looks better not being a string capture group (repeat elsewhere)
```suggestion
                replace: (_, number) => `${number}8`
```

2024-04-24 17:12 UTC, Cynosphere commented on src/plugins/customScreenShare.desktop/index.tsx
> +                match: /updateRemoteWantsFramerate..\{/, // disable discord mute fps reduction
```suggestion
                match: /updateRemoteWantsFramerate\(\)\{/, // disable discord mute fps reduction
```

2024-04-24 17:12 UTC, Cynosphere commented on src/plugins/customScreenShare.desktop/index.tsx
> +                match: /for\(let . of ..ApplicationStreamSettingRequirements\).+?!1/,
```suggestion
                match: /for\(let \i of \i\.ApplicationStreamSettingRequirements\).+?!1/,
```

2024-04-24 17:12 UTC, Cynosphere commented on src/plugins/customScreenShare.desktop/index.tsx
> +                match: /(.=)(.{19}FPS.+?(\i).{11}>(\i).\i,(\i),\i,([A-z.]+).+?\}\)),/,
All `(.=)` should be `(\i=)`

2024-04-24 17:12 UTC, Cynosphere commented on src/plugins/customScreenShare.desktop/index.tsx
> +                match: /(bitrateMin:).+?(,bitrateMax:).+?(,bitrateTarget:).+?,/,
I really dislike this capture group spam just because you're too lazy to retype everything

2024-04-24 17:12 UTC, Cynosphere commented on src/plugins/customScreenShare.desktop/index.tsx
> +                match: /(stream-settings-resolution-.+?children:.)/,
Does this even produce valid JS if `children` is a variable and not an array? If it is an array:
```suggestion
                match: /(stream-settings-resolution-.+?children:\[)/,
```

2024-05-17 03:28 UTC, Golonchy commented
so this is the same as https://github.com/philhk/Vencord/tree/better-plugins/src/plugins/betterScreenshare.desktop ?

2024-05-17 04:18 UTC, thororen1234 commented
> so this is the same as https://github.com/philhk/Vencord/tree/better-plugins/src/plugins/betterScreenshare.desktop ?

I would say correct but this one has a chance at getting merged because it doesn't require an entire plugin lib to run.

2024-05-24 01:38 UTC, Golonchy commented
o ye fair.

2024-06-05 19:46 UTC, Loukious commented
Would be nice if you add an option to select an encoder.

2024-10-01 23:57 UTC, closed without merging