SilentTyping: Option to toggle in context menu
Vendicated/Vencord pull request #2386
Opened 2024-04-24 19:43 UTC by ImBonana

Closes #752

2024-04-25 08:25 UTC, Sqaaakoi requested changes

2024-04-25 08:25 UTC, Sqaaakoi commented on src/plugins/silentTyping/index.tsx
> +    group?.splice(2, 0,
hardcoding the index here might be a bad idea, depending on if discord ever updates this context menu or if any other plugins inject anything above here

I have implemented 
https://github.com/Sqaaakoi/Vencord/blob/5c972722de7dd853fe8ffcf2de0e69e4c6d8803b/src/plugins/composeMode/index.tsx#L38-L39 to hook into this same menu at the same position

2024-05-11 16:10 UTC, Vendicated commented on src/plugins/silentTyping/index.tsx
> +            label="Slient Typing"
```suggestion
            label="Enable Silent Typing"
```

2024-05-11 20:49 UTC, merged

2024-05-11 20:49 UTC, Vendicated commented
thanks, cool addition!!