feat(messageTags): Add message quick reply plugin
Vendicated/Vencord pull request #241
Opened 2022-11-21 18:34 UTC by Luna-devv

Commands:
`/tags create` - create a new tag
`/tags list` - list all tags
`/tags delete` - delete a tag
`/tags preview` - preview a tag
`/<tag>` - makes you explode
![image](https://user-images.githubusercontent.com/71079641/203133243-c9695654-ff72-4f5b-b32e-0efc7a7cd41f.png)

2022-11-21 18:36 UTC, Luna-devv commented
It's a full rewrite of https://github.com/Vendicated/Vencord/blob/customTags/src/plugins/customTags.ts

2022-11-23 02:03 UTC, Vendicated commented on src/plugins/messageTags.ts
> +const emote = "<:luna:1035316192220553236>";
nitpick but
```suggestion
const EMOTE = "<:luna:1035316192220553236>";
```

2022-11-23 02:05 UTC, Vendicated commented on src/plugins/messageTags.ts
> +            get options() {
since these are static options, no need to make this a getter, just make it the actual options instead! The only reason I used a getter was to add dynamic options (but that flopped anyway cause Discord caches optionts it seems :X)

2022-11-23 02:06 UTC, Vendicated commented on src/plugins/messageTags.ts
> +                        description: "Previre a tag from your yourself without sending it publicly",
```suggestion
                        description: "Preview a tag without sending it publicly",
```

2022-11-23 18:26 UTC, Luna-devv commented
This PR does **not** include a bit coin miner (at least it should)

2022-11-23 18:27 UTC, Vendicated commented on src/plugins/messageTags.ts
> +            ].map(prepareOption),
```suggestion
            ]
```

2022-11-23 18:28 UTC, Vendicated requested changes

2022-11-23 18:28 UTC, Vendicated commented on src/plugins/messageTags.ts
> +                content: `${EMOTE} The tag **${tag.name}** has been send!`
```suggestion
                content: `${EMOTE} The tag **${tag.name}** has been sent!`
```

2022-11-23 18:29 UTC, Vendicated commented
Looks good otherwise!

2022-11-23 18:56 UTC, Vendicated approved these changes

2022-11-23 18:56 UTC, merged