Better issue templates
Vendicated/Vencord pull request #2410
Opened 2024-05-03 14:15 UTC by cloudcloudskies

Updated issue templates to make them look like Vesktop's issue templates.

2024-05-03 20:03 UTC, ryan-0324 requested changes
We're is the contraction of we are.

2024-05-03 20:13 UTC, ryan-0324 requested changes
Sorry, I submitted the last review wrong.

2024-05-03 20:13 UTC, ryan-0324 commented on .github/ISSUE_TEMPLATE/blank.yml
> +description: Create a blank issue. Always first use our support channel! Only use this form if you're a contributor or we're told to do so in the support channel.
```suggestion
description: Create a blank issue. Always first use our support channel! Only use this form if you're a contributor or were told to do so in the support channel.
```

2024-05-03 20:13 UTC, ryan-0324 commented on .github/ISSUE_TEMPLATE/blank.yml
> +          - You we're given explicit permission to use this form by a moderator in our support server,
```suggestion
          - You were given explicit permission to use this form by a moderator in our support server,
```

2024-05-03 20:13 UTC, ryan-0324 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +description: Create a bug or crash report for Vesktop. Always use our support channel! Only use this form if you're a contributor or we're told to do so in the support channel.
````suggestion
description: Create a bug or crash report for Vesktop. Always use our support channel! Only use this form if you're a contributor or were told to do so in the support channel.
```

2024-05-03 20:13 UTC, ryan-0324 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          - You we're given explicit permission to use this form by a moderator in our support server.
```suggestion
          - You were given explicit permission to use this form by a moderator in our support server.
```

2024-05-23 08:08 UTC, schoeneBiene commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +description: Create a bug or crash report for Vesktop. Always use our support channel! Only use this form if you're a contributor or we're told to do so in the support channel.
```suggestion
description: Create a bug or crash report for Vencord. Always use our support channel! Only use this form if you're a contributor or we're told to do so in the support channel.
```

2024-06-06 02:26 UTC, Vendicated commented
they're fine as is for now. i might overhaul them from scratch myself in the future

thanks regardless

2024-06-06 02:26 UTC, closed without merging