feat(plugin): ReplaceGoogleSearch
Vendicated/Vencord pull request #2450
Opened 2024-05-12 21:15 UTC by ImpishMoxxie

## ReplaceGoogleSearch
This plugin implements a patch to replace the "Search with Google" in the context menu when right clicking on a highlighted word. You can this engine with the dropdown menu in the settings which gives you the options Google, Bing, Yahoo, Github, Kagi, Yandex, AOL, Baidu and Wikipedia. Alternatively, you can enable the "Use Custom Search Engine" option in the settings to use an alternate engine.

<details>
    <summary><strong>Screenshots</strong></summary>
    <img src="https://i.imgur.com/g3ptYvS.png" />
    <img src="https://i.imgur.com/Y56p7VY.png" />
</details>

2024-05-12 21:26 UTC, Vendicated commented
why not entirely replace the menu and allow multiple options? 
![image](https://github.com/Vendicated/Vencord/assets/45497981/5e3cca42-2b9d-4572-8567-90a0fb6560da)

2024-05-13 20:05 UTC, Vendicated reviewed
looks pretty good! maybe the custom option should be on top?

2024-05-13 20:05 UTC, Vendicated commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +    if(settings.store.customEngineName && settings.store.customEngineURL) {
```suggestion
    if (settings.store.customEngineName && settings.store.customEngineURL) {
```

2024-05-13 20:05 UTC, Vendicated commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +                const key = "search-content-" + engine;
```suggestion
                const key = "vc-search-content-" + engine;
```

2024-05-13 20:05 UTC, Vendicated commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +                                    src={`https://www.google.com/s2/favicons?domain=${new URL(Engines[engine])}`}
what does this URL constructor achieve?
```suggestion
                                    src={`https://www.google.com/s2/favicons?domain=${Engines[engine]}`}
```

2024-05-13 20:05 UTC, Vendicated commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +                                        borderRadius: i >= 3
you copied this from ReverseImageSearch, right? pretty sure i only had this because the saucenao icon looks awful when circle cropped, so you can probably remove this

2024-05-13 20:23 UTC, ethan-davies commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +                                        borderRadius: i >= 3
Yes, this style was originally copied from ReverseImageSearch to try maintain consistent styles throughout Vencord.

2024-05-13 20:24 UTC, ImpishMoxxie commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +                                        borderRadius: i >= 3
you want me to remove the borderRadius?

2024-05-13 20:30 UTC, ImpishMoxxie commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +                match: /\[\(0,\i.jsx\)\(\i.MenuItem,\{id:"search-google",label:\i.default.Messages.SEARCH_WITH_GOOGLE,action:t},"search-google"\)\]/,
Wouldn't that mean we would add to the context menu instead of replacing the pre-existing "Search with Google"

2024-05-14 01:17 UTC, Vendicated commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +                match: /\[\(0,\i.jsx\)\(\i.MenuItem,\{id:"search-google",label:\i.default.Messages.SEARCH_WITH_GOOGLE,action:t},"search-google"\)\]/,
you can just remove it from the array / override it

2024-05-14 01:18 UTC, Vendicated commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +                                        borderRadius: i >= 3
yes and see if it still looks good! like i said im pretty sure i just added it for saucenao

2024-05-14 08:22 UTC, Golonchy commented
merge needed

2024-05-14 09:18 UTC, ImpishMoxxie commented
@Golonchy I'll finish working on it today when I'll get home in a few hours or so

2024-05-14 10:04 UTC, Golonchy commented
alright 👍

2024-05-16 19:14 UTC, ImpishMoxxie commented
@Vendicated all updates that you asked got implemented!

2024-05-17 05:47 UTC, Nuckyz requested changes

2024-05-17 05:47 UTC, Nuckyz commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +    group?.push(makeSearchItem(selection));
```suggestion
    const group = findGroupChildrenByChildId("search-google", children);
    if (group) {
        const idx = group.findIndex(c => c?.props?.id === "search-google");
        group[idx] = makeSearchItem(selection);
    }
```

2024-05-17 05:47 UTC, Nuckyz commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +
```suggestion
```

2024-05-17 05:47 UTC, Nuckyz commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +
```suggestion
```

2024-05-17 05:47 UTC, Nuckyz commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +
```suggestion
```

2024-05-17 05:47 UTC, Nuckyz commented on src/plugins/ReplaceGoogleSearch/index.tsx
> +
```suggestion
```

2024-05-17 07:02 UTC, ImpishMoxxie commented
changed all that was asked @Nuckyz

2024-05-17 07:15 UTC, Nuckyz approved these changes

2024-05-17 07:17 UTC, merged

2024-05-17 07:17 UTC, Nuckyz commented
Thanks for the new plugin!