Add NoDefaultHangStatus plugin
Vendicated/Vencord pull request #2468
Opened 2024-05-16 19:05 UTC by D3SOX

Resolves https://github.com/Vencord/plugin-requests/issues/564

Waiting for confirmation if the logic is okay

2024-05-16 20:34 UTC, Curve commented on src/webpack/common/types/fluxEvents.d.ts
> +export type FluxEvents =
did you mean to format this?

2024-05-16 20:35 UTC, Curve commented on src/plugins/noDefaultHangStatus/index.ts
> +            if (saveAsDefault === undefined && status) {
out of curiosity, would it also be possible to just discard the event instead of dispatching a new one?

2024-05-16 21:45 UTC, Nuckyz requested changes

2024-05-16 21:45 UTC, Nuckyz commented on src/webpack/common/types/fluxEvents.d.ts
Don't update this file, another pr is already targetted for it

2024-05-16 21:45 UTC, Nuckyz commented on src/plugins/noDefaultHangStatus/index.ts
> +            if (saveAsDefault === undefined && status) {
I agree, is it possible to just avoid the update hang status being fired for when you join the channel?

2024-05-16 21:46 UTC, D3SOX commented on src/plugins/noDefaultHangStatus/index.ts
> +            if (saveAsDefault === undefined && status) {
I wanted to do that too but I don't know if there's a way to cancel events :o

2024-05-16 21:47 UTC, D3SOX commented on src/webpack/common/types/fluxEvents.d.ts
> +export type FluxEvents =
I already waited for this comment yeah should probably format back

2024-05-16 21:48 UTC, Nuckyz commented on src/plugins/noDefaultHangStatus/index.ts
> +            if (saveAsDefault === undefined && status) {
What is sending that event? The client or the server websocket?

2024-05-16 21:51 UTC, D3SOX commented on src/plugins/noDefaultHangStatus/index.ts
> +            if (saveAsDefault === undefined && status) {
I'm certain the client dispatches it

2024-05-16 21:51 UTC, D3SOX commented on src/webpack/common/types/fluxEvents.d.ts
Should I just revert my changes?

2024-05-16 21:52 UTC, Nuckyz commented on src/webpack/common/types/fluxEvents.d.ts
for this file yes

2024-05-16 21:53 UTC, Nuckyz commented on src/plugins/noDefaultHangStatus/index.ts
> +            if (saveAsDefault === undefined && status) {
okay but based on what? what is the root cause that causes this to be fired? ws event? joinChannel function?

2024-05-16 22:18 UTC, D3SOX commented
Now it's using a patch to cancel the event

2024-05-17 08:20 UTC, Nuckyz approved these changes

2024-05-17 08:21 UTC, merged

2024-05-17 08:21 UTC, Nuckyz commented
Thanks for the new plugin!