fix(showHiddenThings/disableDiscoveryFilters): More robust patches for removing Algolia filters
Vendicated/Vencord pull request #2484
Opened 2024-05-19 19:41 UTC by dolfies

Current patch doesn't always work as there's multiple functions for fetching Algolia results, might be related to an experiment

2024-05-20 04:45 UTC, Nuckyz requested changes

2024-05-20 04:45 UTC, Nuckyz commented on src/plugins/showHiddenThings/index.ts
> +            find: "\">200\"",
Patch the getter for MINIMUM_MEMBER_COUNT instead. I know in the past I said it's bad to patch exports, but in this case it's better than targetting a nunber

```suggestion
            find: "MINIMUM_MEMBER_COUNT:",
```

2024-05-20 05:02 UTC, dolfies commented on src/plugins/showHiddenThings/index.ts
> +            find: "\">200\"",
Done!

2024-05-21 00:28 UTC, merged

2024-05-21 00:28 UTC, Vendicated commented
thankies

2024-06-19 14:30 UTC, Vendicated commented on src/plugins/showHiddenThings/index.ts
> +            find: "\">200\"",
clueless