File Viewer Plugin
Vendicated/Vencord pull request #2505
Opened 2024-05-25 17:44 UTC by JokerJosh1234

this plugin will add a button to supported files to view the contents (contents dont get loaded unless to user presses the button)

https://github.com/Vendicated/Vencord/assets/103841613/e4502fed-0316-4229-9c81-f475415282f5

in the video you can see how it works, if the file size is over 10MB the preview wont work therefore we tell the uesr that. the video only shows 3 of the 14 supported file types but they all work the same. there are no settings for this plugin.

2024-05-25 17:50 UTC, MrDiamondDog requested changes
Don't use DOM manipulation. Use patches and react components to add whatever you need

2024-05-25 19:04 UTC, lewisakura requested changes

2024-05-25 19:04 UTC, lewisakura commented on src/utils/constants.ts
> +    },
please don't put yourself in the top of the list

2024-05-25 19:04 UTC, lewisakura commented on src/plugins/fileViewer/index.tsx
> +}
use react

2024-05-25 19:04 UTC, lewisakura commented on src/plugins/fileViewer/index.tsx
> +}
use react

2024-05-25 19:04 UTC, lewisakura commented on src/plugins/fileViewer/index.tsx
> +        }, 200);
use a patch to get the chatbox

2024-05-25 19:04 UTC, lewisakura commented on src/plugins/fileViewer/index.tsx
> +        Object.assign(Classes, ...findBulk.apply(null, [filters.byProps("attachment", "metadata"), filters.byProps("scrollerInner"), filters.byProps("fileNameLink"), filters.byProps("layerContainer")
what?

2024-05-25 19:04 UTC, lewisakura commented on src/plugins/fileViewer/index.tsx
> +`;
use react

2024-05-25 19:04 UTC, lewisakura commented on src/plugins/fileViewer/index.tsx
> +}
use react

2024-05-25 19:04 UTC, lewisakura commented on src/plugins/fileViewer/index.tsx
> +};
my understanding of this is that it's meant to add a button to the message, so please use the chat buttons API to do this

2024-05-25 19:07 UTC, JokerJosh1234 commented on src/plugins/fileViewer/index.tsx
> +};
where can i find the chat buttons api? also i literally cannot figure out how to use patches, istg ive spent atleast 5 hours trying to figure it out and haven't got a single bit closer than when i started.

2024-05-25 21:07 UTC, Scyye commented on src/plugins/fileViewer/index.tsx
> +};
look at another plugin that uses the chat buttons api, such as [ViewRaw](https://github.com/Vendicated/Vencord/blob/main/src/plugins/viewRaw/index.tsx)

2024-05-26 05:46 UTC, closed without merging

2024-05-26 15:54 UTC, Sqaaakoi commented on src/plugins/fileViewer/index.tsx
> +};
chat buttons api wouldn't even be suitable for this, this was for attachments