Plugin: DisableDiscordRestart
Vendicated/Vencord pull request #2510
Opened 2024-05-26 22:45 UTC by burlone0

Disables the Ctrl + R shortcut to prevent Discord from restarting.

2024-05-26 22:48 UTC, MrDiamondDog reviewed
I don't really see a use for this plugin but I'll leave this here

2024-05-26 22:48 UTC, MrDiamondDog commented on src/plugins/disableDiscordRestart/index.tsx
> +    const modal = document.createElement('div');
Don't use dom manipulation

2024-05-26 22:48 UTC, MrDiamondDog commented on src/plugins/disableDiscordRestart/index.tsx
> +    description: "Disables the Ctrl + R shortcut to prevent Discord from restarting.",
The plugin makes a pop up instead of fully disables the keybind. The description should reflect that

2024-05-26 22:53 UTC, burlone0 commented on src/plugins/disableDiscordRestart/index.tsx
> +    description: "Disables the Ctrl + R shortcut to prevent Discord from restarting.",
That's the general description, that's what the showAlert setting description says

2024-05-26 22:53 UTC, burlone0 commented on src/plugins/disableDiscordRestart/index.tsx
> +    const modal = document.createElement('div');
wdym

2024-05-26 22:59 UTC, burlone0 commented on src/plugins/disableDiscordRestart/index.tsx
> +    const modal = document.createElement('div');
What do you mean? What should I use?

2024-05-26 23:25 UTC, Inbestigator reviewed
This seems pretty useless, and the execution feels kind of clunky.

2024-05-27 01:33 UTC, Scyye commented on src/plugins/disableDiscordRestart/index.tsx
> +    const modal = document.createElement('div');
react i believe

2024-05-27 01:53 UTC, Scyye reviewed
This doesnt seem useful in the slightest; what's the usecase?

2024-05-27 02:17 UTC, nyakowint commented
If anything this can just be an addition to the NoF1 plugin

2024-05-27 02:32 UTC, nyakowint requested changes
You should get rid of all this dom manipulation (which u shouldn't be using anyways) and replace it with a simple toast or modal (in webpack commons)

2024-05-27 05:49 UTC, MrDiamondDog commented on src/plugins/disableDiscordRestart/index.tsx
> +    const modal = document.createElement('div');
DOM manipulation is bad when you have patches and react components at your disposal. Have a look at some other plugins for reference

2024-05-27 16:57 UTC, schoeneBiene commented on src/plugins/disableDiscordRestart/index.tsx
> +            showAlertPopup("Ctrl + R shortcut disabled", "DisableDiscordRestart - Made by Burlone");
does your name really need to be here?

2024-05-27 22:31 UTC, Inbestigator commented on src/plugins/disableDiscordRestart/index.tsx
> +            showAlertPopup("Ctrl + R shortcut disabled", "DisableDiscordRestart - Made by Burlone");
Yeah, shoving “made by …” down people’s throats feels icky. Also, tbh the whole title for that modal could be removed.

2024-06-06 02:25 UTC, Vendicated commented
this is way too specific and not very useful in its current state, so i'll be rejecting this. have you tried adding `ctrl + r` as unbinded in discord keybind settings instead? might work

thanks for your contribution nevertheless

2024-06-06 02:25 UTC, closed without merging