[Plugin] HiddenMessageEdit
Vendicated/Vencord pull request #2512
Opened 2024-05-27 07:02 UTC by Snawalt

This plugin allow you to modify messages without "edited" mark, also bypass bots, enjoy!!!!

2024-05-27 07:22 UTC, nyakowint requested changes
:neckbeard:

2024-05-27 07:22 UTC, nyakowint commented on src/plugins/hiddenMessageEdit/index.tsx
> +                        }),
Do not do manual fetch requests, use RestAPI

2024-05-27 07:22 UTC, nyakowint commented on src/plugins/hiddenMessageEdit/index.tsx
> +                    replace: `, $1 = (webpackChunkdiscord_app.push([[''], {}, e => {m = []; for (let c in e.c) m.push(e.c[c])}], m).find(m => m?.exports?.default?.getToken !== void 0).exports.default
Just findByProps for this lol

2024-05-27 07:22 UTC, nyakowint commented on src/plugins/hiddenMessageEdit/utils.ts
why

2024-05-27 10:06 UTC, Snawalt commented on src/plugins/hiddenMessageEdit/utils.ts
well, yeah. its my first plugin ever, also im kinda junior in this topic, but dw, i'll fix everything XD

2024-05-27 16:13 UTC, MrDiamondDog requested changes

2024-05-27 16:13 UTC, MrDiamondDog commented on src/plugins/hiddenMessageEdit/icons.tsx
> +import React from "react";
Please run eslint to add our license header and format your plugin consistently

2024-05-27 16:13 UTC, MrDiamondDog commented on src/plugins/hiddenMessageEdit/index.tsx
> +import definePlugin from "../../utils/types";
Use our import shorthands (@utils/...)
If you aren't already using vscode please do as it will import stuff automatically with the correct path

2024-05-27 16:13 UTC, MrDiamondDog commented on src/plugins/hiddenMessageEdit/index.tsx
> +const HiddenMessageEditForm = ({ message, onSave }) => {
This component should be a `Modal`, then you can just use the open modal function instead of dom manip

2024-05-27 16:13 UTC, MrDiamondDog commented on src/plugins/hiddenMessageEdit/index.tsx
> +                const { getToken } = findByProps("getToken");
Don't put finds here, put them on the top level so they only run once
Also pretty sure there's a Webpack.Common thing for this

2024-05-27 16:13 UTC, MrDiamondDog commented on src/plugins/hiddenMessageEdit/index.tsx
> +    authors: [{ id: 390884143749136386n, name: "Prism" }],
Add yourself to `Devs`

2024-05-27 16:13 UTC, MrDiamondDog commented on src/webpack/common/utils.ts
>   *
You should probably discard your changes for this file

2024-05-28 00:07 UTC, Vendicated commented
i don't see a use case for this plugin that isn't malicious

sorry but i will be rejecting this

2024-05-28 00:07 UTC, closed without merging