[PLUGIN] QuickPin
Vendicated/Vencord pull request #2522
Opened 2024-05-29 22:18 UTC by imjustprism

Enables you to pin a message by **clicking** on it while holding down **Ctrl+Shift**

https://github.com/Vendicated/Vencord/assets/69634294/0109eb14-1e92-48ee-89a2-fdbe7c3c6103

2024-05-29 22:22 UTC, ImLvna commented on src/plugins/QuickPin/index.tsx
> +let pinModule;
type this

2024-05-29 22:22 UTC, ImLvna commented on src/plugins/QuickPin/index.tsx
> +    if (msg.pinned) {
maybe make this unpin if it is already pinned?

2024-05-29 22:25 UTC, programminglaboratorys commented
I am thinking that this is better off being merged with MessageClickActions

2024-05-29 22:25 UTC, Vendicated commented
^

2024-05-29 22:51 UTC, MrDiamondDog requested changes

2024-05-29 22:51 UTC, MrDiamondDog commented on src/plugins/QuickPin/index.tsx
> +        pinModule = findByProps("pinMessage", "unpinMessage");
Just initialize this when you make the variable

2024-05-29 22:51 UTC, MrDiamondDog commented on src/plugins/QuickPin/index.tsx
> +async function unpinMessage(channel, message) {
Please put types anywhere where there isn't

2024-05-30 02:45 UTC, MrDiamondDog approved these changes
This should definitely be merged with MessageClickActions

2024-05-30 10:52 UTC, imjustprism commented
> This should definitely be merged with MessageClickActions

yeah understandable and thus logical, if i do it, should i add myself to the authors in the MessageClickAction or?

2024-05-30 11:34 UTC, imjustprism commented on src/plugins/messageClickActions/index.ts
do not ask what the actually fuck happend here, okay? morning coffee, watching a movie, i added myself to authors, and somehow i managed to conjure myself here too

2024-05-30 15:41 UTC, MrDiamondDog commented on src/plugins/messageClickActions/index.ts
That is totally fine actually

That space is meant for plugin authors as well but no one does it lol

2024-05-30 15:41 UTC, MrDiamondDog approved these changes

2024-05-30 15:53 UTC, imjustprism commented on src/plugins/messageClickActions/index.ts
logically, this is correct as well yeah, but i noticed that license information wasnt extended anywhere(i checked some plugin), so i decided to remove it ^^

2024-05-30 16:27 UTC, Vendicated commented on src/plugins/messageClickActions/index.ts
editing the header to include your own name is allowed, but only very few people do it

but there's also no reason to do that, since you own the copyright to the code you wrote either way and are already included in the "and contributors"

2024-05-30 21:57 UTC, imjustprism commented on src/plugins/messageClickActions/index.ts
> +                if (msg.pinned) unpinMessage(channel, msg);
what u guys think, should i add a bot system message confirming successful unpinning? When you pin a message, you see a default message by discord, but theres no notification for unpinning so can be confusing, idk

2024-06-05 13:54 UTC, imjustprism commented
Idk, i think the bot reply solution is not bad, but im thinking about modal.. mhm

https://github.com/Vendicated/Vencord/assets/69634294/ff02dde2-6f1c-45b1-a144-f657a97c2ed3

2024-06-06 02:05 UTC, Vendicated commented on src/plugins/messageClickActions/index.ts
> +    if (!pinModule) return;
1. prefer typing strictly instead of abusing `any`
2. do not explicitly type stuff (in this case return type) if it can be inferred
3. null checking pinModule here will just make debugging harder. also `find*Lazy()` never returns null / undefined so `!pinModule` is always false
 
```suggestion
async function pinMessage(channel: Channel, message: Message) {
    await pinModule.pinMessage(channel, message.id);
}

async function unpinMessage(channel: Channel, message: Message) {
```

2024-06-06 02:05 UTC, Vendicated commented on src/plugins/messageClickActions/index.ts
> +        this.onClick = addClickListener((msg: any, channel: any, event: MouseEvent) => {
?
```suggestion
        this.onClick = addClickListener((msg: any, channel, event) => {
```

2024-09-02 18:31 UTC, closed without merging