Add a new translate command.
Vendicated/Vencord pull request #2532
Opened 2024-06-01 23:35 UTC by anotherkai

This pull request introduces a new `translate` command to the moreCommands plugin. It uses mymemory's (by translated labs) API to retrieve text and either send to the current channel or "preview" the plugin. There is a 50k character limit per day on this due to the API being free.

2024-06-01 23:48 UTC, MrDiamondDog commented
This should really be apart of the translate plugin, not this one

2024-06-01 23:52 UTC, anotherkai commented
> This should really be apart of the translate plugin, not this one

See I would if I knew how to work with Modals, I'm only just learning how to write functional plugins so for the meanwhile, I will be trying to get this added the moreCommands plugin.

2024-06-02 00:05 UTC, MrDiamondDog requested changes
The reason I suggested it be moved is because then you can use the same translating api as the translate plugin, which uses google translate and thus does not have a quota

2024-06-02 00:05 UTC, MrDiamondDog commented on src/plugins/moreCommands/index.ts
> +function mock(input) {
why

2024-06-02 00:05 UTC, MrDiamondDog commented on src/plugins/moreCommands/index.ts
> +import definePlugin, { definePluginSettings, OptionType } from "@utils/types";
?

2024-06-02 00:05 UTC, MrDiamondDog commented on src/plugins/moreCommands/index.ts
> +    },
What does this option do? the description doesn't make sense

2024-06-02 00:09 UTC, anotherkai commented on src/plugins/moreCommands/index.ts
> +function mock(input) {
I actually didn't know I did this :sob:

2024-06-02 00:13 UTC, Vendicated commented
yeah u should add this as a command to the Translate plugin instead, it already has a translate function so you just need to add the command

2024-06-02 00:29 UTC, Scyye requested changes
This should 100% not be in moreCommands. Just move it over to the translation plugin.

2024-06-02 00:29 UTC, Scyye commented on src/plugins/moreCommands/index.ts
> +    authors: [Devs.Arjix, Devs.echo, Devs.Samu, {name: "Kai :3", id: 1205727693811879997n}],
Add yourself to the devs constant

2024-06-02 00:29 UTC, Scyye commented on src/plugins/moreCommands/index.ts
> +function mock(input: string): string {
I- why??

2024-06-02 00:30 UTC, anotherkai commented on src/plugins/moreCommands/index.ts
> +function mock(input: string): string {
Did I seriously forget to symbol link :-:

2024-06-02 00:30 UTC, anotherkai commented on src/plugins/moreCommands/index.ts
> +function mock(input: string): string {
i did :facepalm:

2024-06-02 00:34 UTC, closed without merging

2024-06-02 00:35 UTC, anotherkai commented
Closed as I will be moving it over to translate plugin, will make a new pr soon.