[Plugin] Plural Kit Integration
Vendicated/Vencord pull request #2536
Opened 2024-06-02 15:11 UTC by Scyye

Fork of [PluralChum](https://github.com/estroBiologist/pluralchum) for Vencord

Current features include:
1. Edit button
2. Member IDs in chat
3. Member colour in chat

Planned features:
1. `PK` badge, compatible with moreUserTags
2. Functional member-specific profile popout
3. Blocking 
4. Reproxy modal
5. Option of role colours rather than member colour

There's a few things i dont fully understand how to use (ex. `DataStore`), if I used that, or anything else incorrectly, or theres any changes needed, please let me know and ill be sure to fix them.

2024-06-02 16:08 UTC, MrDiamondDog requested changes
This plugin seems kinda niche but I'll leave this review

2024-06-02 16:08 UTC, MrDiamondDog commented on package.json
> +        "pkapi.js": "7.2.1"
Plugins should not add dependencies. This package is just a wrapper around an api, so use that instead

2024-06-02 16:08 UTC, MrDiamondDog commented on src/plugins/pluralKit/index.tsx
> +    authors = await DataStore.get<Record<string, { name: string; messageIds: string[]; member: Member|string|undefined; system: System; }>>(DATASTORE_KEY) || {};
Put this in your plugin's start function

2024-06-02 16:08 UTC, MrDiamondDog commented on src/plugins/pluralKit/index.tsx
> +let authors: Record<string, { messageIds: string[]; member: Member|string|undefined; system: System; }> = {};
Please make this a type instead of typing it out everytime

2024-06-02 16:08 UTC, MrDiamondDog commented on src/plugins/pluralKit/index.tsx
> +    name: "Plural Kit",
Your plugin's name spills follow our naming convention, so it should be `PluralKit`

2024-06-02 16:08 UTC, MrDiamondDog commented on src/plugins/pluralKit/index.tsx
> +        DataStore.createStore(DATASTORE_KEY, DATASTORE_KEY);
You don't need to do this

2024-06-02 16:08 UTC, MrDiamondDog commented on src/plugins/pluralKit/index.tsx
> +            console.log(msg);
make sure you get rid of these

2024-06-02 16:11 UTC, Vendicated commented
thanks for your contribution!

unfortunately this is way too niche, sorry

2024-06-02 16:11 UTC, closed without merging

2024-06-02 16:58 UTC, Scyye commented
> thanks for your contribution!
> 
> unfortunately this is way too niche, sorry
> @Vendicated 

if i could appeal my ban from the discord, would there be anywhere for me to share it there?

2024-06-02 19:37 UTC, Scyye commented
@Vendicated ?

2024-06-02 22:26 UTC, lewisakura commented
You aren't banned from the Discord server, according to the account you're using as your developer account. Either way, this is not the appropriate place to file such an appeal.

2024-06-03 10:36 UTC, Scyye commented
> You aren't banned from the Discord server, according to the account you're using as your developer account. Either way, this is not the appropriate place to file such an appeal.

i wasnt attempting to appeal here, my hope was i would receive a friend request or something of the sort, and i could do it through DMs; where would be the proper place?

2025-01-04 17:50 UTC, c45513v commented
> thanks for your contribution!
> 
> unfortunately this is way too niche, sorry

For the record, a lot of us who would use this plugin see your reply as pure bigotry. I know in a previous response it was mentioned that its not common in the servers that you as developers are in- That may be true, but that's an extremely selfcentered point of view. I highly implore you to reconsider.

2025-01-04 23:07 UTC, lewisakura commented
@c45513v Please read #3058 with an updated comment, and please note that we do not accept plugins that only work with specific bots under the latest [plugin rules](https://github.com/Vendicated/Vencord/blob/main/CONTRIBUTING.md#plugin-rules).