fix badges for simplified profiles
Vendicated/Vencord pull request #2561
Opened 2024-06-07 17:54 UTC by Masterjoona

makes badges support the new simplified profiles

2024-06-07 18:09 UTC, MrDiamondDog requested changes

2024-06-07 18:09 UTC, MrDiamondDog commented on src/plugins/_api/badges/index.tsx
> +            find: "_.QuestContent.QUEST_BADGE",
The _ in this find is a variable so this find would break very often

2024-06-07 18:16 UTC, Vendicated commented on src/plugins/_api/badges/index.tsx
> +            ]
why do these two patches need to be separate? they can most likely be merged into one

2024-06-07 18:19 UTC, Vendicated commented on src/plugins/_api/badges/index.tsx
> +            ]
it is very dangerous to have one replacement declare a variable and another replacement reference it. if the first replacement breaks but the second one still works, this essentially guarantees a crash since you're referencing an undeclared variable

try to avoid doing that at all cost. if you absolutely must, you can use `group: true` on the patch to mark its replacements to be one group, which makes Vencord only apply them if all work!

2024-06-07 19:05 UTC, Masterjoona commented on src/plugins/_api/badges/index.tsx
> +            ]
Oops, i was testing around, where i had the unshift here too, what need that variable also

2024-06-07 19:11 UTC, Masterjoona commented
From what I gathered, you need to pass it somehow to the another component.
I guess i could throw the user object to badges array and then get it and remove it, which might be more safe? Idk

2024-06-08 03:41 UTC, Vendicated commented
thanks a lot, but superseded by https://github.com/Vendicated/Vencord/commit/65970618d89d4c7383fc88dde8380423e67cd5e5, which does this cleaner, without needing to pass any props / variables around patches

2024-06-08 03:41 UTC, closed without merging