feat(plugin): OpenMoreConnections
Vendicated/Vencord pull request #2642
Opened 2024-06-30 03:06 UTC by coopeeo

This plugin adds an open profile button for connections that don't have it in the native Discord client.
I also edited the ShowConnections plugin so it is supported with my plugin.

2024-06-30 03:16 UTC, Sqaaakoi reviewed
I think you should patch where these connections are fetched from, if possible. This would make the plugin work with ShowConnections without having to edit it directly

2024-06-30 03:16 UTC, Sqaaakoi commented on src/plugins/openMoreConnections/index.ts
> +                return `https://www.xbox.com/en-US/play/user/${con.name}`;
Remove the `en-US/`

2024-06-30 03:16 UTC, Sqaaakoi commented on src/plugins/showConnections/index.tsx
> +    var url = platform.getPlatformUserUrl?.(connection);
Never use `var` in modern JS projects; use `let` instead, as it is block scoped instead of function scoped, which generally makes more sense to read, even though they effectively do the same thing here

2024-06-30 03:22 UTC, coopeeo commented on src/plugins/openMoreConnections/index.ts
> +                return `https://www.xbox.com/en-US/play/user/${con.name}`;
whoops, i'm so smart

2024-06-30 04:59 UTC, coopeeo commented on src/plugins/showConnections/index.tsx
> +    var url = platform.getPlatformUserUrl?.(connection);
instead I used a patch only approach in my plugin instead of editing others now.

2024-06-30 10:40 UTC, schoeneBiene commented on src/plugins/openMoreConnections/README.md
> +## Planned Platforms
Why not implement PSN in this PR?

2024-06-30 10:40 UTC, schoeneBiene commented on src/plugins/openMoreConnections/index.ts
> +    description: "Adds the Open Profile button to connections that don't natively have it in the regular Discord client. Supported Platforms: Xbox, and Roblox. Planned Platforms: PSN. Platforms that
Why do you need information on unsupported platforms in the description?

2024-06-30 11:19 UTC, nin0-dev commented on src/plugins/openMoreConnections/index.ts
> +    description: "Adds the Open Profile button to connections that don't natively have it in the regular Discord client. Supported Platforms: Xbox, and Roblox. Planned Platforms: PSN. Platforms that
true, this could maybe be replaced by a settingsAboutComponent where you list supported/planned/unsupported, and add "Check plugin settings to view supported platforms"

2024-06-30 12:36 UTC, Scyye commented
I think the name could be improved on. not sure how, but "OpenMoreConnections" doesnt easily imply what it does.

2024-06-30 12:47 UTC, verticalsync commented
> I think the name could be improved on. not sure how, but "OpenMoreConnections" doesnt easily imply what it does.

what about something like ExtraConnectLinks

2024-06-30 16:54 UTC, coopeeo commented
> I think the name could be improved on. not sure how, but "OpenMoreConnections" doesnt easily imply what it does.

i agree i just couldn't come up with something else

2024-06-30 16:54 UTC, coopeeo commented
> > I think the name could be improved on. not sure how, but "OpenMoreConnections" doesnt easily imply what it does.
> 
> what about something like ExtraConnectionLinks.

sure that is a good one

2024-06-30 17:03 UTC, coopeeo commented on src/plugins/openMoreConnections/index.ts
> +    description: "Adds the Open Profile button to connections that don't natively have it in the regular Discord client. Supported Platforms: Xbox, and Roblox. Planned Platforms: PSN. Platforms that
I was thinking that not a lot of people see the readme, since that's only on the website, but yea sure I can do that.

2024-06-30 17:13 UTC, coopeeo commented on src/plugins/openMoreConnections/README.md
> +## Planned Platforms
I was really tired but, I am going to make it open a data uri because the service for PSN profiles I will be using is a third party service called psnprofiles.com. But the website will show a not found error for accounts that have not been looked at yet. So I am going to create a data uri that requests psnprofiles.com to load the profile automatically and waits for psnprofiles.com to be done loading the profile.

2024-07-02 18:56 UTC, coopeeo commented on src/plugins/openMoreConnections/README.md
> +## Planned Platforms
actually psn support isn't coming

2024-07-02 19:14 UTC, coopeeo commented on src/plugins/openMoreConnections/index.ts
> +    description: "Adds the Open Profile button to connections that don't natively have it in the regular Discord client. Supported Platforms: Xbox, and Roblox. Planned Platforms: PSN. Platforms that
removed from the description, now it's only in the readme.md file.

2024-07-04 03:13 UTC, coopeeo commented
reminder to self (because i don't feel like doing this rn) remember to update description to: "Allows you to open more connections in browser!"

2024-07-06 16:54 UTC, Scyye commented on src/plugins/extraConnectionLinks/README.md
> +* Epic Games (Nothing made by Epic Games to view profiles online)
> Nothing made by [..] to view profiles online

what does this mean

2024-07-06 17:07 UTC, nin0-dev commented on src/plugins/extraConnectionLinks/README.md
> +* Epic Games (Nothing made by Epic Games to view profiles online)
means you can't open a profile url in the browser

eg. league of legends profiles, vs spotify, that can be opened in a browser

2024-07-06 19:13 UTC, coopeeo commented
Vee, I think this is ready for review.

2024-07-13 15:56 UTC, coopeeo commented
@Vendicated, or @Nuckyz may you please do a review of ExtraConnectionLinks when you guys have time?

2024-07-13 16:10 UTC, coopeeo commented
actually nvm i just found out there is way you can view epic games profiles! (Thanks Guilded!)

2024-07-23 20:45 UTC, coopeeo commented
oki doki i think the mod is done, and ready for submission!

2024-07-23 23:14 UTC, Scyye commented on src/plugins/extraConnectionLinks/index.ts
> +  * ! facebook (don't have discord access token for facebook connection)
What does this mean?

2024-07-23 23:14 UTC, Scyye commented on src/plugins/extraConnectionLinks/index.ts
> +enum contypes {
I'd rename this to connectionTypes

2024-07-23 23:14 UTC, Scyye commented on src/plugins/extraConnectionLinks/index.ts
> +    patches: makePatches(),
Is there a reason to not just put the function here? rather than calling it?

2024-07-24 15:02 UTC, coopeeo commented on src/plugins/extraConnectionLinks/index.ts
> +  * ! facebook (don't have discord access token for facebook connection)
like the whole part? or a certain part?
that was put their before the read me and is basically the things on why i can't do certain things and stuff

2024-07-24 15:02 UTC, coopeeo commented on src/plugins/extraConnectionLinks/index.ts
> +enum contypes {
k

2024-07-24 15:02 UTC, coopeeo commented on src/plugins/extraConnectionLinks/index.ts
> +    patches: makePatches(),
idk me being me ig.

2024-07-24 17:48 UTC, coopeeo commented
ARE YOU FUCKING KIDDING ME, RENAMING A BRANCH DOES THAT? WTF

2024-07-24 17:49 UTC, coopeeo commented
wtf github

2024-08-05 03:25 UTC, Scyye reviewed
nitpicky, but you requested a review so you got it.

2024-08-05 03:25 UTC, Scyye commented on src/plugins/extraConnectionLinks/README.md
> +## Before and After
I personally dont think its needed to have a title thats just 2 subtitles concatenated 
```suggestion

```

2024-08-05 03:25 UTC, Scyye commented on src/plugins/extraConnectionLinks/README.md
> +* None as of currently
If theres none, no need to specify that.
```suggestion
```

2024-08-05 03:25 UTC, Scyye commented on src/plugins/extraConnectionLinks/index.ts
> + **/
This is located in the readme, theres no technical issue with having it here too, just seems redundant from a readability perspective.
```suggestion
```

2024-08-05 03:25 UTC, Scyye commented on src/plugins/extraConnectionLinks/index.ts
> +const serviceNames = {
Why not just go based off the names of the types themselves?
and rename Epic to EpicGames;?

2024-08-05 03:25 UTC, Scyye commented on src/plugins/extraConnectionLinks/index.ts
> +        .filter(v => isNaN(Number(v)))
what?
whats this doing?

2024-08-05 17:24 UTC, coopeeo commented on src/plugins/extraConnectionLinks/index.ts
> +const serviceNames = {
It's shorter and I like it better lol that's all

2024-08-05 17:31 UTC, coopeeo commented on src/plugins/extraConnectionLinks/index.ts
> +        .filter(v => isNaN(Number(v)))
because enums in typescript like to do a number thingy, meaning the Object.keys will return something like
```json
[
	0,
	"Xbox",
	1,
	"PSN",
	etc...
]
```

2024-08-05 17:33 UTC, coopeeo commented on src/plugins/extraConnectionLinks/index.ts
> + **/
yea i can delete this as this was basically just for tracking my progress as i went along doing stuff

2024-08-06 17:27 UTC, Scyye commented
I gave you my review already lol

2024-08-06 17:40 UTC, schoeneBiene commented on src/plugins/extraConnectionLinks/README.md
> +* Amazon Music (nothing references to the actual amazon music user id in discord. I also went on the website for the first time and it decided to give me unlimited for free, then right after upgraded
this really isn't needed
```suggestion
* Amazon Music (nothing references to the actual amazon music user id in discord)
```

2024-08-06 17:41 UTC, Scyye commented on src/plugins/extraConnectionLinks/README.md
> +* Amazon Music (nothing references to the actual amazon music user id in discord. I also went on the website for the first time and it decided to give me unlimited for free, then right after upgraded
is it really that big of a deal lol

its kinda funny

2024-08-06 18:16 UTC, coopeeo commented on src/plugins/extraConnectionLinks/README.md
> +* Amazon Music (nothing references to the actual amazon music user id in discord. I also went on the website for the first time and it decided to give me unlimited for free, then right after upgraded
> Quote reply
> Reference in n

it's very needed

2024-09-02 05:07 UTC, Nuckyz requested changes
btw the roblox one is openable by default now

2024-09-02 05:07 UTC, Nuckyz commented on src/plugins/extraConnectionLinks/index.ts
> +
```suggestion
```

2024-09-02 05:07 UTC, Nuckyz commented on src/plugins/extraConnectionLinks/index.ts
> + * The "id" is an identifier that normal users don't see, it will usually be an user id (, for example Roblox has user ids, and discord stores that user id in the id field of the connection).
```suggestion
 * The "name" is what shows up when viewing a connection on a discord profile.
 * The "id" is the identifier of the account connected, the type depends on the service connected.
```

2024-09-02 05:07 UTC, Nuckyz commented on src/plugins/extraConnectionLinks/index.ts
> +});
```suggestion
        .map(key => {
            const connectionTypeSelected = connectionTypes[key as keyof typeof connectionTypes];
            return {
                find: "getPlatformUserUrl:",
                replacement: {
                    match: new RegExp(`(r`),
                    replace: `, getPlatformUserUrl:e=>{let {name, id} = e; return \`${uris[connectionTypeSelected]}\`;}`
                }
            };
        }),
});
```
Instead of mapping into multiple finds, map into the replacement of a single find

2024-09-07 17:07 UTC, coopeeo commented on src/plugins/extraConnectionLinks/index.ts
> +});
how would I do a single find with this?

2024-09-07 17:21 UTC, coopeeo commented on src/plugins/extraConnectionLinks/index.ts
> +});
i mean i think its simple already.

2024-09-07 18:03 UTC, Masterjoona commented on src/plugins/extraConnectionLinks/index.ts
> +});
You're overcomplicating it, you can just do
```ts
const extraConnections = [
    {
        name: "Xbox",
        input: "name",
        link: "https://www.xbox.com/play/user/"
    },
    {
        name: "Epic Games",
        input: "id",
        link: "https://store.epicgames.com/u/"
    },
];
/* ... */
patches: [
        {
            find: "getPlatformUserUrl:",
            replacement: extraConnections.map(connection => {
                return {
                    match: new RegExp(`name:"${connection.name}",`),
                    replace: `$&getPlatformUserUrl:e=>{return '${connection.link}' + e.${connection.input};},`
                };
            }
            )
        },
    ],
```

2024-09-07 18:04 UTC, coopeeo commented on src/plugins/extraConnectionLinks/index.ts
> +});
i might do something like this, i will remake the thingy again ya hoo!

2024-09-08 13:46 UTC, Scyye commented on src/plugins/extraConnectionLinks/README.md
>  * Crunchyroll (can't view other peoples profiles nor your own profile)
```suggestion
* Crunchyroll (Can't view profiles)
```

2024-09-08 13:46 UTC, Scyye commented on src/plugins/extraConnectionLinks/index.ts
>                      replace: `, getPlatformUserUrl:e=>{let {name, id} = e; return \`${uris[connectionTypeSelected]}\`;}`
i could be wrong but i dont think youre supposed to put spaces where you dont have to.
again, could be wrong, so double check that.

2024-09-12 06:34 UTC, Obsidianninja11 commented on src/plugins/extraConnectionLinks/README.md
> +* Epic Games
Shouldn't Roblox be under here as well?

2024-09-12 13:32 UTC, coopeeo commented on src/plugins/extraConnectionLinks/README.md
> +* Epic Games
I'm removing it, and I have a version on my PC but I'm at school rn lol, I might ssh into my PC later.

2024-09-12 13:33 UTC, coopeeo commented on src/plugins/extraConnectionLinks/README.md
> +* Epic Games
the reason it is removed is because of its native to the discord client now lol

2024-12-15 17:16 UTC, coopeeo commented
God damn it's been a while. but imma try to do the fixes yeppi

2025-12-11 00:35 UTC, coopeeo commented
Hello people I am back :3

2025-12-11 20:02 UTC, auggeeo commented
me need reviews :3  I want I need improvement

2025-12-11 20:03 UTC, coopeeo commented
OHHHHHHHHHHHHHHHH DOES (r MEAN REDO LMAO THAT JUST CLICKED

2026-05-31 18:21 UTC, auggeeo commented
okay finally made it a single find please review once again hopefully this can be included

2026-07-26 17:13 UTC, closed without merging