feat(plugin): ShikiCodeblocks
Vendicated/Vencord pull request #267
Opened 2022-11-28 09:52 UTC by Vap0r1ze

some shiki codeblock stuff

2022-11-28 10:46 UTC, Vap0r1ze commented
Quick overview of out of scope changes:
  - added an optional `paths` param to [`useSettings`](https://github.com/Vendicated/Vencord/pull/267/files#diff-3c8501547f6f6c951239aeed2abcf2e47cae318a486be0154503b038bd0410b8) so u can subscribe to specific keys
  - [new csp parsing](https://github.com/Vendicated/Vencord/pull/267/files#diff-9a380b1e6cc28b9e0f9351e48ad74ec7ee7bff0388ec3bdaaaf2679848aa6cd3)
  - add [module type](https://github.com/Vendicated/Vencord/pull/267/files#diff-884a2fb17edc1f2ad8e6b5337ea995514b10644c35559cb5b6315f4ea8d589ff) for `.txt` files (esbuild does this by default)
  - general [url](https://github.com/Vendicated/Vencord/pull/267/files#diff-69fc08f3a6190fbb9be394c676bea64aad03c350e4729ede32428f71c569cbf5) and [text](https://github.com/Vendicated/Vencord/pull/267/files#diff-712ffc191bdeefcad981f5da7c2bb1550371e10c6854ed1b624ec4f415f7686e) utils
  - added [`hljs`](https://github.com/Vendicated/Vencord/pull/267/files#diff-d81e8c10cd7caf6ba37902248179ce745966ef5072095a0cbc9eb31c7075642c) to webpack common

2022-11-28 11:48 UTC, Vap0r1ze commented
yea so
![image](https://user-images.githubusercontent.com/20448879/204270445-3ad28ac3-b931-4d39-9759-f56f6010df50.png)

2022-11-29 11:26 UTC, Vap0r1ze commented
New out of scope change:
  - added support for a "--sourcemap" flag in the [`buildWeb`](https://github.com/Vendicated/Vencord/blob/4fe8ac993d454c0cfb6983c62849df4c9ad1d58a/scripts/build/buildWeb.mjs#L59) script

2022-11-29 12:00 UTC, Vendicated commented
> New out of scope change:
> 
> * added support for a "--sourcemap" flag in the [`buildWeb`](https://github.com/Vendicated/Vencord/blob/4fe8ac993d454c0cfb6983c62849df4c9ad1d58a/scripts/build/buildWeb.mjs#L59) script

you can just run with the --watch flag to achieve the same result plus no minification

2022-11-29 12:10 UTC, ArjixWasTaken requested changes
plz

2022-11-29 12:10 UTC, ArjixWasTaken commented on src/plugins/shikiCodeblocks/api/languages.ts
> +    if (Object.hasOwn(languages, idOrAlias)) return languages[idOrAlias];
```suggestion
    if (Object.hasOwnProperty.call(languages, idOrAlias)) return languages[idOrAlias];
```

2022-11-30 16:35 UTC, Vendicated commented on src/modules.d.ts
> +    const plugins: Record<string, import("./utils/types").Plugin>;
huh? is the old one broken?

2022-11-30 16:53 UTC, Vendicated submitted a review, later dismissed
Thanks for the pr! Other than the feedback below, a bit nitpicky but could you please use interfaces instead of types (where applicable) and actual named functions over arrow function assignments for consistency?

2022-11-30 16:53 UTC, Vendicated commented on src/plugins/shikiCodeblocks/api/shiki.ts
> +        if (!themeUrl) themeUrl = themeUrls[0];
```suggestion
        themeUrl ||= themeUrls[0];
```

2022-11-30 16:53 UTC, Vendicated commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +        <tr>
these should have a key to prevent bugs https://reactjs.org/docs/lists-and-keys.html

2022-11-30 16:53 UTC, Vendicated commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +                        <span
same as below, add a key please

2022-11-30 16:53 UTC, Vendicated commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +                .map(line => <span dangerouslySetInnerHTML={{ __html: line }} />);
also needs a key, also i really really hate the dangerouslySetInnerHTML is there no other way?

2022-11-30 16:53 UTC, Vendicated commented on src/plugins/shikiCodeblocks/components/Highlighter.tsx
> +    const themeBase: ThemeBase = React.useMemo(() => ({
could probably not memo this (unless object equality is needed) cause recomputing this is probably cheaper than the memo logic

2022-11-30 16:53 UTC, Vendicated commented on src/plugins/shikiCodeblocks/hooks/useAsyncMemo.ts
> +export function useAsyncMemo<V>(factory: () => Promise<V>, deps: unknown[], initialValue: V) {
you can use the useAwaiter utility instead! (well it doesn't have the deps argument but feel free to add it

2022-11-30 16:53 UTC, Vendicated commented on src/plugins/shikiCodeblocks/hooks/useIntersection.ts
> +};
cool utilities, maybe add these to the general utils? At least quickReply can make use of the top function

2022-11-30 16:53 UTC, Vendicated commented on src/plugins/shikiCodeblocks/index.ts
> +devIconStyle.innerHTML = "@import url('https://cdn.jsdelivr.net/gh/devicons/devicon@v2.10.1/devicon.min.css');";
you should move these into the start method so we don't create pointless style elements when the plugin is off

2022-11-30 16:53 UTC, Vendicated commented on src/utils/text.ts
> +export const fromTitle = (text: string) => text.toLowerCase().split(" ");
these names don't really say much, maybe wordsFromTitle or titleToWords or similar would make more sense?

2022-11-30 16:53 UTC, Vendicated commented on src/utils/text.ts
> +export const fromConst = (text: string) => text.toLowerCase().split("_");
const? this is snake_case

2022-11-30 19:21 UTC, ArjixWasTaken commented
Just so you know, it appears that discord already has lodash bundled, so you can just do
![image](https://user-images.githubusercontent.com/53124886/204888848-3872e2dc-db15-45a6-a913-7e38b9bff254.png)

Instead of the ugly `Object.prototype.hasOwnProperty.call({cat: 5}, "cat");`

#234 adds the types and declares that it is globally accessible (for typescript to not complain)

2022-11-30 19:26 UTC, Vendicated commented
that'd still be pretty ugly with `window._.isIn`. The cleanest solution would be to polyfill Object.hasOwn, I personally wouldn't mind adding super simple polyfills like this one

2022-11-30 19:27 UTC, ArjixWasTaken commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +        <tr>
how would it prevent bugs? keys are only for rendering optimization...
instead of re-rendering the entire list of elements, it just re-renders the specific items

2022-11-30 19:30 UTC, ArjixWasTaken commented on src/utils/text.ts
> +export const fromTitle = (text: string) => text.toLowerCase().split(" ");
`titleToWords` feels wrong, maybe `titleCaseToWords`, but that is too long

2022-11-30 19:31 UTC, Vendicated commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +        <tr>
this is not true. If you omit keys, React has no way of knowing which element exactly is which, which will in the worst case lead to mixed up states (as was the case in the old plugin page where if you searched something the switch state got messed up). if it works as expected, you were simply lucky. It also technically shouldn't matter if the rendered items are stable and never change but its still best practice to add them anyway

2022-11-30 19:36 UTC, ArjixWasTaken commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +        <tr>
state? what state? they don't have individual state, unless you are referring to smth else

2022-11-30 19:38 UTC, ArjixWasTaken commented
> that'd still be pretty ugly with `window._.isIn`.

That is up for debate tbh

2022-11-30 19:39 UTC, MeguminSama commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +        <tr>
If the values in `lines` ever changes, the contents of the elements returned from the map can get mixed up badly. In this case "state" isn't referring to things like useState, but just the state of the components in general (props, children, etc)

2022-11-30 19:46 UTC, ArjixWasTaken commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +        <tr>
from what I see, lines is assigned to only once during the function's lifetime
(well, the try/catch could count as two assignments)

the component would fully re-render if the lines change

PS: In case I am THAT blind, please do point it out

2022-11-30 21:19 UTC, Vap0r1ze commented on src/modules.d.ts
> +    const plugins: Record<string, import("./utils/types").Plugin>;
not intentional, prob some git merge and eslint magic, will fix

2022-11-30 22:58 UTC, Vap0r1ze commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +                .map(line => <span dangerouslySetInnerHTML={{ __html: line }} />);
when i made the first iteration of this plugin like 2y ago discord's hljs only had an html output, i'll see if it has an AST output in its current state

2022-11-30 23:05 UTC, Vendicated commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +                .map(line => <span dangerouslySetInnerHTML={{ __html: line }} />);
.highlight("js", "console.log('owo')", true).emitter.rootNode.children returns an AST like structure but you'd have to format that yourself so probably not really usable. It's fine to use dangerouslySetInnerHTML since hljs is safe but it's just a bit terrifying to look at

2022-12-01 00:11 UTC, Vap0r1ze commented on src/plugins/shikiCodeblocks/components/Code.tsx
> +                .map(line => <span dangerouslySetInnerHTML={{ __html: line }} />);
afaict there is only an html output

2022-12-01 02:50 UTC, Vap0r1ze commented
Let me know if I missed anything in [`0cfa569`](https://github.com/Vendicated/Vencord/pull/267/commits/0cfa56985f388de446cbdb3a6797942bb2bb9254)

2022-12-01 03:02 UTC, Vendicated commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +    const dirtyRefetch = () => setRefetchCount(refetchCount + 1);
pretty sure this won't work? even if the state changes, useAwaiter won't rerun its body. Did you forget to add the refetch count as dependency?

2022-12-01 03:02 UTC, Vap0r1ze commented on src/plugins/reviewDB/components/ReviewsView.tsx
> +    const dirtyRefetch = () => setRefetchCount(refetchCount + 1);
ah yep

2022-12-01 03:09 UTC, Vendicated commented on src/plugins/shikiCodeblocks/index.ts
> +                },
what exactly do these do?

2022-12-01 03:09 UTC, Vendicated commented on src/plugins/shikiCodeblocks/index.ts
> +            description: "How to show devicons on codeblocks",
```suggestion
            description: "How to show language icons on codeblocks",
```
(?) I'm not sure what devicons stands for

2022-12-01 03:10 UTC, Vap0r1ze commented on src/plugins/shikiCodeblocks/index.ts
> +            description: "How to show devicons on codeblocks",
its the library i use for lang icons, this is prob better since its user-facing text

2022-12-01 03:11 UTC, Vendicated commented on src/utils/misc.tsx
> +    onError?: (e: unknown) => unknown,
```suggestion
    onError?(e: any): void,
```
unknown is absolute pain to work with

2022-12-01 03:11 UTC, Vap0r1ze commented on src/utils/misc.tsx
> +    onError?: (e: unknown) => unknown,
this was ur code lol

2022-12-01 03:13 UTC, Vendicated commented on src/utils/misc.tsx
> +    onError?: (e: unknown) => unknown,
lol really

2022-12-01 03:17 UTC, Vap0r1ze commented on src/plugins/shikiCodeblocks/index.ts
> +                },
Decides when to use hljs highlighter rather than shiki
`Primary` uses hljs if the language exists in hljs, otherwise use shiki
`Secondary` uses shiki if the language exists in shiki, otherwise use hljs

2022-12-01 03:19 UTC, Vendicated commented on src/plugins/shikiCodeblocks/index.ts
> +                },
Always is the same as disabling the plugin? If so, why even have that option

Would be nice to change the labels to a more descriptive text so it's easier to Understand. If it looks weird because too much text you could use the settingsAboutComponent prop

2022-12-01 03:21 UTC, Vap0r1ze commented on src/plugins/shikiCodeblocks/index.ts
> +                },
`Always` still has the shiki theme background and the copy button, in the future i plan on adding a language switcher too

2022-12-01 03:21 UTC, Vap0r1ze commented on src/plugins/shikiCodeblocks/index.ts
> +                },
and also line numbers

2022-12-01 03:39 UTC, Vap0r1ze commented
[`39e53c5`](https://github.com/Vendicated/Vencord/pull/267/commits/39e53c5d4f9d95c1ac965549df57f0e3700b20ba)

2022-12-01 03:46 UTC, Vap0r1ze commented
Done and merged

2022-12-01 21:21 UTC, Vendicated commented
uhhh 
![image](https://user-images.githubusercontent.com/45497981/205161708-40012c0d-1210-4b08-9a31-5b97543f14b8.png)

![image](https://user-images.githubusercontent.com/45497981/205161676-640995b4-e7d7-4664-a373-eb0fd73530cc.png)

2022-12-01 21:22 UTC, Vendicated commented
This crashed Discord btw - To prevent crashes please wrap components in an ErrorBoundary

2022-12-02 13:54 UTC, Vendicated approved these changes

2022-12-02 15:43 UTC, merged