Port volume booster to web/vesktop
Vendicated/Vencord pull request #2730
Opened 2024-07-27 03:01 UTC by sadan4

resolves: #1944 
ports volume booster to web/vesktop

VERY ROUGH RN, will polish soon

2024-07-27 09:00 UTC, Sqaaakoi reviewed
works but idk if it really is 200% volume sounds like the "fix" you told me you made where it was 2x the volume it was supposed to be is actually what is intended

tl;dr: i think your fix broke it more

2024-07-28 21:29 UTC, Sqaaakoi commented
> It does raise the volume but it doesnt _seem_ to be ex: 500% louder.

yeah this was my experience too

> also it basically functions as a fake deafen at the moment.,...

we cannot ship that, theres a good reason why fake deafen is explicitly not a feature, regardless of that I think I'd still like to have a "I want my friends to be quiet for a bit" button

2024-07-29 00:02 UTC, sadan4 commented
> also it basically functions as a fake deafen at the moment.,...
somehow I didn't notice this, thanks!

2024-08-02 10:57 UTC, Vendicated commented on src/plugins/volumeBooster/index.ts
> +};
```suggestion
const PerceptualVolume = {
    amplitudeToPerceptual: findByCodeLazy("6+1:"),
    perceptualToAmplitude: findByCodeLazy("50-50"),
};
```

2024-08-02 14:34 UTC, sadan4 commented on src/plugins/volumeBooster/index.ts
> +};
done

2024-08-02 14:44 UTC, Nuckyz commented
You are doing two webpack searches yet only one is used, remove the other one

also the code style doesn't match the rest of project, mainly the spacing in if conditions

2024-08-02 15:49 UTC, sadan4 commented on src/plugins/volumeBooster/index.ts
> +                    match: /volume=t.*?;/,
it is matching the t in `this`

2024-08-02 16:16 UTC, sadan4 commented
> You are doing two webpack searches yet only one is used, remove the other one
> 
> also the code style doesn't match the rest of project, mainly the spacing in if conditions

I may be a tad stupid, but what are/were you referring to by the spacing in if conditions

2024-08-02 18:43 UTC, Vendicated commented on src/plugins/volumeBooster/index.ts
> +                    match: /volume=t.*?;/,
```suggestion
                    match: /\.volume=this._volume/100;/,
```

2024-08-02 18:57 UTC, sadan4 commented on src/plugins/volumeBooster/index.ts
> +                    match: /volume=t.*?;/,
fixed

2024-08-03 09:08 UTC, Vendicated reviewed
like nuckyz said, follow the code style

2024-08-03 09:08 UTC, Vendicated commented on src/plugins/volumeBooster/index.ts
> +        if(data.stream.getAudioTracks().length === 0) return;
```suggestion
        if (data.stream.getAudioTracks().length === 0) return;
```

2024-08-03 09:08 UTC, Vendicated commented on src/plugins/volumeBooster/index.ts
> +        if(!data.gainNode){
```suggestion
        if (!data.gainNode){
```

2024-08-03 09:08 UTC, Vendicated commented on src/plugins/volumeBooster/index.ts
> +    patchVolume(data: StreamData){
```suggestion
    patchVolume(data: StreamData) {
```

2024-08-03 09:08 UTC, Vendicated commented on src/plugins/volumeBooster/index.ts
> +                // to pervent the cap of 100
```suggestion
                // remove the cap of 100%
```

2024-08-03 09:08 UTC, Vendicated commented on src/plugins/volumeBooster/index.ts
> +interface StreamData{
```suggestion
interface StreamData {
```

2024-08-03 22:57 UTC, Nuckyz requested changes

2024-08-03 22:57 UTC, Nuckyz commented on src/plugins/volumeBooster/index.ts
> +    },
```suggestion
    }
```

2024-08-03 22:57 UTC, Nuckyz commented on src/plugins/volumeBooster/index.ts
> +};
```suggestion
const perceptualToAmplitude = findByCodeLazy("50-50");

```

2024-08-03 22:57 UTC, Nuckyz commented on src/plugins/volumeBooster/index.ts
> +    patchVolume(data: StreamData) {
```suggestion

    patchVolume(data: StreamData) {
```

2024-08-03 22:57 UTC, Nuckyz requested changes

2024-08-03 22:57 UTC, Nuckyz commented on src/plugins/volumeBooster/index.ts
> +        data.gainNode.gain.value = data._mute ? 0 : PerceptualVolume.amplitudeToPerceptual(data._volume)/100;
```suggestion
        data.gainNode.gain.value = data._mute ? 0 : amplitudeToPerceptual(data._volume)/100;
```

2024-08-04 00:08 UTC, sadan4 commented on src/plugins/volumeBooster/index.ts
> +};
I'll push the fixes to your changes when I push my fix for low volumes

2024-08-15 13:07 UTC, Vendicated commented
i think it would be a good idea to extract this into a separate plugin like WebExtraVolume and make it enabled by default. That way more users can profit from it and Vesktop users will get the expected stock equivalent behaviour

2024-08-15 14:10 UTC, sadan4 commented
> i think it would be a good idea to extract this into a separate plugin like WebExtraVolume and make it enabled by default. That way more users can profit from it and Vesktop users will get the expected stock equivalent behaviour

It depends on the patches already introduced by Volume Booster.

2024-08-30 16:39 UTC, MaxBosse commented
Is there anything I can help with to get this merged? :) Would love to have this feature on web/vesktop

2024-08-30 23:39 UTC, sadan4 commented
This should be ready as i fixed the stock discord issue that made it glitch out at low volumes

2024-09-01 03:08 UTC, merged

2024-09-01 03:10 UTC, Nuckyz commented
Thank you!

2024-09-01 15:28 UTC, sadan4 commented
Apparently this isn't working on the vesktop, which is weird because that's where I tested it. I have family over today, but I will work on it tomorrow if nobody else fixes it