new plugin: fullUserInChatbox
Vendicated/Vencord pull request #2766
Opened 2024-08-07 04:56 UTC by sadan4

adds the full user mention component to the chatbox, this has a good amount of benefits, which ill fill out later

2024-08-07 05:21 UTC, Sqaaakoi commented on src/plugins/fullUserInChatbox/README.md
you should probably remove this file, it provides no use in upstream

2024-08-07 05:21 UTC, Sqaaakoi commented on src/plugins/fullUserInChatbox/index.tsx
> +    description: "",
add a description (you probably know to do this already)

2024-08-07 05:21 UTC, Sqaaakoi commented on src/plugins/fullUserInChatbox/index.tsx
> +            className: "mention",
seems very generic

2024-08-07 05:23 UTC, sadan4 commented on src/plugins/fullUserInChatbox/README.md
im going to change it to a normal readme, that's why this is a draft

2024-08-07 05:24 UTC, sadan4 commented on src/plugins/fullUserInChatbox/index.tsx
> +            className: "mention",
im aware, thats what discord passes from what I can see, leaving it because its generic, will look into it more later

2024-08-07 05:31 UTC, sadan4 commented
i think the name on this also needs some work

2024-08-07 14:42 UTC, Vendicated commented on src/plugins/fullUserInChatbox/index.tsx
> +export default definePlugin({
```suggestion
import { Devs } from "@utils/constants";
import definePlugin from "@utils/types";
import { findByCodeLazy } from "@webpack";

const normalMessageComponent = findByCodeLazy(".USER_MENTION)");

export default definePlugin({
```

2024-08-12 16:29 UTC, sadan4 commented
The main benefits of this plugin are that it adds the full context menu for users in the chat box,  
it also adds mention avatars into the chat box, but that could have been done by the plugin itself and is not important

![image](https://github.com/user-attachments/assets/de7f9b03-64fa-4e51-9e32-159905569a22)

2024-08-12 17:01 UTC, ImLvna commented
might be better as a general "Better Context Menus" plugin that does this in more than just the chatbox

2024-08-12 17:03 UTC, sadan4 commented on src/plugins/fullUserInChatbox/index.tsx
> +            className: "mention",
just got around to this, it looks like discord has the value hardcoded 

![image](https://github.com/user-attachments/assets/4d04bb6d-c590-47c2-8505-e0eb98638628)

2024-08-12 17:13 UTC, Sqaaakoi commented
> might be better as a general "Better Context Menus" plugin that does this in more than just the chatbox

I feel like this does enough that isn't just changing how context menus work with this that it doesn't seem appropriate to classify this as a context menu plugin

2024-12-22 04:59 UTC, Nuckyz requested changes

2024-12-22 04:59 UTC, Nuckyz commented on src/plugins/fullUserInChatbox/index.tsx
> +const NormalMessageComponent = findComponentByCodeLazy(".USER_MENTION)");
```suggestion
const UserMentionComponent = findComponentByCodeLazy(".USER_MENTION)");
```

2024-12-22 04:59 UTC, Nuckyz commented on src/plugins/fullUserInChatbox/index.tsx
> +    patchChatboxMention(props: any) {
```suggestion
    UserMentionComponent(props: any) {
```

Also wrab in ErrorBoundary

2024-12-22 04:59 UTC, Nuckyz commented on src/plugins/fullUserInChatbox/index.tsx
> +            inlinePreview={undefined}
```suggestion
```

If it's undefined you can just take it off

2024-12-22 05:38 UTC, Nuckyz requested changes

2024-12-22 05:38 UTC, Nuckyz commented on src/plugins/fullUserInChatbox/index.tsx
> +    description: "Puts the full user mention object in the chatbox",
```suggestion
    description: "Makes the user mention in the chatbox have more functionalities, like right clicking",
```

2024-12-22 05:38 UTC, Nuckyz commented on src/plugins/fullUserInChatbox/README.md
> +# FullUserInChatbox
```suggestion
# Full User In Chatbox
```

2024-12-30 05:07 UTC, merged