feat(Plugin): CopyFileContents
Vendicated/Vencord pull request #2790
Opened 2024-08-18 00:37 UTC by Obsidianninja11

Adds a button to copy the contents of a text file (even if the text isn't in the tiny preview).
After clicking, the copy icon will turn into a checkmark (like in large codeblocks), and the text will be copied to your clipboard.
For files over 50kb (50 thousand characters) that don't fully show in the "View whole file" preview, it shows "File too large to copy". I made a version that fetches files that are large, but I don't think that's necessary for 99% of users, and it could lead to problems if a user tries to copy a huge file.
This pr also updates the copy icon in `components\icons.tsx`, as the icon that was in there is long outdated.

<details><summary>Images</summary>

![image](https://github.com/user-attachments/assets/57284d64-1423-4915-890e-daf801825eb2)
![image](https://github.com/user-attachments/assets/f288d256-ee5c-4cdf-8409-f267a988e8b8)

A file containing 51kb that is unable to be copied (the first 683 numbers in the fibonacci sequence in this example).
![image](https://github.com/user-attachments/assets/2fb53a12-60f4-4e47-b796-9c38ef52a81d)
</details>

2024-08-26 02:24 UTC, Scyye reviewed
Im tired and youre asking for a review, so i gave it to ya lol
just verify everything is accurate before changing stuff.

2024-08-26 02:24 UTC, Scyye commented on src/plugins/CopyFileContents/index.tsx
> +                replace: "$&$self.AddCopyButton({ fileContents: $1, bytesLeft: $2 }),"
I dont think youre supposed to put spaces in replaces
```suggestion
                replace: "$&self.AddCopyButton({$1,$2}),"
```
verify that works, im not sure, and im tired

2024-08-26 02:24 UTC, Scyye commented on src/plugins/CopyFileContents/index.tsx
> +    AddCopyButton: ErrorBoundary.wrap(({ fileContents, bytesLeft }: { fileContents: string, bytesLeft: number; }) => {
shouldnt this be `addCopyButton`? 
not certain.

2024-08-26 02:24 UTC, Scyye commented on src/plugins/CopyFileContents/index.tsx
> +                        className="vc-cfc-button"
i think youre meant to use a class name factory for this.

2024-08-26 02:48 UTC, Obsidianninja11 commented on src/plugins/CopyFileContents/index.tsx
> +                        className="vc-cfc-button"
Class name factory seems to be for when there's multiple class names all prefixed by `vc-cfc-` (cfc in this case). So I don't think I am supposed to use it for this.

2024-08-26 03:02 UTC, Scyye commented on src/plugins/CopyFileContents/index.tsx
> +                        className="vc-cfc-button"
ahh, okay.

2024-08-30 11:33 UTC, Nuckyz requested changes

2024-08-30 11:33 UTC, Nuckyz commented on src/plugins/CopyFileContents/index.tsx
> +                        className="vc-cfc-button"
Since the plugin only has two classes I would hardcode with the style attribute and delete the css file

2024-08-30 11:33 UTC, Nuckyz commented on src/plugins/CopyFileContents/index.tsx
> +    ],
```suggestion
    ],
    
```

2024-08-30 11:36 UTC, Nuckyz requested changes

2024-08-30 11:36 UTC, Nuckyz commented on src/plugins/CopyFileContents/index.tsx
> +    return <svg aria-hidden="true" width="24" height="24" fill="none" viewBox="0 0 24 24">
```suggestion
    return <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
```

2024-08-30 11:39 UTC, Nuckyz commented
You never change setRecentlyCopied back to false, is that intended?

2024-08-30 11:40 UTC, Obsidianninja11 commented on src/plugins/CopyFileContents/index.tsx
> +                        className="vc-cfc-button"
:hover doesn't work in style=

2024-08-30 11:40 UTC, Nuckyz commented on src/plugins/CopyFileContents/index.tsx
> +                        className="vc-cfc-button"
right

2024-08-30 12:11 UTC, Obsidianninja11 commented
> You never change setRecentlyCopied back to false, is that intended?

Yes. That's how it works in code blocks, so I recreated it here.

2024-08-30 13:25 UTC, Scyye commented
I still feel like it should

2024-08-31 01:19 UTC, Obsidianninja11 commented
I added a toast when copying. It's currently stay as a checkmark with a toast (the first video).
I don't think the checkmark changing back is necessary because it can create some buggy behaviour, and I don't think it looks as good (second video).

https://github.com/user-attachments/assets/1acdfc0e-078c-4a00-ab57-90dfbc52b504

https://github.com/user-attachments/assets/0c488b46-5231-4f2f-af2c-c53d7c38bf0e

2024-09-01 01:53 UTC, Nuckyz commented
I fixed the buggy behavior and made the checkmark change back, it makes way more sense

2024-09-01 02:02 UTC, merged

2024-09-01 02:03 UTC, Nuckyz commented
Thank you for the new plugin!