feat(plugin) MutualGroupDMs: Add mutual groups to dm sidebar
Vendicated/Vencord pull request #2817
Opened 2024-08-31 09:04 UTC by Masterjoona

https://github.com/Vencord/plugin-requests/issues/1046

2024-09-01 02:26 UTC, Nuckyz requested changes

2024-09-01 02:26 UTC, Nuckyz commented on src/plugins/mutualGroupDMs/index.tsx
> +                        </Clickable>
Extract this to a separate component so you can re-use in the other patch too

2024-09-01 02:26 UTC, Nuckyz commented on src/plugins/mutualGroupDMs/index.tsx
> +                match: /,\i\)}\)}\)(?<=(\(0,\i\.jsx\)\(\i\.\i,{className:\i\.divider}\)).+?)/,
```suggestion
                match: /\.openUserProfileModal.+?\)}\)}\)(?<=(\(0,\i\.jsxs?\)\(\i\.\i,{className:\i\.divider}\)).+?)/,
```

2024-09-01 02:26 UTC, Nuckyz commented on src/plugins/mutualGroupDMs/index.tsx
> +        return (
```suggestion
        const mutualGDms = getMutualGroupDms(user.id);
        if (mutualGDms.length === 0) return null;
        
        const header = getMutualGDMCountText(user);
        
        return (
```

2024-09-01 02:26 UTC, Nuckyz commented on src/plugins/mutualGroupDMs/index.tsx
> +const ListStyles = findByPropsLazy("list", "divider");
Duplicate find, if you want you can grab the class from the patch

2024-09-01 10:13 UTC, Masterjoona commented
Ty nuckyz, fixed

2024-09-02 03:50 UTC, Nuckyz commented
Thank you for the addition!

2024-09-02 03:50 UTC, merged