Add invert option to dearrow plugin
Vendicated/Vencord pull request #2818
Opened 2024-08-31 17:38 UTC by electricsteve

Fix #2783 
Just need feedback if the option should be marked restart needed. (line 174)

2024-08-31 17:40 UTC, Vendicated commented
why do you need feedback for if a restart is needed? it simply depends on if the option can apply immediately or needs a restart to work

2024-08-31 17:45 UTC, EDM115 commented
@Vendicated from what I understand the option will have an immediate effect but will not work retroactively on already dearrowed embeds, unless the user reload their client

2024-08-31 17:48 UTC, electricsteve commented
Yes, its just idk if it is worth requiring a restart.

2024-08-31 17:50 UTC, Vendicated commented
ah i see. that's fine

2024-08-31 18:05 UTC, electricsteve commented
Yea ok but my question is still not answered, @EDM115 what do you think?

2024-08-31 18:08 UTC, EDM115 commented
I believe it's alright, if users want to see changes on their old embeds that are already dearrowed they just have to refresh discord or close & reopen, which isn't a big problem  
I don't think that this setting needs a restart to work out of the box

2024-08-31 18:14 UTC, electricsteve commented
Ok, will remove comment in a few min, currently eating.

2024-09-01 02:08 UTC, Nuckyz commented
Instead of being an option to invert we should do something like how ShowHiddenChannels does:
![image](https://github.com/user-attachments/assets/a8a1ae76-7a76-419a-a887-3e573a7c3847)

Every time you click the toggle button it also updates the setting, so it remembers what you last chose

2024-09-01 10:39 UTC, electricsteve commented
Wtf is that option name

2024-09-01 11:04 UTC, electricsteve commented
> Instead of being an option to invert we should do something like how ShowHiddenChannels does: ![image](https://private-user-images.githubusercontent.com/61953774/363452670-a8a1ae76-7a76-419a-a887-3e573a7c3847.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODg2NzQsIm5iZiI6MTcyNTE4ODM3NCwicGF0aCI6Ii82MTk1Mzc3NC8zNjM0NTI2NzAtYThhMWFlNzYtN2E3Ni00MTlhLWE4ODctM2U1NzNhN2MzODQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDEwNTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2M2IxZTFjNjYxNGRjYmZiMjA2YzQ1OWI0YmI0MzFlYTU0Yzg4YjZkZTk4YTk4OTkyYjdiNzllMjEyM2E3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Chnk4Ocu2BBnxX_V6cU69zafw0PYQHOQ6EhJPzM9KW4)
> 
> Every time you click the toggle button it also updates the setting, so it remembers what you last chose

OK will do that

2024-09-01 11:07 UTC, electricsteve commented
But wait the name of that setting contradicts the function, because it isn't the default, right?

2024-09-01 11:32 UTC, electricsteve commented
(Spelling mistake)

2024-09-02 03:44 UTC, Nuckyz commented
> But wait the name of that setting contradicts the function, because it isn't the default, right?

It's the default value which is applied the next time you view the button where it's used

2024-09-03 01:59 UTC, Nuckyz requested changes

2024-09-03 01:59 UTC, Nuckyz commented on src/plugins/dearrow/index.tsx
> +                        const { invert } = settings.store;
```suggestion
```

2024-09-03 01:59 UTC, Nuckyz commented on src/plugins/dearrow/index.tsx
> +                        settings.store.invert = !invert;
```suggestion
                        settings.store.invert = !enabled;
```

2024-09-03 02:05 UTC, Vendicated commented on src/plugins/dearrow/index.tsx
> +        }
this is just undoing the previous work. why not just use a condition above?

2024-09-03 09:39 UTC, electricsteve commented on src/plugins/dearrow/index.tsx
> +                        settings.store.invert = !invert;
Ah ok

2024-09-03 09:40 UTC, electricsteve commented on src/plugins/dearrow/index.tsx
> +        }
Will do!

2024-09-04 12:00 UTC, merged

2024-09-04 12:01 UTC, Nuckyz commented
Thank you for the contribution!

2024-09-04 13:19 UTC, Nuckyz commented
> NP! also I didn't notice enabled didn't need to be inverted. LOL

no worries, my suggestion was wrong too, I only noticed after testing haha