Added extra option to enable the Snow Halation theme
Vendicated/Vencord pull request #2831
Opened 2024-09-02 01:43 UTC by ramzialhaddad

Adds an extra option to the SecretRingToneEnabler plugin to only play the Snow Halation discord ring theme.

Let me know if there are any errors or discrepancies!

2024-09-02 01:47 UTC, sadan4 commented
i cant hear a difference, is your patch correct?

2024-09-02 01:48 UTC, sadan4 commented on src/plugins/secretRingTone/index.ts
> -// NOTE - Ultimately should probably be turned into a ringtone picker plugin
why did you remove this comment?

2024-09-02 01:56 UTC, ramzialhaddad commented on src/plugins/secretRingTone/index.ts
> -// NOTE - Ultimately should probably be turned into a ringtone picker plugin
Initially I checked if there was an existing plugin that did this PR functionality and I stumbled on #1827 which got moved to #1765. And as such I felt like the comment was then redundant. Have I made a mistake?

2024-09-02 01:57 UTC, ramzialhaddad commented
> i cant hear a difference, is your patch correct?

It should be, I tested it both on a client and via the extension build. That is very odd.

2024-09-02 02:02 UTC, ramzialhaddad commented
> i cant hear a difference, is your patch correct?

Just confirming too you did enable the setting "Only Snow" right? Inside the plugin settings window?

2024-09-02 02:03 UTC, sadan4 commented
not your fault, they were so similar that I didn't notice a difference until I googled them

sorry about that

2024-09-02 02:06 UTC, ramzialhaddad commented
No worries

2024-09-02 03:54 UTC, Nuckyz requested changes

2024-09-02 03:54 UTC, Nuckyz commented on src/plugins/secretRingTone/index.ts
> +    options: {
Use definePluginSettings please

2024-09-02 03:54 UTC, Nuckyz commented on src/plugins/secretRingTone/index.ts
> +            find: '"call_ringing_beat"',
Move this to the same find as the patch above and put the predicate inside the replacement

2024-09-03 01:08 UTC, ramzialhaddad commented on src/plugins/secretRingTone/index.ts
> +            find: '"call_ringing_beat"',
Completed

2024-09-03 01:08 UTC, ramzialhaddad commented on src/plugins/secretRingTone/index.ts
> +    options: {
Done

2024-09-03 01:50 UTC, Nuckyz requested changes

2024-09-03 01:50 UTC, Nuckyz commented on src/plugins/secretRingTone/index.ts
> +        description: "Only play the Snow Halation Theme?",
```suggestion
        description: "Only play the Snow Halation Theme",
```

2024-09-03 03:12 UTC, ramzialhaddad commented
Assuming there isn't anything else to be changed I believe this PR is ready? (First time PR-ing here :D)

2024-09-03 10:50 UTC, Nuckyz commented
> Assuming there isn't anything else to be changed I believe this PR is ready? (First time PR-ing here :D)

yepp!

2024-09-03 10:50 UTC, merged

2024-09-03 10:50 UTC, Nuckyz commented
Thanks for the contribution!