feat(BlurNsfw): Additionally blur the embeds
Vendicated/Vencord pull request #2862
Opened 2024-09-11 11:30 UTC by ryanamay

Closes #2837 

demo:
![image](https://github.com/user-attachments/assets/75155bc3-df9a-409f-84de-3358e847956f)

2024-09-11 12:28 UTC, Masterjoona commented on src/plugins/blurNsfw/index.ts
> +                match: /(?<=channel:\s*\i).*?\.container/g,
You end up with a long match with this and you aren't capturing the channel variable

2024-09-11 12:30 UTC, Masterjoona commented on src/utils/constants.ts
> +    rya: {
dont add yourself to devs for minor changes

2024-09-11 13:14 UTC, ryanamay commented on src/utils/constants.ts
> +    rya: {
fixed in [93e1385](https://github.com/Vendicated/Vencord/pull/2862/commits/93e13858deb2110a7506b0539497d3f306a849ee)

2024-09-11 13:16 UTC, Nuckyz commented
Isn't this just a fix of an already existing feature?

2024-09-11 13:18 UTC, ryanamay commented
> Isn't this just a fix of an already existing feature?

yeah, though the issue is labeled as a feature request. which should i follow?

2024-09-11 15:04 UTC, ryanamay commented on src/plugins/blurNsfw/index.ts
> +                match: /\.container(?=.+?a&&(this))/g,
attempted fix: [cd347c3](https://github.com/Vendicated/Vencord/pull/2862/commits/cd347c361d2c8f1342174976f3f20a20e3c25658) (removed `a` from regex match)

2024-10-03 07:10 UTC, Nuckyz requested changes

2024-10-03 07:10 UTC, Nuckyz commented on src/plugins/blurNsfw/index.ts
> +        },
```suggestion
        }
```

2024-10-03 07:11 UTC, Nuckyz commented
Thank you!

2024-10-03 07:11 UTC, merged