feat(RCE): Add a touch of color to message contents
Vendicated/Vencord pull request #2893
Opened 2024-09-21 08:18 UTC by Kyuuhachi

![image](https://github.com/user-attachments/assets/0175c82e-e16d-4ed5-921e-49ebb6cad8f5)

Adapted from my [ColorMessage](<https://github.com/Kyuuhachi/VencordPlugins/tree/main/ColorMessage>) plugin.

2024-09-21 10:40 UTC, Nuckyz requested changes

2024-09-21 10:40 UTC, Nuckyz commented on src/plugins/roleColorEverywhere/index.tsx
> +        description: "Message color saturation",
```suggestion
        description: "Message color saturation. 0 to disable coloring messages",
```

2024-09-21 10:40 UTC, Nuckyz commented on src/plugins/roleColorEverywhere/index.tsx
> +                replace: 'style:{"color":$self.useMessageColor($1)},'
```suggestion
                replace: "style:{color:$self.useMessageColor($1)},"
```

2024-09-21 11:43 UTC, lewisakura requested changes

2024-09-21 11:43 UTC, lewisakura commented on src/plugins/roleColorEverywhere/index.tsx
> +                return `color-mix(in lab, ${author.colorString} ${messageSaturation}%, var(--text-normal))`;
```suggestion
                return `color-mix(in oklab, ${author.colorString} ${messageSaturation}%, var(--text-normal))`;
```

2024-09-21 23:24 UTC, Kyuuhachi commented
Adjusted according to feedback, as well as a few other small changes.

2024-09-22 07:11 UTC, merged

2024-09-22 07:11 UTC, Nuckyz commented
Thank you for the addition!