feat(plugin): add KyzaMode
Vendicated/Vencord pull request #29
Opened 2022-10-02 23:06 UTC by Ruthenic

2022-10-02 23:54 UTC, ArjixWasTaken commented
:thumbsup:

2022-10-04 20:09 UTC, ArjixWasTaken commented
merge wen

2022-10-04 20:09 UTC, Ruthenic commented
my thoughts exactly

2022-10-05 02:42 UTC, adryd325 requested changes

2022-10-05 02:42 UTC, adryd325 commented on src/plugins/kyzaMode.ts
> +    description: "Fixes your goofy grammar",
make sure to add
```dependencies: ["MessageEventsAPI"],```

2022-10-08 19:11 UTC, Ruthenic commented
if the fucking uwuifier can get merged this can get merged 
![image](https://user-images.githubusercontent.com/53356436/194723718-d8cc9469-2644-4721-ae0b-11c4763837e1.png)

2022-10-08 19:12 UTC, ArjixWasTaken commented
you didn't even follow the suggestion by adryd from 4 days ago

2022-10-08 19:13 UTC, Ruthenic commented
i did i just didn't push the commit until now lol

2022-10-08 19:13 UTC, Ruthenic commented
(and it's broken anyways because i forgot a comma :skull:)

2022-10-12 12:16 UTC, somerandomcloud commented
Im just wondering why the name

2022-10-12 15:48 UTC, ArjixWasTaken commented
> Im just wondering why the name

I assume the name stuck from the BD plugin
Which might be named after a person that was a grammar Nazi

(I am making assumptions, nothing I said is confirmed)

2022-10-12 16:37 UTC, emir4169 commented
can i put this in a dumb github repo for 3rd party plugins

2022-10-22 15:36 UTC, luximus-hunter commented on src/plugins/kyzaMode.ts
> +    getPunctuation(msg) {
Maybe rename to addPunctuationm, as it doesn't return the current punctuation>

2022-10-22 15:44 UTC, ArjixWasTaken commented on src/plugins/kyzaMode.ts
> +    getPunctuation(msg) {
It is not named `getCurrentPunctuation`, it is named `getPunctuation`, and it does just that.
It also does not "add", it only "gets", "add" that would mean it returns the message + punctuation, but what it does is just return the punctuation.

2022-11-10 17:56 UTC, closed without merging