Support poll results in roleColourEverywhere
Vendicated/Vencord pull request #2940
Opened 2024-10-08 20:40 UTC by jamesbt365

First time messing around with patches, mine is probably suboptimal and is mainly a rip of the `.reactorDefault` patch.

Also not that well versed with js/ts, so I don't expect my code to be the most optimal/fit convention of this project, but hey, I tried!

2024-10-08 21:25 UTC, Vendicated commented on src/plugins/roleColorEverywhere/index.tsx
> +                match: /,onContextMenu:e=>.{0,15}\((\i),(\i),(\i)\).{0,300}nickname/,
no hardcoding!
```suggestion
                match: /,onContextMenu:\i=>.{0,15}\((\i),(\i),(\i)\).{0,300}nickname/,
```

2024-10-08 21:25 UTC, Vendicated commented on src/plugins/roleColorEverywhere/index.tsx
> +    getPollColor(args: { channel: { guild_id: string | null; }; user: { id: string; }; }) {
```suggestion
    getPollColor(props: { channel: Channel; user: User; }) {
```

2024-10-08 21:25 UTC, Vendicated commented on src/plugins/roleColorEverywhere/index.tsx
> +        return args.channel.guild_id
```suggestion
        return props.channel?.guild_id
```

2024-10-08 21:43 UTC, jamesbt365 commented on src/plugins/roleColorEverywhere/index.tsx
> +    getPollColor(args: { channel: { guild_id: string | null; }; user: { id: string; }; }) {
the Channel type's guild_id is a `string` whereas the actual type discord can return here can be null?

2024-10-08 21:44 UTC, jamesbt365 commented on src/plugins/roleColorEverywhere/index.tsx
> +                match: /,onContextMenu:e=>.{0,15}\((\i),(\i),(\i)\).{0,300}nickname/,
The patch above this one hardcodes it too, should that also be changed?

2024-11-14 23:13 UTC, Nuckyz requested changes

2024-11-14 23:24 UTC, Vendicated commented on src/plugins/roleColorEverywhere/index.tsx
> +                replace: "$&style:{color:$self.getColor(arguments[0]?.user?.id,{channelId:arguments[0]?.channel.id})},"
```suggestion
                replace: "$&style:{color:$self.getColor(arguments[0]?.user?.id,{channelId:arguments[0]?.channel?.id})},"
```

or better yet, pass the raw arguments and handle it inside the function with try catch

2024-11-17 21:48 UTC, Nuckyz commented
Supersed by https://github.com/Vendicated/Vencord/commit/ea2772476dc6d042b1e3769ad24727b01b02878d

I've added your feature and credits

2024-11-17 21:48 UTC, closed without merging