Replace API add/remove funcs with methods in plugin definition
Vendicated/Vencord pull request #3028
Opened 2024-11-21 02:38 UTC by Vendicated

2024-11-21 03:23 UTC, Vendicated commented
TODO: test every plugin I migrated to make sure I didn't break anything by accident

2024-11-21 03:28 UTC, Vendicated commented
This renamed a lot of the API functions to be more specific (`addDecoration` -> `addMessageDecoration`) so it will likely break many third party plugins

2024-11-21 04:22 UTC, Nuckyz requested changes

2024-11-21 04:22 UTC, Nuckyz commented on src/plugins/messageLinkEmbeds/index.tsx
> +        addMessageAccessory("messageLinkEmbed", props => {
These shouldnt be using the start method

2025-01-22 23:52 UTC, Nuckyz requested changes

2025-01-22 23:52 UTC, Nuckyz commented on src/api/MessageAccessories.tsx
> +        if (!accessories.length)
```suggestion
        const accessories = Array.isArray(res) ? res : [res];
        if (!accessories.length)
```

This wont ever be an array because it's wrapped in an ErrorBoundary

2025-01-22 23:52 UTC, Nuckyz commented on src/plugins/clearURLs/index.ts
> -        this.createRules();
this,createRules(); is gone

2025-01-23 00:22 UTC, Nuckyz requested changes

2025-01-23 00:22 UTC, Nuckyz commented on src/api/MessageAccessories.tsx
> +export type MessageAccessoryFactory = (props: Record<string, any>) => JSX.Element | null | Array<JSX.Element | null>;
```suggestion
export type MessageAccessoryFactory = (props: Record<string, any>) => JSX.Element | null | Array<JSX.Element | null>;
```

This should probably just return React.ReactNode

2025-01-23 01:14 UTC, Nuckyz approved these changes

2025-01-23 01:48 UTC, merged