Add React eslint & update depencenies
Vendicated/Vencord pull request #3090
Opened 2024-12-19 19:06 UTC by Vendicated

what it says in the title

I also was in the process of adding eslint-react-hooks but I realised it sucks ass for a multitude of reasons so I aborted adding that. there are a few hook changes from that nevertheless

Before merging, everywhere where a component key was added or a hook usage was changed needs testing

2024-12-19 20:06 UTC, Vendicated commented
my changes made TypingTweaks cause crashes, honestly so incredible

anyway should be fixed now and everything else seems to work fine

2024-12-22 00:31 UTC, Nuckyz requested changes

2024-12-22 00:31 UTC, Nuckyz commented on src/components/ErrorBoundary.tsx
>      };
Since we are sure this is a FunctionalComponent, we should use the proper type for it

2024-12-22 00:31 UTC, Nuckyz commented on src/components/VencordSettings/PatchHelperTab.tsx
> -            return <div style={{ color, userSelect: "text", wordBreak: "break-all", lineBreak: "anywhere" }}>{p.value}</div>;
Shouldnt this use something like p.value for the key instead of the index?

2024-12-22 00:31 UTC, Nuckyz commented on src/components/VencordSettings/UpdaterTab.tsx
> -                        {err.split("\n").map(line => <div>{Parser.parse(line)}</div>)}
Same argument as the other, use line for key instead?

2024-12-22 00:31 UTC, Nuckyz commented on src/plugins/messageLinkEmbeds/index.tsx
> -                        <div>
Use url for key?

2024-12-22 00:31 UTC, Nuckyz commented on src/plugins/messageLogger/HistoryModal.tsx
> +                            key={index}
Since there are a lot of index usage for keys i'll leave a warning in each to be sure they get changed, if we go that way

2024-12-22 00:31 UTC, Nuckyz commented on src/plugins/messageLogger/index.tsx
> +                    <div key={idx} className="messagelogger-edited">
key warning

2024-12-22 00:31 UTC, Nuckyz commented on src/plugins/permissionsViewer/components/RolesAndUsersPermissions.tsx
> +                                        key={index}
key warning

2024-12-22 00:31 UTC, Nuckyz commented on src/plugins/reviewDB/components/ReviewComponent.tsx
> +                {review.sender.badges.map((badge, idx) => <ReviewBadge key={idx} {...badge} />)}
key warning

2024-12-22 00:31 UTC, Nuckyz commented on src/plugins/shikiCodeblocks.desktop/components/Code.tsx
> +            lines = content.split("\n").map((line, idx) => <span key={idx}>{line}</span>);
key warning

2024-12-22 00:31 UTC, Nuckyz commented on src/plugins/shikiCodeblocks.desktop/components/Code.tsx
> +                return <span key={idx}>{"\n"}</span>;
key warning

2024-12-22 00:31 UTC, Nuckyz commented on src/plugins/startupTimings/StartupTimingPage.tsx
> +                        <span key={idx}>{line}</span>
key warning

2024-12-22 00:36 UTC, Nuckyz requested changes

2024-12-22 00:36 UTC, Nuckyz commented on src/utils/modal.tsx
> +type RenderFunction = (props: ModalProps) => ReactElement<any>;
Why does it need to be ReactElement exactly?

2024-12-22 09:10 UTC, Vendicated commented on src/components/ErrorBoundary.tsx
>      };
no because react updated FunctionComponent type, it can now also return `Promise<ReactElement>` and that causes type errors and is not desired

2025-01-04 05:19 UTC, Nuckyz commented on src/components/ErrorBoundary.tsx
>      };
I looked into it and didnt found Promise<ReactElement> anywhere, I'm reverting this

2025-01-04 06:24 UTC, merged