CSS Snippet Manager
Vendicated/Vencord pull request #345
Opened 2022-12-16 23:49 UTC by ArjixWasTaken

## About
Uses the message accessories API to add the following buttons `Apply`, `Update`, `Remove`.

- Apply: Saves the code snippet in the plugin settings and appends it to the head.
- Update: Appears when a message (of an installed snippet) has been edited, clicking it would simply use the new code.
- Remove: Removes the snippet from the plugin settings and from the head.

<details>
  <summary>Screenshots</summary>
  
  <p align="center">
    <img src="https://user-images.githubusercontent.com/53124886/208208964-88d12bc2-dab6-4eda-9faf-bf412d8e49a0.png">
    <img src="https://user-images.githubusercontent.com/53124886/208208977-c5ce0d10-5195-43e8-9a5f-85bf75431368.png">
    <img src="https://user-images.githubusercontent.com/53124886/208208985-d7555230-7f23-4c0d-a602-ed064eea0bbe.png">
  </p>

</details>

## TODO:
- [ ] Implement the settings UI
- [ ] Figure out why the elements do not re-render until the mouse cursor does not intersect with it.
- [ ] Possibly find a more graceful way of saving the snippets.

2022-12-16 23:51 UTC, somerandomcloud commented on src/plugins/cssSnippetManager.tsx
> +        // console.log("ayo", { message, code, time: moment(message.timestamp).unix() });
Debug moment

2022-12-16 23:52 UTC, ArjixWasTaken commented on src/plugins/cssSnippetManager.tsx
> +        // console.log("ayo", { message, code, time: moment(message.timestamp).unix() });
lmao

2022-12-17 00:17 UTC, somerandomcloud commented on src/plugins/cssSnippetManager.tsx
> +        if (message.channel_id !== "1028106818368589824") return <></>;
`Settings.plugins.CssSnippetManager?.cssSnippetChannel` or some bs like that would work just fine, no?

2022-12-17 00:42 UTC, ArjixWasTaken commented on src/plugins/cssSnippetManager.tsx
> +        if (message.channel_id !== "1028106818368589824") return <></>;
Oh my god, thank you very much, it was too hard for me to figure out, I totally did not add a TODO because I wanted to deal with it later and not bc I don't know what to do.

2022-12-17 00:46 UTC, Vap0r1ze commented on src/plugins/cssSnippetManager.tsx
> +        const snippets = (Settings.plugins.CssSnippetManager?.cssSnippets as Snippet[] | undefined || []);
I think this would make more sense as:
```ts
const snippets: Snippet[] = Settings.plugins.CssSnippetManager?.cssSnippets ?? []
```

2022-12-17 00:48 UTC, somerandomcloud commented on src/plugins/cssSnippetManager.tsx
> +        if (message.channel_id !== "1028106818368589824") return <></>;
:trollface:

2022-12-18 20:14 UTC, ArjixWasTaken commented
@Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated 

![image](https://user-images.githubusercontent.com/53124886/208317309-8573fb22-b1ed-4fd6-b2be-09e0ff05b191.png)
![image](https://user-images.githubusercontent.com/53124886/208317314-05a03226-c56b-445b-a932-2a5a9c3d83a8.png)

2022-12-19 19:13 UTC, ArjixWasTaken commented
@Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated @Vendicated

2022-12-20 00:04 UTC, Vendicated commented on src/plugins/cssSnippetManager.tsx
> +    if (codeBlocks.length !== 1) return <></>;
```suggestion
    if (codeBlocks.length !== 1) return null;
```
null is the proper return to render nothing!

2022-12-20 00:05 UTC, Vendicated commented on src/plugins/cssSnippetManager.tsx
> +            isValid: value => value.split(",").map(id => /\d+/.test(id.trim()) || id.trim().length === 0).every(id => id),
perhaps allow an optional space between elements?
```suggestion
            isValid: value => value.split(/, ?/).map(id => /\d+/.test(id.trim()) || id.trim().length === 0).every(id => id),
```

2022-12-20 00:07 UTC, Vendicated commented on src/plugins/cssSnippetManager.tsx
> +        while (this.styles.length) this.styles.pop();
why not just do this?
```suggestion
        this.styles = []
```

2022-12-20 00:08 UTC, Vendicated commented on src/plugins/cssSnippetManager.tsx
> +});
imo adding possibly dozens of style elements is a bit messy, why not make a more generic function that joins the snippets and writes all to one style element and just call that after modifications?

2022-12-20 00:10 UTC, ArjixWasTaken commented on src/plugins/cssSnippetManager.tsx
> +            isValid: value => value.split(",").map(id => /\d+/.test(id.trim()) || id.trim().length === 0).every(id => id),
I use .trim() tho...

2022-12-20 00:12 UTC, ArjixWasTaken commented on src/plugins/cssSnippetManager.tsx
> +        while (this.styles.length) this.styles.pop();
I have grown too accustomed to `const`, that re-assigning a property it was not even a possibility in my head.

2022-12-20 00:14 UTC, ArjixWasTaken commented on src/plugins/cssSnippetManager.tsx
> +});
It may be a bit messy, but when it comes to removing a single snippet, it is better.

Although I may consider changing it to only use one style tag.

2022-12-23 02:20 UTC, Vendicated requested changes

2022-12-23 02:20 UTC, Vendicated commented on src/plugins/cssSnippetManager.tsx
> +const useEffect = (...args: Parameters<typeof React.useEffect>) => React.useEffect(...args);
```suggestion

```

2022-12-23 02:20 UTC, Vendicated commented on src/plugins/cssSnippetManager.tsx
> +const useState = makeLazy(() => React.useState);
```suggestion

```

2022-12-23 02:20 UTC, Vendicated commented on src/plugins/cssSnippetManager.tsx
> +import { findByProps } from "@webpack";
```suggestion
import { findByProps, useEffect, useState } from "@webpack";
```

2022-12-23 02:20 UTC, Vendicated commented on src/plugins/cssSnippetManager.tsx
> +});
please do

2022-12-25 19:17 UTC, ArjixWasTaken commented
![image](https://user-images.githubusercontent.com/53124886/209479693-ea56656a-e7ff-4310-902c-ddfc8923e1d6.png)

2022-12-25 19:20 UTC, ArjixWasTaken commented
ven will now merge

2022-12-25 19:22 UTC, ArjixWasTaken commented
Note: Because ven requested that all the snippets are in one style node, you can no longer view the entire CSS if you have too many snippets, the browser just gives up and has `...` after some point

2022-12-25 19:24 UTC, ArjixWasTaken commented
the linter is retarded...

![image](https://user-images.githubusercontent.com/53124886/209479831-94450743-b504-4fcb-9ee5-aff63b3ab509.png)
![image](https://user-images.githubusercontent.com/53124886/209479839-effd469e-0cd7-4c2c-90b3-6641b118b2ee.png)
![image](https://user-images.githubusercontent.com/53124886/209479853-9cc996ff-31b9-4dd5-9f5c-145fcf1e4a9b.png)

2022-12-25 19:47 UTC, Vap0r1ze commented
its not the linter its you, you didnt type it

2022-12-25 19:54 UTC, Vap0r1ze requested changes

2022-12-25 19:54 UTC, Vap0r1ze commented on src/plugins/cssSnippetManager.tsx
> +                guilds[snippet.guildId] = guild;
```ts
const channels = GuildChannelStore.getChannels(snippet.guildId).SELECTABLE.map(c => c.channel);
guilds[snippet.guildId] = { ...guild, channels };
```

2022-12-25 20:09 UTC, ArjixWasTaken commented
> its not the linter its you, you didnt type it

I typed it, typescript recognizes it and does not complain.

2022-12-25 20:13 UTC, Vap0r1ze commented
The `Guild` type does not have a `channels` property idk what to tell you, you can ctrl + click `getGuild` to find that out

2022-12-25 20:13 UTC, ArjixWasTaken commented on src/plugins/cssSnippetManager.tsx
> +                guilds[snippet.guildId] = guild;
Could have used the suggestion feature.

I'm on my phone, and it's not a "suggestion" that I can commit directly, so this will have to wait. (Unless you edit it to be a suggestion)

PS: I am not accepting this bc it "types it", I already typed it correctly, I am accepting this bc it is cleaner.

2022-12-25 20:14 UTC, ArjixWasTaken commented
> The `Guild` type does not have a `channels` property idk what to tell you, you can ctrl + click `getGuild` to find that out

Then you must be blind, cause I did `Guild & { channels }` as the type.

2022-12-25 20:55 UTC, Vap0r1ze approved these changes

2022-12-26 15:39 UTC, ArjixWasTaken commented
ven will merge

2022-12-26 15:46 UTC, SammCheese commented
Ven will not merge

2022-12-26 15:52 UTC, ArjixWasTaken commented
@SammCheese 😭

2022-12-26 15:53 UTC, ArjixWasTaken commented
<@343383572805058560>

2022-12-26 15:54 UTC, SammCheese commented
Cursed to be unmerged. Such is the fate of every PR on Vencord

2022-12-29 02:47 UTC, ArjixWasTaken commented
I have sent the assassins, if you don't merge within 5 business days your life is over.

2022-12-29 11:06 UTC, C10udburst commented
> I have sent the assassins, if you don't merge within 5 business days your life is over.

he will not. (he forgot what the merge PR button looks like)

2023-01-18 17:23 UTC, closed without merging