feat(plugin): SpotiMbed
Vendicated/Vencord pull request #351
Opened 2022-12-19 21:56 UTC by Vap0r1ze

2023-01-13 22:39 UTC, Vendicated commented
r u still gonna make this?

2023-01-13 23:07 UTC, Vap0r1ze commented
yea later

2023-01-28 15:51 UTC, Vap0r1ze commented
- [ ] put actions as cover art hover overlay
- [ ] use intersection for resource data
- [ ] tooltip unavailable tracks
- [ ] batch track/album requests with a debounce
- [ ] add embed preview in settings

2023-02-01 15:22 UTC, Vap0r1ze commented
ok its ready

2023-02-02 04:02 UTC, Vap0r1ze commented
# The
https://user-images.githubusercontent.com/20448879/216228660-28aff5d5-6743-46f3-9cd6-081c5485a32c.mp4

2023-02-02 04:08 UTC, Vendicated commented on src/plugins/apiSpotify.ts
> +                // get: superagent.bind(null, "get"),
superman

2023-02-02 04:11 UTC, Vendicated commented on src/plugins/spotimbed/index.tsx
> +    description: "Your mom",
🤨

2023-02-02 04:13 UTC, Vendicated commented on src/plugins/spotimbed/spotimbed.css
> +.spotimbed-embed.spotimbed-unavailable.spotimbed-dismissed::after {
whats up with these unnecessarily verbose selectors, just .spotimbed-dismissed::after shoul be enough

2023-02-02 04:19 UTC, Vap0r1ze commented on src/plugins/spotimbed/index.tsx
> +    description: "Your mom",
LMFAO I FORGOT

2023-02-02 04:28 UTC, Vap0r1ze commented on src/plugins/spotimbed/spotimbed.css
> +.spotimbed-embed.spotimbed-unavailable.spotimbed-dismissed::after {
true fixed

2023-02-04 17:04 UTC, Vendicated commented
- playing an embed should pause other embeds
- it would be useful to have a setting to launch spotify:// uris instead of https urls to open in app
- clicking a specific song in an album should play that song

2023-02-04 17:07 UTC, Vendicated commented
seems like the "this song won't be playable" doesn't work for albums

![image](https://user-images.githubusercontent.com/45497981/216780125-2aa81e9b-e47c-40b1-85ae-9b0cf0513c75.png)

it is also not very intuitive right now, so a tooltip might also help

also idk what happened here but
![image](https://user-images.githubusercontent.com/45497981/216780177-b1bc6ef5-15b6-449e-9a65-f1f8c1fb2ee4.png)

2023-02-04 17:47 UTC, Vap0r1ze commented
- it would be useful to have a setting to launch spotify:// uris instead of https urls to open in app
did u look at the settings xd

2023-02-04 17:48 UTC, Vap0r1ze commented
everything else so trueee

2023-02-04 18:23 UTC, Vendicated commented
> did u look at the settings xd

guh i didnt scroll so i didnt see other settings. Why is market a thing, isn't there a way to do that by ip

2023-02-04 18:25 UTC, Vap0r1ze commented
because u have to specify a market in the requests for song relinking to work, basically if you send an old spotify link from your saves theres a somewhat noticeable change that the label has reuploaded it and it has a different ID now, it wont redirect u to the new one unless u give it a market, i guess i could make a request to some ip for the default value but that sounds weird

2023-02-09 13:44 UTC, Vap0r1ze commented
review? :3

2023-02-18 16:02 UTC, Vap0r1ze commented
trolley

2023-02-23 11:13 UTC, KraXen72 commented
this is cool & goated

2023-02-28 04:49 UTC, Vap0r1ze commented
@MeguminSama review / merge?

2023-03-01 17:34 UTC, Vendicated commented on src/api/Spotify/index.ts
> +const useStateFromStores: <T>(
this is in webpack commons now so please use that

2023-03-01 17:35 UTC, Vendicated commented on src/api/Spotify/index.ts
> +        resourcePromiseCache.set(path, resourcePromise);
so the cache seems to be just for grouping up simultaneous requests for the same resource?

2023-03-01 17:42 UTC, Vendicated commented on src/api/Spotify/index.ts
> +    images.sort((a, b) => Math.abs(size - a.width) - Math.abs(size - b.width));
it probably doesn't matter much since I assume this array will be small but you do unnecessary work here by cloning and sorting, reduce would probably be nicer
```js
return images.reduce((prev, curr) => {
	const diff = Math.abs(size - curr.width);
	return prev[0] > diff ? [diff, curr] : prev;
}, [Infinity, null] as [number, ResourceImage | null])[1];
```

2023-03-01 17:43 UTC, Vendicated commented on src/api/Spotify/store.ts
> +            // eslint-disable-next-line dot-notation
```suggestion
```

2023-03-01 17:55 UTC, Vendicated requested changes
i didnt look at everything yet because there's so much

2023-03-01 17:55 UTC, Vendicated commented on src/api/Spotify/types.ts
> +export interface SpotifyStore {
```suggestion
export interface SpotifyStore extends Flux.Store {
```

2023-03-01 17:55 UTC, Vendicated commented on src/api/Spotify/types.ts
> +    [K in "get" | "put" | "post"]: (accountId: string, accessToken: string, options: { url: string; }) => Promise<any>;
```suggestion
    Record<"get" | "put" | "post", (accountId: string, accessToken: string, options: { url: string; }) => Promise<any>>
```

2023-03-01 17:55 UTC, Vendicated commented on src/api/Spotify/store.ts
> +import { Spotify } from ".";
circular import. Please try refactoring this to not be circular if possible, for example by moving the Spotify export to a different file than index.ts (and just reexporting from index)

2023-03-01 17:55 UTC, Vendicated commented on src/utils/text.ts
> +export function indexesOf(text: string, sub: string) {
could maybe be a generator function that yields the indices rather than returning an array? I doubt people will need this as an array

2023-03-01 17:55 UTC, Vendicated commented on src/plugins/spotimbed/utils/time.ts
> +export const formatDuration = (ms: number) => {
a similar function already exists maybe u can use that

2023-03-01 17:55 UTC, Vendicated commented on src/plugins/spotimbed/utils/spotify.ts
> +export function formatReleaseDate(date: string) {
maybe use Intl for that or find some other way that will respect the user's preference

2023-03-01 17:55 UTC, Vendicated commented on src/plugins/spotimbed/spotimbed.css
> +.spotimbed-embed {
Why do you use px everywhere? You should use em or rem whenever possible, px is bad

2023-03-01 17:55 UTC, Vendicated commented on src/api/Spotify/index.ts
> +        resourcePromiseCache.set(path, resourcePromise);
(not feedback just trying to understand what's going on)

2023-03-01 17:57 UTC, Vendicated commented on src/plugins/spotimbed/utils/spotify.ts
> +export function formatReleaseDate(date: string) {
![image](https://user-images.githubusercontent.com/45497981/222222860-ce45b84d-0909-4b45-afa9-a3fd3b96caa4.png)

2023-03-01 18:16 UTC, Vap0r1ze commented on src/api/Spotify/index.ts
> +        resourcePromiseCache.set(path, resourcePromise);
> so the cache seems to be just for grouping up simultaneous requests for the same resource? But the resource will be refetched if no currently ongoing request fetches the resource?

Yea at least thats the point of the promise cache, spotimbed handles the caching of specific resources on its own.

2023-03-01 18:18 UTC, Vap0r1ze commented on src/plugins/spotimbed/spotimbed.css
> +.spotimbed-embed {
super old stylesheet i was planning on (r)em-ifying it but i forgot

2023-03-02 02:01 UTC, Vap0r1ze commented on src/api/Spotify/types.ts
> +export interface SpotifyStore {
oh weird that it works without that

2023-03-02 02:02 UTC, Vap0r1ze commented on src/api/Spotify/types.ts
> +export interface SpotifyStore {
nvm i didnt realize this was in types

2023-03-02 02:47 UTC, Vap0r1ze commented on src/plugins/spotimbed/utils/spotify.ts
> +export function formatReleaseDate(date: string) {
I dont know a good way to do this that accounts for just month and year, as many albums dont have a date set in their release

2023-03-02 03:08 UTC, Vap0r1ze commented on src/plugins/spotimbed/utils/time.ts
> +export const formatDuration = (ms: number) => {
nah its a different format

2023-03-02 22:11 UTC, Vap0r1ze commented
This is currently broken so don't merge until this is fixed
![image](https://user-images.githubusercontent.com/20448879/222570437-e642e152-dd6a-4f6b-bd96-609c123fbacc.png)

2023-03-03 17:04 UTC, Vap0r1ze commented
Nevermind, the issue wasn't in this PR and was fixed in 727297e

2023-03-04 22:49 UTC, Vendicated commented on src/utils/types.ts
> +export type NonMethodsKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T];
```suggestion
export type NonMethodKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T];
```

2023-03-04 22:51 UTC, Vendicated commented on src/plugins/spotimbed/utils/time.ts
> +export const getMonth = (n: number) => MONTH_NAMES[n];
remooooove

2023-03-04 23:01 UTC, Vendicated commented on src/plugins/spotimbed/components/buttons/QueueButton.tsx
> +const QueueIcon = () => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="currentColor" d="M14 6H4c-.55 0-1 .45-1 1s.45 1 1 1h10c.55 0 1-.45 1-1s-.45-1-1-1zm0 4H4c-.55 0-1 .45-1
```suggestion
const QueueIcon = () => <svg viewBox="0 0 24 24"><path fill="currentColor" d="M14 6H4c-.55 0-1 .45-1 1s.45 1 1 1h10c.55 0 1-.45 1-1s-.45-1-1-1zm0 4H4c-.55 0-1 .45-1 1s.45 1 1 1h10c.55 0 1-.45 1-1s-.45-1-1-1zM4 16h6c.55 0 1-.45 1-1s-.45-1-1-1H4c-.55 0-1 .45-1 1s.45 1 1 1zM19 6c-1.1 0-2 .9-2 2v6.18c-.31-.11-.65-.18-1-.18c-1.84 0-3.28 1.64-2.95 3.54c.21 1.21 1.2 2.2 2.41 2.41c1.9.33 3.54-1.11 3.54-2.95V8h2c.55 0 1-.45 1-1s-.45-1-1-1h-2z"></path></svg>;
```

2023-03-04 23:05 UTC, Vendicated commented on src/plugins/spotimbed/components/common.tsx
> +        className={[cl("link")].concat(className.split(" ")).join(" ")}
baaaad

2023-03-04 23:33 UTC, Vendicated commented on src/plugins/spotimbed/utils/color.ts
> +// } satisfies Record<string, (palette: RgbPalette) => RgbPalette[number]>;
kill

2023-03-04 23:37 UTC, Vendicated commented on src/plugins/spotimbed/components/Art.tsx
> +    } else if (pending) {
if

2023-03-04 23:40 UTC, Vendicated commented on src/api/Spotify/store.ts
> +                console.error("[VencordSpotifyAPI] Failed to seek", err);
this should use le epic Logger

2023-03-04 23:47 UTC, Vendicated commented on src/api/Spotify/index.ts
> +    if (!images || images.length === 0) return null;
```suggestion
    if (!images?.length) return null;
```

2023-03-04 23:49 UTC, Vendicated commented on src/api/Spotify/index.ts
> +    if ("images" in resource) images = resource.images.slice();
```suggestion
    if ("images" in resource) images = resource.images;
```
```suggestion
    if ("images" in resource) images = resource.images;
```

goner

2023-03-04 23:51 UTC, Vendicated commented on src/plugins/spotimbed/components/AudioControls.tsx
> +    const firstRender = useRef(true);
```suggestion
    const [firstRender, setFirstRender] = useState(true);
```

2023-03-04 23:55 UTC, Vendicated commented on src/plugins/spotimbed/components/Embed.tsx
> +import { repository } from "../../../../package.json";
import repository from "~git-remote"

2023-03-04 23:56 UTC, Vendicated commented on src/plugins/spotimbed/components/Embed.tsx
> +    if (!url) return <></>;
```suggestion
    if (!url) return null;
```

2023-03-05 00:19 UTC, Vendicated commented on src/plugins/spotimbed/hooks/usePlayer.ts
> +    const [, update] = React.useReducer(() => ({}), {});
```suggestion
    const baller = useForceUopdater();
```

2023-03-05 00:22 UTC, Vendicated commented on src/plugins/spotimbed/hooks/useResource.ts
> +    else if (error) console.error(error);
bad console user bad

2023-03-05 00:25 UTC, Vendicated commented on src/plugins/spotimbed/index.tsx
> +                replace: "$&$1={...$1,embeds:$self.patchEmbeds($1)};",
making clone risky cause loses prototypes and methods, better to use Proxy which traps get("embeds") to return custom array

2023-03-05 00:30 UTC, Vendicated commented on src/plugins/spotimbed/settings.ts
> +    },
instead of making user choose one specific store, it would be best to first try default market, then if song not available in that store, see what stores it is available in and use one of those instead

2023-03-05 00:38 UTC, Vendicated commented on src/plugins/spotimbed/utils/misc.ts
> +export const sortBy = <T, R extends string | number>(valueFn: (elem: T) => R, reverse = false) => (a: T, b: T) => {
obsolete just kill

2023-03-05 00:40 UTC, Vendicated commented on src/plugins/spotimbed/utils/data.ts
> +/* eslint-disable consistent-return */
```suggestion
```

2023-03-21 00:45 UTC, Vap0r1ze commented on src/plugins/spotimbed/components/AudioControls.tsx
> +    const firstRender = useRef(true);
actually using a key doesnt make sense in this case, nor does using state

2023-03-21 00:49 UTC, Vap0r1ze commented on src/plugins/spotimbed/hooks/usePlayer.ts
> +    const [, update] = React.useReducer(() => ({}), {});
> ```
>     const [, update] = React.useReducer(() => ({}), {});
>	  const baller = useForceUopdater();
> ```
so true

2023-03-21 00:51 UTC, Vendicated commented on src/plugins/spotimbed/hooks/usePlayer.ts
> +    const [, update] = React.useReducer(() => ({}), {});
I need to stop calling everything baller

2023-03-21 02:41 UTC, Vap0r1ze commented
🚀🎉 YOOOO, THE PR IS FINALLY READY! 🔥👀 🙌🎊 WOOHOO, THE PR IS READY FOR LIFTOFF! 🚀🌟 🤩👌 LOOK AT THIS SHINY PR, ALL POLISHED AND READY TO GO! 💅👀 🥳🎉 IT'S PARTY TIME, FOLKS! THE PR IS DONE! 🎊🎉 🤘👀 ROCK ON, OUR PR IS READY TO CONQUER THE WORLD! 🌎🚀 🎯🎉 BULLSEYE, THE PR IS OFFICIALLY LOCKED AND LOADED! 🔒💣 🚨👀 ALERT ALERT, THE PR IS READY FOR LAUNCH! 🚀🔥 🙏🎊 HALLELUJAH, THE PR HAS BEEN BLESSED AND IS NOW READY! 🙏🌟 🌟👌 LOOK AT THIS GORGEOUS PR, IT'S BASICALLY A WORK OF ART! 🎨🤩 🤑🎉 CHA-CHING, THE PR IS READY TO MAKE US ALL RICH AND FAMOUS! 💰🌟

2023-03-21 02:42 UTC, Vap0r1ze commented
🎶 Hey hey, the PR is ready today! 🎶
🎉🌟👀💻
🎶 It's polished and perfect, all ready to play! 🎶
💅🥳🔒🚀
🎶 So let's give a cheer, and shout hip-hip-hooray! 🎶
🙌🎊🎉🌟
🎶 This PR is a star, shining bright like a ray! 🎶
🌟🤩💰👌
🎶 Let's merge it right now, without any delay! 🎶
🤝🚀🔥🎉
🎶 For it's sure to bring joy, and make our day! 🎶
😁🎉🤑🎊

2023-03-21 02:47 UTC, Vap0r1ze commented
🎶 Attention everyone, we have some great news! 🎶
🎉🔊📣
🎶 A new feature is ready to use, 🎶
💡🆕👌
🎶 SpotiMbed is its name, no need to refuse! 🎶
🎶🎵📻🎶
🎶 Let's merge it into Vencord, no need to confuse, 🎶
🤝💻🚀🎉
🎶 It'll elevate our music experience, that's no lie! 🎶
🎧🤩🌟👀
🎶 So let's celebrate, there's no need to deny, 🎶
🎉🎊🎉🎊
🎶 for our prayers will be answered, and Ven will soon reply! 🎶
🌟💻🤝🚀

2023-03-21 02:48 UTC, MeguminSama commented
🎶 Hey hey, the PR is ready today! 🎶
💻🌟👀🎉
🎶 It's polished and perfect, all ready to play! 🎶
🤮🤢👎😖
🎶 So let's give a cheer, and shout hip-hip-hooray! 🎶
🙄😒🤮🤢
🎶 This PR is a star, shining bright like a ray! 🎶
🤯💣👎🔥
🎶 Let's merge it right now, without any delay! 🎶
🤝💥🔥😤
🎶 For it's sure to bring joy, and make our day! 🎶
😔😖🤢💩

2023-06-10 18:15 UTC, KraXen72 commented
pls merg vendy

2023-07-15 14:56 UTC, Vap0r1ze commented
I'm gonna turn this into a third party plugin

2023-07-15 14:56 UTC, closed without merging