feat(plugin): replace Webhook Tags with More Tags
Vendicated/Vencord pull request #378
Opened 2023-01-01 11:36 UTC by ActuallyTheSun

alongside tags for webhooks, this plugin adds tags for moderative roles
![chat-message](https://user-images.githubusercontent.com/78964224/210169251-c80bff56-79e9-4965-8066-8f19480043ce.png)
also adding them to the sidebar and profiles
![member-list](https://user-images.githubusercontent.com/78964224/210169279-460fc8ef-6663-4fb5-ad85-430e77372dcc.png)
![profile](https://user-images.githubusercontent.com/78964224/210169295-da5f5113-02f6-4a66-9692-7167c6818c8e.png)
and it combines bot and op tags so they both show
![bot-admin](https://user-images.githubusercontent.com/78964224/210169351-b3c69071-a7d8-4f3f-9a4c-0438ef03897e.png)
![op-owner](https://user-images.githubusercontent.com/78964224/210169359-8311e24f-1907-456b-9248-2489c5a47454.png)

2023-01-01 16:00 UTC, C10udburst commented
https://github.com/ActuallyTheSun/Vencord/pull/1 <:verycool:888951267873923093>

2023-01-01 16:01 UTC, ActuallyTheSun commented
real

2023-01-01 17:26 UTC, Vendicated commented on src/utils/patches.ts
> +    return replace.replaceAll("$self", pluginName.includes(" ") ? `Vencord.Plugins.plugins["${pluginName}"]` : `Vencord.Plugins.plugins.${pluginName}`);
```suggestion
    return replace.replaceAll("$self", `Vencord.Plugins.plugins["${pluginName}"]`);
```

2023-01-01 20:10 UTC, C10udburst commented
@Vendicated will merge

2023-01-02 21:53 UTC, KraXen72 commented
+1 plz merg

2023-01-07 10:51 UTC, castdrian commented
the option to use the round OP tags for all would be great + maybe different colors per permission

2023-01-07 20:23 UTC, Vendicated commented on src/plugins/moreTags.ts
> +waitFor(["computePermissions", "canEveryoneRole"], m => ({ computePermissions } = m));
Isn't this already in webpack Commons as PermissionStore?

2023-01-07 20:24 UTC, Vendicated commented on src/plugins/moreTags.ts
> +        find: "().copiableNameTag",
please update these patches to latest canary change! these modules no longer use functions, so the () must be removed

2023-01-07 20:24 UTC, Vendicated commented on src/plugins/moreTags.ts
> +    name: "More Tags",
```suggestion
    name: "MoreTags",
```

2023-01-07 20:27 UTC, Vendicated requested changes

2023-01-07 20:27 UTC, Vendicated commented on src/plugins/moreTags.ts
> +            description: "Don't show \"BOT\" text for bots with other tags (verified bots will still have checkmark)",
```suggestion
            description: 'Don't show "BOT" text for bots with other tags (verified bots will still have checkmark)',
```

2023-01-07 20:27 UTC, Vendicated commented on src/plugins/moreTags.ts
> +                },
these patches are terribly unreadable, please make them more readable somehow, or why not extract this logic into a method and call that instead?

2023-01-07 20:27 UTC, Vendicated commented on src/plugins/moreTags.ts
> +        const guild = GuildStore.getGuild(channel.guild_id);
```suggestion
        const guild = GuildStore.getGuild(channel?.guild_id);
```
if you do this, you can delete the above channel check

2023-01-07 20:27 UTC, Vendicated commented on src/plugins/moreTags.ts
> +        ).filter(i => i);
```suggestion
        ).filter(Boolean);
```

2023-01-07 20:27 UTC, Vendicated commented on src/plugins/moreTags.ts
> +        return Object.entries({ ...Permissions }).map(([perm, permInt]) =>
whats the point of this spread?

2023-01-07 20:27 UTC, Vendicated commented on src/plugins/moreTags.ts
> +    isOPTag: (tag: number) => tag === Tags.ORIGINAL_POSTER || (tag >= 100 && tag % 10 === 1),
wtf

2023-01-07 20:41 UTC, KraXen72 commented on src/plugins/moreTags.ts
> +        return Object.entries({ ...Permissions }).map(([perm, permInt]) =>
maybe a shallow copy?

2023-01-18 22:59 UTC, Vendicated commented on src/plugins/moreTags.ts
> +waitFor(["computePermissions", "canEveryoneRole"], m => ({ computePermissions } = m));
?

2023-03-12 09:12 UTC, ActuallyTheSun commented on src/plugins/moreTags.ts
> +waitFor(["computePermissions", "canEveryoneRole"], m => ({ computePermissions } = m));
oh i forgot to give a reason

`computePermissions` from PermissionStore isnt the same function and that one cant be used here (the one from PermissionStore can only compute for the current user). i've added a comment to clear things up

2023-03-24 18:22 UTC, ActuallyTheSun commented
maybe rename to MoreUserTags or StaffTags to avoid confusion with MessageTags?

2023-04-02 16:08 UTC, Vendicated requested changes

2023-04-02 16:08 UTC, Vendicated commented on src/plugins/moreTags.ts
> +                    replace: (orig, types, text, strings) =>
i don't like these two replacements. You're dynamically building a lot of javascript. Why not use a proper function for this? That's so much more robust

2023-04-02 16:08 UTC, Vendicated commented on src/plugins/moreTags.ts
> +                    type = Tags[tag.name];
if you add `break` to these if cases, you can remove the .reverse() above and do less work, no?

2023-04-06 01:28 UTC, merged