Added commands API
Vendicated/Vencord pull request #38
Opened 2022-10-04 12:16 UTC by ArjixWasTaken

2022-10-04 19:29 UTC, ArjixWasTaken commented
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge 
Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge Merge

2022-10-04 19:32 UTC, Vendicated commented on src/api/Commands.ts
> +    (opt as any).displayName = opt.name;
i would put all these on the interface and just make them optional so you aren't required to specify them

2022-10-04 19:33 UTC, ArjixWasTaken commented on src/api/Commands.ts
> +    (opt as any).displayName = opt.name;
name is internal anyways, only displayName is show to the user, so them being the same is ok
but oh well

2022-10-04 19:36 UTC, Vendicated requested changes

2022-10-04 19:36 UTC, Vendicated commented on src/api/Commands.ts
> +    return ((Math.abs(existingIds.sort((a, b) => a - b)[0]) + 1) * -1).toString()
i have no idea what this is supposed to do, why not use Discord's Snowflake module to generate an id? findByProps("fromTimestamp").fromTimestamp(Date.now()) or smth like that

2022-10-04 19:36 UTC, Vendicated commented on src/plugins/commandsAPI.ts
> +                        `((()=>Vencord.Api.Commands._BuiltIn=${v})())${rest}`,
just webpack search it so we don't need this plugin

2022-10-04 19:37 UTC, ArjixWasTaken commented on src/api/Commands.ts
> +    return ((Math.abs(existingIds.sort((a, b) => a - b)[0]) + 1) * -1).toString()
uhh, they are not snowflakes...they are numbers starting from -1 and going down

2022-10-04 19:38 UTC, ArjixWasTaken commented on src/plugins/commandsAPI.ts
> +                        `((()=>Vencord.Api.Commands._BuiltIn=${v})())${rest}`,
:pain:

2022-10-04 19:43 UTC, ArjixWasTaken commented on src/plugins/commandsAPI.ts
> +                        `((()=>Vencord.Api.Commands._BuiltIn=${v})())${rest}`,
not exposed

2022-10-04 20:42 UTC, Vendicated commented on src/plugins/commandsAPI.ts
> +                        `((()=>Vencord.Api.Commands._BuiltIn=${v})())${rest}`,
I see

2022-10-04 20:47 UTC, Vendicated commented on src/plugins/commandsAPI.ts
> +                    match: /(?<=\w=)([A-Za-z])(\.filter\(\(function\(\w\){return\[(?:(?:"\w+?")|,)+\]\.includes)/,
why use A-Z over \w?

2022-10-04 20:49 UTC, ArjixWasTaken commented on src/plugins/commandsAPI.ts
> +                    match: /(?<=\w=)([A-Za-z])(\.filter\(\(function\(\w\){return\[(?:(?:"\w+?")|,)+\]\.includes)/,
paranoia, \w is fine

2022-10-04 20:50 UTC, Vendicated commented on src/api/Commands.d.ts
> +    value: string;
are you sure this is always a string?

2022-10-04 20:50 UTC, Vendicated commented on src/api/Commands.d.ts
> +    type: number;
shouldnt this be ApplicationCommandOptionType?

2022-10-04 20:51 UTC, Vendicated commented on src/plugins/vencordCommands.ts
> +    } as Command,
looks good but should remove this plugin / change to more useful commands

2022-10-04 20:53 UTC, ArjixWasTaken commented on src/api/Commands.d.ts
> +    type: number;
honestly, its been so long that I have forgotten
+ discord obfuscated everything so i cant easily find the enums again

2022-10-04 20:53 UTC, ArjixWasTaken commented on src/api/Commands.d.ts
> +    value: string;
value? yeah, it is always a string, the type is only used for validation

2022-10-04 20:56 UTC, Vendicated commented on src/api/Commands.d.ts
> +    type: number;
you have the interface in the same file xd just change it to that

oh also please change it from type => interface

2022-10-04 20:57 UTC, ArjixWasTaken commented on src/api/Commands.d.ts
> +    type: number;
> you have the interface in the same file xd just change it to that

you might have misunderstood me, by `so i cant easily find the enums again` i meant that i cant verify that it is correct/incorrect

2022-10-04 20:58 UTC, ArjixWasTaken commented on src/plugins/vencordCommands.ts
> +    } as Command,
hmm, are meme commands ok with you?

2022-10-04 21:05 UTC, ArjixWasTaken commented on src/plugins/vencordCommands.ts
> +    } as Command,
will go with a lenny face command

2022-10-04 21:05 UTC, Ruthenic commented on src/plugins/vencordCommands.ts
> +    } as Command,
uwuifier where?

2022-10-04 21:09 UTC, ArjixWasTaken commented on src/plugins/vencordCommands.ts
> +    } as Command,
> uwuifier where?

PR it later, lol

2022-10-04 21:10 UTC, Ruthenic commented on src/plugins/vencordCommands.ts
> +    } as Command,
i will as soon as ven merges the fucking pr :imp:

2022-10-04 21:34 UTC, Vendicated commented on src/api/Commands.ts
> +    if (command.displayName == undefined) command.displayName = command.name;
```suggestion
    command.displayName ||= command.name;
```
same below

2022-10-04 21:35 UTC, Vendicated commented on src/api/Commands.ts
> +export function unregisterCommand(command: Command) {
this should only take the command name

2022-10-04 21:49 UTC, ArjixWasTaken commented on src/api/Commands.ts
> +export function unregisterCommand(command: Command) {
but there can be multiple commands with the same name...

2022-10-05 21:00 UTC, Vendicated approved these changes

2022-10-05 21:03 UTC, Vendicated commented
good to merge?

2022-10-05 22:11 UTC, merged