feat(SilentTyping): add toggle command
Vendicated/Vencord pull request #398
Opened 2023-01-10 06:24 UTC by dzshn

adds a simple command `/silenttype` so you can toggle whether the plugin is enabled without having to restart

2023-01-10 06:26 UTC, Vendicated commented
way cooler would be to add a chatbar button like invisiblechat

2023-01-10 06:27 UTC, dzshn commented
I'm kinda against adding a button cuz it's not something you toggle often but yeah maybe could be an option

2023-01-11 15:35 UTC, Vendicated commented on src/plugins/silentTyping.tsx
> +import { Settings } from "Vencord";
```suggestion
import { Settings } from "@api/settings";
```

2023-01-11 16:04 UTC, fawni commented
if ur gonna add a button can u make its existence toggleable because i personally don't need to toggle it so a button would just be annoyance to me

2023-01-11 18:25 UTC, Vap0r1ze reviewed
hmm

2023-01-13 22:25 UTC, Vendicated commented
are u two done now?

2023-01-13 22:26 UTC, dzshn commented
I'd say so yes

2023-01-13 22:27 UTC, Vendicated commented
oh yeah you should switch to vaps new settings api maybe

2023-01-13 22:28 UTC, Vendicated commented on src/plugins/silentTyping.tsx
> +        <Tooltip text={isEnabled ? "Disable silent typing" : "Enable silent typing"} style={{ scale: "0.5" }}>
huh why this scale

2023-01-13 22:30 UTC, Vendicated commented on src/plugins/silentTyping.tsx
> +                <Button
you should wrap this in a div similar to https://github.com/Vendicated/Vencord/commit/19c9a132733dfb67de6d62d6da1348944cbe1146

2023-01-14 00:15 UTC, Vap0r1ze requested changes

2023-01-14 00:15 UTC, Vap0r1ze commented on src/plugins/silentTyping.tsx
> +    dependencies: ["CommandsAPI"],
```suggestion
    dependencies: ["CommandsAPI"],
    settings,
```

2023-01-14 17:46 UTC, Vendicated approved these changes

2023-01-14 17:47 UTC, merged