feat: Typesafe Settings Definitions
Vendicated/Vencord pull request #403
Opened 2023-01-12 06:40 UTC by Vap0r1ze

This PR creates an alternative to the `options` field that is more typesafe: a new `settings` plugin field that takes in settings, which can be defined using `definePluginSettings`

You can check the changes to see shiki as a usage example, but a [^1]basic overview:
```ts
const settings = definePluginSettings({
  someText: { type: OptionType.STRING },
  amount: { type: OptionType.NUMBER },
}, {
  // value is implicitly a string
  someText: {
    isValid(value) { return value.length > 5 && this.store.amount > 0 }
  },
})

// After plugin initialization
settings.store.someText; // string
settings.store.someText = "hello"; // will send out updates to existing react hooks

// React hook (optional filter to avoid needless updates)
settings.use() // { someText: string, amount: number }
settings.use(["amount"]) // { amount: number }
```

[^1]: Some fields were left out for simplicity, I think only `description`

`definePluginSettings(defs[, checks])`: this uses essentially the same format as the `options` property, except the option properties that are (what I'm calling) "checks". A "check" is a option property that:
   - Is a method
   - Has a return value that may rely on other plugin settings

At the moment the only "check" fields that exist are `disabled` and `isValid`

2023-01-12 18:38 UTC, MeguminSama commented on src/api/settings.ts
> +        get store() {
Could you add some jsdoc to these properties?

2023-01-12 18:41 UTC, MeguminSama approved these changes
There's a lot going on here, but code works & looks fine to me.

2023-01-12 18:53 UTC, Vap0r1ze commented on src/api/settings.ts
> +        get store() {
yop

2023-01-12 18:55 UTC, Vap0r1ze commented
> There's a lot going on here, but code works & looks fine to me.

I tried to make it completely opt-in and compatible with the `options` field type-wise. Runtime-wise the `settings` field is just [an alias for `options`](https://github.com/Vendicated/Vencord/pull/403/files#diff-66ace9db4d3f14bc7ff52498147b0a9ef6e33070073803893afdaee7be8e3198R63-R72) at the moment.

2023-01-13 01:55 UTC, Vendicated requested changes

2023-01-13 01:55 UTC, Vendicated commented on src/utils/types.ts
> +    use<F extends Extract<keyof D, string>>(filter?: F[]): F extends `${any}` ? Pick<SettingsStore<D>, F> : never;
![image](https://user-images.githubusercontent.com/20448879/212218905-c15d6fe4-eeec-4572-adf3-d4f5f03c3728.png)

2023-01-13 22:14 UTC, Vendicated approved these changes

2023-01-13 22:15 UTC, merged

2023-01-13 22:50 UTC, Vendicated commented
this is epic btw, now migrate all plugins and I'll buy you a pizza 🚎 💯