feat(plugins): add TypingTweaks
Vendicated/Vencord pull request #432
Opened 2023-01-19 03:12 UTC by zt64

Adds avatars and role colors to typing users

2023-01-19 03:34 UTC, Vendicated commented on src/plugins/typingTweaks.tsx
> +    description: "Adds some tweaks to typing indicators",
```suggestion
    description: "Show avatars and role colours in the typing indicator",
```

2023-01-19 03:36 UTC, Vendicated commented on src/plugins/typingTweaks.tsx
> +        }
you can use a .map for this like
```js
return children.map(c => c.type === "strong" ? c : <this.TypingUser {...props} user={users[element++]} />)
```

2023-01-19 03:39 UTC, Vendicated commented on src/plugins/typingTweaks.tsx
> +    TypingUser({ user, guildId }) {
```suggestion
    TypingUser: ErrorBoundary.wrap(({ user, guildId }) => {
```

(You of course also need to close the function call at the end of the function and should also pass { noop: true } as option to .wrap()

ErrorBoundaries are component wrappers that will catch errors thrown by the wrapped component (instead of crashing) and optionally render fallback ui (by default a fat error card so thats why noop, to render nothing instead)
Just good practice to prevent crashes if your plugin ever breaks

2023-01-19 03:46 UTC, Vendicated commented
other than that epic, I'm surprised it's this simple

2023-01-19 03:47 UTC, Vendicated commented on src/plugins/typingTweaks.tsx
> +                match: /=(.{1,2})\[2];(.+)"aria-atomic":!0,children:(.{1,2})}\)/,
```suggestion
                match: /=(\i)\[2];(.+)"aria-atomic":!0,children:(\i)}\)/,
```
you can use \i to match identifiers instead of .{1,2}, recently added patcher feature

2023-01-19 03:48 UTC, Vendicated commented on src/plugins/typingTweaks.tsx
> +                    src={user.getAvatarURL(guildId, 16)}
SO SMALL WHAT

i would do 256 so it's high res and downscaled

2023-01-23 03:13 UTC, Vendicated requested changes

2023-01-23 03:13 UTC, Vendicated commented on src/plugins/typingTweaks.tsx
> +        description: "Use alternative formatting for when several users are typing"
```suggestion
        description: "Show a more useful message when several users are typing"
```

2023-01-23 03:13 UTC, Vendicated commented on src/plugins/typingTweaks.tsx
> +    ],
could you please add comments explaining what each individual patch does?

2023-01-23 04:58 UTC, zt64 commented on src/plugins/typingTweaks.tsx
> +    ],
Guhhh fine

2023-01-25 02:37 UTC, Vendicated commented on src/plugins/typingTweaks.tsx
> +            find: "t(n,\"SEVERAL_USERS_TYPING\"",
```suggestion
            find: ',"SEVERAL_USERS_TYPING","',
```

2023-01-28 23:05 UTC, Vendicated commented
good

2023-01-28 23:06 UTC, merged