[WIP] Notification API
Vendicated/Vencord pull request #467
Opened 2023-02-01 20:50 UTC by Vendicated

https://user-images.githubusercontent.com/45497981/216160334-9f372003-ae4f-4bd1-924b-6e09a2e6737f.mp4

2023-02-02 03:55 UTC, xafn requested changes
guhh

2023-02-02 03:55 UTC, xafn commented on src/api/Notifications/styles.css
> +    display: flex;
```suggestion
```

2023-02-09 17:30 UTC, Vendicated commented
Ready

2023-02-09 21:27 UTC, MeguminSama requested changes

2023-02-09 21:27 UTC, MeguminSama commented on src/api/Notifications/NotificationComponent.tsx
> +            {image && <img className="vc-notification-img" src={image} alt="" />}
why the `alt=""`?

2023-02-09 21:27 UTC, MeguminSama commented on src/api/Notifications/Notifications.tsx
> +let id = 42;
Why is this 42?

2023-02-09 21:27 UTC, MeguminSama commented on src/components/VencordSettings/VencordTab.tsx
> +            <Select
Missing padding between title and dropdown
![image](https://user-images.githubusercontent.com/27697325/217942143-b6ce075c-7922-4d20-8abe-9373e562ac10.png)

2023-02-09 21:29 UTC, Vendicated commented on src/api/Notifications/NotificationComponent.tsx
> +            {image && <img className="vc-notification-img" src={image} alt="" />}
![image](https://user-images.githubusercontent.com/45497981/217943309-fc8d71e7-9917-4d8d-bc00-602e0133483f.png)
https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/alternative-text/

2023-02-09 21:29 UTC, Vendicated commented on src/api/Notifications/Notifications.tsx
> +let id = 42;
why not

2023-02-09 21:34 UTC, Vendicated commented on src/components/VencordSettings/VencordTab.tsx
> +            <Select
le fixed

2023-02-09 21:38 UTC, MeguminSama approved these changes
:shipit:

2023-02-10 21:33 UTC, merged