feat(plugin): richerCider
Vendicated/Vencord pull request #471
Opened 2023-02-06 22:50 UTC by cryptofyre

This plugin addition adds additional capabilities to our music app Cider by allowing it to use the "Listening" activity type, more will likely be added down the road as Discord matures or we deem more RPC features suitable.

This does not interfere with other plugins/apps outside of potentially Cider Rich Presence when combined with other global modifiers.

[Cider](https://cider.sh)
[GitHub](https://github.com/ciderapp/Cider)

It was fun collaborating with you all in the Discord server on this and I hope to contribute more in the future!

2023-02-06 23:09 UTC, Vendicated commented on src/plugins/richerCider.ts
> +    description: "Enhances Cider by adding the \"Listening to\" to the user's rich presence when applicable ID is found.",
maybe explain more thoroughly what cider even is because I assume most people don't know

2023-02-06 23:12 UTC, cryptofyre commented on src/plugins/richerCider.ts
> +    description: "Enhances Cider by adding the \"Listening to\" to the user's rich presence when applicable ID is found.",
Yeah fair, ill update the description.

2023-02-06 23:30 UTC, cryptofyre commented on src/plugins/richerCider.ts
> +    description: "Enhances Cider by adding the \"Listening to\" to the user's rich presence when applicable ID is found.",
Should be good now, take a look!

2023-02-07 21:37 UTC, d3rpp commented
seems legit

2023-02-07 21:49 UTC, somerandomcloud commented
y'all are impossible to please wtf

2023-02-08 01:46 UTC, Vendicated requested changes
pls fix lint issues, otherwise looks fine

2023-02-08 01:46 UTC, Vendicated approved these changes

2023-02-08 02:51 UTC, cryptofyre commented
Should be nice and tidy now, thanks for the pointers!

2023-02-08 20:48 UTC, merged