feat(plugin): RoleColorEverywhere
Vendicated/Vencord pull request #482
Opened 2023-02-11 16:48 UTC by lewisakura

supersedes #273

colors chat mentions and member list role titles, typing colors are handled by TypingTweaks so it's not included here to prevent duplicate functionality.

2023-02-12 02:10 UTC, Vendicated requested changes

2023-02-12 02:10 UTC, Vendicated commented on src/plugins/roleColorEverywhere.tsx
> +                    match: /user:(.),channelId:(.).{0,300}?"@".concat\(.+?\)/,
```suggestion
                    match: /user:(\i),channelId:(\i).{0,300}?"@"\.concat\(.+?\)/,
```

2023-02-12 02:10 UTC, Vendicated commented on src/plugins/roleColorEverywhere.tsx
> +                    match: /(function\((.)\).+?roleIcon.{5,20}null,).," \u2014 ",.\]/,
this is extremely dangerous. This will match everything starting from the first instance of (function(a) up to roleIcon, which could be thousands of characters! Please rewrite this in a different way or alternatively change the .+? to .{0,100} or whatever is appropriate

2023-02-12 02:10 UTC, Vendicated commented on src/plugins/roleColorEverywhere.tsx
> +        const channel = Vencord.Webpack.Common.ChannelStore.getChannel(channelId);
```suggestion
        const channel = ChannelStore.getChannel(channelId);
```
Just import it!!

2023-02-12 02:12 UTC, lewisakura commented on src/plugins/roleColorEverywhere.tsx
> +                    match: /(function\((.)\).+?roleIcon.{5,20}null,).," \u2014 ",.\]/,
this is how it was in the original patch too which is scary

2023-02-14 17:30 UTC, lewisakura commented
@Vendicated im happy that im not going to add anything or change this now so i think it's ready for a final review

2023-02-16 01:32 UTC, Vendicated commented on src/plugins/roleColorEverywhere.tsx
> +        logger.info(guildId);
```suggestion
```

:shipit:

2023-02-16 01:33 UTC, lewisakura commented on src/plugins/roleColorEverywhere.tsx
> +        logger.info(guildId);
oops

2023-02-16 01:37 UTC, Vendicated requested changes
Also could you please type the function params? Helps to catch silly bugs like typos / partial refactors later down the road

2023-02-16 01:37 UTC, Vendicated commented on src/plugins/roleColorEverywhere.tsx
> +        if (!guildId && !channelId) return null;
u can do all the below via
```suggestion
        if (!(guildId ??= ChannelStore.getChannel(channelId!)?.guild_id)) return null;
```
(there's no need to check channelId, getChannel handles null case)

2023-02-16 01:37 UTC, Vendicated commented on src/plugins/roleColorEverywhere.tsx
> +        return member?.colorString;
```suggestion
        return GuildMemberStore.getMember(guildId, userId)?.colorString ?? null;
```

2023-02-16 01:45 UTC, Vendicated approved these changes
okay looks good, thank you!

2023-02-16 01:50 UTC, Vendicated commented
:shipit:

2023-02-16 01:50 UTC, merged