Update LastFM plugin
Vendicated/Vencord pull request #483
Opened 2023-02-11 20:45 UTC by RuiNtD

Reformat the results
Simplify some code
Add some sanity checks

2023-02-11 22:04 UTC, Vendicated requested changes

2023-02-11 22:04 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +type ActivityButton = {
```suggestion
interface ActivityButton {
```

2023-02-11 22:04 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +            }).toString();
```suggestion
            });
```

2023-02-11 22:04 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +                imageUrl: (trackData.image || []).filter(x => x.size === "large")[0]?.["#text"]
```suggestion
                imageUrl: trackData.image?.find(x => x.size === "large")?.["#text"]
```

2023-02-11 22:04 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +            console.log("Failed to query Last.fm API", e);
```suggestion
            new Logger("LastFMRichPresence").error("Failed to query Last.fm API", e);
```

2023-02-11 22:04 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +        let buttons: ActivityButton[] = [
```suggestion
        const buttons: ActivityButton[] = [
```

2023-02-11 22:04 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +                url: `https://www.last.fm/user/${this.settings.username}`,
you should probably urlencode this

2023-02-11 22:06 UTC, RuiNtD commented on src/plugins/lastfm.tsx
> +                url: `https://www.last.fm/user/${this.settings.username}`,
The code won't get this far unless the API returns something (which assumes the username is already valid).

2023-02-11 22:15 UTC, RuiNtD commented on src/plugins/lastfm.tsx
> +            console.log("Failed to query Last.fm API", e);
This requires an additional import. I'll add that in a separate commit.

2023-02-11 23:30 UTC, RuiNtD commented
Feel free to merge the commits btw :P

2023-02-12 02:06 UTC, Vendicated commented
@dzshn look

2023-02-18 05:59 UTC, RuiNtD commented
My changes also recommending replacing the `lastfm-large` asset in the Discord application with either [Last.fm's placeholder song icon](https://lastfm.freetls.fastly.net/i/u/200x200/2a96cbd8b46e442fc41c2b86b821562f.png) (which is what the API incorrectly provides if the album has no art) or [Last.fm's placeholder album icon](https://lastfm.freetls.fastly.net/i/u/300x300/c6f59c1e5e7240a4c0d427abd71f3dbb.jpg) for consistency, because TBH [this](https://user-images.githubusercontent.com/1149870/219843897-2944753c-b2ec-4c2f-9d9a-80374e4bd96c.png) looks ugly AF. Am I trying to advertise Last.fm or something? I just want people to know what I'm listening to. lol

2023-03-11 17:01 UTC, RuiNtD commented
![image](https://user-images.githubusercontent.com/1149870/224499083-dd0cfb61-806c-4593-8369-dd20515f3a88.jpeg)
![image](https://user-images.githubusercontent.com/1149870/224498794-da2e0500-56fe-4ced-abc5-e6887120d7cb.jpeg)

I literally could've just added a "Hide album art if empty" toggle. Apparently nobody felt the desire to work with me to get it done.

2023-03-11 19:42 UTC, RuiNtD commented
You brought it up that *one* time, and all you said was to add an option for custom application ID, which would do nothing to solve the problem. I was willing to collaborate and all I got was "my way is the only way" (paraphrase). You can even see a 😴 reaction in the screenshot you sent. I even made a thread in the Discord that nobody ever talked in.

2023-03-18 04:05 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +    useLogo: {
i think the way this setting is worded is confusing, why not do something like this instead?

## Fallback Logo
- Use last.fm logo when album is unknown or has no album art
- Use last.fm logo when album is unknown, use last.fm placeholder logo when album has no album art
- Use last.fm placeholder logo when album is unknown or has no album art

2023-03-18 04:09 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +                throw new Error(`${res.status} ${res.statusText}`);
this code is weird, I would do something like this instead
```js
try {
	const res = await fetch(`https://ws.audioscrobbler.com/2.0/?${params}`);
	if (!res.ok) throw `${res.status} ${res.statusText}`;

	var json = await res.json();
	if (json.error) throw `${json.error}: ${json.message}`;
} catch (err) {
	logger.error("Error fetching last.fm data", err);
	return null;
}
const trackData = json.recenttracks?.track[0];
...
```

2023-03-18 04:12 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +            });
instead of conditionally pushing, you could
```js
const buttons: ActivityButton[] = [
    {
        label: "View Song",
        url: trackData.url,
    },
	settings.store.shareUsername && {
        label: "Last.fm Profile",
        url: `https://www.last.fm/user/${settings.store.username}`,
    }
].filter(isTruthy);
```

2023-03-18 04:13 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +                throw new Error(`${res.status} ${res.statusText}`);
I just realised you're nesting try catches here. Why? One is enough

2023-03-18 05:12 UTC, RuiNtD commented on src/plugins/lastfm.tsx
> +                throw new Error(`${res.status} ${res.statusText}`);
The inner try catch is used just to properly format the error message provided to the outer catch, so it would say something like "Failed to query Last.fm API 500 Internal Server Error" instead of returning a JSON error, but yeah, I agree with the above code. Will commit that in a bit.

2023-03-18 05:15 UTC, RuiNtD commented on src/plugins/lastfm.tsx
> +            });
...I mean, I *could*, but this code is more readable. Besides, it's only one conditional. Maybe if there were more conditional buttons, it would make more sense, but I don't think rich presence even allows more than two buttons?

2023-03-18 05:23 UTC, RuiNtD commented on src/plugins/lastfm.tsx
> +    useLogo: {
Seems a bit too wordy, tho. It might make more sense to remove the middle option, for something like this:

## When album is unknown or album art is missing
- Prefer generic placeholder
- Prefer Last.fm logo

Feedback? Could also open up potential in the future for more options; like trying to look up album art on another service (like Google Images) or [Identicons](http://identicon.net/) (unlikely, but possible).

2023-03-25 01:33 UTC, Vendicated commented on src/plugins/lastfm.tsx
> +                logger.error("Error from Last.fm API", `${json.error}: ${json.message}`);
very small nitpick: you could just make this
```suggestion
                throw `${json.error}: ${json.message}`;
```
to have slightly less duplicated code (the catch already logs and returns null)

2023-03-25 01:34 UTC, Vendicated approved these changes
other than the small nitpick LGTM

2023-03-25 02:50 UTC, RuiNtD commented on src/plugins/lastfm.tsx
> +                logger.error("Error from Last.fm API", `${json.error}: ${json.message}`);
This is an error from the API itself, rather than an error parsing the response.

2023-03-25 03:00 UTC, merged