feat: message logger plugin
Vendicated/Vencord pull request #49
Opened 2022-10-05 05:05 UTC by DiamondMiner88

This is still pretty incomplete, however it can log deleted messages and edit history in-memory.

## TODO:
- MESSAGE_DELETE_BULK
- referenced messages
- save to disk (possibly?)
- timestamp popup on (edited) of edit history

2022-10-05 10:48 UTC, taskylizard commented
you will explode

2022-10-05 10:48 UTC, MeguminSama commented
I will explode

2022-10-08 08:03 UTC, ShiroBlank commented
you will finish this plugin NOW

2022-10-08 17:33 UTC, Vendicated commented on src/plugins/messageLogger/index.ts
> +        return React.createElement("div", { className: "messageLogger-edited" }, [
u can use tsx btw

2022-10-08 17:35 UTC, Vendicated commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
so that it won't what

2022-10-08 17:38 UTC, x6r commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it wont

2022-10-08 17:40 UTC, Vendicated commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
true

2022-10-08 17:43 UTC, DiamondMiner88 commented on src/plugins/messageLogger/index.ts
> +        return React.createElement("div", { className: "messageLogger-edited" }, [
I know but i was gonna have to use React.createElement anyways for the timestamp component so i decided to stick to one
It would have worse indentation layers anyways

2022-10-08 17:43 UTC, DiamondMiner88 commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it wont

2022-10-15 14:25 UTC, hairyfred commented
you will explode ram by loggin ven furry pics

2022-10-21 02:48 UTC, TymanWasTaken commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it simply will not

2022-10-21 12:28 UTC, Kyiro commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it wont

2022-10-21 14:20 UTC, mantikafasi commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it wont

2022-10-21 14:21 UTC, mantikafasi commented
NO

2022-10-21 14:23 UTC, somerandomcloud commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it wont

2022-10-21 19:41 UTC, ItzOnlyAnimal commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it just wont

2022-10-24 17:49 UTC, hairyfred commented
this pr will explode so hard ven will commit it

2022-10-24 18:15 UTC, DiamondMiner88 commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it wont

2022-10-24 20:27 UTC, somerandomcloud commented
[cat_shrink.webm](https://user-images.githubusercontent.com/39058370/197622315-1418fd1e-4c2b-4672-8de6-e89c95732870.webm)

2022-10-25 09:21 UTC, taskylizard commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it wont

2022-10-30 04:48 UTC, x6r requested changes
finish this you dumb fuck

2022-10-30 05:17 UTC, DiamondMiner88 commented
fawn is in love with me

2022-10-30 06:21 UTC, mantikafasi commented
guys



EXPLODE

2022-10-30 06:37 UTC, taskylizard commented
shut the fuck up

2022-10-30 07:09 UTC, mantikafasi commented
never

2022-10-30 07:17 UTC, somerandomcloud commented
@DiamondMiner88 finish this or I will force you to explode

2022-10-30 10:37 UTC, hairyfred commented
> @DiamondMiner88 finish this or I will force you to explode

no explodes u

2022-10-30 15:18 UTC, DiamondMiner88 commented
you will force ven to support canary alhamdulillah

2022-10-30 15:32 UTC, somerandomcloud commented
you will collapse, stop using canary

2022-10-30 15:48 UTC, mantikafasi commented
Guys stop mailing me

On Sun, Oct 30, 2022, 6:32 PM Berlin ***@***.***> wrote:

> you will collapse, stop using canary
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Vendicated/Vencord/pull/49#issuecomment-1296285666>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQERV2OQGSI7LAKCTIHOWFTWF2BJJANCNFSM6AAAAAAQ5GRABM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-10-30 16:18 UTC, somerandomcloud commented
no

On Sun, 30 Oct 2022 at 16:48, Manti ***@***.***> wrote:

> Guys stop mailing me
>
> On Sun, Oct 30, 2022, 6:32 PM Berlin ***@***.***> wrote:
>
> > you will collapse, stop using canary
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Vendicated/Vencord/pull/49#issuecomment-1296285666>,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AQERV2OQGSI7LAKCTIHOWFTWF2BJJANCNFSM6AAAAAAQ5GRABM
> >
> > .
> > You are receiving this because you commented.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Vendicated/Vencord/pull/49#issuecomment-1296288597>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJJ7XQTBV47EYVZUOBFFJWDWF2KFNANCNFSM6AAAAAAQ5GRABM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-11-03 19:08 UTC, Nuckyz commented on src/plugins/messageLogger/index.ts
> +                // Mark the timestamp component clearly so that it won't
it wont

2022-11-09 14:34 UTC, ChurlOat commented
I'm code-tarded
how do I install this

2022-11-13 17:15 UTC, hairyfred commented
this pull request be looking like 1984 George Orwell animal farm review

2022-11-13 19:05 UTC, Vendicated commented on src/plugins/messageLogger/index.ts
> +            -o-transition: 250ms -o-filter linear;
you don't need all these prefixes

2022-11-13 19:05 UTC, Vendicated commented on src/plugins/messageLogger/index.ts
> +            -o-transition: 250ms -o-filter linear;
also im pretty sure transitions should be on the element itself, not its :hover

2022-11-13 19:09 UTC, Vendicated commented on src/plugins/messageLogger/index.ts
> +                        "$1.editHistory = $2.editHistory || [];"
what does this do?

2022-11-13 19:24 UTC, DiamondMiner88 commented on src/plugins/messageLogger/index.ts
> +            -o-transition: 250ms -o-filter linear;
spoiler would be affected then as well afaik
also yes prefixes needed because browser extension soon ™️

2022-11-13 19:24 UTC, DiamondMiner88 commented on src/plugins/messageLogger/index.ts
> +                        "$1.editHistory = $2.editHistory || [];"
pass through data through a domain model parser or something

2022-11-13 19:28 UTC, Vendicated commented on src/plugins/messageLogger/index.ts
> +            -o-transition: 250ms -o-filter linear;
I'm saying you don't need prefixes for transitions anymore

2022-11-13 22:06 UTC, DiamondMiner88 commented
good

2022-11-13 22:07 UTC, DiamondMiner88 commented
no wait bad

2022-11-13 22:07 UTC, DiamondMiner88 commented
merge highlight default

2022-11-13 22:10 UTC, Vendicated commented
nop

2022-11-13 22:10 UTC, somerandomcloud commented
holy shit this pr is actually alive wtf

2022-11-13 22:13 UTC, merged

2022-11-14 03:58 UTC, DiamondMiner88 commented
ven will explode