feat: Context Menu API
Vendicated/Vencord pull request #496
Opened 2023-02-15 01:34 UTC by Nuckyz

2023-02-16 01:07 UTC, Vendicated commented on src/api/ContextMenu.ts
> +    const contextMenuPatches = patches.get(props.navId);
i'm not a fan of doing it per navId, what if someone wants to patch multiple navIds? We could just call the callbacks unconditionally and let the consumer be responsible of checking the navId and or children

2023-02-16 01:15 UTC, Vendicated requested changes

2023-02-16 01:15 UTC, Vendicated commented on src/api/ContextMenu.ts
> +        let previousChildren: Array<React.ReactElement> = [...props.children];
I'm not a fan of this spread, not only will it unnecessarily make and destruct a lot of arrays, it also doesn't cover the case of modifying something like children[0].props.children. Also are you sure children is always an array? The name is a bit misleading, in the case of a single child it will be a flat ReactNode. If you really want to do this, wrapping it with a Proxy would be more robust, but I personally don't think it's necessary to even do this in the first place

2023-02-16 01:15 UTC, Vendicated commented on src/plugins/apiContextMenu.ts
> +addListener(listener);
couldn't this be a waitFor?

2023-02-16 01:15 UTC, Vendicated commented on src/webpack/webpack.ts
> +    return isWaitFor ? [found ?? null, foundId ?? null] : found ?? null;
i would prefer inlining this over the break since it likely performs better and the breaks with nested loops are a bti confusing to follow. Also on a different note, all waitFors ( I think ) across Vencord never find anything here because they are ran too early, they just call this function so it also works fine when ran later

2023-02-16 01:18 UTC, Nuckyz commented on src/plugins/apiContextMenu.ts
> +addListener(listener);
makes no difference

2023-02-16 01:20 UTC, Vendicated commented on src/plugins/apiContextMenu.ts
> +addListener(listener);
the difference is that you then repeat less code cause waitFor handles the looping and stuff for u :P

2023-02-16 01:25 UTC, Vendicated commented on src/plugins/apiContextMenu.ts
> -        if (str.includes("♫ ⊂(｡◕‿‿◕｡⊂) ♪")) {
NOOOOO I MISS HIM ALREADY

2023-02-16 01:26 UTC, Nuckyz commented on src/plugins/apiContextMenu.ts
> -        if (str.includes("♫ ⊂(｡◕‿‿◕｡⊂) ♪")) {
😭

2023-02-18 02:30 UTC, Vendicated approved these changes

2023-02-18 02:30 UTC, Vendicated commented
Looks good but i want to test this more because I'm worried it could break stuff

2023-02-19 20:27 UTC, Vendicated commented on src/webpack/webpack.ts
> +    return isWaitFor ? [found ?? null, foundId ?? null] : found ?? null;
(thats not how i meant it )

2023-02-19 20:27 UTC, Vendicated commented on src/webpack/webpack.ts
> +                break outer;
i meant inlining it here and in the other places
```js
return isWaitFor ? [nested, Number(key)] : nested;
```

2023-02-19 20:32 UTC, Nuckyz commented on src/webpack/webpack.ts
> +                break outer;
oh

2023-02-20 20:27 UTC, Vendicated commented on src/api/ContextMenu.ts
> +import React from "react";
```suggestion
import type { ReactElement } from "react";
```

2023-02-20 20:30 UTC, Vendicated commented on src/api/ContextMenu.ts
> +    const results: Array<boolean> = [];
```suggestion
    const results = navIds.map(id => navPatches.get(id)?.delete(patch) ?? false);
```

2023-02-20 20:31 UTC, Vendicated commented on src/api/ContextMenu.ts
> +    contextMenuAPIArguments?: Array<any>;
```suggestion
    contextMenuApiArguments?: Array<any>;
```

2023-02-20 20:32 UTC, Vendicated commented on src/plugins/apiContextMenu.ts
> +addListener(listener);
this should probably be done either conditionally (only when the plugin is enabled), or the plugin should be marked as required

2023-03-08 04:59 UTC, merged