feat(plugin): ChannelTabs
Vendicated/Vencord pull request #499
Opened 2023-02-15 17:17 UTC by ActuallyTheSun

stuff i wanna add before i'd consider this ready
- [ ] drag and drop tabs
- [ ] typing indicators
- [ ] "open in new tab" context menu option for guilds/channels/message links
- [ ] right click on the "Jump" button of search results to open in a new tab
- [ ] remember tabs on close
- [ ] specific set of tabs at startup
- [ ] look good on light theme
also i didn't test this with group dm's and favorite servers so probably all hell breaks losse there

screenshots
![image](https://user-images.githubusercontent.com/78964224/219102776-ec16c5e6-72e4-4956-8486-8278aba3d744.png)
![image](https://user-images.githubusercontent.com/78964224/219103128-ed9c3a47-ba2b-4974-990b-2b7c1a912355.png)
![image](https://user-images.githubusercontent.com/78964224/219103893-67baadae-9449-47ed-8a39-3de3eb0f91b1.png)

2023-02-21 16:36 UTC, nmsturcke commented on src/plugins/channelTabs/components.tsx
> +const UserAvatar = ({ user }: { user: User; }) =>
This assumes the user has an avatar

2023-02-24 19:43 UTC, nmsturcke commented
https://github.com/ActuallyTheSun/Vencord/pull/2

2023-02-24 19:45 UTC, nmsturcke commented
Customise/Browse Channels/Home is unknown

2023-05-10 12:09 UTC, ActuallyTheSun commented
ready for review

2023-05-15 23:08 UTC, Vendicated commented on src/plugins/channelTabs/components.tsx
> +import { LazyComponent, useForceUpdater } from "@utils/react.jsx";
please don't use extensions in imports

2023-05-21 19:05 UTC, ActuallyTheSun commented
![nyaboom](https://cdn.discordapp.com/emojis/1105406110724268075.webp?size=48&quality=lossless)

2023-06-27 17:22 UTC, keifufu commented
If there is anything left to be done for this to be merged please lmk :3

2023-08-06 20:26 UTC, cryptianm commented
Hey ! Can you add ping about unread messages in bookmarks tab?
![image](https://github.com/Vendicated/Vencord/assets/110204116/73cf200c-8207-4bdf-b20a-7e79cbbd0a16)

2023-08-06 20:54 UTC, cryptianm reviewed
![image](https://github.com/Vendicated/Vencord/assets/110204116/e152dd19-084c-47fa-a094-8926a81cafde)
it doesn't work

2023-08-07 11:06 UTC, cryptianm commented
> Hey ! Can you add ping about unread messages in bookmarks tab? ![image](https://user-images.githubusercontent.com/110204116/258664532-73cf200c-8207-4bdf-b20a-7e79cbbd0a16.png)

![image](https://github.com/Vendicated/Vencord/assets/110204116/89aafd42-617e-4075-8945-a2c1c30ca65b)
still can't see ping
I updated BookmarkContainer.tsx

2023-08-07 11:27 UTC, cryptianm commented
Is it possible you can add NotificationDot and Typing indicator functions in the bookmarks?(not only in tabs).
It will be a very useful feature
![image](https://github.com/Vendicated/Vencord/assets/110204116/3f4597c4-6917-47d0-af00-088b7fea0e34)

2023-08-14 10:52 UTC, cryptianm commented
add this feature please!
![image](https://github.com/Vendicated/Vencord/assets/110204116/f0c0112a-a0c3-4cd8-871e-91cd83edc3fc)

2023-08-17 12:32 UTC, Methosss commented
how actually install this plugin?

2023-08-18 21:33 UTC, cryptianm commented
hey, could please add NotificationsDot component to BookmarksContainer.tsx

2023-08-20 13:50 UTC, Methosss commented
can someone build for me dev/beta release of Vencord? with this plugin?  i tried it by myself and i got bunch of errors /platform: windows

2023-09-14 19:24 UTC, cryptianm commented
add the ability to add channels to a folder using drag n drop

Also add the ability to see a notification dot near the folder, and near the channels within that folder.

2023-09-14 19:32 UTC, Vendicated commented
> add the ability to add channels to a folder using drag n drop
> 
> Also add the ability to see a notification dot near the folder, and near the channels within that folder.

reminder that this is voluntary work free of charge. do not demand that others add features, instead ask nicely or offer your suggestions in a non demanding way: "nice work! i think [feature] would be a great addition, what do you think?"

2023-09-16 17:53 UTC, cryptianm commented
> > add the ability to add channels to a folder using drag n drop
> > Also add the ability to see a notification dot near the folder, and near the channels within that folder.
> 
> reminder that this is voluntary work people do in their free time, free of charge. do not demand that others add features, instead ask nicely or offer your suggestions in a non demanding way: "nice work! i think [feature] would be a great addition, what do you think?"

I'm sorry, I didn't mean to be rude in any way. Just suggested how this plugin could be improved. Thank you for making it

2023-09-18 11:56 UTC, ActuallyTheSun commented
> > Thank you for improving this plugin every day. I found a bug with bookmarks. When you add too many bookmarks, they don't fit on the screen. I think it would be great if you move these bookmarks to the next line? Discord's workspace will be a little smaller, but you'll be able to make a lot of bookmarks.
> > 
> > ![image](https://user-images.githubusercontent.com/110204116/268520531-68cde40e-7be9-4dc7-9dff-302745af2b3c.png)
> 
> If you want to, you could do something similar to chrome and use the bookmark overflow. 
> <img width="250" alt="Screen Shot 2023-09-17 at 3 07 21 PM" src="https://github.com/Vendicated/Vencord/assets/101288516/bb221e0f-0d92-49a5-9fdd-f11f2478bd48">
> 

thank you for the suggestions

- bookmark overflow probably wouldn't work because nested context menus within discord are a mess
- moving extra bookmarks to the next like might work but could get a bit messy; might be more effort than it's worth

i'll see if i can get moving to a new line working, otherwise i'll either add a scrollbar or allow bookmarks to shrink to the point they'd always fit on screen

2023-09-20 11:21 UTC, cryptianm commented
Hey guys, is it possible to export my channel tabs setting to use on other device?
I set up this plugin on my windows pc, and want to have the same bookmarks on my mac.

2023-10-03 18:32 UTC, sunnniee commented
> > ![image](https://user-images.githubusercontent.com/110204116/272361127-831396d2-bafd-4dda-9bf4-4c5a68dd10b1.png) Hey guys! I think it will be cool if we'll be able to read notifications through this dropdown menu
> > 
> > thanks for improving this plugin :3
> 
> sounds like a ton of work tbh
> cool but not worth it

nah this'll take like 15 minutes and i'll probably do it tomorrow cause it sometimes annoys me too 👍

2023-10-05 05:59 UTC, sunnniee commented
> very bugged on acc switcher, will not let me add or remove bookmarks, says Loading Bookmarks forever

are you sure you're on the latest version of the plugin? (enabling Bookmark Notification Dot should give a Mark as Read context menu on bookmarks, if it's not there please update). if you are, can you look for any errors (open devtools with ctrl+shift+i or cmd+opt+i for mac -> console tab) and ping me on discord (`<@406028027768733696>`) with a screenshot of them?

2023-10-05 18:29 UTC, cryptianm commented
best plugin ever!

2023-10-06 14:55 UTC, nmsturcke commented
Moving plugins within folders would be nice but I'm not really sure how it could be done. Dragging would be ideal but as Menu Items I don't think there's an easy way to drag, so I don't think it's an option unless they're changed to being a custom Element :(

This is an option I guess, but not sure if it's the best one
![BbJMD](https://github.com/Vendicated/Vencord/assets/30734036/2c770ee1-e3de-4756-a716-5e5c505435cf)

2023-10-06 14:56 UTC, TheKodeToad commented
that's pretty bad in terms of ux

2023-12-29 21:57 UTC, lewisakura approved these changes

2024-01-20 00:25 UTC, lewisakura requested changes

2024-01-20 00:25 UTC, lewisakura commented on src/plugins/channelTabs/components/BookmarkContainer.tsx
> +                                />
please resolve compile error

2024-01-25 19:36 UTC, zany130 commented
tried to build this to test with a dev install and I am getting the following build errors.

```
Build failed
Build failed with 3 errors:
../channeltabs/Vencord/src/plugins/channelTabs/components/BookmarkContainer.tsx:22:87: ERROR: No matching export in "src/webpack/common/index.ts" for import "ReactDnd"
../channeltabs/Vencord/src/plugins/channelTabs/components/ChannelTab.tsx:22:70: ERROR: No matching export in "src/webpack/common/index.ts" for import "ReactDnd"
../channeltabs/Vencord/src/plugins/channelTabs/components/ChannelTab.tsx:22:102: ERROR: No matching export in "src/webpack/common/index.ts" for import "TypingStore"
3 errors
```

2024-01-25 19:46 UTC, thororen1234 commented
@zany130 you didn't add the webpack additions then as it works fine for me.

2024-01-25 20:01 UTC, zany130 commented
> @zany130 you didn't add the webpack additions then as it works fine for me.
how do I do that?

2024-01-25 20:19 UTC, thororen1234 commented
> > @zany130 you didn't add the webpack additions then as it works fine for me.
> 
> how do I do that? Thanks for helping. Sorry if this was answered somewhere else I tried to do a search through this discussion

Look at the files changed all the way at the bottom will be the webpack changes add those to the file path it gives as the name or the directory explorer on the left side.

2024-02-10 00:16 UTC, kingofcube commented
would use it if it wouldnt be the errors

2024-02-14 23:16 UTC, zany130 commented
latest vencord changes breaks this. gets stuck on  the discord loading screen after merging all of the upstream changes and building

rebuilding without this plugin fixes the infinite loading screen

2024-02-15 19:24 UTC, sunnniee commented
> latest vencord changes breaks this. gets stuck on the discord loading screen after merging all of the upstream changes and building
> 
> rebuilding without this plugin fixes the infinite loading screen

works on my machine i don't see any change that could've broken the plugin so ¯\\_(ツ)_/¯

2024-02-16 01:08 UTC, zany130 commented
really strange if I clone the channel tab repo and build that it works but if I clone upstream vencord and manually add the channel tab files (which is how I was doing it before) it does not work

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/components/BookmarkContainer.tsx
> +                : "https://discord.com/assets/c6851bd0b03f1cca5a8c1e720ea6ea17.png" // Default Group Icon
```suggestion
                : "/assets/c6851bd0b03f1cca5a8c1e720ea6ea17.png" // Default Group Icon
```

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/util.ts
> +export const ChannelTabsUtils = {
why do this

just export all utils individually and directly with their declaration: `export function doThing() {}`

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/util.ts
> +/*
this file is kind of just a bunch of unrelated stuff thrown together

it would likely help to create a util/ folder and split the helpers into multiple categorised files like `types.ts`, `constants.ts`, etc

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/index.tsx
> +        const { channel, messageId }: { channel: Channel, messageId?: string; } = props;
it would be better to move the type into the function declaration

also i don't think checking for definedness is necessary

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/index.tsx
> +        if (group)
group?.push

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/index.tsx
> +                    key="open-link-in-tab"
key should not be necessary

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/components/ContextMenus.tsx
> +                key="close-tab"
all these keys should not be necessary

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/components/ContextMenus.tsx
> +                Yes
it would likely be better to make the button text more meaningful, like "Delete"

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/components/ContextMenus.tsx
> +                })).filter(v => v._isFolder).map(({ label, value }) => ({ label, value })),
this first map seems useless. why not just `Object.entries(bookmarks).filter(bookmark => "bookmarks" in boomark[1]).map()`?

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/components/ContextMenus.tsx
> +export function EditModal({ modalProps, modalKey, bookmark, onSave }) {
you should type all parameters on all functions to prevent bugs

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/components/ChannelTabsContainer.tsx
> +    const { tabSet }: { tabSet: { [userId: string]: ChannelTabsProps[]; }; } = settings.use(["tabSet"]);
this is pretty unreadable. consider extracting `{ [userId: string]: ChannelTabsProps[]; }` into a named type. also, you can better express that type via `Record<string, ChannelTabsProps[]>`

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/components/ChannelTabsContainer.tsx
> +const cl = (name: string) => `vc-channeltabs-${name}`;
use the classFactory utility

2024-02-29 23:53 UTC, Vendicated commented on src/plugins/channelTabs/components/BookmarkContainer.tsx
> +        {bookmark.bookmarks.map((bkm, i) => <Menu.MenuItem
dont use weird abbrevations that omit letters. either name it one letter or the entire word

2024-02-29 23:55 UTC, Vendicated commented
consider formatting your jsx as
```jsx
return (
  <div>
    hi
  </div>
)
```
instead of your current
```jsx
return <div>
  hi
</div>
``` 

imo it is so much more readable

2024-02-29 23:58 UTC, Vendicated commented on src/plugins/channelTabs/components/BookmarkContainer.tsx
> +function HorizontallyScrolling({ children, className }: React.PropsWithChildren<{ className?: string; }>) {
```suggestion
function HorizontalScroller({ children, className }: React.PropsWithChildren<{ className?: string; }>) {
```

2024-03-01 00:00 UTC, Vendicated commented on src/plugins/channelTabs/components/BookmarkContainer.tsx
> +                : methods.addBookmark({
ternary soup does not taste very good

declaring these actions as named functions before the return would do a lot for readability

2024-03-01 00:03 UTC, Vendicated commented on src/plugins/channelTabs/components/BookmarkContainer.tsx
> +                : <Text className={cl("bookmark-placeholder-text")} variant="text-xs/normal">
avoid ternary soup:
```jsx
{!bookmarks && (
	<p>Loading</p>
)}
{!bookmarks?.length && (
	<p>No bookmarks</p>
)}
{!!bookmarks.length && 
	bookmarps.map((_, i) => (
		<Bookmark key={i} index={i} />
	))
}
```

or declare them as component functions (possibly inside the parent component scope) and use them that way

2024-03-01 00:04 UTC, Vendicated commented on src/plugins/channelTabs/components/ChannelTab.tsx
> +            ref={node => node?.style.setProperty("background-color",
why does this need a ref? can't this just be inside style above?

2024-03-01 00:05 UTC, Vendicated commented on src/plugins/channelTabs/components/ChannelTab.tsx
> +            {/* @ts-ignore */}
resolve this ts error instead of ignoring it. you should not be accessiging non menu properties on `Menu`. instead, export it from webpack/commons/components

2024-03-01 00:06 UTC, Vendicated commented on src/plugins/channelTabs/util.ts
> +    // @ts-ignore
```suggestion
```

2024-03-06 19:47 UTC, sunnniee commented on src/plugins/channelTabs/components/ChannelTab.tsx
> +            ref={node => node?.style.setProperty("background-color",
react intentionally doesn't allow using important within the style property. i wanted to make the color important because plenty of themes break it, but it's likely fine to remove

2024-04-03 16:43 UTC, belg1o commented
Is there a way to turn off the channel tabs and keep only the book marking functionality? Personally tend to use BetterFolders more but find the bookmark bar very beneficial.

2024-04-12 00:00 UTC, kittenvr commented
When added?

2024-05-19 16:22 UTC, zany130 commented
could you please rebase this pull @sunnniee ?  Really useful plugin  Thank You

2024-05-19 18:35 UTC, Lu9-ST commented
is it planned at some point for this to have navigation buttons (back, forward) like in the original BD plugin? i find going to a channel/DM that i was previously rather useful.

2024-05-31 20:01 UTC, kittenvr commented
when do you think this will be done

2024-06-10 04:20 UTC, Z4ne4what commented
Hello, I'm unsure if this is working or not, if it is:
I would love to download it, however I'm not sure how :[ I have already done vencord dev tool but whatever I do doesn't work (that being cmd or putting into the folder as said from the vencord/docs/plugin and restarting it). But other folders have worked, they just need to be already within folders. Which I've put them into folders, still nothing, so I'm confused. (After already moving the plugin into the userplugins)

Unsure if it's an issue on my end, but I would love some helpful steps if anyone could point me in the right direction. Thank you! ^^

2024-06-10 05:31 UTC, Inbestigator commented
@Z4ne4what are you doing `pnpm build` before restarting?

2024-06-10 07:19 UTC, Inbestigator commented
* Wdym devtools?
* Try cloning the repo instead of manually assigning files, and see if that works
* The could not resolve suggests that those folders do not in fact contain an `index.tsx`

2024-06-10 08:12 UTC, Z4ne4what commented
> * Wdym devtools?
> 
>     * Try cloning the repo instead of manually assigning files, and see if that works
> 
>     * The could not resolve suggests that those folders do not in fact contain an `index.tsx`

I'm probably saying it wrong bc I'm tired, and it's 4am. But it's used for third party plugins, enabling vencord into dev mode so it works, which is how I got timezones and fake profile. Apparently by some lucky miracle...

![image](https://github.com/Vendicated/Vencord/assets/171169053/a275780f-dcd1-4aac-a494-dcb8ed786f5d)

I also do have the index.txs manually placed into there. However, I may not need this as discord put in a favorite tab in experiments which is a nice alternative.

But after trying with what you suggested using the better folders, IDK if I should say this in this thread and not the custom folders/keyboard sounds, still no dice... Although, again, Idk what the hell I'm doing:

![image](https://github.com/Vendicated/Vencord/assets/171169053/17333b79-979c-4198-a41c-14f301644a7b)

(Also put an empty index to see if that would help it, but nah.)
![image](https://github.com/Vendicated/Vencord/assets/171169053/97f8e6c0-b8e5-40c9-8c24-096fe50a395a)

2024-06-19 16:52 UTC, zany130 commented
Is anyone having issues loading this plugin? using vesktop I did the following

```
git clone -b channeltabs https://github.com/sunnniee/Vencord.git
cd Vencord
pnpm install --frozen-lockfile
pnpm build
```
then pointed vesktop to the `dist` folder in the cloned git

and while it does show on the plugin settings, no tabs get added to the ui

2024-07-03 18:18 UTC, jurohn commented
Is this gonna be pushed as a plugin for Vencord? Im waiting for a year already <3

2024-07-18 09:53 UTC, kittenvr commented
if this works can you add it to [unofficial plugins](https://discord.com/channels/1015060230222131221/1256395889354997771)

2024-07-30 15:25 UTC, lucas112222 commented
hey where is the plugin?

2024-07-30 16:22 UTC, kittenvr commented
> hey where is the plugin?

It not done

2024-08-28 01:12 UTC, RobinRMC commented
For all of the people wanting the plugin without knowing how to compile Vencord, you can always use a Vencord fork (unofficial and unsupported edited version of Vencord). Vencord will be available prebuilt with unapproved plugins. Just know that using a Vencord fork is at your own risk, as the plugins in it might not properly get checked for malware and plugins might stop functioning properly at any time. Anyways, if you really want the plugin, that is an option and there are some good Vencord forks.

I'm not sure if Ven allows sharing links to Vencord forks.

2024-08-28 01:25 UTC, verticalsync commented
> For all of the people wanting the plugin without knowing how to compile Vencord, you can always use a Vencord fork (unofficial and unsupported edited version of Vencord). Vencord will be available prebuilt with unapproved plugins (like this one). Just know that using a Vencord fork is at your own risk, as the plugins in it might not properly get checked for malware and plugins might stop functioning properly at any time. Anyways, if you really want the plugin, that is an option and there are some good Vencord forks.
> 
> I'm not sure if Ven allows sharing links to Vencord forks.

No, and just don't. most forks dont appreciate being talked about in official vencord repositories

2024-09-06 22:52 UTC, zany130 commented
is the plugin currently broken? git cloneing the channeltab branch, building , and pointing vesktop to that folder doesn't load the plugin

2024-09-15 16:05 UTC, closed without merging

2024-09-15 16:19 UTC, KaKi87 commented
Hi @sunnniee,
Why did you close your PR ?
Thanks

2024-09-15 16:22 UTC, surgedevs commented
> Hi @sunnniee, Why did you close your PR ? Thanks

Please read the entire PR and applicable comments before commenting yourself.
As per the MR:

> closing because i dont care enough to maintain this anymore, feel free to work on this without asking

2024-09-15 16:24 UTC, KaKi87 commented
Oh, but that's an edit of the original post, which GitHub doesn't notify of. I only reacted as per the notification, sorry

2024-09-15 18:24 UTC, RobinRMC commented
Please, someone continue working on this. This plugin is amazing.

2024-10-11 10:41 UTC, guibzo commented
just wondering, why is there 300 commits for 4 archives? 💀

2025-04-24 16:41 UTC, dnestico commented
So this is never gonna happen? smh

2025-11-18 17:04 UTC, Hebgbs commented
A reprisal of this using the new _forced-upon_ titlebar in Discord would be a welcome sight if anyone with the skills to do it wish to make that happen. It would certainly bring justice to an eyesore of the current Discord UI.