feat: Cloud settings sync
Vendicated/Vencord pull request #505
Opened 2023-02-17 00:51 UTC by lewisakura

#313

At present, you can authorize the Vencord OAuth application (in app) and sync settings to and from the server, with timestamp validation. Next steps would be to sync on startup if necessary, encryption(?), actually check if settings sync is enabled for certain operations, and then finally prettying up the UI before shipping.

The backend server (https://github.com/Vencord/Backend) is a running project alongside this PR and nothing is final as of writing.

2023-02-20 23:46 UTC, lewisakura commented
changes of note:
- this now creates a new settings entry (`settingsSync`) to control whether it's turned on or off, instead of relying on the presence of the secret purely
- cloud settings now has a separate tab to hold its settings, and in the event that we extend the backend more, we can shove all of this under a generic "cloud" tab, or.. "Vencloud" if you will :^)
- uses a lot less IDB entries (in fact, just two - one to store the secret and one to store when settings were last written to)
- it can now synchronize your settings on startup, but currently requires vencord to be restarted after - i am not sure of a better workaround besides putting the settings sync before plugin loading, but i'm not sure of the consequences (@Vendicated you'll have to tell me if this is okay to do or not)
- backend is now go

2023-02-21 18:57 UTC, lewisakura commented
whilst not fully finished i will now accept reviews for improvements and changes - just bare in mind some of this may not be final still and therefore may be invalidated at a later date, even if the change is made.

2023-03-01 18:19 UTC, Vendicated requested changes

2023-03-01 18:19 UTC, Vendicated commented on src/Vencord.ts
> +        showNotice(
Maybe use a notification here? A notice would be a pretty big nuisance imo

2023-03-01 18:19 UTC, Vendicated commented on src/Vencord.ts
> +    await syncSettings();
I don't think blocking here is relevant
```suggestion
    syncSettings();
```

2023-03-01 18:19 UTC, Vendicated commented on src/api/settings.ts
> +            DataStore.set("Vencord_settingsLastSaved", Date.now());
This might or might not be problematic and cause corruption due to concurrent writes, I think this would be better to store alongside settings

2023-03-01 18:19 UTC, Vendicated commented on src/components/VencordSettings/index.tsx
> +    VencordCloudSettings: { name: "Cloud Settings", component: () => <CloudSettingsTab /> }
any reason this isn't just in the settings sync tab?

2023-03-01 18:19 UTC, Vendicated commented on src/utils/cloud.tsx
> +import { Settings } from "../Vencord";
```suggestion
import { Settings } from "@api/Settings";
```

2023-03-01 18:19 UTC, Vendicated commented on src/utils/cloud.tsx
> +        callback={async (u: string) => {
```suggestion
        callback={async (callbackUrl: string) => {
```

2023-03-01 18:19 UTC, Vendicated commented on src/utils/cloud.tsx
> +                toast(Toasts.Type.FAILURE, `Setup failed (${e.toString()}).`);
I'd use Notifications here instead of Toasts as Toasts are awkward for this

2023-03-01 18:19 UTC, Vendicated commented on src/utils/cloud.tsx
> +    return btoa(`${userId}:${secret}`);
```suggestion
    return window.btoa(`${userId}:${secret}`);
```
Just to avoid the deprecation warning

2023-03-01 18:19 UTC, Vendicated commented on src/utils/settingsSync.ts
> +import * as fflate from "fflate";
Only import the named members you need so unused code can be treeshaked

2023-03-01 18:19 UTC, Vendicated commented on src/utils/settingsSync.ts
> +export async function shouldCloudSync() {
This screams race condition. In IO you should never first check availablity then execute, since the state might change inbetween those two actions. Instead, you should just execute the actual operation then handle errors (or in this case you should use If-None-Match and check for 304 status code)

2023-03-01 18:28 UTC, lewisakura commented on src/Vencord.ts
> +        showNotice(
my personal justification for this was that a settings sync should be a big deal since it changes all of the settings and the standard importSettings() requires you to reload the client too, but i can switch to a notif

2023-03-01 18:29 UTC, Vendicated commented on src/Vencord.ts
> +        showNotice(
That may be true for the majority of users, but imagine dual booting and regularely changing ur settings so u get the notice every time u open discord essentially

2023-03-01 18:29 UTC, lewisakura commented on src/api/settings.ts
> +            DataStore.set("Vencord_settingsLastSaved", Date.now());
it shouldn't be too big of a deal, it just mainly needs to be different to whatever it was before so even a corrupted value is okay, but to be fair i have actually hammered this and it doesn't seem to ever get corrupted. storing alongside settings wouldn't be too bad of an idea though

2023-03-01 18:30 UTC, lewisakura commented on src/components/VencordSettings/index.tsx
> +    VencordCloudSettings: { name: "Cloud Settings", component: () => <CloudSettingsTab /> }
clutter and futureproofing - if we decide to have more backend integrations it'd be best for a separate tab. also the reason why it's now the generic "cloud integrations" when enabling

2023-03-01 18:30 UTC, lewisakura commented on src/utils/settingsSync.ts
> +import * as fflate from "fflate";
oops, this was meant to be temporary

2023-03-01 18:31 UTC, lewisakura commented on src/utils/settingsSync.ts
> +export async function shouldCloudSync() {
that's a new header i've learnt of today, will implement and change

2023-03-01 18:32 UTC, Vendicated commented on src/api/settings.ts
> +            DataStore.set("Vencord_settingsLastSaved", Date.now());
yeah I'm not sure how much race conditions are of an issue for idb, i assume they already have locking mechanisms or similar, so this might just be fine. But i also think since this is just a number and makes no sense outside of the context of the settings object it's best stored alongside them

2023-03-08 23:56 UTC, lewisakura commented
can someone check if they can repro a strange bug where plugins don't enable when settings are synchronized, even after a full restart? not sure if it's a me thing or just some weird side effect of the way i import settings, but i experienced it earlier and couldn't replicate it after, so i can't give steps 😓

2023-03-16 01:26 UTC, lewisakura commented
> can someone check if they can repro a strange bug where plugins don't enable when settings are synchronized, even after a full restart? not sure if it's a me thing or just some weird side effect of the way i import settings, but i experienced it earlier and couldn't replicate it after, so i can't give steps 😓

I haven't been able to replicate this so I assume it's been fixed in some passing Vencord update either by accident or the bug was never a real thing in the first place and I'm just stupid.

2023-04-06 01:08 UTC, Vendicated commented on package.json
> +    "packageManager": "pnpm@7.30.5",
is this just latest @7? Maybe we could just @8

2023-04-06 09:53 UTC, lewisakura commented on package.json
> +    "packageManager": "pnpm@7.30.5",
It is. I'll bump it to 8.

2023-04-06 15:25 UTC, Vendicated requested changes

2023-04-06 15:25 UTC, Vendicated commented on src/components/VencordSettings/CloudTab.tsx
> +    const settings = useSettings(["cloud.authenticated", "cloud.settingsSync"]);
could destructure
```suggestion
    const { cloud: { authenticated, settingsSync } } = useSettings(["cloud.authenticated", "cloud.settingsSync"]);
```

2023-04-06 15:25 UTC, Vendicated commented on src/components/VencordSettings/CloudTab.tsx
> +    const sectionEnabled = useMemo(
memo is pointless here
```suggestion
    const sectionEnabled = authenticated && settingsSync;
```

2023-04-06 15:25 UTC, Vendicated commented on src/utils/settingsSync.ts
> +                "if-none-match": Settings.cloud.settingsSyncVersion.toString()
soooo inconsistent :(
```suggestion
                "If-None-Match": Settings.cloud.settingsSyncVersion.toString()
```

2023-04-06 15:25 UTC, Vendicated commented on src/utils/settingsSync.ts
> +        const written = parseInt(res.headers.get("etag")!);
```suggestion
        const written = Number(res.headers.get("etag")!);
```

2023-04-06 23:32 UTC, Vendicated approved these changes

2023-04-07 00:12 UTC, MeguminSama approved these changes

2023-04-07 00:27 UTC, merged