feat(plugin): Image Zoom
Vendicated/Vencord pull request #510
Opened 2023-02-18 16:49 UTC by Syncxv

hi
this plugin lets you zoom into images and gifs

scroll wheel to increase / decrase zoom level

shift + scroll wheel to increase / decrease lens size

would love feedback

https://user-images.githubusercontent.com/47534062/219877725-71edaa8c-3326-4297-b444-3031acc04fa4.mp4

2023-02-18 16:51 UTC, somerandomcloud commented
commit messages are a rollercoaster.

2023-02-18 17:02 UTC, Nuckyz commented
> commit messages are a rollercoaster.

who cares about prs commit messages

2023-02-18 17:10 UTC, Nuckyz requested changes

2023-02-18 17:10 UTC, Nuckyz commented on src/plugins/imageZoom/components/Magnifer.tsx
> +            console.log("zoom: ", val);
```suggestion
```

2023-02-18 17:10 UTC, Nuckyz commented on src/plugins/imageZoom/components/Magnifer.tsx
> +            console.log("size: ", val);
```suggestion
```

2023-02-18 17:10 UTC, Nuckyz commented on src/plugins/imageZoom/components/Magnifer.tsx
> +                        className="embedVideo-2ixt5A embedMedia-1mdWSP"
Hard coded classes bad, get the classes from webpack

2023-02-18 17:10 UTC, Nuckyz commented on src/plugins/imageZoom/constants.ts
> +export const ELEMENT_ID = "magnify-thingy-image-so-how-was-your-day";
what's this name lmao

2023-02-18 17:10 UTC, Nuckyz commented on src/plugins/imageZoom/index.ts
> +                            $self.currentMagniferElement = Vencord.Webpack.Common.React.createElement($self.Magnifer, {size: Vencord.Settings.plugins.ImageZoom.size ?? 100, zoom: Vencord.Settings.plu
You will render the element and apply the settings outside the module code, inside your plugin code

2023-02-18 17:10 UTC, Nuckyz commented on src/plugins/imageZoom/index.ts
> +                        Vencord.Webpack.Common.ReactDOM.unmountComponentAtNode(document.querySelector('.magniferContainer'))
same thing here, do the code inside your plugin, not the module code

2023-02-18 17:12 UTC, Syncxv commented on src/plugins/imageZoom/components/Magnifer.tsx
> +                        className="embedVideo-2ixt5A embedMedia-1mdWSP"
ooops forgor about that however i dont think we need them

2023-02-18 17:13 UTC, Nuckyz commented on src/plugins/imageZoom/components/Magnifer.tsx
> +                        className="embedVideo-2ixt5A embedMedia-1mdWSP"
even better lol

2023-02-18 17:23 UTC, Syncxv commented on src/plugins/imageZoom/index.ts
> +                            $self.currentMagniferElement = Vencord.Webpack.Common.React.createElement($self.Magnifer, {size: Vencord.Settings.plugins.ImageZoom.size ?? 100, zoom: Vencord.Settings.plu
aight should be fixed

2023-02-18 17:24 UTC, Syncxv commented on src/plugins/imageZoom/constants.ts
> +export const ELEMENT_ID = "magnify-thingy-image-so-how-was-your-day";
what would you like me to change it to

2023-02-18 17:30 UTC, Nuckyz commented on src/plugins/imageZoom/constants.ts
> +export const ELEMENT_ID = "magnify-thingy-image-so-how-was-your-day";
just remove the joke part

2023-02-18 17:40 UTC, Syncxv commented on src/plugins/imageZoom/components/Magnifer.tsx
> +            this.setState({ ...this.state, zoom: val <= 1 ? 1 : val });
i feel like we could add a setting option to change the 200. like maybe a slider from 0.1 to 2.0 (or higher)

then x = zoom + e.deltaY * settings.multipler;

maybe /shrug

2023-02-18 17:57 UTC, Nuckyz commented on src/plugins/imageZoom/components/Magnifer.tsx
> +            this.setState({ ...this.state, zoom: val <= 1 ? 1 : val });
if you want to do it, just explain what it does

2023-02-18 18:18 UTC, Syncxv commented on src/plugins/imageZoom/components/Magnifer.tsx
> +            this.setState({ ...this.state, zoom: val <= 1 ? 1 : val });
basically how fast it should zoom in
i implemented it so play around with the setting if you dont understand (my bad)

2023-02-18 18:54 UTC, Nuckyz requested changes

2023-02-18 18:54 UTC, Nuckyz commented on src/plugins/imageZoom/components/Magnifer.tsx
> +            const val = this.state.zoom + (Settings.plugins.ImageZoom.invertScroll ? -(e.deltaY / 100) : (e.deltaY / 100)) * Settings.plugins.ImageZoom.zoomSpeed;
```suggestion
            const val = this.state.zoom + ((e.deltaY / 100) * Settings.plugins.ImageZoom.invertScroll ? -1 : 1 *) Settings.plugins.ImageZoom.zoomSpeed;
```

2023-02-18 18:54 UTC, Nuckyz commented on src/plugins/imageZoom/components/Magnifer.tsx
> +            const val = this.state.size + (Settings.plugins.ImageZoom.invertScroll ? -e.deltaY : e.deltaY) * Settings.plugins.ImageZoom.zoomSpeed;
```suggestion
            const val = this.state.size + (e.deltaY * Settings.plugins.ImageZoom.invertScroll ? -1 : 1) * Settings.plugins.ImageZoom.zoomSpeed;
```

2023-02-18 18:58 UTC, Nuckyz requested changes

2023-02-18 18:58 UTC, Nuckyz commented on src/plugins/imageZoom/index.ts
> +    unMounntMagnifier() {
```suggestion
    unMountMagnifier() {
```

2023-02-18 18:58 UTC, Nuckyz commented on src/plugins/imageZoom/index.ts
> +                    replace: "$1$self.unMounntMagnifier();"
```suggestion
                    replace: "$1$self.unMountMagnifier();"
```

2023-02-18 19:17 UTC, Nuckyz approved these changes

2023-02-18 20:19 UTC, Nuckyz approved these changes

2023-03-18 04:57 UTC, Vendicated requested changes

2023-03-18 04:57 UTC, Vendicated commented on src/plugins/imageZoom/styles.css
> +    -o-user-drag: none;
why aren't you using the properly standardised html draggable attribute that does the exact same thing instead?

2023-03-18 04:57 UTC, Vendicated commented on src/plugins/imageZoom/components/Magnifier.tsx
> +// class component because i like it more
how, class components are terrible

do u just not know how hooks work?

2023-03-18 04:57 UTC, Vendicated commented on src/plugins/imageZoom/index.ts
> +                    onMouseEnter:`
this is a lot of code in a patch, why not make this a method instead?
```js
replace: `$1...$self.makeProps(this),onMouseEnter:`
```

2023-03-18 04:57 UTC, Vendicated commented on src/plugins/imageZoom/index.ts
> +                    replace: "$1$self.renderMagnifier(this);",
$& = whole match, so u can remove the group

```suggestion
                    replace: "$&$self.renderMagnifier(this);",
```

2023-03-18 04:57 UTC, Vendicated commented on src/plugins/imageZoom/index.ts
> +                    match: /(componentWillUnmount=function\(\){)/,
same as above

2023-03-18 04:57 UTC, Vendicated commented on src/plugins/imageZoom/index.ts
> +                match: /onClick:(.{1,3}),/,
```suggestion
                match: /onClick:(\i),/,
```

2023-03-18 04:57 UTC, Vendicated commented on src/plugins/imageZoom/index.ts
> +                replace: "onClick:Vencord.Settings.plugins.ImageZoom.preventCarouselFromClosingOnClick ? () => {} : $1,"
```suggestion
                replace: "onClick:$self.preventCarouselFromClosingOnClick ? () => {} : $1,"
```

2023-03-18 04:57 UTC, Vendicated commented on src/plugins/imageZoom/index.ts
> +        document.getElementById("app-mount")!.appendChild(this.element);
i think since you're essentially making this a new root it should not be in a different react root to avoid conflicts, so adding it to the body instead would be better

2023-03-18 04:57 UTC, Vendicated commented on src/plugins/imageZoom/index.ts
> +                ReactDOM.render(this.currentMagnifierElement, this.element);
render is deprecated, you should use the new methods instead https://legacy.reactjs.org/docs/react-dom-client.html#createroot

2023-03-18 05:00 UTC, Vendicated commented
Sorry for taking so long to look at this, it totally went under my radar :( Thanks for the patience

2023-03-18 06:30 UTC, Syncxv commented on src/plugins/imageZoom/components/Magnifier.tsx
> +// class component because i like it more
like the comment says i just enjoy working with class components more and have more expereince with them.
would you like me to change it to functional component?

2023-04-02 15:01 UTC, Vendicated requested changes

2023-04-02 15:01 UTC, Vendicated commented on src/plugins/imageZoom/utils/waitFor.ts
> +        setTimeout(() => waitFor(condition, cb), 1);
is this just for waiting for the dom to finish layout? If so, you should probably use requestAnimationFrame
```js
function waitFor(condition: () => boolean, cb: () => void) {
	if (condition()) cb();
	else requestAnimationFrame(() => waitFor(condition, cb));
}
```

2023-04-02 15:14 UTC, Vendicated commented
![image](https://user-images.githubusercontent.com/45497981/229361935-724fd05e-3e3a-4237-a032-ce324d655437.png)

Maybe add the options like lens size here too? It should be fairly simple with our ContextMenuApi

2023-04-02 15:14 UTC, Vendicated commented
Also very sorry for the long wait!!

2023-04-03 06:34 UTC, Syncxv commented on src/plugins/imageZoom/components/Magnifier.tsx
> +    const onKeyUp = React.useCallback((e: KeyboardEvent) => {
If by "plain function" you meant `const onKeyUp = (e: KeyboardEvent) => {` or `function onKeyUp(e: KeyboardEvent) {`, I used useCallback to prevent the function from being recreated each time the mouse is moved, which could impact performance

if you meant something else by plain function let me know.

2023-04-03 06:47 UTC, Syncxv commented on src/plugins/imageZoom/components/Magnifier.tsx
> +    const onKeyUp = React.useCallback((e: KeyboardEvent) => {
wait im stupid. i didnt understand exactly what you wanted. but its fixed now

2023-04-03 07:00 UTC, Syncxv commented on src/plugins/imageZoom/utils/waitFor.ts
> +        setTimeout(() => waitFor(condition, cb), 1);
its not waiting for the dom to finish layout.
its waiting for the actual image modal component state to be "READY"
`waitFor(() => instance.state.readyState === "READY",`

when the state is not "READY", the component is in a loading state, and the actual image has not yet been inserted into the DOM. In this case, a placeholder is displayed.

However, using `requestAnimationFrame` is indeed a better approach compared to `setTimeout`. Thank you for the suggestion.

2023-04-03 07:01 UTC, Syncxv commented on src/plugins/imageZoom/components/Magnifier.tsx
> +    const isShiftDown = useRef(false);
why? please elaborate. i don't understand what you are asking exactly.
i didnt make isShiftDown a state because that would cause a rerender.


do you want me to:
`const [isShiftDown, setIsShiftDown] = useState(false);`

or
`const [state, setState] = useState({
    imagePosition: {x: 0, y: 0,},
    opacity: 0,
    isShiftDown: false,
    });`

2023-04-03 10:33 UTC, Syncxv commented
like this?
![Discord_DPb8lw9Xfj](https://user-images.githubusercontent.com/47534062/229484876-7414af5c-d782-4697-a291-c09b0cf47766.png)

2023-04-03 13:58 UTC, Vendicated commented
yeah! looks good

2023-04-03 13:58 UTC, Vendicated commented
though maybe put it in a new section with divider

2023-04-05 21:21 UTC, Vendicated approved these changes

2023-04-06 01:06 UTC, merged