feat(MessageEvents): Promisable send/edit listeners
Vendicated/Vencord pull request #514
Opened 2023-02-20 01:06 UTC by hunt-g

makes pre-send and pre-edit events optionally asynchronous

2023-03-03 21:46 UTC, Nuckyz requested changes

2023-03-03 21:46 UTC, Nuckyz commented on src/api/MessageEvents.ts
> +import type { Promisable } from "type-fest";
```suggestion
```

2023-03-03 21:46 UTC, Nuckyz commented on src/api/MessageEvents.ts
> +export type SendListener = (channelId: string, messageObj: MessageObject, extra: MessageExtra) => Promisable<void | { cancel: boolean; }>;
```suggestion
type SendListernerReturn = void | { cancel: boolean; };

export type SendListener = (channelId: string, messageObj: MessageObject, extra: MessageExtra) => SendListernerReturn | Promise<SendListernerReturn>;
```

2023-03-03 21:46 UTC, Nuckyz commented on src/api/MessageEvents.ts
> +export type EditListener = (channelId: string, messageId: string, messageObj: MessageObject) => Promisable<void>;
```suggestion
export type EditListener = (channelId: string, messageId: string, messageObj: MessageObject) => void | Promise<void>;
```

2023-03-03 21:46 UTC, Nuckyz commented on src/plugins/apiMessageEvents.ts
>              find: "sendMessage:function",
```suggestion
            find: '"MessageActionCreators"',
```

2023-03-03 21:46 UTC, Nuckyz commented on src/plugins/apiMessageEvents.ts
> +                match: /(_sendMessage:function.*?{)(.*?)(},[^}]*?:function)/,
```suggestion
                match: /(_sendMessage:function\((?:\i,?).+?\){)(.+?)(?=},.{1,30}:function)/,
```

2023-03-03 21:46 UTC, Nuckyz commented on src/plugins/apiMessageEvents.ts
> +                replace: "$1return Vencord.Api.MessageEvents._handlePreSend(...arguments).then(()=>{$2})$3"
```suggestion
                replace: "$1return Vencord.Api.MessageEvents._handlePreSend(...arguments).then(()=>{$2})"
```

2023-03-03 21:46 UTC, Nuckyz commented on src/plugins/apiMessageEvents.ts
> +                match: /(editMessage:function.*?{)(.*?)(},[^}]*?:function)/,
```suggestion
                match: /(editMessage:function\((?:\i,?).+?\){)(.+?)(?=},.{1,30}:function)/,
```

2023-03-03 21:46 UTC, Nuckyz commented on src/plugins/apiMessageEvents.ts
> +                replace: "$1return Vencord.Api.MessageEvents._handlePreEdit(...arguments).then(()=>{$2})$3"
```suggestion
                replace: "$1return Vencord.Api.MessageEvents._handlePreEdit(...arguments).then(()=>{$2})"
```

2023-03-25 02:54 UTC, Vendicated commented
I simplified and fixed the now broken patches, thank you and sorry for the wait!

2023-03-25 02:54 UTC, merged