feat: View raw button
Vendicated/Vencord pull request #52
Opened 2022-10-05 14:28 UTC by ArjixWasTaken

2022-10-05 14:32 UTC, ArjixWasTaken commented
Adds a view raw button to the shift+hover popup on messages
![image](https://user-images.githubusercontent.com/53124886/194086820-7f79366a-f473-4780-b27f-22efaa9848e8.png)


for now it just logs the message in the console, when the modals are fixed this will change, hence why it is a draft

2022-10-05 14:38 UTC, ArjixWasTaken commented
I intended to make this a util instead (so plugins can register their own buttons) but...
I couldn't figure out how to insert a button at runtime, so yeah...

Other plugins can just copy paste and modify this one instead.

2022-10-16 00:01 UTC, ArjixWasTaken commented
Ok, so this is ready, *but*, should I add an API to register action buttons (on messages) in this same PR.
*Or* make another PR that also updates this plugin?

2022-10-16 21:12 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +                            highlightJs,
you can just pass null here

2022-10-16 21:12 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +const highlightJsHelperFuncs = lazyWebpack(filters.byProps(["codeBlock"]));
```suggestion
const parser = lazyWebpack(filters.byProps(["codeBlock"]));
```

2022-10-16 21:13 UTC, ArjixWasTaken commented on src/plugins/viewRaw.tsx
> +                            highlightJs,
where?

2022-10-16 21:14 UTC, Vendicated requested changes

2022-10-16 21:14 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +                            if (item[1] === "key") item[2] = "\"view-raw\"";
switch block would be nicer here

2022-10-16 21:14 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +                            highlightJs,
highlightJs

2022-10-16 21:15 UTC, ArjixWasTaken commented on src/plugins/viewRaw.tsx
> +                            highlightJs,
are you sure about that? I just did what the discord code does

2022-10-16 21:17 UTC, ArjixWasTaken commented on src/plugins/viewRaw.tsx
> +                            if (item[1] === "key") item[2] = "\"view-raw\"";
well...yes, but have you read my previous comments?
There is no point refactoring this if it will be removed entirely in case I add an API for adding icons.

2022-10-16 21:17 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +                            highlightJs,
![image](https://user-images.githubusercontent.com/45497981/196058759-ee8504bc-9a3d-4c9f-a012-daaa1768a80e.png)

2022-10-16 22:39 UTC, ArjixWasTaken commented
> Ok, so this is ready, _but_, should I add an API to register action buttons (on messages) in this same PR. _Or_ make another PR for that API that also updates this plugin (to use it instead of manually patching the buttons)?

@Vendicated

2022-10-19 20:01 UTC, Vendicated requested changes

2022-10-19 20:01 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +                    <div style={{ overflow: "scroll" }}>
overflow scroll is very ugly, try text wrap

2022-10-19 20:01 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +        // prettier-ignore
?

2022-10-19 20:01 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +                    <div style={{ overflow: "scroll" }}>
Also you must now wrap your modal into ModalRoot. You should also consider using different Modal sections to add more info and perhaps add buttons to copy the raw content or raw json to your clipboard in this modal

2022-10-19 20:37 UTC, ArjixWasTaken commented on src/plugins/viewRaw.tsx
> +        // prettier-ignore
in case you don't use prettier, that comment disables automatic formatting for the next block/statement

2022-10-19 20:39 UTC, ArjixWasTaken commented on src/plugins/viewRaw.tsx
> +                    const items = menuItem.matchAll(
well, you never really answered my question, will this be made into an API or not?
there really is no reason to document this if i am going to erase it later either way...

2022-10-19 20:43 UTC, Vendicated commented on src/plugins/viewRaw.tsx
> +                    const items = menuItem.matchAll(
probably api would make sense

2022-10-22 08:59 UTC, somerandomcloud commented on src/plugins/viewRaw.tsx
> +        // prettier-ignore
The repo uses eslint??

2022-10-22 10:22 UTC, ArjixWasTaken commented on src/plugins/viewRaw.tsx
> +        // prettier-ignore
> The repo uses eslint??

What does it matter that the repo uses eslint?

I have prettier as a vscode extension, the repo doesn't need to have it configured for it to work.

And also, most of the famous linters/formatters can detect the prettier-ignore comments, in the same way that prettier can detect eslint comments.

As long as the formatter you use is popular enough, it will support other formatters' comments.


Finally, it is just a fucking comment, what's your problem?

2022-12-02 15:39 UTC, Vendicated commented
superseded by #275

2022-12-02 15:39 UTC, closed without merging