Add BetterFolders plugin
Vendicated/Vencord pull request #530
Opened 2023-02-25 13:33 UTC by Juby210

2023-02-25 14:30 UTC, scrazzz approved these changes

2023-02-28 00:15 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +        const { toggleGuildFolderExpand } = findByProps("move", "toggleGuildFolderExpand");
you can just move these to the top and use findByPropsLazy, then you also don't need to assign to this.closeFolders here!

2023-02-28 00:15 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +        if (!this.GuildsTree) this.GuildsTree = find(m => m.prototype?.convertToFolder);
same here

2023-02-28 00:16 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +            find: "(\"guildsnav\")",
```suggestion
            find: '("guildsnav")',
```

2023-02-28 00:18 UTC, Vendicated requested changes

2023-02-28 00:18 UTC, Vendicated commented on src/plugins/betterFolders/betterFolders.css
> +.bf-folder-sidebar [class*="wrapper-"] > div:first-of-type {
for consistency and possibly avoiding clashes with other mods, can you please make classes start with .vc-?
```suggestion
.vc-bf-folder-sidebar [class*="wrapper-"] > div:first-of-type {
```

2023-02-28 00:18 UTC, Vendicated commented on src/plugins/betterFolders/FolderSideBar.tsx
> +    return self._FolderSideBar = () => {
I don't really follow what's going on here, is this just to create a closure and do the webpack searches lazily? If so, same thing applies, use find(byX)Lazy!!

2023-03-04 17:22 UTC, Vendicated requested changes

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +    options: {
options is deprecated, instead you should use
```js
const settings = definePluginSettings(OptionsObject);

console.log(settings.store.sidebar)

definePlugin({
	...,
	settings
})

```

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +const GuildFolderStore = findByPropsLazy("getSortedGuilds");
```suggestion
const GuildFolderStore = findStoreLazy("SortedGuildStore");
```

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +const ExpandedFolderStore = findByPropsLazy("getExpandedFolders");
```suggestion
const ExpandedFolderStore = findStoreLazy("ExpandedGuildFolderStore");
```

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +        const getGuildFolder = id => GuildFolderStore.guildFolders[getGuildFolderIdx(id)];
why not just
```suggestion
        const getGuildFolder = id => GuildFolderStore.guildFolders.find(f => f.guildIds.includes(id));
```

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +        if (closeAllFolders || forceOpen) FluxDispatcher.subscribe("CHANNEL_SELECT", this.onSwitch = data => {
I would just subscribe unconditionally here and instead check the settings inside the handler so that people don't need to restart when changing settings

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +                    match: /(\w{1,3})\(\){return \w{1,3}\(\(0,\i\.jsx\)\("div",{className:\w{1,3}\(\)\.guildSeparator}\)\)}/,
```suggestion
                    match: /(\i)\(\){return \i\(\(0,\i\.jsx\)\("div",{className:\i\(\)\.guildSeparator}\)\)}/,
```

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +                    match: /\w{1,3}\(\(function\(\i,\i,\i\){var \i=\i\.key;return.+\(\i\)},\i\)}\)\)/,
```suggestion
                    match: /\i\(\(function\(\i,\i,\i\){var \i=\i\.key;return.+\(\i\)},\i\)}\)\)/,
```

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +                    match: /(\i)\.themeOverride,(.{15,25}\(function\(\){var \i=)(\w{1,3}\.\i\.getGuildsTree\(\))/,
```suggestion
                    match: /(\i)\.themeOverride,(.{15,25}\(function\(\){var \i=)(\i\.\i\.getGuildsTree\(\))/,
```

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +                    match: /\((\i)\)({switch\(\i\.type\){case \w{1,3}\.\w{1,3}\.FOLDER)/,
```suggestion
                    match: /\((\i)\)({switch\(\i\.type\){case \i\.\i\.FOLDER)/,
```

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +                    match: /return(\(0,\i\.jsx\))(\(\w{1,3},{)(folderNode:\i,setNodeRef:\i\.setNodeRef,draggable:!0,.+},\i\.id\));case/,
```suggestion
                    match: /return(\(0,\i\.jsx\))(\(\i,{)(folderNode:\i,setNodeRef:\i\.setNodeRef,draggable:!0,.+},\i\.id\));case/,
```

2023-03-04 17:22 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +                    replace: "bfHideServers?null:$&"
this is really bad because you use a variable declared in a different patch here. If the first patch fails but this one still works, you will now use an undeclared variable which will instantly make this code throw and likely cause a crash

2023-03-04 21:56 UTC, Juby210 commented on src/plugins/betterFolders/index.ts
> +                    replace: "bfHideServers?null:$&"
fixed by using arguments[0] to get props

2023-03-05 21:12 UTC, Vendicated commented on src/plugins/betterFolders/FolderSideBar.tsx
> +const Animations = findByPropsLazy("useTransition");
![image](https://user-images.githubusercontent.com/45497981/222986314-9b8faf11-51fc-4fc1-9143-a1d4008980c0.png)

2023-03-05 21:13 UTC, Vendicated commented on src/plugins/betterFolders/FolderSideBar.tsx
> +const classes = findByPropsLazy("sidebar", "guilds");
![image](https://user-images.githubusercontent.com/45497981/222986341-6643991a-8e80-4496-bb35-5ee06fe4f866.png)

2023-03-05 21:17 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +                    replace: "var folder=$1$2bfHideServers:!bfPatch,$3;return bfPatch&&arguments[1]?[$1($self.Separator,{}),folder]:folder;case"
this relies on a variable from an earlier patch which is a really bad idea. Please either find a better way to do it or at least check that that variable exists first using `typeof bfPatch !== "undefined"`

2023-03-05 21:17 UTC, Vendicated commented on src/plugins/betterFolders/index.ts
> +const FolderUtils = findByPropsLazy("move", "toggleGuildFolderExpand");
![image](https://user-images.githubusercontent.com/45497981/222986550-3bd20d7b-9dd3-4ea2-aa75-5df137a87a61.png)

2023-04-02 15:41 UTC, Vendicated approved these changes

2023-04-02 15:43 UTC, merged