feat: Crash Handler
Vendicated/Vencord pull request #531
Opened 2023-02-25 20:41 UTC by Nuckyz

Todo
- [ ] Find responsible plugins for crashing and disable them til next update
- [ ] Improve handlePreventCrash

2023-02-28 22:45 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +    defaultEnabled: true,
i would rename this to enabledByDefault

2023-02-28 22:48 UTC, Vendicated requested changes

2023-02-28 22:48 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +        description: "Wheter to attempt to navigate to the home when preventing Discord crashes.",
```suggestion
        description: "Whether to attempt to navigate to the home when preventing Discord crashes.",
```

2023-02-28 22:48 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +        description: "Wheter to attempt to prevent Discord crashes.",
```suggestion
        description: "Whether to attempt to prevent Discord crashes.",
```

2023-02-28 22:48 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +import { ReactElement } from "react";
```suggestion
import type { ReactElement } from "react";
```

2023-02-28 22:48 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +                    + "$self.settings.store.attemptToPreventCrashes?$self.handlePreventCrash(this):"
i would prefer if you moved this logic into a proper function and only called $self.handleCrash

2023-02-28 22:48 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +                replace: ",ch1:()=>$<popAll>"
what's this for? If you need it exported, you can just dispatch the event manually with FluxDispacher from webpack commons

2023-02-28 22:48 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +    },
why didn't you use the already existing function here?

2023-02-28 22:48 UTC, Vendicated commented on src/plugins/noF1.ts
> +    name: "NoF1",
1) Why
2) If you're gonna rename a plugin, use migratePluginSettings to migrate people's settings!

2023-02-28 22:49 UTC, Nuckyz commented on src/plugins/crashHandler.ts
> +                replace: ",ch1:()=>$<popAll>"
That method contains multiple dispatches

2023-02-28 22:52 UTC, Nuckyz commented on src/plugins/crashHandler.ts
> +    },
wdym?

2023-02-28 22:53 UTC, Nuckyz commented on src/plugins/noF1.ts
> +    name: "NoF1",
That's the only plugin name with a space on it, consistency

2023-02-28 22:56 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +    },
handleComponentFailed (kinda bad name) already has this code

2023-02-28 22:58 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +                replace: ",ch1:()=>$<popAll>"
i see. Why did u name it ch1 tho?

2023-02-28 22:58 UTC, Nuckyz commented on src/plugins/crashHandler.ts
> +                replace: ",ch1:()=>$<popAll>"
cuz I'm limited to 3 letter names

2023-02-28 22:59 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +                replace: ",ch1:()=>$<popAll>"
why

2023-03-01 04:09 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +    description: "Utility plugin for handling Discord crashes caused or not by Vencord.",
```suggestion
    description: "Utility plugin for handling and possibly recovering from Crashes without a restart",
```

2023-03-01 04:12 UTC, Vendicated approved these changes

2023-03-01 04:19 UTC, Vendicated commented on src/plugins/crashHandler.ts
> +    handleCrash(_this: ReactElement & { forceUpdate: () => void; }) {
```suggestion
    handleCrash(_this: ReactElement & { forceUpdate: () => void; }) {
    	try {
```
(and close it)

just to be safe, we woudln't want the crash handler to make it even worse LOL

2023-03-01 04:26 UTC, merged