Add MoreSearchOperators plugin
Vendicated/Vencord pull request #534
Opened 2023-02-26 13:21 UTC by Davr1

This plugin adds/fixes experimental search filters. Some of these are already available in the mobile app TabsV2 redesign as a part of the gui.

- fileType - already implemented in the desktop app, but it doesn't work
- fileName - should be implemented soon
- embedType
- sortBy / sortOrder - same thing as the buttons below the search bar

![image](https://user-images.githubusercontent.com/42148912/221412651-31188355-a1f0-4aff-8d69-1b3d1cec8cbe.png)
![image](https://user-images.githubusercontent.com/42148912/221412663-d51ca0db-1a94-47ac-bda1-67a4dc01efed.png)

2023-02-26 14:59 UTC, somerandomcloud approved these changes

2023-02-26 15:30 UTC, Vap0r1ze requested changes

2023-02-26 15:30 UTC, Vap0r1ze commented on src/plugins/MoreSearchOperators.ts
> +            replace: Object.keys(searchOperators).map(a => `$1($2,"${a}",$self.searchOperators.${a}),`).join("") + Object.keys(searchAnswers).map(a => `$1($2,"${a}",$self.searchAnswers.${a}),`).join(
```suggestion
            match: /(\i)\((\i),\i\.\i\.ANSWER_PINNED/,
            replace: Object.keys(searchOperators).map(a => `$1($2,"${a}",$self.searchOperators.${a}),`).join("") + Object.keys(searchAnswers).map(a => `$1($2,"${a}",$self.searchAnswers.${a}),`).join("") + "$&"
```
Vencord has a custom regex escape `\i` that matches SWC's mangled variable names

2023-02-26 15:30 UTC, Vap0r1ze commented on src/plugins/MoreSearchOperators.ts
> +            replace: "$&" + Object.entries(searchAnswers).map(([k, v]) => `case "${k}":a.add(e.getData("${v['_dataKey']}"));break;`).join("")
```suggestion
            match: /(?<=\i\.forEach\(\(function\((\i)\).{300,500})var (\i)=\i\[\i\];switch\(\i\)\{/,
            replace: "$&" + Object.entries(searchAnswers).map(([k, v]) => `case "${k}":$2.add($1.getData("${v['_dataKey']}"));break;`).join("")
```
You shouldn't hard code variable names in replaces. I used a lookbehind here to capture the search answer variable, and to not mess with the match replacement. Also using a limited wildcard match is kinda epic for things like this (eg: `.{200,500}`)

2023-02-26 15:30 UTC, Vap0r1ze commented on src/plugins/MoreSearchOperators.ts
> +            match: /function .\(.\)\{switch\(.\)\{/,
```suggestion
            match: /function \i\(\i\)\{switch\(\i\)\{/,
```

2023-02-26 15:30 UTC, Vap0r1ze commented on src/plugins/MoreSearchOperators.ts
> +            match: /(.{2})\((.{2}),.\..{3}\.FILTER_HAS,\{titleText:function\(\)\{return .\..\.Messages.SEARCH_GROUP_HEADER_HAS\}\}\)/,
```suggestion
            match: /(\i)\((\i),\i\.\i\.FILTER_HAS,\{titleText:function\(\)\{return \i\.\i\.Messages.SEARCH_GROUP_HEADER_HAS\}\}\)/,
```
@Vendicated we need brace balancing so baddd

2023-02-26 15:30 UTC, Vap0r1ze commented on src/plugins/MoreSearchOperators.ts
> +            match: /(.{2})\((.),.\..{3}\.FILTER_PINNED,!0\),/,
```suggestion
            match: /(\i)\((\i),\i\.\i\.FILTER_PINNED,!0\),/,
```

2023-02-26 15:46 UTC, Davr1 commented on src/plugins/MoreSearchOperators.ts
> +            replace: Object.keys(searchOperators).map(a => `$1($2,"${a}",$self.searchOperators.${a}),`).join("") + Object.keys(searchAnswers).map(a => `$1($2,"${a}",$self.searchAnswers.${a}),`).join(
Didn't know about that, it should probably be added to the plugin guide

2023-05-13 22:43 UTC, Vendicated commented
Sorry for not looking at this in so long. I really like this but like I mentioned the first time this was brought up I am still worried about the risks involved with sending "bad" requests like this or whether using this is safe. Have you been using this for a while? Do you know of others who used this?

2023-05-13 22:46 UTC, ArjixWasTaken commented
Is your concern that discord would think of the user as a self-bot user?

2023-05-13 22:54 UTC, Vendicated commented
Other than those concerns and the fact that there are many lint errors (pnpm lint:fix to the rescue!), it still works now, which is neat

Following the patches is a bit hard though. Please comment them so we can understand what's going on

Also you seem to be generating a lot of code as string with your patches, which tends to not be as robust and not very maintainable, better style is to insert a function call to $self.doFoo() and then implement the code in an actual function doFoo() on your plugin, passing arguments to it if necessary

2023-05-14 05:32 UTC, Davr1 commented
> Sorry for not looking at this in so long. I really like this but like I mentioned the first time this was brought up I am still worried about the risks involved with sending "bad" requests like this or whether using this is safe. Have you been using this for a while? Do you know of others who used this?

I mainly use the filetype option and have not had any issues with it, and I doubt that discord even cares about additional search parameters. I briefly mentioned this plugin in a private server with ~1 vencord user, tho I'm not sure if they use it.

Since my original pull request they have rewritten the backend to further optimize stuff before it's released on mobile, so there were some minor changes in how it works.
EmbedType now only works when searching in a channel (for example in the favorites server where channels are not directly related) and not the entire server. I couldn't think of a good way to address this issue, it's possible to conditionally switch to channel-only search with the source being the current channel (or in:channel), but that's inconsistent with the rest of the operators. 
![image](https://github.com/Vendicated/Vencord/assets/42148912/afbbd01b-2022-47c5-9e9f-2c915b516bb6)

2023-05-14 08:20 UTC, Davr1 commented
Some patches affect switch statements so it's probably better to keep them as is

2023-05-31 16:51 UTC, Vendicated commented
using embedType gives me a 500 Internal Server error lol

2023-05-31 16:54 UTC, Vendicated commented
lol what
![image](https://github.com/Vendicated/Vencord/assets/45497981/c071a95f-2e67-47aa-95a5-6ac55b6a3c8c)

2023-05-31 17:07 UTC, Vendicated commented
> lol what ![image](https://user-images.githubusercontent.com/45497981/242350037-c071a95f-2e67-47aa-95a5-6ac55b6a3c8c.png)

fileName seems to just not work at all and for some reason always only returns this message. That leaves only one relevant filter fileType

2023-05-31 19:12 UTC, Davr1 commented
> using embedType gives me a 500 Internal Server error lol

it should now work when searching in a single channel (either the currently selected channel or using in:channel)

2023-05-31 19:19 UTC, Davr1 commented
kinda wish that the other embed types were also searchable
I don't even know where post_preview or application_news is used, would be helpful if someone could test that
![image](https://github.com/Vendicated/Vencord/assets/42148912/ff32d0af-31e7-4ae9-8b53-c75cc267938b)

2023-05-31 19:30 UTC, Davr1 commented
> > lol what ![image](https://user-images.githubusercontent.com/45497981/242350037-c071a95f-2e67-47aa-95a5-6ac55b6a3c8c.png)
> 
> fileName seems to just not work at all and for some reason always only returns this message. That leaves only one relevant filter fileType

this is so confusing lol
it only finds files where at least one letter from the query matches the entire filename (can't be more than one letter long)

2023-05-31 19:43 UTC, Vendicated commented
lol average discord code

2023-06-20 13:23 UTC, Vendicated commented
i was kinda expecing you to push more changes. Should we not remove the filename param? seeing how useless it is

2023-06-21 16:59 UTC, Davr1 commented
tbh I was hoping they would fix it but they probably changed their decision, they're still working on a new search ui so I will add it back if it gets fixed at some point

2023-06-23 00:23 UTC, Pierre2004 commented
Too bad it's only for mobile

2024-01-05 23:14 UTC, Vendicated commented
how's the status on it, did they fix it now?

2024-01-06 07:21 UTC, Davr1 commented
I've lost interest, will not update this further

2024-01-06 07:21 UTC, closed without merging