feat(plugin): SearchReply
Vendicated/Vencord pull request #551
Opened 2023-03-01 23:49 UTC by Syncxv

simple plugin that adds a reply button to search results

before:
![before](https://i.imgur.com/BAWiOLV.png)

after:
![after](https://i.imgur.com/wPKfT77.png)

2023-03-02 00:02 UTC, Vendicated commented
wait for context menu api

2023-03-18 04:00 UTC, Vendicated commented
Context menu api is here now so you can use it instead!

2023-03-18 07:57 UTC, Syncxv commented
ready

2023-03-25 02:13 UTC, Vendicated commented on src/plugins/searchReply.tsx
> +const i18n = findLazy(m => m.Messages?.MESSAGE_ACTION_REPLY);
Could you move this to Webpack commons please? I feel like many more plugins would want to use it, and I'm pretty sure MessageLogegr already does!

2023-03-25 02:16 UTC, Vendicated requested changes
Looks good other than the feedback!

2023-03-25 02:16 UTC, Vendicated commented on src/plugins/searchReply.tsx
> +    if (!props) return;
i don't think this is a relevant case to check?

2023-03-25 02:16 UTC, Vendicated commented on src/plugins/searchReply.tsx
> +    const { message } = props as { message: Message; };
you could just type the props argument up above I'm fairly certain

2023-03-25 02:16 UTC, Vendicated commented on src/plugins/searchReply.tsx
> +    if (!message || SelectedChannelStore.getChannelId() !== (message.channel_id ?? message.getChannelId())) return;
```suggestion
    if (!message || SelectedChannelStore.getChannelId() !== message.channel_id)) return;
```

2023-03-25 02:16 UTC, Vendicated commented on src/plugins/searchReply.tsx
> +    const channel = ChannelStore.getChannel(message.channel_id ?? message.getChannelId());
same as above!

2023-03-25 02:35 UTC, Vendicated approved these changes

2023-03-25 02:37 UTC, merged