Replace update notices with notifications
Vendicated/Vencord pull request #558
Opened 2023-03-03 18:05 UTC by X1nto

2023-03-05 22:07 UTC, Nuckyz commented
rebase from main and make the notifications permanent using the `permanent: true` option

2023-03-06 08:40 UTC, X1nto commented
Uhhh what the fuck happened with commits

2023-03-19 08:26 UTC, Nuckyz requested changes

2023-03-19 08:26 UTC, Nuckyz commented on src/Vencord.ts
> +                    await showNotification({
```suggestion
                    showNotification({
```

2023-03-19 08:26 UTC, Nuckyz commented on src/Vencord.ts
> +                await showNotification({
```suggestion
                showNotification({
```

2023-03-19 08:40 UTC, X1nto commented on src/Vencord.ts
> +                    await showNotification({
Any particular reason why awaiting is a bad thing here?

2023-03-19 08:42 UTC, Nuckyz commented on src/Vencord.ts
> +                    await showNotification({
Actually just cuz there is no reason to await, let the next code run as soon as possible

2023-03-19 08:53 UTC, X1nto commented on src/Vencord.ts
> +                    await showNotification({
sure then

2023-03-19 09:01 UTC, Nuckyz requested changes

2023-03-19 09:01 UTC, Nuckyz commented on src/components/VencordSettings/Updater.tsx
https://github.com/Vendicated/Vencord/pull/558/files#diff-aeca2fccccc4f3357e578dafdd5dd914e6841e9222065d3a5392822fe0624e3dR208

Should probably change to Shows a notification on startup

2023-03-19 09:01 UTC, Nuckyz commented on src/components/VencordSettings/Updater.tsx
> +                Notify auto-update completion
```suggestion
                Get notified when an automatic update completes
```

2023-03-19 09:19 UTC, Nuckyz approved these changes

2023-03-19 09:21 UTC, merged