feat(plugin): Wikisearch
Vendicated/Vencord pull request #585
Opened 2023-03-08 21:14 UTC by somerandomcloud

Description: `Searches Wikipedia for your requested query. (/wikisearch)`
(If you have any better description ideas please comment I beg of you)

![image](https://user-images.githubusercontent.com/39058370/223851230-c4499b57-38d1-469d-9b22-e24ff9a45891.png)

2023-03-09 10:52 UTC, lewisakura requested changes

2023-03-09 10:52 UTC, lewisakura commented on src/plugins/wikisearch.ts
> +                    .then(async data => {
why are you doing this if your execute is async?
```typescript
const data = await fetch(`https://en.wikipedia.org/w/api.php?action=query&format=json&list=search&formatversion=2&origin=*&srsearch=${word}`)
    .then(response => response.json())
```

also you need to handle errors correctly in case this fails

2023-03-09 10:52 UTC, lewisakura commented on src/plugins/wikisearch.ts
> +                            .then(data => alt_data = data.query.pages[0] || null);
```typescript
const alt_data = await fetch(`https://en.wikipedia.org/w/api.php?action=query&format=json&prop=info%7Cdescription%7Cimages%7Cimageinfo%7Cpageimages&list=&meta=&indexpageids=1&pageids=${firstres.pageid}&formatversion=2&origin=*`)
    .then(data => data.json())
    .then(data => data.query.pages[0] ?? null);
```

and same issue with error handling

2023-03-10 09:12 UTC, Vendicated requested changes
Other than the feedback, don't use snake_case this isn't python. Use camelCase

2023-03-10 09:12 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                if (!data.query) {
```suggestion
                if (!data.query?.search?.length) {
```
then u can just merge this if with the one below

2023-03-10 09:12 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                        return sendBotMessage(ctx.channel.id, { content: "There was an error. Please report this issue on the Vencord repository." });
```suggestion
                        return sendBotMessage(ctx.channel.id, { content: "There was an error. Check the console for more info" });
```

2023-03-10 09:12 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                        return sendBotMessage(ctx.channel.id, { content: "There was an error. Please report this issue on the Vencord repository." });
this return returns from the catch, not from the surrounding function. Instead, you need to return something like null here then check for that condition after the fetch

2023-03-10 09:12 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                    .then(data => data.json())
```suggestion
                    .then(res => res.json())
                    .then(data => data.query.pages[0])
```

2023-03-10 09:12 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                if (!thumbnail_data) thumbnail = null;
```suggestion
                const thumbnail = thumbnail_data && { url: .... };
```

2023-03-10 15:32 UTC, somerandomcloud commented
Should have resolved everything

2023-03-11 00:14 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                        return sendBotMessage(ctx.channel.id, { content: "There was an error. Check the console for more info" });
as I said, return inside catch and similar returns from THAT function (the one passed to catch), so you need to return some value from it like null and check outside of the catch

like
```ts
const res = await fetch(....).catch(err => { ...; return null });
if (!res) return;
```

2023-03-11 00:14 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                        return sendBotMessage(ctx.channel.id, { content: "There was an error. Check the console for more info" });
same as above

2023-03-25 18:25 UTC, somerandomcloud commented
Resolved all conversations! Sorry for inactivity <:trolley:1024751352028602449>

2023-03-28 19:35 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                const data = await fetch(`https://en.wikipedia.org/w/api.php?action=query&format=json&list=search&formatversion=2&origin=*&srsearch=${encodeURIComponent(word.toString())}`).then(respo
these hardcoded query params are kind of painful to read & maintain, you can make it more readable by using URLSearchParams!
```suggestion
                const data = await fetch("https://en.wikipedia.org/w/api.php?" + new URLSearchParams({
                	action: "query",
                	format: "json",
                	list: "search",
                	formatversion: 2,
                	origin: "*",
                	srsearch: word
                }).then(response => response.json())
```

2023-03-29 19:42 UTC, somerandomcloud commented on src/plugins/wikisearch.ts
> +                const data = await fetch(`https://en.wikipedia.org/w/api.php?action=query&format=json&list=search&formatversion=2&origin=*&srsearch=${encodeURIComponent(word.toString())}`).then(respo
thought it looked good an autocommitted. oops

2023-03-29 20:07 UTC, somerandomcloud commented on src/plugins/wikisearch.ts
> +                const data = await fetch(`https://en.wikipedia.org/w/api.php?action=query&format=json&list=search&formatversion=2&origin=*&srsearch=${encodeURIComponent(word.toString())}`).then(respo
fixed

2023-03-30 15:21 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                } as unknown as URLSearchParams); // URLSearchParams doesn't take obj for some reason???
```suggestion
                });
```

it very much does, I just tested it

2023-03-30 21:27 UTC, somerandomcloud commented on src/plugins/wikisearch.ts
> +                } as unknown as URLSearchParams); // URLSearchParams doesn't take obj for some reason???
![image](https://user-images.githubusercontent.com/39058370/228968605-62080536-7132-4f5a-b86b-f4592e5eaa02.png)

2023-03-30 21:29 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                } as unknown as URLSearchParams); // URLSearchParams doesn't take obj for some reason???
because the type of srsearch is not string

2023-03-30 21:30 UTC, Vendicated commented on src/plugins/wikisearch.ts
> +                } as unknown as URLSearchParams); // URLSearchParams doesn't take obj for some reason???
add a third Parameter that's just an empty string to findOption

2023-03-30 21:43 UTC, somerandomcloud commented on src/plugins/wikisearch.ts
> +                } as unknown as URLSearchParams); // URLSearchParams doesn't take obj for some reason???
Well, fixed I guess...

2023-03-31 04:08 UTC, Vendicated approved these changes

2023-03-31 04:09 UTC, merged