Game Activity Toggle and SettingsStoreAPI
Vendicated/Vencord pull request #587
Opened 2023-03-09 02:48 UTC by Nuckyz

2023-03-19 11:26 UTC, Uruknara commented
Please merge this we need it so bad !

2023-04-02 14:17 UTC, Vendicated commented
I'm really confused by some parts of this PR, i think some of the changes you've made to the context menu api here have already landed in main?

2023-04-02 14:53 UTC, Vendicated requested changes

2023-04-02 14:53 UTC, Vendicated commented on src/plugins/apiSettingsStore.ts
> +                    match: /INFREQUENT_USER_ACTION.+?useSetting.+?}(?<=function \i\((\i),(\i),\i,\i\).+?)/,
```suggestion
                    match: /(?<=INFREQUENT_USER_ACTION.{0,20}),useSetting:function/,
```

2023-04-02 14:53 UTC, Vendicated commented on src/plugins/apiSettingsStore.ts
> +                    replace: (m, group, name) => `${m},settingsStoreApiGroup:${group},settingsStoreApiName:${name}`
```suggestion
                    replace: ",settingsStoreApiGroup:arguments[0],settingsStoreApiName:arguments[1],useSetting:function"`
```

2023-04-02 14:53 UTC, Vendicated commented on src/plugins/apiSettingsStore.ts
> +    description: "Adds settings groups and names to the exported object to allow for Webpack searching.",
```suggestion
    description: "Patches Discord's SettingsStores to expose their group and name",
```

2023-04-02 23:01 UTC, Nuckyz commented
I did your changes and "rebased" from main

2023-04-02 23:16 UTC, Vendicated requested changes

2023-04-02 23:16 UTC, Vendicated commented on src/api/SettingsStore.ts
> +    useSetting(): boolean;
```suggestion
    useSetting(): boolean;
    settingsStoreApiGroup: string;
    settingsStoreApiName: string;
```

why not add these members?

2023-04-02 23:16 UTC, Vendicated commented on src/plugins/gameActivityToggle/index.tsx
> +    ShowCurrentGame?.useSetting();
```suggestion
    const showCurrentGame = ShowCurrentGame?.useSetting();
```

2023-04-02 23:16 UTC, Vendicated commented on src/plugins/gameActivityToggle/index.tsx
> +                    onClick={() => ShowCurrentGame?.updateSetting(!ShowCurrentGame.getSetting())}
```suggestion
                    onClick={() => ShowCurrentGame?.updateSetting(s => !s)}
```
i think this is a thing? If so, please fix the type above

2023-04-02 23:16 UTC, Vendicated commented on src/api/SettingsStore.ts
> +    useSetting(): boolean;
```suggestion
    useSetting(): T;
```

2023-04-02 23:16 UTC, Vendicated commented on src/plugins/gameActivityToggle/index.tsx
> +                            {!ShowCurrentGame?.getSetting() && <line x1="920" y1="280" x2="40" y2="880" stroke="var(--status-danger)" stroke-width="80" />}
```suggestion
                            {!showCurrentGame && <line x1="920" y1="280" x2="40" y2="880" stroke="var(--status-danger)" stroke-width="80" />}
```

2023-04-02 23:45 UTC, Nuckyz commented
ok done

2023-04-02 23:49 UTC, Vendicated commented on src/api/SettingsStore.ts
> +    if (modId == null) return;
maybe log here just to make it easier to debug
```suggestion
    if (modId == null) return new Logger("SettingsStoreAPI").error("Didn't find stores module");
```

2023-04-02 23:50 UTC, Vendicated commented on src/plugins/gameActivityToggle/index.tsx
> +const ShowCurrentGame = getSettingStore<boolean>("status", "showCurrentGame");
i think we still need getSettingsStoreLazy because this just wouldn't work, right?

2023-04-03 00:09 UTC, Nuckyz commented
done

2023-04-03 00:13 UTC, Vendicated approved these changes

2023-04-03 00:13 UTC, merged