PronounDB Improvements
Vendicated/Vencord pull request #604
Opened 2023-03-15 00:25 UTC by TheKodeToad

- More customisation
- Visible in compact mode!
- Less duplicate code.
- probably bad!
- made without coffee (i'm a tea person)!

2023-03-15 01:39 UTC, Vendicated commented on src/plugins/pronoundb/components/PronounsChatComponent.tsx
> +    // Respect showInProfile
outdated comment

2023-03-15 01:40 UTC, Vendicated commented on src/plugins/pronoundb/components/PronounsProfileWrapper.tsx
> +    // Respect showInMessages
same as above

2023-03-15 01:42 UTC, Vendicated requested changes

2023-03-15 01:42 UTC, Vendicated commented on src/plugins/pronoundb/index.ts
> +                match: /(\"span\",{id:.{1,2},className:.{1,2},children:.{1,2}}\))/,
```suggestion
                match: /(\"span\",{id:.\i,className:\i,children:\i}\))/,
```

2023-03-15 01:42 UTC, Vendicated commented on src/plugins/pronoundb/styles.css
> +div[class*=compact] .vc-pronoundb-compact {
```suggestion
[class*=compact] .vc-pronoundb-compact {
```

2023-03-18 03:40 UTC, Vendicated commented on src/plugins/pronoundb/index.ts
> +        // Add next to username
since it's now being added to both the username and timestamp, wouldn't that mean showing twice?

2023-03-18 04:00 UTC, Vendicated commented
@TymanWasTaken Since it's your plugin, could you review please?

2023-03-18 10:32 UTC, TheKodeToad commented on src/plugins/pronoundb/index.ts
> +        // Add next to username
The CSS fixes this. Well, the code still runs.

2023-03-25 01:17 UTC, Vendicated commented on src/plugins/pronoundb/index.ts
> +                match: /(\"span\",{id:.\i,className:.\i,children:.\i}\))/,
why are there 3 dots here? \i already covers that if you're just trying to match variable names

2023-03-25 01:22 UTC, Vendicated commented
Doesn't actually seem to work?
![image](https://user-images.githubusercontent.com/45497981/227675900-e6a39185-06b7-4b4b-b10c-7302a6e050bf.png)
![image](https://user-images.githubusercontent.com/45497981/227675980-52630dbb-cf1a-45a8-a644-93d75994f7f7.png)

2023-03-25 01:23 UTC, Vendicated commented
Ah! It works after removing the periods mentioned in my recent feedback. Perhaps I gave you a wrong suggestion in code review, sorry if that was the case

2023-03-25 01:29 UTC, Vendicated approved these changes

2023-03-25 01:30 UTC, merged