feat(plugin): add MessageLinkEmbeds
Vendicated/Vencord pull request #68
Opened 2022-10-08 18:17 UTC by ActuallyTheSun

plugin to show message links as embeds in chat

not gonna do them as message components because i am way too smooth brained for that, just embeds for now

also at the moment it only gets the messages from cache and will not fetch them, which i'm assuming is an issue. i'll fix soon after i figure out how to actually fetch stuff

plus the embed looks good now and has a decent amount of info (definitely didn't just copy the aliucord plugin embed :trollface:)

2022-10-08 18:47 UTC, ArjixWasTaken commented
All `findByProps` calls should only be called once, there is no need to call them multiple times.

2022-10-08 18:56 UTC, ActuallyTheSun commented
> All `findByProps` calls should only be called once, there is no need to call them multiple times.

I'm... not sure what you mean by that. It looks like they're all called only once to me. Or do you mean move them to someone where they're only declared on plugin start?

2022-10-08 18:57 UTC, ArjixWasTaken commented
> > All `findByProps` calls should only be called once, there is no need to call them multiple times.
> 
> I'm... not sure what you mean by that. It looks like they're all called only once to me. Or do you mean move them to someone where they're only declared on plugin start?

they are called whenever you create an embed, that doesn't seem only once to me

2022-10-08 18:58 UTC, ActuallyTheSun commented
yeah then good idea

2022-10-08 18:58 UTC, Vendicated commented
yeah you should use waitFor / lazyWebpack on the top level and reuse the same module to not unnecessarily fetch the module multiple times

Your patch also has a lot of inline logic, it'd be cleaner and nicer to maintain if the patch would only call a method on the plugin and have no logic in the actual patch

2022-10-08 19:14 UTC, ArjixWasTaken requested changes
Oops, forgot to submit my review...

2022-10-08 19:14 UTC, ArjixWasTaken commented on src/plugins/messageLinkEmbeds.ts
> +            var $1=$2.channel,$3=$2.message,$4=$2.renderSuppressEmbeds"
you can do smth like
```javascript

const replacement = `
const msgLink = $2.message.content
    ?.match(Vencord.Plugins.plugins.MessageLinkEmbeds.messageLinkRegex)?.[1];

if (msgLink) {
    $2.message.embeds = [
        ...$2.message.embeds,
        Vencord.Plugins.plugins.MessageLinkEmbeds
          .generateEmbed(msgLink, $2.message.embeds)
    ].filter(item => item);
};

var 
  $1 = $2.channel,
  $3 = $2.message,
  $4 = $2.renderSuppressEmbeds;
`.trim().replace(/(?<=[^(?:const)|(?:var)])\s+/gm, "")

// ... and use the variable as is

2022-10-08 19:14 UTC, ArjixWasTaken commented on src/plugins/messageLinkEmbeds.ts
> +            var $1=$2.channel,$3=$2.message,$4=$2.renderSuppressEmbeds"
this would be much easier to maintain as well

2022-10-08 19:16 UTC, ActuallyTheSun commented on src/plugins/messageLinkEmbeds.ts
> +            var $1=$2.channel,$3=$2.message,$4=$2.renderSuppressEmbeds"
i tried to instead move most of the logic outside of the replacement string to a new function and i'm failing horribly at that so that's a better idea

2022-10-08 19:16 UTC, ArjixWasTaken commented on src/plugins/messageLinkEmbeds.ts
> +        const message = findByProps("getMessage").getMessage(channelID, messageID);
this review was written before ven commented, use `waitFor` / `lazyWebpack` instead

2022-10-08 19:26 UTC, ActuallyTheSun commented
okay so its really late for me and i wanna sleep so i'll just leave this as a dumpster fire and deal with it tomorrow

2022-10-08 21:58 UTC, ArjixWasTaken commented
Ok so, in `webpack/common.tsx`, add

```typescript
export const UserStore: Stores.UserStore = lazyWebpack(filters.byProps(["getCurrentUser", "initialize"]));
export const GuildStore: Stores.GuildStore = lazyWebpack(filters.byProps(["getGuildCount", "initialize"]));
export const ChannelStore: Stores.ChannelStore = lazyWebpack(filters.byProps(["getChannel", "initialize"]));
export const GuildMemberStore: Stores.GuildMemberStore = lazyWebpack(filters.byProps(["getMember", "initialize"]));
export const MessageStore: Stores.MessageStore = lazyWebpack(filters.byProps(["getMessage", "initialize"]));
```

and remove the conflicting `UserStore` lines

<br/>
<br/>
and in ur plugin change the code to

```typescript
import definePlugin from "../utils/types";
import { GuildStore, ChannelStore, MessageStore, GuildMemberStore } from "../webpack/common";

const replacement = `
const msgLink = $2.message.content?.match(Vencord.Plugins.plugins.MessageLinkEmbeds.messageLinkRegex)?.[1];

if (msgLink) {
    $2.message.embeds = [
        ...$2.message.embeds,
        Vencord.Plugins.plugins.MessageLinkEmbeds
          .generateEmbed(msgLink, $2.message.embeds)
    ].filter(item => item);
};

var
  $1 = $2.channel,
  $3 = $2.message,
  $4 = $2.renderSuppressEmbeds /* Don't add a semicolon here, there are more definitions after this. */
`.trim().replace(/(?<=[^(?:const)|(?:var)])\s+/gm, "");


export default definePlugin({
    name: "MessageLinkEmbeds",
    description: "Embeds message links",
    authors: [{
        name: "ActuallyTheSun",
        id: 406028027768733696n
    }],
    patches: [{
        find: "_messageAttachmentToEmbedMedia",
        replacement: {
            match: /var (.{1,2})=(.{1,2})\.channel,(.{1,2})=.{1,2}\.message,(.{1,2})=.{1,2}\.renderSuppressEmbeds/,
            replace: replacement
        }
    }],

    messageLinkRegex: /https?:\/\/(?:\w+\.)?discord(?:app)?\.com\/channels\/((?:\d{17,19}|@me)\/\d{17,19}\/\d{17,19})/,

    generateEmbed(messageURL: string, existingEmbeds: any[]) {
        const [guildID, channelID, messageID] = messageURL.split("/");
        if (existingEmbeds.find(i => i.id === `messageLinkEmbeds-${messageID}`)) return null;
        const message = MessageStore.getMessage(channelID, messageID);
        if (!message) return null;
        return {
            author: {
                iconProxyURL: `https://${window.GLOBAL_ENV.CDN_HOST}/avatars/${message.author.id}/${message.author.avatar}`,
                iconURL: `https://${window.GLOBAL_ENV.CDN_HOST}/avatars/${message.author.id}/${message.author.avatar}`,
                name: `${message.author.username}#${message.author.discriminator}`
            },
            color: GuildMemberStore.getMember(guildID, message.author.id)?.colorString,
            image: message.attachments.length != 0 ? {
                height: message.attachments[0].height,
                width: message.attachments[0].width,
                url: message.attachments[0].url,
                proxyURL: message.attachments[0].proxy_url
            } : (message.embeds[0]?.type === "image" ? { ...message.embeds[0].image } : null),
            rawDescription: message.content,
            footer: {
                text: "#" + ChannelStore.getChannel(channelID).name +
                    ` (${GuildStore.getGuild(guildID).name})`
            },
            timestamp: message.timestamp,
            id: `messageLinkEmbeds-${messageID}`,
            fields: [],
            type: "rich"
        };
    }
});
```

2022-10-09 07:02 UTC, ActuallyTheSun commented
the reason tenor gif's aren't embedded is because there's no convenient way of getting the gif itself, and the discord proxy only has the gif as a video which cannot be embedded. any non-tenor embeds should work though.

2022-10-09 07:17 UTC, ArjixWasTaken commented
Nooo

2022-10-09 07:18 UTC, ArjixWasTaken commented
Add the store definitions in `webpack/common.tsx`

2022-10-09 07:18 UTC, ActuallyTheSun commented
is it a good idea to add definitions to `webpack/common.tsx` in a pr that is most likely gonna get squash-merged

2022-10-09 07:20 UTC, ArjixWasTaken commented
Why would it not be?

2022-10-09 16:46 UTC, ArjixWasTaken commented
you still haven't changed it?

2022-10-09 16:53 UTC, ActuallyTheSun commented
i missed it 🗿

2022-10-09 17:32 UTC, ArjixWasTaken commented
So far so good, what about fetching messages that are not cached?

2022-10-09 18:17 UTC, ActuallyTheSun commented
currently no progress, but i think i know where to start
tomorrow i'll have a decent amount of time so i expect support to be added then

2022-10-09 18:37 UTC, ArjixWasTaken commented
worst case scenario you fetch the message using discord's REST API

but if you do that, make sure all the headers and stuff are present, so it is just like a normal request

2022-10-10 15:01 UTC, ActuallyTheSun commented
this is definitely not ready for a merge
- no support for actual embeds
- no support for videos or tenor gifs
- some other really bad code
will try to fix all of these today, worst case tomorrow

2022-10-11 07:01 UTC, BanTheNons commented
Maybe we can reuse the automod embed for this? Would look a lot better if that's possible

2022-10-11 12:37 UTC, ActuallyTheSun commented
> Maybe we can reuse the automod embed for this? Would look a lot better if that's possible

I've never seen an automod embed (i've never seen anything related to discord's automod) so idk. good idea though

2022-10-11 12:42 UTC, somerandomcloud commented
The automod embed is beautiful

2022-10-11 12:50 UTC, ActuallyTheSun commented
don't think it's possible, as the author of the automod message is the user that sent the message which got blocked, and there's no way to get it to show another user than the author. plus the message only has content and no image embeds/attachments/etc.

2022-10-11 14:08 UTC, Cynosphere commented
The component for it (pre-swc name: ChatMessageEmbedCard) isn't exported anymore due to module flattening.

2022-10-12 01:11 UTC, ArjixWasTaken commented
> The component for it (pre-swc name: ChatMessageEmbedCard) isn't exported anymore due to module flattening.

That ain't an issue since we can export it via a patch.

That is if we can find it via regex that is....

2022-10-12 01:14 UTC, Cynosphere commented
> If we can find it via regex that is....
`find: "().embedCard,"`, then figure out which function it is an export it.

2022-10-13 18:37 UTC, ActuallyTheSun commented
after probably close to 2 hours of trying, i can say i am not adding the automod embed right now. main reason is that adding a component to the message requires basic React knowledge which i do not have, and even then i'd have to look for ways for how to render everything that discord doesn't do automatically

also tried to simply add an `auto_moderator_message` to the embed but discord refuses to render it no matter what

2022-10-13 18:55 UTC, ActuallyTheSun commented
...good question

2022-10-16 15:37 UTC, ActuallyTheSun commented
yep, i give up on trying to add the automod message embed
the same error ("Invalid hook call. Hooks can only be called inside of the body of a function component.") has been stopping me from doing anything for 3 days, and i cant fix it (both because i have no idea what causes it and because i lack basic react knowledge)
[i'll still leave what i did so far here](https://cdn.discordapp.com/attachments/764071870336598016/1031225946704969758/messageLinkEmbeds.ts) (it crashes as soon as it sees a message link) so it doesn't go to waste, but i'm not fixing it

2022-10-16 15:37 UTC, ActuallyTheSun commented
i misclicked close with comment 🗿

2022-10-24 03:21 UTC, Cynosphere commented
MessageAccessoriesAPI is a thing now if you want to try again with the message card stuff without having to deal with embed limitations.

2022-10-24 08:20 UTC, ActuallyTheSun commented
yeah saw that, gonna mess with it later today or tomorrow

2022-10-28 06:33 UTC, ActuallyTheSun commented
added the automod embed 👍
does not embed video but should otherwise work
is there anything to put in settings other than the option to always use rich embeds?

2022-10-29 10:17 UTC, ArjixWasTaken commented on src/plugins/messageLinkEmbeds.ts
> +    if (message.attachments) message.attachments.forEach(a => {
```suggestion
    message.attachments?.forEach(a => {
```

2022-10-29 10:18 UTC, ArjixWasTaken commented on src/plugins/messageLinkEmbeds.ts
> +    message.embeds.forEach(e => {
```suggestion
    message.embeds?.forEach(e => {
```

2022-10-29 10:20 UTC, ArjixWasTaken reviewed
some code style suggestions, nothing much

2022-11-06 00:00 UTC, D3SOX commented
I've been using this for a while now and it LGTM from a user perspective ^^

2022-11-15 21:31 UTC, ArjixWasTaken commented
:skull:

2022-11-18 04:21 UTC, Vendicated requested changes

2022-11-18 04:21 UTC, Vendicated commented on src/plugins/messageLinkEmbeds.ts
> +    messageLinkRegex: /https?:\/\/(?:\w+\.)?discord(?:app)?\.com\/channels\/((?:\d{17,19}|@me)\/\d{17,19}\/\d{17,19}(?:>)?)/,
```suggestion
    messageLinkRegex: /https?:\/\/(?:\w+\.)?discord(?:app)?\.com\/channels\/((?:\d{17,19}|@me)\/\d{17,19}\/\d{17,19}(?!>))/,
```
use a negative lookahead

2022-11-18 04:21 UTC, Vendicated commented on src/plugins/messageLinkEmbeds.ts
> +        const Nothing = React.createElement("Fragment");
u can just return null

2022-11-18 04:21 UTC, Vendicated commented on src/plugins/messageLinkEmbeds.ts
> +        const [guildID, channelID, messageID] = msgLink.split("/");
why not use regex groups for this?

2022-11-18 04:21 UTC, Vendicated commented on src/plugins/messageLinkEmbeds.ts
> +waitFor(["parse", "parseTopic"], _ => ({ parse } = _));
use Parser from commons

2022-11-18 04:21 UTC, Vendicated commented on src/plugins/messageLinkEmbeds.ts
> +    return get({
please use the Queue util to make sure this doesn't spam the api

2022-11-18 04:21 UTC, Vendicated commented on src/plugins/messageLinkEmbeds.ts
> +        if (e.type === "gifv" && !e.url!.match(/https:\/\/(?:www.)?tenor\.com/)) {
please use regex.test

2022-11-18 04:21 UTC, Vendicated commented on src/plugins/messageLinkEmbeds.ts
> +        removeAccessory("messageLinkEmbed");
you can keep track of the message ids and dispatch an update for each or perhaps attach a custom class to your embed somehow and use query selector to remove them. But imo stop cleanup is not that important, people should just restart

2022-11-18 04:21 UTC, Vendicated commented on src/plugins/messageLinkEmbeds.ts
> +        const MessageEmbedElement = React.createElement(MessageEmbed, {
please use jsx

2022-11-18 04:21 UTC, Vendicated commented
sorry for taking so long btw, thanks a lot for your effort!

2022-11-18 04:24 UTC, Cynosphere commented on src/plugins/messageLinkEmbeds.ts
> +        const [guildID, channelID, messageID] = msgLink.split("/");
Alternatively there's a function with the pre-swc name of `tryParseChannelPath`

2022-11-26 18:41 UTC, ActuallyTheSun commented
![image](https://user-images.githubusercontent.com/78964224/204104191-39c4f403-6c6e-45fa-9a19-d27bdac28f45.png)

2022-11-26 18:41 UTC, closed without merging