Fake Nitro Transform Stickers option and other stuff
Vendicated/Vencord pull request #683
Opened 2023-03-24 07:39 UTC by Nuckyz

2023-03-26 01:00 UTC, Nuckyz commented
I'm making this a draft until I make things like this not transform cuz they look hella bad 
![image](https://user-images.githubusercontent.com/61953774/227749571-469e76b8-957a-4f76-ae37-51b664d8118d.png)

2023-03-31 08:19 UTC, Nuckyz commented
I did the things

2023-04-01 02:05 UTC, Vendicated commented on src/plugins/fakeNitro.tsx
> +const fakeNitroNameRegex = /(?:\?|&)name=(\w+)/;
Parsing url stuff with regex like this is meh, it's way more robust to use the URL api (this will throw on invalid urls so might wanna try catch)
```js
new URL(url).searchParams.get("name")
```

2023-04-01 02:11 UTC, Vendicated commented on src/plugins/fakeNitro.tsx
> +                    newContent.push(MessageElementsParser.customEmoji.react({
the way u get this is really cursed, you can just use the Parser from webpack commons

```suggestion
                    newContent.push(Parser.defaultRules.customEmoji.react({
```

2023-04-01 02:11 UTC, Vendicated commented on src/plugins/fakeNitro.tsx
> +                    }, void 0, { key: "0" }));
this is likely not the key you should be using

2023-04-01 02:15 UTC, Nuckyz commented on src/plugins/fakeNitro.tsx
> +                    }, void 0, { key: "0" }));
I don't know the right key lol, from my tests it was sometimes "1"

2023-04-01 03:49 UTC, Nuckyz commented
I did the le things

2023-04-02 14:22 UTC, Vendicated commented on src/plugins/fakeNitro.tsx
> +                    + `&name=${emoji.name}`;
It would probably be better to use URLSearchParams here as well
```js
emoji.url.replace(/\?size=\d+/, "?" + new URLSearchParams({
	size: Settings.plugins.FakeNitro.emojiSize,
	name: emoji.name
}))
```

2023-04-02 14:27 UTC, Vendicated requested changes

2023-04-02 14:27 UTC, Vendicated commented on src/plugins/fakeNitro.tsx
> +                    messageObj.content += " " + link + `&name=${sticker.name}`;
Not sure if names can contain non urlsafe characters but better be safe than sorry

```suggestion
                    messageObj.content += " " + link + `&name=${encodeURIComponent(sticker.name)}`;
```

2023-04-02 14:27 UTC, Vendicated commented on src/plugins/fakeNitro.tsx
> +            if (previousFrame?.disposeOp === ApngDisposeOp.BACKGROUND) {
why not keep this logic at the end of the loop like previously? Would eliminate the need for keeping some variables

2023-04-02 14:27 UTC, Vendicated commented on src/plugins/fakeNitro.tsx
> +        return link.target?.match(fakeNitroEmojiRegex);
```suggestion
        return link.target && fakeNitroEmojiRegex.test(link.target);
```

2023-04-02 14:27 UTC, Vendicated commented on src/plugins/fakeNitro.tsx
> +                if (StickerStore.getStickerById(match[1])) return false;
Why is this here? Maybe add a comment explaining what's going on cause i have no clue

2023-04-02 14:27 UTC, Vendicated commented on src/plugins/fakeNitro.tsx
> +                    const match = embed.url!.match(fakeNitroEmojiRegex);
same as below and same for everywhere else, if you just need a boolean whether it matches or not, use regex.test() instead (has some weird behaviour on global regexes but that isn't the case here)

2023-04-05 03:05 UTC, Vendicated approved these changes

2023-04-05 03:06 UTC, merged