Add FakeProfileThemes plugin
Vendicated/Vencord pull request #710
Opened 2023-03-26 22:59 UTC by remty5

This plugin allows users to theme their profile by storing the colors in an invisible string in their bio.
This is a port of [Alyxia's Vendetta plugin](https://github.com/lexisother/vendetta-plugins/tree/master/plugins/hiddenProfileColours)

https://user-images.githubusercontent.com/42155711/227810001-bf04f0e5-1f9a-4356-9bcd-0feb987e1263.mp4

2023-03-28 19:29 UTC, Vendicated commented on src/plugins/fakeProfileThemes.tsx
> +                user.themeColors = colors;
mutating the user in place like this is meh, maybe you could make this pure?
```js
return new Proxy(user, {
	get(target, prop) {
		switch (prop) {
			case "premiumType": return 2;
			case "themeColors": colors;
		}
		return target[prop];
	}
});
```

2023-03-28 19:31 UTC, Vendicated requested changes

2023-03-28 19:31 UTC, Vendicated commented on src/plugins/fakeProfileThemes.tsx
> +            style={{ marginLeft: "16px" }}
```suggestion
            className={Margins.left16}
```

2023-03-28 19:31 UTC, Vendicated commented on src/plugins/fakeProfileThemes.tsx
> +    addCopy3y3Button(primary: number, accent: number) {
Always wrap react stuffs in an ErrorBoundary to catch errors
```suggestion
    addCopy3y3Button: ErrorBoundary.wrap(function (primary: number, accent: number) {
```
(and close it at the end)

2023-03-28 19:32 UTC, Vendicated commented
Also for future reference, you should never pr from the main branch! Make a feature branch for that

2023-03-31 05:12 UTC, Vendicated requested changes

2023-03-31 05:12 UTC, Vendicated commented on src/plugins/fakeProfileThemes.tsx
> +                match: /(getUserProfile=function\(\i\){return )(\i\[\i\])/,
```suggestion
                match: /(?<=getUserProfile=function\(\i\){return )(\i\[\i\])/,
```

No reason to match unchanged code

2023-03-31 05:12 UTC, Vendicated commented on src/plugins/fakeProfileThemes.tsx
> +                replace: "$1$self.colorDecodeHook($2)"
```suggestion
                replace: "$self.colorDecodeHook($1)"
```

followup of above change

2023-03-31 05:12 UTC, Vendicated commented on src/plugins/fakeProfileThemes.tsx
> +                match: /ACCENT}\)}\)}\)(?<=(?<=},color:(\i).+)},color:(\i).+)/,
this is kind of messy, matching specific brackets is always only a last resort as it's not very robust, I will look more at this tomorrow

2023-03-31 09:59 UTC, Pixel556 commented
How to install?

2023-03-31 11:35 UTC, TheKodeToad commented
If you wait it will probably be available in Vencord at some point unless there are issues.

2023-04-02 14:05 UTC, Vendicated approved these changes

2023-04-02 14:12 UTC, Vendicated commented
Thank you!

2023-04-02 14:12 UTC, merged

2023-04-02 14:40 UTC, Im-IntoDev commented
Can other people see it?

2023-04-02 14:41 UTC, Vendicated commented
Anyone who has the plugin enabled will see it. Everyone else who doesn't will not see it

2023-04-02 14:42 UTC, Im-IntoDev commented
Well then it's not so usefull, it's extremely cool and well thought out tho!

2023-04-02 14:43 UTC, Vendicated commented
The other alternative would be to hack into Discord's servers and add the features to you but I fear that is not possible and also not very legal, so this is the best we can do

2023-04-02 14:44 UTC, somerandomcloud commented
common bestdiscord L

2023-04-02 14:46 UTC, Im-IntoDev commented
Well there's the better quality and emojis working without hacking into the servers.

2023-04-02 14:46 UTC, somerandomcloud commented
Sounds like you arent actually into dev

2023-04-02 15:58 UTC, TheKodeToad commented
xD it works by sending images

2023-04-03 17:22 UTC, Yudin101 commented
Umm....How do i enable it??
like i have the plugin enabled but it is not doing anything i can see a copy button beside it but idk