Add theming support & show on hover option
Vendicated/Vencord pull request #733
Opened 2023-03-30 03:44 UTC by anakojm

69 additions, you are obligated to merge.

2023-03-30 14:12 UTC, Vendicated requested changes

2023-03-30 14:12 UTC, Vendicated commented on src/plugins/pronoundb/components/PronounsChatComponent.tsx
> +                className={classes(styles.timestampInline, styles.timestamp, cl("cozy", { cozyhover: () => Settings.plugins.PronounDB.showOnHover !== true }))}
```suggestion
                className={classes(styles.timestampInline, styles.timestamp, cl("cozy", { cozyhover: Settings.plugins.PronounDB.showOnHover }))}
```

2023-03-30 14:12 UTC, Vendicated commented on src/plugins/pronoundb/components/PronounsChatComponent.tsx
> +                className={classes(styles.timestampInline, styles.timestamp, cl("compact", { compacthover: () => Settings.plugins.PronounDB.showOnHover !== true }))}
```suggestion
                className={classes(styles.timestampInline, styles.timestamp, cl("compact", { compacthover: Settings.plugins.PronounDB.showOnHover }))}
```

2023-03-30 14:12 UTC, Vendicated commented on src/plugins/pronoundb/styles.css
> +    will-change: transform, opacity;
```suggestion
```

2023-03-30 14:12 UTC, Vendicated commented on src/plugins/pronoundb/styles.css
> +    transition: 0.4s ease;
```suggestion
    transition: 0.4s ease;
    transition-property: transform, opacity;
```

2023-03-30 15:09 UTC, Vendicated commented on src/plugins/pronoundb/index.ts
> +            disabled: () => Settings.plugins.PronounDB.showInMessages !== true,
```suggestion
            disabled: () => !Settings.plugins.PronounDB.showInMessages,
```

2023-03-30 15:12 UTC, Vendicated commented on src/plugins/pronoundb/styles.css
> +.vc-pronoundb-compacthover {
these classnames are slightly misleading since they imply it's hovered. Maybe change it to something like `.vc-pronoundb-hoveronly-compact`?

2023-03-30 15:13 UTC, anakojm commented on src/plugins/pronoundb/styles.css
> +[class*="pointerCover-"] {
I'm not 100% sure but I asked on BD #custom-css and no one knew for what it was, also https://grep.app/search?q=pointerCover yield no results so I'm pretty confident

2023-03-30 15:14 UTC, anakojm commented on src/plugins/pronoundb/styles.css
> +.vc-pronoundb-compacthover {
sure

2023-03-30 15:17 UTC, anakojm commented on src/plugins/pronoundb/styles.css
> +[class*="pointerCover-"] {
a div with no child nor content which has only this class appears and disappears multiples times when hovering on any child of `.scrollerContent-2SW0kQ`, causing the flickering

2023-03-31 04:10 UTC, Vendicated commented
don't pr from the main branch in the future please

2023-04-01 02:02 UTC, Vendicated commented
this makes the ui shift and the transition only works on show not on hide

https://user-images.githubusercontent.com/45497981/229260591-5af2b25e-d3cc-4c27-a5e7-a3b79af050a2.mp4

2023-04-01 02:15 UTC, Vendicated commented
Scrolling chat with this feature is also extremely buggy and keeps scrolling you down again

2023-05-23 01:08 UTC, Vendicated commented
Closing due to inactivity. Feel free to reopen if you're still interested in finishing this

2023-05-23 01:08 UTC, closed without merging