feat(plugin): USRBG
Vendicated/Vencord pull request #844
Opened 2023-04-08 15:03 UTC by AutumnVN

💀

2023-04-08 16:00 UTC, Vendicated commented on src/plugins/usrbg/index.tsx
> +import "./index.css";
If you do this and then enableStyle in start(), it will not apply unless the plugin is enabled
```suggestion
import style from "./index.css?managed";
```

2023-04-09 06:59 UTC, AutumnVN commented
seperated the 5MB json to 32000 files

2023-04-09 07:48 UTC, xHyroM commented
yey cool thanks for this :D

2023-04-10 07:32 UTC, xHyroM commented
Don't you want to make some limit to the cache maybe? Won't it eat up too much memory?

2023-04-10 07:38 UTC, AutumnVN commented
i seperated it to 32k files, each per user.
it don't load 5MB json from original usrbg anymore.
when u open a profile, it fetch only one link for that user, and cache it.
if user don't have link, still cache something so it won't try to fetch again.

2023-04-10 22:15 UTC, Vendicated commented on src/plugins/usrbg/index.tsx
> +                <Forms.FormText>Join <Link href="https://discord.gg/TeRQEPb">Discord server</Link> to get your own banner</Forms.FormText>
```suggestion
                <Link href="https://github.com/Discord-Custom-Covers/usrbg#request-your-own-usrbg">Get your own banner</Link>
```

2023-04-10 22:15 UTC, Vendicated commented on src/plugins/usrbg/index.tsx
> +        const [bg] = useAwaiter(
maybe add a setting to prefer the original banner if applicable?

2023-04-11 00:49 UTC, AutumnVN commented on src/plugins/usrbg/index.tsx
> +            () => fetch(`${URL}${userId}.txt`).then(res => res.ok ? res.text() : null)
it screams some type errors

2023-04-16 01:03 UTC, choco705 commented
There is an issue with the centring of the usrbg banner in the user profile. (this issue has also occurred for previous Discord and Vencord versions)

Theme: Material Discord (https://raw.githubusercontent.com/choco705/Vencord-Theme-Links/main/Material-Discord.theme.css)
DIscord: Canary 189727 (f51ec60)
Vencord: 0e58342
Electron: 22.3.2
Chromium: 108.0.5359.215
Host: 0.0.295
OS: OS X 10.15.7 (22.1.0)

![CleanShot 2023-04-16 at 11 01 27](https://user-images.githubusercontent.com/119661802/232260588-e412653e-bcb6-458c-8055-f0f2802287ac.png)

2023-04-17 21:54 UTC, Vendicated requested changes

2023-04-17 21:54 UTC, Vendicated commented on src/plugins/usrbg/index.css
> +[class*="userProfile"] [class*="bannerPremium"],
you can make this more elegant using the :is operator
```suggestion
:is([class*="userProfile"], [class*="userPopout"]) [class*="bannerPremium"],
```

2023-04-17 22:16 UTC, Vendicated approved these changes

2023-04-17 22:18 UTC, merged