Add Meowcrypt plugin
Vendicated/Vencord pull request #875
Opened 2023-04-12 01:43 UTC by itsnebulalol

Meowcrypt is a fun little plugin that is similar to other encryption plugins. I may add support for other profiles in the future.

Uses code from a couple of other Vencord plugins for the toggle button and hooking message sending.

Had to change name from before.

2023-04-25 13:44 UTC, Vendicated commented
Hiya! If I understood correctly, anyone with the plugin will be able to encrypt & decrypt your messages? Or how does this work?

2023-04-25 17:54 UTC, itsnebulalol commented
Yes, I intend on adding profile support with a popup when right-clicking the icon, although I'm not sure how to do that yet. I may do it with slash commands if I cant figure it out :3

2023-04-25 18:10 UTC, Vendicated commented
> when right-clicking the icon, although I'm not sure how to do that yet

You can use React's onContextMenu prop for this, then either open a context menu (you can find an example for this in the welcomeStickerPicker plugin) or a modal (you can find an example for this in many places, for example EmoteCloner)

2023-04-25 20:04 UTC, Vendicated commented
Because String.fromCharCode expects a plain array, not a TypedArray. Why not use a TextDecoder instead? `new TextDecoder().decode(theArray)`

2023-04-25 20:08 UTC, itsnebulalol commented
If I do that, then I get the error `DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`. Do I have to decode it a different way than `btoa(new TextDecoder().decode(str))`?

2023-04-25 20:11 UTC, Vendicated requested changes

2023-04-25 20:11 UTC, Vendicated commented on src/plugins/meowcrypt.tsx
> +    return new Uint8Array(atob(str).split("").map(c => { return c.charCodeAt(0); }));
```suggestion
    return new TextEncoder().encode(atob(str));
```

2023-04-25 20:11 UTC, Vendicated commented on src/plugins/meowcrypt.tsx
> +    const b64 = btoa(String.fromCharCode.apply(null, str));
```suggestion
    return btoa(new TextDecoder().decode(str));
```

2023-04-25 20:11 UTC, Vendicated commented on src/plugins/meowcrypt.tsx
> +        FluxDispatcher.subscribe("MESSAGE_CREATE", this.onMessage);
instead of manually subscribing, you can use the `flux` property on your plugin:
```js
flux: {
	MESSAGE_CREATE(e: IMessageCreate) {
		// ...
	}
}
```

2023-04-25 20:11 UTC, Vendicated commented on src/plugins/meowcrypt.tsx
> +function base64urldecode(str: string): Uint8Array {
```suggestion
function base64UrlDecode(str: string): Uint8Array {
```

2023-04-25 20:11 UTC, Vendicated commented on src/plugins/meowcrypt.tsx
> +function base64urlencode(str: Uint8Array): string {
```suggestion
function base64UrlEncode(str: Uint8Array): string {
```

2023-04-25 20:13 UTC, Vendicated commented
> If I do that, then I get the error `DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`. Do I have to decode it a different way than `btoa(new TextDecoder().decode(str))`?

Wait what? What kind of text are you dealing with? Maybe try `btoa(unescape(...))`

2023-04-25 20:16 UTC, Vendicated commented
Alternatively, you could still use String.fromCharCode, I think if you spread instead of using apply, ts should no longer complain:
```js
String.fromCharCode(...theUint8Array)
```

2023-04-25 20:21 UTC, itsnebulalol commented
The `base64UrlDecode` function needs to do what it did before... I'm dealing with random bytes from the Crypto API. TypeScript isn't complaining anymore, at least on VSCode.

2023-04-25 20:25 UTC, Vendicated commented
Yeah don't worry about unescape, i realised it's actually deprecated oop

but using a TextEncoder in decode should work fine? Works fine for me
![image](https://user-images.githubusercontent.com/45497981/234395430-f7922d59-7fad-4c2a-a543-c4a9a8576b67.png)

2023-04-25 20:34 UTC, itsnebulalol commented
It might be failing for the 3rd part which is the actual encrypted message. I'll test it.. hold on.

2023-04-25 20:35 UTC, Vendicated commented
oh i see, you're not using all charCodes. Isn't that bad?

![image](https://user-images.githubusercontent.com/45497981/234397480-18fdc5cd-c4bb-405d-af74-6d94ea04fd98.png)

2023-04-26 17:18 UTC, Vendicated requested changes

2023-04-26 17:18 UTC, Vendicated commented on src/plugins/meowcrypt/index.tsx
> +        let matchedPublic = false;
```suggestion
        const hasPublic = p.some(p => p.name === "Public");
```

2023-04-26 17:18 UTC, Vendicated commented on src/plugins/meowcrypt/index.tsx
> +            const p2 = await addProfile(publicProfile);
```suggestion
            return addProfile(publicProfile);
```

2023-04-26 17:18 UTC, Vendicated commented on src/plugins/meowcrypt/index.tsx
> +export const addProfile = async (profile: Profile) => {
this operation isn't atomic, you should use DataStore.update() instead to avoid possible race conditions

2023-04-26 17:18 UTC, Vendicated commented on src/plugins/meowcrypt/index.tsx
> +                        FluxDispatcher.dispatch({
this update call will break attachments, could encrypted messages possibly contain attachments?

2023-04-26 17:18 UTC, Vendicated commented on src/plugins/meowcrypt/index.tsx
> +                    action={async () => await removeProfile(currentProfile).then(async () => await setCurrentProfile("Public").then(refetchProfile))}
there is no need for these awaits
```suggestion
                    action={() => 
                    	removeProfile(currentProfile)
                    		.then(() => setCurrentProfile("Public"))
                    		.then(refetchProfile)
              		}
```

2023-04-26 17:20 UTC, Vendicated commented on src/plugins/meowcrypt/index.tsx
> +const removeProfile = async (name: string) => {
same as above, use DataStore.update

2023-04-26 17:23 UTC, Vendicated commented on src/plugins/meowcrypt/index.tsx
> +                            key={profile.name}
can there be duplicate profile names? If yes, this would cause ui glitches when you add duplicate keys

2023-04-26 18:27 UTC, itsnebulalol commented on src/plugins/meowcrypt/index.tsx
> +                            key={profile.name}
this should be handled in the addProfile function.. let me know if it needs improving though

2023-04-26 18:48 UTC, itsnebulalol commented on src/plugins/meowcrypt/index.tsx
> +                        FluxDispatcher.dispatch({
how would I persist attachments?

2023-04-26 20:00 UTC, Vendicated commented on src/plugins/meowcrypt/index.tsx
> +        array.filter((p: Profile) => p.name !== name);
filter doesn't mutate the array, so this will do nothing! What you instead want is something like
```js
return old?.filter(p => p.name !== name) ?? [];
```

2023-04-26 20:21 UTC, BrylanBristopherNFTs commented
My good sir, upon close scrutiny of the particulars encompassed within this pull request, it has become *strokes beard pensively* abundantly clear that the legal and ethical ramifications inherent herein simply *cannot* be disregarded.  

As evidenced by the commit history for this repository, readily available [here](<https://github.com/Vendicated/Vencord/compare/3ff225c27947597e0df1cb4e5c164f1173404976..191f173d0fe4286e35b4fb2683d640546d07c831>), this code has been derived from [Eggcrypt](<https://github.com/BrylanBristopherNFTs/eggcrypt>), and thus is subject to the terms of the [FAIE/OAIO License](<https://github.com/BrylanBristopherNFTs/eggcrypt/blob/master/LICENSE>) under which Eggcrypt has been so benevolently open sourced. *shakes head gravely*

Specifically, as explicitly defined in §3.b of said license:
>Any Derivative Works created using the Software must be licensed under __this__ Open Source License. *adjusts glasses*  

By attempting to transition the license of this repository to the GNU Public License, and force-pushing to conceal the origins of this pull request in the commit history, you have *shakes head gravely* attempted to surreptitiously circumvent this unambiguous requirement in a manner that can only be described as *strokes beard pensively* ethically questionable. *shakes head gravely*

Should this pull request be merged as proposed, employing an incompatible license, the developers of Eggcrypt would have no recourse but to issue a Digital Millennium Copyright Act takedown request targeting the [Vendicated/Vencord](<https://github.com/Vendicated/Vencord>) repository in its entirety.  Given the *adjusts glasses* incontrovertible facts of the matter, the granting of such a request by GitHub would be *shakes head gravely* inevitable.  

I implore you, in the strongest possible terms, to retract this pull request immediately, and submit a new one adhering to the proper license terms, in order to avoid this *shakes head gravely* regrettable, though entirely unavoidable, outcome. The open source community depends intractably upon strict compliance with licensing requirements, and cannot function otherwise. *strokes beard pensively*  

The integrity of open-source depends upon strict adherence to clearly defined licensing terms and ethical standards. *shakes head gravely* I urge you once more to rectify this situation posthaste, before more drastic measures become *strokes beard pensively* necessary. *shakes head gravely*

2023-04-26 20:35 UTC, MeguminSama commented
@BrylanBristopherNFTs This PR is older than your linked repo. Please provide real evidence or stop trolling.

2023-04-26 20:38 UTC, BrylanBristopherNFTs commented
My sincerest apologies, in my previous missives on this topic I neglected to mention that the maintainers of Eggcrypt recently released updated source code under the auspices of “Project Beijing” which implements several new security features that may be of interest.  

In particular, this new release of Eggcrypt utilizes an in-house pseudo-Mandarin encoding solution to provide an additional layer of plausible deniability for encrypted communications. Users of the novel Project Beijing edition of Eggcrypt have access to industry-standard encryption that prevents unauthorized parties lacking the proper key from deciphering encrypted messages. However, should unauthorized state actors attempt to access unencrypted messages, they will be met with nonsense unreadable Chinese text rather than the true communications content.
 
*strokes beard pensively* Given your evident interest in utilizing Eggcrypt within your own Vendicated/Vencord repository, rebasing your fork on the latest Project Beijing code release may be prudent to take advantage of these additional security and obfuscation mechanisms. *shakes head gravely* Failure to do so could potentially expose users of your software to undesirable scrutiny and associated ethical dilemmas, should the encryption of their messages be compromised. *adjusts glasses*

Moreover, as the Project Beijing edition of Eggcrypt qualifies as an update to the original open-source codebase rather than a separate derivative work, licensing terms require any forks or modifications to adopt the same FAIE/OAIO license under which it has so generously been released.  rebasing your fork on Project Beijing would ensure compliance with these requirements, avoiding legal entanglements and allowing Eggcrypt users to benefit from the latest available security features. 

The open-source community depends upon an atmosphere of transparency and collaboration to thrive. I heartily suggest open communication with the creators of Eggcrypt to ensure your repository stays up-to-date with the latest changes and aligned with proper licensing guidelines. Strict standards around licensing and security are crucial pillars supporting the integrity of open-source software, and should not be disregarded.

Please do consider these recommendations carefully. The privacy and security of Eggcrypt users depend upon it. *shakes head gravely* I wish you the very best in resolving this matter.

2023-04-26 20:39 UTC, BrylanBristopherNFTs commented
> @BrylanBristopherNFTs This PR is older than your linked repo. Please provide real evidence or stop trolling.

The linked repository was around for years. I have simply just now updated it. It is my understanding you have used an old copy of eggcrypt which was also under the same license.

2023-04-26 20:41 UTC, MeguminSama commented
> > @BrylanBristopherNFTs This PR is older than your linked repo. Please provide real evidence or stop trolling.
> 
> The linked repository was around for years. I have simply just now updated it. It is my understanding you have used an old copy of eggcrypt which was also under the same license.

Your account is a week old. Goodbye.

2023-04-26 20:41 UTC, ItzOnlyAnimal commented
*shakes head gravely*

2023-04-26 20:41 UTC, BrylanBristopherNFTs commented
https://www.reddit.com/r/jailbreak/comments/g83ehp/release_eggcrypt_public_beta_by_castyte_encrypt/

2023-04-26 20:42 UTC, MeguminSama commented
> [reddit.com/r/jailbreak/comments/g83ehp/release_eggcrypt_public_beta_by_castyte_encrypt](https://www.reddit.com/r/jailbreak/comments/g83ehp/release_eggcrypt_public_beta_by_castyte_encrypt/)
> 
> Here is the original which you have based your code upon

There is very obviously no source code here.

2023-04-26 20:45 UTC, ggtylerr commented
> My good sir, upon close scrutiny of the particulars encompassed within this pull request, it has become *strokes beard pensively* abundantly clear that the legal and ethical ramifications inherent herein simply *cannot* be disregarded.  
> 
> As evidenced by the commit history for this repository, readily available [here](https://github.com/Vendicated/Vencord/compare/3ff225c27947597e0df1cb4e5c164f1173404976..191f173d0fe4286e35b4fb2683d640546d07c831), this code has been derived from [Eggcrypt](https://github.com/BrylanBristopherNFTs/eggcrypt), and thus is subject to the terms of the [FAIE/OAIO License](https://github.com/BrylanBristopherNFTs/eggcrypt/blob/master/LICENSE) under which Eggcrypt has been so benevolently open sourced. *shakes head gravely*
> 
> Specifically, as explicitly defined in §3.b of said license:
> >Any Derivative Works created using the Software must be licensed under __this__ Open Source License. *adjusts glasses*  
> 
> By attempting to transition the license of this repository to the GNU Public License, and force-pushing to conceal the origins of this pull request in the commit history, you have *shakes head gravely* attempted to surreptitiously circumvent this unambiguous requirement in a manner that can only be described as *strokes beard pensively* ethically questionable. *shakes head gravely*
> 
> Should this pull request be merged as proposed, employing an incompatible license, the developers of Eggcrypt would have no recourse but to issue a Digital Millennium Copyright Act takedown request targeting the [Vendicated/Vencord](https://github.com/Vendicated/Vencord) repository in its entirety.  Given the *adjusts glasses* incontrovertible facts of the matter, the granting of such a request by GitHub would be *shakes head gravely* inevitable.  
> 
> I implore you, in the strongest possible terms, to retract this pull request immediately, and submit a new one adhering to the proper license terms, in order to avoid this *shakes head gravely* regrettable, though entirely unavoidable, outcome. The open source community depends intractably upon strict compliance with licensing requirements, and cannot function otherwise. *strokes beard pensively*  
> 
> The integrity of open-source depends upon strict adherence to clearly defined licensing terms and ethical standards. *shakes head gravely* I urge you once more to rectify this situation posthaste, before more drastic measures become *strokes beard pensively* necessary. *shakes head gravely*

I honestly cant tell if this is a troll or legitimate cause of the NFT crap

2023-04-26 20:53 UTC, anonymousassociate commented
Well howdy there partner! *tips cowboy hat* Looks like ya'll done gone and decrypted that egg-crypt doohickey.  Must've taken a whole heap of effort and smarts to unscramble that there techno-wizardry. I hear they really muddled up the insides to keep folks from peekin' under the hood.  

No matter how slick ya'll are at coverin' your tracks though, takin' someone else's code without askin' still ain't right.  My associates and I are gonna have to ask ya kindly to mosey on over to that repository of yours and take it down now, ya hear? Don't make us get the law involved, we'd rather settle this peaceable-like.

2023-04-26 21:11 UTC, clydebottoms commented
As an established and respected software engineer, I feel compelled to comment on the troubling matters surrounding this Pull Request and its dubious origins. 
 
At IBM, transparency and ethical conduct are of paramount importance in all of our business operations, especially open-source software development. We strive to build trusted relationships with both users and the greater technical community through a commitment to responsible disclosure and strict compliance with all legal obligations.

The censorship and deletion of critical feedback on this repository raises serious ethical red flags and undermines the good faith of open communication so essential to collaborative progress. Moreover, indications that the codebase has been derived in part from IBM’s proprietary Eggcrypt product without proper authorization represent a violation of intellectual property laws and reasonable standards of professional conduct.   

As an ethical technology leader focused on trust and transparency, IBM cannot condone such irresponsible behavior. We strongly advise the maintainers of this repository to immediately reinstate all censored feedback, issue a public statement acknowledging the origins of any proprietary code used, and bring licensing terms into alignment with those of the original Eggcrypt open-source release. Failure to do so may force IBM to pursue legal action to defend our intellectual property and commercial interests.

Open-source software development depends on accountability, trust, and shared ethical values across the community. Repositories that violate these principles threaten to compromise user security, enable unethical behavior, and undermine the integrity of collaborative work. IBM remains fully committed to supporting and advancing open technology ecosystems through responsible, transparent practices. We hope the maintainers of this repository will make the necessary changes to bring it into line with these values. The open-source community deserves nothing less.

2023-04-27 16:28 UTC, Vendicated commented on src/plugins/meowcrypt/components/AddProfileModal.tsx
> +            <ModalContent>
there's no margin between the header and "name" which looks a bit strange. Why not put some padding on the modal content itself (and remove the margin on the colour text input)

![image](https://user-images.githubusercontent.com/45497981/234928587-af45dcf6-1a29-45a1-8c4a-44caa97f5c10.png)

2023-04-27 16:31 UTC, Vendicated commented
I think it would be nice to add an additional "Edit current profile" option

additionally, there seems to be an incompatibility between MessageLogger and this plugin, I wonder how we could best solve that
![image](https://user-images.githubusercontent.com/45497981/234929163-2a32eaaa-750f-4bcf-b5ee-1ff03a17d57e.png)

2023-04-27 16:33 UTC, Vendicated commented
i think the lock icon could use a slight diet (or maybe use a (simplistic) cat icon it'd be cute)
![image](https://user-images.githubusercontent.com/45497981/234929741-7b24e5ef-8f2e-47a1-9feb-f3c776d2daf3.png)

2023-04-27 19:15 UTC, Vendicated commented
the text colour seems to revert to white if you switch channels then come back. I think a good fix to the last 2 issues would be patching the message content component instead of actually updating the message text

2023-05-23 21:18 UTC, closed without merging