feat: Add Decor plugin
Vendicated/Vencord pull request #910
Opened 2023-04-15 05:12 UTC by FieryFlames

Custom avatar decorations plugin

2023-04-16 04:19 UTC, Nuckyz commented on src/plugins/decor.tsx
> +                replace: "$&const vcDecorDecoration=$self.patchGetAvatarDecorationURL(arguments[0]); if (vcDecorDecoration) return vcDecorDecoration;"
```suggestion
                replace: "$&const vcDecorDecoration=$self.patchGetAvatarDecorationURL(arguments[0]);if (vcDecorDecoration)return vcDecorDecoration;"
```

2023-10-15 08:22 UTC, Yeetov commented
Please add this

2023-10-17 01:21 UTC, Vap0r1ze commented on src/components/Icons.tsx
> +            className={classes(props.className, "vc-plus-icon")}
nitpick but might wanna namespace this as `vc-decor-plus-icon`

2023-10-17 02:44 UTC, Vap0r1ze requested changes
just some regex nitpicks for now

2023-10-17 02:44 UTC, Vap0r1ze commented on src/plugins/decor/index.tsx
> +                replace: "$1.skuId !== $self.SKU_ID ? $& : true"
i'd do this just in case
```suggestion
                replace: "($1.skuId !== $self.SKU_ID ? $& : true)"
```

2023-10-17 02:44 UTC, Vap0r1ze commented on src/plugins/decor/index.tsx
> +                replace: "$1t.skuId === $self.SKU_ID || ($3)"
```suggestion
                match: /(?<=(\i)\.label\}\),)(\i===\i\.PURCHASE\|\|\i===\i\.PREMIUM_PURCHASE&&\i)/,
                replace: "($1.skuId === $self.SKU_ID || ($2))"
```

2023-10-17 02:44 UTC, Vap0r1ze commented on src/plugins/decor/index.tsx
> +                replace: "$1$2=$self.openCreateStickerModalLazy=$3"
```suggestion
                match: /(?<=numTotal:.{1,50}?,)(\i)=(function\(\i\){var \i=\i\.guildId)/,
                replace: "$1=$self.openCreateStickerModalLazy=$2"
```

2023-10-17 02:59 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +                match: /{user:(.)},"decoration"\),/,
Probably not, idk why I captured it

2023-10-21 16:51 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +            const channel = getCurrentChannel();
you should use SelectedChannelStore.getChannelId() instead

2023-10-21 16:52 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +        // Still need to fetch for member list
```suggestion
        // TODO: Still need to fetch for member list
```
(or just complete it?)

2023-10-21 16:53 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +        if (user && store.has(user.id)) {
this is kinda an anti pattern. could just do smth like
```js
const decor = user && store.get(user.id);
if (!decor) return user;
...

2023-10-21 17:23 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +        if (user && store.has(user.id)) {
I've pushed a attempt at making this function clearer

2023-11-08 20:04 UTC, Yeetov approved these changes
Why do you need to include encryption

2023-11-08 20:05 UTC, FieryFlames commented
> Why do you need to include encryption

What? what encryption?

2023-11-09 02:26 UTC, Vendicated commented on src/components/Icons.tsx
> +export function NoneIcon(props: IconProps) {
NoneIcon is a bit of a weird name. it would be helpful if you could add a jsdoc comment explaining a bit closer what it is or found a better name

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +                match: /(\i===\i\.Section\.PURCHASE\|\|\i===\i\.Section\.PREMIUM_PURCHASE&&\i)(?<=avatarDecoration:(\i).{0,800}?)/,
```suggestion
                match: /(\i===\i\.Section\.PURCHASE\|\|\i===\i\.Section\.PREMIUM_PURCHASE&&\i)(?<=avatarDecoration:(\i).+?)/,
```

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +                match: /(\i=)(\i=>{let{user:\i,avatarDecoration)/,
you don't seem to be using this group other than immediately reinserting, so just make it a lookbehind. then you also don't need the other group
```suggestion
                match: /(?<=\i=)\i=>{let{user:\i,avatarDecoration/,
```

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +                replace: "$1$self.DecorationGridDecoration=$2"
```suggestion
                replace: "$self.DecorationGridDecoration=$&"
```

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +            replacement: [{
the way you formatted it is a bit misleading
```suggestion
            replacement: [
            	{
```

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +            if (data.channelId === channelId) {
nit: this variable is not needed, just inline the getChannelId() call

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +            if (data.channelId === channelId) {
nit: this variable is not needed, just inline the getChannelId() call

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +        // TODO: Still need to fetch for member list
this TODO comment should be resolved, unless you want to add it some time later

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +        useUsersDecorationsStore.getState().fetch(UserStore.getCurrentUser().id, true);
should this not also call .init() and .clear(), just like CONNECTION_OPEN?

this potentially (in most cases actually) will also be called at the same time as your CONNECTION_OPEN handler, so you might want to deduplicate those calls to avoid unnecessary requests to your api

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +    patchUser(user) {
```suggestion
    patchUser(user: User) {
```

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +        const store = useUsersDecorationsStore.getState();
is getState() a simple variable lookup? cause getUser() will be called tons of times so performance kinda matters

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +        const decoration = store.get(user.id);
```suggestion
        const decoration = store.get(user.id);
        if (!decoration) return user;
```
and remove the above if (!store.has())

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +        } else if (!decoration && user.avatarDecoration && user.avatarDecoration.skuId === SKU_ID) {
```suggestion
        } else if (!decoration && user.avatarDecoration?.skuId === SKU_ID) {
```

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +        user.avatarDecorationData = user.avatarDecoration;
what is this property useful for? i only ever see you assign it, never use it - unless this is a property discord uses? maybe add a short comment

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +        const { selectedDecoration, select: selectDecoration, fetch } = useCurrentUserDecorationsStore();
much similar to select, giving this property a more specific name makes the code easier to read (and avoids confusing it with the builtin fetch)
```suggestion
        const { selectedDecoration, select: selectDecoration, fetch: fetchDecoration } = useCurrentUserDecorationsStore();
```

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/index.tsx
> +                    Change Decor Decoration
honestly, always specifying "Decor Decoration" seems a bit excessive (and weird sounding). i think it should be obv to the user it's a decor decoration?

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/lib/api.ts
> +    const res = await fetch(url, { ...options, headers: { ...options?.headers, Authorization: `Bearer ${useAuthorizationStore.getState().token}` } });
```suggestion
    const res = await fetch(url, {
    	...options,
    	headers: { 
    		...options?.headers,
    		Authorization: `Bearer ${useAuthorizationStore.getState().token}`
  		}
	});
```

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/lib/api.ts
> +export const getUsersDecorations = async (ids: string[] | undefined = undefined) => {
```suggestion
export const getUsersDecorations = async (ids?: string[]) => {
```

2023-11-09 02:26 UTC, Vendicated commented on src/plugins/decor/lib/api.ts
> +    if (ids && ids.length === 0) return {};
```suggestion
    if (ids?.length === 0) return {};
```

2023-11-09 02:33 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +        // TODO: Still need to fetch for member list
I couldn't find a viable flux event :/

2023-11-09 02:34 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +        useUsersDecorationsStore.getState().fetch(UserStore.getCurrentUser().id, true);
.init() no, the auth store handles initing after hydrating. it just needs to re-init when switching accounts
.clear() maybe.. typically it should get re-fetched before user sees existing data?

2023-11-09 02:34 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +    patchUser(user) {
this is fine but the type are outdated

2023-11-09 02:37 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +        const store = useUsersDecorationsStore.getState();
seems like it

2023-11-09 02:37 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +        const decoration = store.get(user.id);
fine

2023-11-09 02:37 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +        } else if (!decoration && user.avatarDecoration && user.avatarDecoration.skuId === SKU_ID) {
I swear I had these explicit && checks for a reason

2023-11-09 02:38 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +        user.avatarDecorationData = user.avatarDecoration;
I have zero clue I just saw it in the user class and played it safe and assign it

2023-11-09 08:28 UTC, FieryFlames commented on src/plugins/decor/lib/api.ts
> +    if (ids && ids.length === 0) return {};
marking as resolved as the ids && is correct behavior

2023-11-14 23:16 UTC, redstonekasi approved these changes

2023-11-14 23:34 UTC, Cynosphere approved these changes

2023-11-22 05:16 UTC, Nuckyz commented on src/plugins/decor/index.tsx
> +                    replace: "$1.skuId === $self.SKU_ID || ($&)"
```suggestion
                    match: /\.Section\.PREMIUM_PURCHASE&&\i;if\((?<=avatarDecoration:(\i).+?)/,
                    replace: "$&$1.skuId===$self.SKU_ID||"
```

2023-11-22 05:16 UTC, Nuckyz commented on src/plugins/decor/index.tsx
> +                    replace: "vcDecorAvatarDecoration,"
```suggestion
                    replace: '...[typeof vcDecorAvatarDecoration!=="undefined"?vcDecorAvatarDecoration:null].filter(Boolean),'
```

2023-11-22 05:16 UTC, Nuckyz commented on src/plugins/decor/index.tsx
> +                    replace: "$1 ?? vcDecorAvatarDecoration ?? ($&)"
```suggestion
                    match: /(?<={avatarDecoration:).{1,20}(?=,)(?<=avatarDecorationOverride:(\i).+?)/,
                    replace: '$1??typeof vcDecorAvatarDecoration!=="undefined"?vcDecorAvatarDecoration:null??($&)'
```

2023-11-22 05:16 UTC, Nuckyz commented on src/plugins/decor/index.tsx
> +                    replace: "vcDecorAvatarDecoration ?? $&"
```suggestion
                    match: /(?<=getAvatarDecorationURL\)\({avatarDecoration:).{1,20}(?=,)(?<=currentUser:(\i).+?)/,
                    replace: "$self.useUserDecorAvatarDecoration($1)??$&"
```

2023-11-22 05:16 UTC, Nuckyz commented on src/plugins/decor/index.tsx
> +                },
```suggestion
```

2023-11-22 05:19 UTC, Cynosphere commented on src/plugins/decor/index.tsx
> +                    replace: "$1 ?? vcDecorAvatarDecoration ?? ($&)"
why aggressive type checking here? this is just killing readability

2023-11-22 05:20 UTC, Nuckyz commented on src/plugins/decor/index.tsx
> +                    replace: "$1 ?? vcDecorAvatarDecoration ?? ($&)"
The variable is defined in another patch, if the patch fails it will cause a crash unless we type check

2023-11-22 05:20 UTC, FieryFlames commented on src/plugins/decor/index.tsx
> +                    replace: "$1 ?? vcDecorAvatarDecoration ?? ($&)"
I'd rather solve this with #2009

2023-11-30 01:48 UTC, Nuckyz requested changes

2023-11-30 01:48 UTC, Nuckyz commented on src/plugins/decor/ui/modals/CreateDecorationModal.tsx
> +            if (!object) setUrl(null);
wasnt this supposed to be `if (object)`?

2023-11-30 01:48 UTC, Nuckyz commented on src/plugins/decor/ui/modals/CreateDecorationModal.tsx
> +                    <br />You can recieve updates on your decoration's review by joining <Link
```suggestion
                    <br />You can receive updates on your decoration's review by joining <Link
```

2023-11-30 01:48 UTC, Nuckyz commented on src/plugins/decor/ui/modals/CreateDecorationModal.tsx
> +                </>}
```suggestion
                <br />You can receive updates on your decoration's review by joining <Link
                    href={`https://discord.gg/${INVITE_KEY}`}
                    onClick={e => {
                        e.preventDefault();
                        if (!GuildStore.getGuild(GUILD_ID)) {
                            openInviteModal(INVITE_KEY);
                        } else {
                            props.onClose();
                            FluxDispatcher.dispatch({ type: "LAYER_POP_ALL" });
                            NavigationRouter.transitionToGuild(GUILD_ID);
                        }
                    }}
                >Decor's Discord server
                </Link>.
```

2023-11-30 01:48 UTC, Nuckyz commented on src/plugins/decor/ui/components/DecorationGridCreate.tsx
> +            Create
```suggestion
            {i18n.Messages.NONE}
```

2023-11-30 01:48 UTC, Nuckyz commented on src/plugins/decor/ui/components/SectionedGridList.tsx
> +};
```suggestion
};

```

2023-11-30 01:48 UTC, Nuckyz commented on src/plugins/decor/ui/modals/ChangeDecorationModal.tsx
> +import { Margins } from "@utils/margins";
```suggestion
import { Margins } from "@utils/margins";
```
```suggestion
import { Flex } from "@components/Flex";
import { Margins } from "@utils/margins";
```

2023-11-30 01:48 UTC, Nuckyz commented on src/plugins/decor/ui/modals/ChangeDecorationModal.tsx
> +        <div style={{ display: "flex" }}>
```suggestion
        <Flex>
```

2023-11-30 01:48 UTC, Nuckyz commented on src/plugins/decor/ui/modals/ChangeDecorationModal.tsx
> +        </div>
```suggestion
        </Flex>
```

2023-11-30 03:04 UTC, FieryFlames commented on src/plugins/decor/ui/modals/CreateDecorationModal.tsx
> +            if (!object) setUrl(null);
nop

2023-11-30 04:01 UTC, Nuckyz commented on src/plugins/decor/lib/stores/UsersDecorationsStore.ts
>                  if (Date.now() - fetchedAt.getTime() < DECORATION_FETCH_COOLDOWN) continue;
make a `const now = Date.now()` here

2023-11-30 05:09 UTC, Nuckyz approved these changes

2023-11-30 05:10 UTC, merged