Relationship viewer
Vendicated/Vencord pull request #917
Opened 2023-04-15 17:27 UTC by MagikManz

This plugin allows you to view your relationships within servers.

Fixed:
Crashing when un-able to load server profiles
Now profiles should load in with time if not immediately (due to ratelimits etc, it all depends on your amount of friends).
Slider no longer affects everything globally.

Video:
https://user-images.githubusercontent.com/36787474/232242773-6668c71a-486c-4637-ac17-2e543a87bad0.mp4

2023-06-20 14:14 UTC, Vendicated requested changes

2023-06-20 14:14 UTC, Vendicated commented on src/plugins/relationshipViewer/relationsStyles.css
> +    --expandable: #6d6d6d;
avoid hardcoding colours. Always use Discord's css varialbles for proper theme support

2023-06-20 14:14 UTC, Vendicated commented on src/plugins/relationshipViewer/relationsStyles.css
> +    overflow-y: hidden;
```suggestion
```

2023-06-20 14:14 UTC, Vendicated commented on src/plugins/relationshipViewer/index.tsx
> +    const unloadedIds: Array<string> = [];
```suggestion
    return ids.filter(id => !GuildMemberStore.isMember(guildId, id));
```

2023-06-28 10:56 UTC, MagikManz commented
thnnx

2023-07-02 20:06 UTC, MagikManz commented
🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗
🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗
(ven) 🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗

2023-07-05 04:59 UTC, MagikManz commented
🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗🦗

2023-09-23 21:16 UTC, nmsturcke commented
BTW this has been added in the ServerProfile plugin (2c758ccdf8372c48f2d2a79ece8f2eba63f1510c)

2023-09-23 21:22 UTC, MagikManz commented
yes I saw.... kinda disappointed tbh

2023-09-23 21:22 UTC, closed without merging