Quick connections plugin
Vendicated/Vencord pull request #923
Opened 2023-04-16 11:50 UTC by TheKodeToad

Adds connections to the profile as clickable icons with tooltips! Inspiration: https://github.com/Vendicated/Vencord/discussions/871 and devilbro's betterdiscord plugin

Here are some screenshots: 

![Bad showcase](https://user-images.githubusercontent.com/57493648/232307555-7d5860e7-5681-4a7e-a675-5620b768872d.png)

I also added some "helpful" text

TODO: maybe add to the DM profile card thing too and fix the icon spacing a bit

2023-04-16 16:54 UTC, TheKodeToad commented
Kind of useable, I'm having trouble finding the dm widget :p

2023-04-17 21:43 UTC, Vendicated commented
>  I'm having trouble finding the dm widget :p

Did you find it? And by that, do you mean the profile bar on the right?

2023-04-17 21:51 UTC, Vendicated requested changes

2023-04-17 21:51 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +import { Tooltip } from "webpack/common/components";
```suggestion
import { Tooltip } from "@webpack/common";
```

2023-04-17 21:51 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +    const url = platform.getPlatformUserUrl && platform.getPlatformUserUrl(connection);
```suggestion
    const url = platform.getPlatformUserUrl?.(connection);
```

2023-04-17 21:51 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +    options: {
you should use definePluginSettings() instead of the deprecated options

2023-04-17 21:51 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +            }
using a patch to obtain this is unnecessary, a simple `findByProps("isSupported", "getByUrl")` does it

2023-04-17 21:51 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +            find: "\"lastSection\",",
same as below, you can get this via `findByCode("().lastSection")`

2023-04-17 21:51 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +                match: /,hideNote:\i\|\|\i}\)(?<=(\i)=\i\.user,.+?)(?<=(\i)=\(0,\i\.\i\)\(\i,\i\)\.profileTheme.+?)/,
this matcher is very specific, are you sure this is necessary? You seem to be matching the profile theme, why not use the function call you match manually? It takes the user and their profile, both of which are passed as an argument to the function your code is inside (accessible via arguments[0].user and argument[0].profileTheme)

2023-04-18 08:08 UTC, TheKodeToad commented on src/plugins/quickConnections/index.tsx
> +                match: /,hideNote:\i\|\|\i}\)(?<=(\i)=\i\.user,.+?)(?<=(\i)=\(0,\i\.\i\)\(\i,\i\)\.profileTheme.+?)/,
I don't think that would account for this option
![Sync profile themes](https://user-images.githubusercontent.com/57493648/232713268-ee62935e-c252-47ce-a97f-2a3eac7fb7d4.png)

2023-04-18 14:10 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +                match: /,hideNote:\i\|\|\i}\)(?<=(\i)=\i\.user,.+?)(?<=(\i)=\(0,\i\.\i\)\(\i,\i\)\.profileTheme.+?)/,
![image](https://user-images.githubusercontent.com/45497981/232803723-d466a583-55a3-4f6c-9e75-1bd37db167b1.png)

What I meant is you're matching this, but it would be way simpler to just call p.Z yourself

2023-04-18 14:11 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +                match: /,hideNote:\i\|\|\i}\)(?<=(\i)=\i\.user,.+?)(?<=(\i)=\(0,\i\.\i\)\(\i,\i\)\.profileTheme.+?)/,
![image](https://user-images.githubusercontent.com/45497981/232803960-ac5f1c0b-252b-43bf-b77a-9a9928a90637.png)
![image](https://user-images.githubusercontent.com/45497981/232804005-b951e396-f3fd-4c83-a176-7403a96f2bd7.png)

you can use a findByCode to find this function

2023-04-18 14:12 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +                match: /,hideNote:\i\|\|\i}\)(?<=(\i)=\i\.user,.+?)(?<=(\i)=\(0,\i\.\i\)\(\i,\i\)\.profileTheme.+?)/,
This way you can make your patch way way simpler and don't have to match any variables and instead only use arguments[0]

2023-04-18 14:16 UTC, TheKodeToad commented on src/plugins/quickConnections/index.tsx
> +                match: /,hideNote:\i\|\|\i}\)(?<=(\i)=\i\.user,.+?)(?<=(\i)=\(0,\i\.\i\)\(\i,\i\)\.profileTheme.+?)/,
Wouldn't it require calling it with "o" and "y"? tbh i don't really understand what's going on with (0, p.Z) as it looks like a call with no method.

2023-04-18 14:22 UTC, TheKodeToad commented on src/plugins/quickConnections/index.tsx
> +                match: /,hideNote:\i\|\|\i}\)(?<=(\i)=\i\.user,.+?)(?<=(\i)=\(0,\i\.\i\)\(\i,\i\)\.profileTheme.+?)/,
Ohh, right I read it again

2023-04-18 17:03 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +    return component(e.user.id, getTheme(e.user, e.displayProfile).profileTheme);
please properly use react:
```jsx
return <Component id={e.user.id} theme={getTheme(e.user, e.displayProfile).profileTheme} />

2023-04-18 17:04 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +function profilePopoutComponent(e: any) {
Instead of using the ErrorBoundary in the below component (where it cannot catch all errors that might happen), you should instead wrap the outer function:
```js
const profilePopoutComponent = ErrorBoundary.wrap((e: any) => {
	...
});
```

2023-04-28 02:16 UTC, Vendicated requested changes

2023-04-28 02:16 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +import { Tooltip } from "webpack/common";
```suggestion
import { Tooltip } from "@webpack/common";
```

2023-04-28 02:16 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +const Section: React.ComponentType<any> = findByCodeLazy("().lastSection");
```suggestion
const Section = LazyComponent(() => findByCode("().lastSection"));
```

2023-04-28 02:16 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +        description: "Icon size",
you should specify the unit here, i assume px?

2023-04-28 02:16 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +        description: "Icon spacing",
what's spacing? Do you mean padding/margin? If so, please change it to that

2023-04-28 02:16 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +        description: "Icon spacing",
but also the average user doesn't want to manually juggle px values. Maybe it would be better to use different presets like cozy & compact

2023-04-28 02:16 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +    if (connections && connections.length !== 0) {
the happy path should come last imo, so I think it would be nicer (and shorter) to write this as `if (!connections?.length) return null`

2023-04-28 02:16 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +                    href={url ?? "javascript:void(0)"}
i think this might throw an ugly csp error because Discord doesn't allow inline handler script, please verify if this is the case by checking the console for errors

2023-04-28 02:16 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +                    onClick={() => !url && navigator.clipboard.writeText(connection.name)}
this should use the clipboard api from webpack commons instead

2023-04-28 10:12 UTC, TheKodeToad commented on src/plugins/quickConnections/index.tsx
> +    if (connections && connections.length !== 0) {
Ah, probably an artifact of refactoring :P

2023-04-28 10:14 UTC, TheKodeToad commented on src/plugins/quickConnections/index.tsx
> +        description: "Icon size",
I suppose I could have presets.

2023-04-28 10:46 UTC, TheKodeToad commented on src/plugins/quickConnections/index.tsx
> +                    href={url ?? "javascript:void(0)"}
I can't see anything

2023-04-29 22:11 UTC, Vendicated commented
Your screenshots show it above roles but for me it's below the notes box for some reason

2023-04-29 22:26 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +                    href={url ?? "javascript:void(0)"}
!!
![image](https://user-images.githubusercontent.com/45497981/235326589-2b538860-779a-4c57-84c4-f7c88cdf60e0.png)

2023-04-29 22:41 UTC, Vendicated commented on src/plugins/quickConnections/index.tsx
> +                    href={url ?? "javascript:void(0)"}
i fixed

2023-04-29 22:48 UTC, Vendicated approved these changes

2023-04-29 22:48 UTC, Vendicated commented
I went ahead and renamed the plugin from QuickConnections to ShowConnections to have the same name as the BD plugin (and imo be more self explanatory)

2023-04-29 22:49 UTC, merged

2023-04-29 22:49 UTC, Vendicated commented
awesome thank you, very cool plugin :3

2023-04-30 10:26 UTC, TheKodeToad commented
> Your screenshots show it above roles but for me it's below the notes box for some reason

I changed it intentionally.

2023-04-30 11:27 UTC, Vendicated commented
> I changed it intentionally.

Oh I see, I'm sorry for changing it then (though I personally like it better where it is now)! :(

We could perhaps add a setting to change their location if you care?

2023-04-30 12:37 UTC, TheKodeToad commented
It works both ways! I thought it was more consistent without the heading.