feat(plugin): ImplicitRelationships
Vendicated/Vencord pull request #947
Opened 2023-04-18 23:50 UTC by dolfies

### Summary
Adds a section to the Friends tab that shows your implicit relationships.

### Limitations
The tab will usually be empty until implicit relationships are calculated, after which you have to reopen the Friends tab to see them. No idea how to go about fixing this.

2023-04-19 14:47 UTC, ArjixWasTaken reviewed
looks good to me, just one small thing

2023-04-19 14:47 UTC, ArjixWasTaken commented on src/plugins/implicitRelationships.ts
> +    ],
Since all the patches use the same `find`, that means they are in the same file.
One optimization is to have one patch with multiple replacements.

Yes it is valid, the type is [here](https://github.com/Vendicated/Vencord/blob/main/src/utils/types.ts#L38).

TL;DR you can do

```js
{
    find: "...",
    replacement: [
        {  },
        {  }
    ]
}
```

2023-04-19 22:17 UTC, dolfies commented on src/plugins/implicitRelationships.ts
> +    ],
Didn't know this was possible, thanks!

2023-04-19 23:14 UTC, ArjixWasTaken reviewed
oops, one more thing!

2023-04-19 23:14 UTC, ArjixWasTaken commented on src/plugins/implicitRelationships.ts
> +                    replace: "$1.$2.fetchRelationships(),Vencord.Plugins.plugins.ImplicitRelationships.fetchImplicitRelationships()"
```suggestion
                    replace: "$1.$2.fetchRelationships(),$self.fetchImplicitRelationships()"
```

you should use `$self` instead of the full path

2023-04-19 23:57 UTC, dolfies commented on src/plugins/implicitRelationships.ts
> +                    replace: "$1.$2.fetchRelationships(),Vencord.Plugins.plugins.ImplicitRelationships.fetchImplicitRelationships()"
Another thing I didn't know existed, thanks again!

2023-05-12 00:08 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +                    match: /toString\(\)\}\);case ([^;]+)\.([^;]+)\.BLOCKED/,
are these identifiers? aka `case foo.bar.BLOCKED`

If so:
```suggestion
                    match: /toString\(\)\}\);case (\i\.\i\.BLOCKED)/,
```

2023-05-12 00:09 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +                    replace: "toString()});case $1.$2.IMPLICIT:return \"Implicit — \"+t.toString();case $1.$2.BLOCKED"
don't hardcode minified variable names like "t" here

2023-05-12 00:13 UTC, Vendicated requested changes

2023-05-12 00:13 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +        return privateChannels.some(channel => channel.recipients.includes(userId));
avoid pointless variables
```suggestion
        return ChannelStore.getSortedPrivateChannels().some(channel => channel.recipients.includes(userId));
```

2023-05-12 00:13 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +            id => !RelationshipStore.getRelationshipType(id)
shouldn't this be
```suggestion
            id => RelationshipStore.getRelationshipType(id) === 5 /* IMPLICIT */
```
![image](https://github.com/Vendicated/Vencord/assets/45497981/1565d147-9575-4bc1-a6d8-b0b87e77abe6)

2023-05-12 00:56 UTC, dolfies commented on src/plugins/implicitRelationships.ts
> +            id => !RelationshipStore.getRelationshipType(id)
No, the whole point of this function is to figure out what users Discord treats as implicit relationships and insert them into cache. `nonFriendAffinities` is just user affinities that you do not have an existing *real* relationship with.

Implicit relationships aren't actually stored as relationships on Discord's end, so they aren't sent in READY or normal `GET /users/@me/relationships` calls. Implicit relationships themselves are a GameSDK artifact that was kept alive when they added the `relationships.read` OAuth2 scope (if you `GET /users/@me/relationships?with_implicit=true` with a bearer token with said scope, Discord calculates your implicit relationships and returns them as type 5).

The client backfills type 5 relationships when it detects them from PRESENCE_UPDATE events, and also caches all of them when the GameSDK's GET_RELATIONSHIPS is called (though it has the logic slightly wrong 😭).

2023-05-12 00:57 UTC, dolfies commented on src/plugins/implicitRelationships.ts
> +                    replace: "toString()});case $1.$2.IMPLICIT:return \"Implicit — \"+t.toString();case $1.$2.BLOCKED"
Oopsies, forgot to change that after testing

2023-05-12 01:58 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +                    replace: "toString()});case $1.IMPLICIT:return \"Implicit — \"+arguments[1].toString();case $1.BLOCKED"
```suggestion
                    replace: 'toString()});case $1.IMPLICIT:return "Implicit — "+arguments[1];case $1.BLOCKED'
```

2023-05-12 02:02 UTC, Vendicated requested changes

2023-05-12 02:02 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +                    match: /case (\i\.\i)\.BLOCKED:return (\i)\.type===(\i\.\i)\.BLOCKED/,
using lookarounds, you can avoid just replacing Discord's code with itself
```suggestion
                    match: /(?<=case (\i\.\i)\.BLOCKED:return (\i)\.type===\i\.\i\.BLOCKED)/,
```

2023-05-12 02:02 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +                    replace: "case $1.BLOCKED:return $2.type===$3.BLOCKED;case $1.IMPLICIT:return $2.type===5"
now you don't need any of their jazz
```suggestion
                    replace: ";case $1.IMPLICIT:return $2.type===5"
```

2023-05-12 02:02 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +                    replace: "case $1.BLOCKED:return $2.type===$3.BLOCKED;case $1.IMPLICIT:return $2.type===5"
now you don't need any of their jazz
```suggestion
                    replace: ";case $1.IMPLICIT:return $2.type===5"
```

2023-05-12 02:35 UTC, dolfies commented on src/plugins/implicitRelationships.ts
> +                    match: /case (\i\.\i)\.BLOCKED:return (\i)\.type===(\i\.\i)\.BLOCKED/,
one day I will learn how these work 🙏

2023-05-13 23:33 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +        return ChannelStore.getSortedPrivateChannels().some(channel => channel.recipients.includes(userId));
```suggestion
        return userId in ChannelStore.getMutablePrivateChannels();
```

2023-05-13 23:37 UTC, dolfies commented on src/plugins/implicitRelationships.ts
> +        return ChannelStore.getSortedPrivateChannels().some(channel => channel.recipients.includes(userId));
I don't think this accounts for group DMs

2023-05-13 23:38 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +        return ChannelStore.getSortedPrivateChannels().some(channel => channel.recipients.includes(userId));
it does! getSortedPrivateChannels just does Object.values(mutablePrivateChannels).sort().reverse()

2023-05-13 23:44 UTC, Vendicated commented on src/plugins/implicitRelationships.ts
> +        return ChannelStore.getSortedPrivateChannels().some(channel => channel.recipients.includes(userId));
my bad, i didn#t read the original code correctly
```suggestion
        return Object.values(ChannelStore.getSortedPrivateChannels()).some(channel => channel.recipients.includes(userId));
```

2023-06-04 18:44 UTC, TheKodeToad commented
> ### Limitations
> 
> The tab will be empty until implicit relationships are calculated, after which you have to reopen the Friends tab to see them. No idea how to go about fixing this.

Maybe with `useState` or `useForceUpdater` hackily put in a global?

2023-06-10 00:26 UTC, dolfies commented
> > ### Limitations
> > The tab will be empty until implicit relationships are calculated, after which you have to reopen the Friends tab to see them. No idea how to go about fixing this.
> 
> Maybe with `useState` or `useForceUpdater` possibly hackily put in a global?

No idea how to do that :)

2023-06-10 10:06 UTC, ArjixWasTaken commented
> > ### Limitations
> > The tab will be empty until implicit relationships are calculated, after which you have to reopen the Friends tab to see them. No idea how to go about fixing this.
> 
> Maybe with `useState` or `useForceUpdater` possibly hackily put in a global?

Tried it, doesn't work.
It clearly re-renders, but I think it has a cache of the data to render.

2023-06-10 10:18 UTC, TheKodeToad commented
Maybe make the data use `useState`?

2023-06-10 10:40 UTC, ArjixWasTaken commented
> Maybe make the data use `useState`?

please no more suggestions, they are dumb, I'm already investigating this

2023-06-10 10:43 UTC, ArjixWasTaken commented on src/plugins/implicitRelationships.ts
> +        implicitRelationships.forEach(user => relationships[user.id] = 5);
```suggestion
        implicitRelationships.forEach(user => relationships[user.id] = 5);
        
        RelationshipStore.emitChange();
```

2023-06-10 10:43 UTC, ArjixWasTaken commented on src/plugins/implicitRelationships.ts
> +        implicitRelationships.forEach(user => relationships[user.id] = 5);
🙏

2023-06-10 10:50 UTC, ArjixWasTaken commented
> Maybe make the data use `useState`?

Why did I call this dumb?
Well, this plugin does not inject a component or anything really.
It does not have its own data to render.

It inserts a relationship type, and users with that type, into an already existing component.
It then adds a label so that you can view that relationship type.

All the rendering and stuff is done by discord's code.

Event w/o that in mind, `useState` is not different in behavior from `useForceUpdater` when it comes to triggering a re-render of the component.

The issue was that discord listens for changes in the RelationshipStore with `useStateFromStores`, and the state was directly modified w/o React being aware of it.

So the `useStateFromStores` did not find a change.
Calling `RelationshipStore.emitChange();` is the fix, as it signals that the store has a new state.

2023-06-10 17:13 UTC, dolfies commented on src/plugins/implicitRelationships.ts
> +        implicitRelationships.forEach(user => relationships[user.id] = 5);
very nice ty

2024-04-23 00:07 UTC, Vendicated commented on src/plugins/implicitRelationships/index.ts
> +                match: /case (\i\.\i)\.ONLINE:return (\i)\.SECTION_ONLINE/,
if you don't actually need that part for anything, you can just slap it in a lookaround so you dont match it
```suggestion
                match: /case (\i\.\i)\.ONLINE:(?=return (\i)\.SECTION_ONLINE)/,
```

2024-04-23 00:07 UTC, Vendicated commented on src/plugins/implicitRelationships/index.ts
> +                replace: "case $1.ONLINE:case $1.IMPLICIT:return $2.SECTION_ONLINE"
```suggestion
                replace: "case $1.ONLINE:case $1.IMPLICIT:"
```

2024-04-23 00:07 UTC, Vendicated commented on src/plugins/implicitRelationships/index.ts
> +        return Object.values(ChannelStore.getSortedPrivateChannels()).some(channel => channel.recipients.includes(userId));
i see that you're calling this from an array loop and this is also a loop, so this could potentially add up and do a lot of looping

you could do it way more performant by doing something like
```js
const dmUserIds = new Set(
	Object.values(ChannelStore.getSortedPrivateChannels()).flatMap(c => c.recipients)
);

const toRequest = nonFriendAffinities.filter(id => !UserStore.getUser(id) || dmUserIds.has(id));
```

2024-04-23 00:21 UTC, dolfies commented on src/plugins/implicitRelationships/index.ts
> +        return Object.values(ChannelStore.getSortedPrivateChannels()).some(channel => channel.recipients.includes(userId));
fixed!

2024-04-23 00:26 UTC, dolfies commented on src/plugins/implicitRelationships/index.ts
> +        // Modify sort -- thanks megu for the patch (from sortFriendRequests)
they are now!!

2024-04-23 01:24 UTC, Vendicated commented on src/plugins/implicitRelationships/index.ts
> +        return affinities.find(affinity => affinity.user_id === user.id)?.affinity ?? 0;
can't you just use `findStore("UserAffinitiesStore").getUserAffinity(user.id)`? i dont have any affinities so cant test but seems to be what u want :p

2024-04-23 02:05 UTC, dolfies commented on src/plugins/implicitRelationships/index.ts
> +        return affinities.find(affinity => affinity.user_id === user.id)?.affinity ?? 0;
i swear that's new lol

2024-04-24 03:41 UTC, merged

2024-04-24 03:50 UTC, Vendicated commented
thank you!! yet another tab to show me i have no friends :blobcatcozy: