Perm Lurking Plugin
Vendicated/Vencord pull request #993
Opened 2023-04-26 22:13 UTC by Jupith

2023-04-28 11:42 UTC, ArjixWasTaken commented on src/plugins/permLurk.ts
> +            }, 600);
Don't repeatedly fetch modules on an event.
Fetch them once.

```suggestion
import { findByPropsLazy } from "@webpack";

const getGuildsTree = findByPropsLazy("getGuildsTree");
const getGuildCount = findByPropsLazy("getGuildCount");
const lurkingGuildIds = findByPropsLazy("lurkingGuildIds");
const joinGuild = findByPropsLazy("joinGuild");

export default definePlugin({
    name: "PermLurk",
    description: "allows you to perm lurk guilds",
    authors: [Devs.Jup],

    flux: {
        GUILD_JOIN({ guildId }) {
            setTimeout(() => {
                getGuildsTree.getGuildsTree().root.children.unshift({ type: "guild", guildId, unavailable: false, children: [] });
                getGuildCount.getGuild(guildId).joinedAt = new Date;
                lurkingGuildIds.lurkingGuildIds().pop();
                joinGuild.transitionToGuildSync(guildId);
            }, 600);
```

Since I didn't care to find the module names, I just named them the same as the function to be invoked.
You might want to rename them.

2023-05-14 00:35 UTC, Vendicated commented on src/plugins/permLurk.ts
> +        GUILD_JOIN({ guildId }) {
wait i'm really confused, won't this lurk ALL guilds? how would you normally join a guild with this on

2023-05-14 00:36 UTC, Vendicated requested changes

2023-05-14 00:36 UTC, Vendicated commented on src/plugins/permLurk.ts
> +const lurkingGuildIds = findByPropsLazy("lurkingGuildIds");
```suggestion
const LurkingStore = findStoreLazy("LurkingStore");
```

2023-05-14 00:36 UTC, Vendicated commented on src/plugins/permLurk.ts
> +const getGuildCount = findByPropsLazy("getGuildCount");
this is GuildStore from webpack commons

2023-05-14 00:36 UTC, Vendicated commented on src/plugins/permLurk.ts
> +const getGuildsTree = findByPropsLazy("getGuildsTree");
```suggestion
const SortedGuildStore = findStoreLazy("SortedGuildStore");
```

2023-05-14 00:37 UTC, Vendicated commented on src/utils/constants.ts
> +        id: 1088725200000000000n
what in the world is your id :shipit:

2023-08-15 23:46 UTC, Vendicated commented
closing as this pr has been stale with unresolved feedback for months now. Feel free to reopen if you're still interested in getting this merged! Thank you

2023-08-15 23:46 UTC, closed without merging